<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- CA2007 conflicts with xUnit1030 in test projects -->
    <NoWarn>$(NoWarn);CA2007</NoWarn>
    <ExcludeSharedTesting>true</ExcludeSharedTesting>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Pragmatic.Audit.EFCore\Pragmatic.Audit.EFCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
  </ItemGroup>

</Project>
