// <auto-generated>
// Pragmatic.Design - Shared Source Generator Code
// This file is linked into generator projects, not distributed as a package.
// </auto-generated>

namespace Pragmatic.SourceGen;

/// <summary>
/// Constants for ForAttributeWithMetadataName to hide ugly generic syntax.
/// Using constants makes the generator code cleaner and more maintainable.
/// </summary>
/// <remarks>
/// Generic attributes use backtick notation in metadata names:
/// - `1 = one type parameter
/// - `2 = two type parameters
///
/// Example: MapFromAttribute&lt;TSource&gt; becomes "MapFromAttribute`1"
/// </remarks>
internal static class AttributeNames
{
    // ═══════════════════════════════════════════════════════════════════════
    // Layer 0 - Foundation
    // ═══════════════════════════════════════════════════════════════════════

    // Composition
    public const string UsePackage = "Pragmatic.Composition.Attributes.UsePackageAttribute`1";

    // ═══════════════════════════════════════════════════════════════════════
    // Layer 1 - Capabilities
    // ═══════════════════════════════════════════════════════════════════════

    // Validation
    public const string Validate = "Pragmatic.Validation.Attributes.ValidationAttribute";
    public const string Validator = "Pragmatic.Validation.Attributes.ValidatorAttribute";
    public const string ValidationRequired = "Pragmatic.Validation.Attributes.RequiredAttribute";

    // Authoring — lifecycle domain events
    public const string Raises = "Pragmatic.Authoring.RaisesAttribute`1";

    // Mapping
    public const string MapFrom = "Pragmatic.Mapping.Attributes.MapFromAttribute`1";
    public const string MapTo = "Pragmatic.Mapping.Attributes.MapToAttribute`1";
    public const string MapIgnore = "Pragmatic.Mapping.Attributes.MapIgnoreAttribute";

    // Actions (Mediator)
    public const string DomainAction = "Pragmatic.Actions.Attributes.DomainActionAttribute";
    // [EventHandler] lives in Pragmatic.Events.Attributes (NOT Actions) — consumed by SerializationFeature
    // to add handled domain-event types to the generated JsonSerializerContext.
    public const string EventHandler = "Pragmatic.Events.Attributes.EventHandlerAttribute";

    // [EnableEventOutbox] on a boundary marker → the Persistence feature wires the domain-event outbox
    // into that boundary's generated DbContext (table mapping, interceptor, delivery, schema).
    public const string EnableEventOutbox = "Pragmatic.Events.Attributes.EnableEventOutboxAttribute";

    // [PublicEvent] marks a domain event as part of the cross-boundary contract. ⚠️ Namespace
    // Pragmatic.Events, no .Attributes segment, and it lives in Pragmatic.Abstractions — read from the
    // declaration and not inferred from its neighbours above. Consumed by AsyncApiFeature, and by the
    // PRAG0836 shape diagnostic for the case where the marked type is not a domain event at all.
    public const string PublicEvent = "Pragmatic.Events.PublicEventAttribute";
    public const string LoadEntity = "Pragmatic.Actions.Attributes.LoadEntityAttribute`1";
    public const string Boundary = "Pragmatic.Actions.Attributes.BoundaryAttribute";
    public const string BelongsTo = "Pragmatic.Persistence.Entity.BelongsToAttribute`1";
    public const string Mutation = "Pragmatic.Actions.Mutation.MutationAttribute";
    public const string CompositeAction = "Pragmatic.Actions.Attributes.CompositeActionAttribute";
    public const string ReadAccess = "Pragmatic.Actions.Attributes.ReadAccessAttribute`1";

    // Domain Entity
    public const string ValueObject = "Pragmatic.Persistence.Entity.ValueObjectAttribute";

    // ═══════════════════════════════════════════════════════════════════════
    // Layer 2 - Infrastructure
    // ═══════════════════════════════════════════════════════════════════════

    // Endpoints
    public const string Endpoint = "Pragmatic.Endpoints.Attributes.EndpointAttribute";
    public const string ExposeEndpoint = "Pragmatic.Endpoints.Attributes.ExposeEndpointAttribute`1";
    public const string ExposeEndpointWithGroup = "Pragmatic.Endpoints.Attributes.ExposeEndpointAttribute`2";

    // Messaging
    public const string MessageHandler = "Pragmatic.Messaging.Attributes.MessageHandlerAttribute";
    public const string MessageMiddleware = "Pragmatic.Messaging.Attributes.MessageMiddlewareAttribute";
    public const string EnableOutbox = "Pragmatic.Messaging.Attributes.EnableOutboxAttribute";
    public const string EnableSagaPersistence = "Pragmatic.Messaging.Attributes.EnableSagaPersistenceAttribute";
    public const string EnableBatchProgress = "Pragmatic.Messaging.Attributes.EnableBatchProgressAttribute";
    public const string Saga = "Pragmatic.Messaging.Attributes.SagaAttribute`1";
    public const string SagaStart = "Pragmatic.Messaging.Attributes.SagaStartAttribute";
    public const string InState = "Pragmatic.Messaging.Attributes.InStateAttribute";
    public const string CompensateWith = "Pragmatic.Messaging.Attributes.CompensateWithAttribute`1";
    public const string SagaTimeout = "Pragmatic.Messaging.Attributes.SagaTimeoutAttribute";
    public const string OnBus = "Pragmatic.Messaging.Attributes.OnBusAttribute";
    public const string RequestHandler = "Pragmatic.Messaging.Attributes.RequestHandlerAttribute";
    public const string PartitionKey = "Pragmatic.Messaging.Attributes.PartitionKeyAttribute";

    // Configuration
    public const string Configuration = "Pragmatic.Configuration.ConfigurationAttribute";

    // Identity
    public const string PragmaticUser = "Pragmatic.Identity.PragmaticUserAttribute";
    public const string ProfileProperty = "Pragmatic.Identity.ProfilePropertyAttribute";
    public const string FromCurrentUser = "Pragmatic.Identity.FromCurrentUserAttribute";

    // Temporal
    public const string FromClock = "Pragmatic.Temporal.Clock.FromClockAttribute";

    // Caching
    public const string Cacheable = "Pragmatic.Caching.Attributes.CacheableAttribute";
    public const string CacheKey = "Pragmatic.Caching.Attributes.CacheKeyAttribute";
    public const string InvalidatesCache = "Pragmatic.Caching.Attributes.InvalidatesCacheAttribute";

    // Patch
    public const string GeneratePatch = "Pragmatic.Patch.Attributes.GeneratePatchAttribute`1";

    // Persistence Entity Traits (used by TraitDetector and EntityTransform)
    public const string PersistenceAuditable = "Pragmatic.Persistence.Entity.AuditableAttribute";
    public const string SoftDelete = "Pragmatic.Persistence.Entity.SoftDeleteAttribute";
    public const string ConcurrencyAware = "Pragmatic.Persistence.Entity.ConcurrencyAwareAttribute";
    public const string HasOwner = "Pragmatic.Persistence.Entity.HasOwnerAttribute";
    public const string HasAccessScopes = "Pragmatic.Persistence.Entity.HasAccessScopesAttribute";

    // Resource
    public const string Resource = "Pragmatic.Persistence.Entity.ResourceAttribute";

    // Rich Traits
    public const string HasComments = "Pragmatic.Comments.HasCommentsAttribute";
    public const string HasTags = "Pragmatic.Tags.HasTagsAttribute";
    public const string HasNotes = "Pragmatic.Notes.HasNotesAttribute";
    public const string HasAttachments = "Pragmatic.Attachments.HasAttachmentsAttribute";

    // Grid Bridge
    public const string GenerateGridBridge = "Pragmatic.Persistence.Query.Attributes.GenerateGridBridgeAttribute";

    // Jobs
    public const string RecurringJob = "Pragmatic.Jobs.Attributes.RecurringJobAttribute";
    public const string Job = "Pragmatic.Jobs.Attributes.JobAttribute";
    public const string ContinueWith = "Pragmatic.Jobs.Attributes.ContinuationAttribute`1";
    public const string EnableJobPersistence = "Pragmatic.Jobs.Attributes.EnableJobPersistenceAttribute";

    // Notifications
    public const string StoresNotifications = "Pragmatic.Notifications.Attributes.StoresNotificationsAttribute";

    // ═══════════════════════════════════════════════════════════════════════
    // Persistence - Relations
    // ═══════════════════════════════════════════════════════════════════════

    // Relation attributes use nested types inside Relation static class.
    // Metadata name format: ContainingType+NestedType`arity
    public const string RelationOneToOne = "Pragmatic.Persistence.Entity.Relation+OneToOne`1";
    public const string RelationOneToMany = "Pragmatic.Persistence.Entity.Relation+OneToMany`1";
    public const string RelationManyToOne = "Pragmatic.Persistence.Entity.Relation+ManyToOne`1";
    public const string RelationManyToMany = "Pragmatic.Persistence.Entity.Relation+ManyToMany`1";
    public const string RelationManyToManyWithJoin = "Pragmatic.Persistence.Entity.Relation+ManyToMany`2";

    // ═══════════════════════════════════════════════════════════════════════
    // Temporal - Timezone conversion behaviors
    // ═══════════════════════════════════════════════════════════════════════

    public const string TemporalAsUtc = "Pragmatic.Temporal.Attributes.AsUtcAttribute";
    public const string TemporalFromClientTimezone = "Pragmatic.Temporal.Attributes.FromClientTimezoneAttribute";
    public const string TemporalFromBusinessTimezone = "Pragmatic.Temporal.Attributes.FromBusinessTimezoneAttribute";
    public const string TemporalToClientTimezone = "Pragmatic.Temporal.Attributes.ToClientTimezoneAttribute";
    public const string TemporalToBusinessTimezone = "Pragmatic.Temporal.Attributes.ToBusinessTimezoneAttribute";
    public const string TemporalKeepTimezone = "Pragmatic.Temporal.Attributes.KeepTimezoneAttribute";

    /// <summary>
    ///     The six timezone attributes and the <c>TemporalJsonBehavior</c> member each one means.
    /// </summary>
    /// <remarks>
    ///     <para>
    ///         One list, because two features read it and a second copy is how they drift. The Temporal
    ///         feature builds a pipeline per entry; the Endpoints feature asks it what a trigger property
    ///         declares, so the behaviour reaches the generated <c>{Trigger}Body</c> record — the type the
    ///         endpoint actually deserializes.
    ///     </para>
    ///     <para>
    ///         ⚠️ Without this list on the Endpoints side the body record would carry the property's
    ///         <em>documentation describing the conversion</em> and not the conversion, and a declaration
    ///         on a mutation would be inert. A seventh attribute is one line here, and
    ///         <c>TemporalBehaviourMapIsComplete</c> fails if it is added anywhere else.
    ///     </para>
    /// </remarks>
    public static readonly (string AttributeName, string Behavior)[] TemporalBehaviors =
    [
        (TemporalAsUtc, "AsUtc"),
        (TemporalFromClientTimezone, "FromClientTimezone"),
        (TemporalFromBusinessTimezone, "FromBusinessTimezone"),
        (TemporalToClientTimezone, "ToClientTimezone"),
        (TemporalToBusinessTimezone, "ToBusinessTimezone"),
        (TemporalKeepTimezone, "KeepTimezone"),
    ];

    // ═══════════════════════════════════════════════════════════════════════
    // Privacy — personal-data classification
    // ═══════════════════════════════════════════════════════════════════════

    /// <summary>Marks a property as personal data and declares how it is erased.</summary>
    public const string PrivacyPersonalData = "Pragmatic.Privacy.PersonalDataAttribute";

    /// <summary>Marks an entity as a data subject. Its presence is what switches the privacy analysis on.</summary>
    public const string PrivacyDataSubject = "Pragmatic.Privacy.DataSubjectAttribute";

    /// <summary>Declares the path from an entity to the data subject it belongs to.</summary>
    public const string PrivacyLinksToSubject = "Pragmatic.Privacy.LinksToSubjectAttribute";

    /// <summary>Records that a subject-reachable property is deliberately not personal data.</summary>
    public const string PrivacyNotPersonalData = "Pragmatic.Privacy.NotPersonalDataAttribute";

    /// <summary>The personal data an operation reaches through another operation.</summary>
    /// <remarks>
    ///     ⚠️ The metadata form, with the arity, because that is what a generic attribute's
    ///     <c>MetadataName</c> gives — <c>ToDisplayString()</c> renders it as
    ///     <c>ProcessesDataAttribute&lt;TEntity&gt;</c> and a comparison against this constant then
    ///     silently never matches.
    /// </remarks>
    public const string PrivacyProcessesData = "Pragmatic.Privacy.ProcessesDataAttribute`1";

    /// <summary>The non-generic form: reviewed, reaches no personal data.</summary>
    /// <remarks>
    ///     No arity, because it has none — and it is a different metadata name from the generic one, so
    ///     a check that only knows the generic form reads "declares nothing" for an operation that
    ///     declared exactly the answer it was asked for.
    /// </remarks>
    public const string PrivacyProcessesNoData = "Pragmatic.Privacy.ProcessesDataAttribute";

    // ═══════════════════════════════════════════════════════════════════════
    // Helpers
    // ═══════════════════════════════════════════════════════════════════════

    /// <summary>
    /// Creates a generic attribute name with the specified arity.
    /// </summary>
    /// <param name="fullTypeName">Full type name without generic arity (e.g., "Pragmatic.Mapping.Attributes.MapFromAttribute")</param>
    /// <param name="arity">Number of type parameters (e.g., 1 for MapFrom&lt;T&gt;)</param>
    /// <returns>Metadata name with arity suffix (e.g., "Pragmatic.Mapping.Attributes.MapFromAttribute`1")</returns>
    public static string WithArity(string fullTypeName, int arity) => $"{fullTypeName}`{arity}";
}
