// =============================================================================
// Pragmatic.Design - CSharpTemplate
// Abstract base class for C# source code generation templates
// =============================================================================

using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace Pragmatic.SourceGen;

/// <summary>
///     Abstract base class for generating C# source code using the template pattern.
///     Provides type-safe methods for generating classes, methods, properties, etc.
/// </summary>
/// <remarks>
///     <para>
///         This is a partial class split across multiple files for maintainability:
///         <list type="bullet">
///             <item>
///                 <description>CSharpTemplate.cs - Core writing, usings, blocks, comments, nested types</description>
///             </item>
///             <item>
///                 <description>CSharpTemplate.ControlFlow.cs - If, ElseIf, Else, Switch, Case, Return</description>
///             </item>
///             <item>
///                 <description>CSharpTemplate.Types.cs - Class, Struct, Record, RecordStruct</description>
///             </item>
///             <item>
///                 <description>CSharpTemplate.Members.cs - Field, Property, Method, Constructor, Operators</description>
///             </item>
///         </list>
///     </para>
/// </remarks>
internal abstract partial class CSharpTemplate(CodeWriterOptions? options = null, CSharpTemplate? parent = null)
{
    private readonly List<string> _aliases = new();
    private readonly StringBuilder _codeBuilder = new();
    private readonly StringBuilder _headerBuilder = new();
    private readonly Stack<(int indent, int customSpace)> _indentStack = new();
    private readonly CodeWriterOptions _options = options ?? CodeWriterOptions.Default;
    private readonly List<string> _usings = new();

    private int _currentLineLength;
    private int _indent;
    private bool _isNewLine = true;

    private int RelativeIndent => _indentStack.Count > 0 ? _indent - _indentStack.Peek().indent : _indent;
    private int? CustomLevel => _indentStack.Count > 0 ? _indentStack.Peek().customSpace : null;

    // =============================================================================
    // Abstract members - must be implemented by derived classes
    // =============================================================================

    /// <summary>
    ///     Renders the output artifact (file name + content).
    /// </summary>
    public abstract Artifact RenderOutput();

    /// <summary>
    ///     Renders the file content (called by ToString).
    /// </summary>
    public abstract void RenderFile();

    /// <summary>
    ///     Validates the template before rendering.
    /// </summary>
    protected virtual bool Validate()
    {
        return true;
    }

    /// <summary>
    ///     Optional generator name for the file header comment.
    ///     Override to include "Generated by {name}" in the auto-generated header.
    ///     Returns null by default (no generator name in header).
    /// </summary>
    protected virtual string? GeneratorName => null;

    /// <summary>
    ///     Optional source info for the file header comment.
    ///     Override to include "Source: {info}" in the auto-generated header.
    ///     Example: "OrderDto from MyApp.Models"
    /// </summary>
    protected virtual string? SourceInfo => null;

    /// <summary>
    ///     Optional trigger info for the file header comment.
    ///     Override to include "Trigger: {info}" in the auto-generated header.
    ///     Example: "[MapFrom] on OrderDto"
    /// </summary>
    protected virtual string? TriggerInfo => null;

    // =============================================================================
    // Core writing methods
    // =============================================================================

    protected void Append(string text)
    {
        if (parent != null)
        {
            parent.Append(text);
            return;
        }

        if (_isNewLine)
        {
            var indent = _options.String(RelativeIndent, CustomLevel);
            var line = indent + text;
            _currentLineLength = line.Length;
            _codeBuilder.Append(line);
        }
        else
        {
            _codeBuilder.Append(text);
            _currentLineLength += text.Length;
        }

        _isNewLine = false;
    }

    protected void AppendLine(string line = "")
    {
        if (parent != null)
        {
            parent.AppendLine(line);
            return;
        }

        if (!_isNewLine)
        {
            _codeBuilder.AppendLine(line);
        }
        else
        {
            var indent = _options.String(RelativeIndent, CustomLevel);
            _codeBuilder.AppendLine(indent + line);
        }

        _isNewLine = true;
    }

    // =============================================================================
    // Indentation
    // =============================================================================

    protected void IncreaseIndent()
    {
        if (parent != null)
        {
            parent.IncreaseIndent();
            return;
        }

        _indent++;
    }

    protected void DecreaseIndent()
    {
        if (parent != null)
        {
            parent.DecreaseIndent();
            return;
        }

        if (_indent > 0)
            _indent--;
    }

    protected void PushCustomIndentation()
    {
        if (parent != null)
        {
            parent.PushCustomIndentation();
            return;
        }

        _indentStack.Push((_indent, _currentLineLength));
    }

    protected void PopCustomIndentation()
    {
        if (parent != null)
        {
            parent.PopCustomIndentation();
            return;
        }

        if (_indentStack.Count > 0)
        {
            _currentLineLength = _indentStack.Peek().customSpace;
            _indentStack.Pop();
        }
        else
        {
            _currentLineLength = 0;
        }
    }

    // =============================================================================
    // Usings and Namespace
    // =============================================================================

    protected void AddUsing(string @namespace)
    {
        if (string.IsNullOrEmpty(@namespace) || @namespace == "<global namespace>")
            return;
        if (parent != null)
        {
            parent.AddUsing(@namespace);
            return;
        }

        if (!_usings.Contains(@namespace))
            _usings.Add(@namespace);
    }

    protected void AddUsings(params string[] namespaces)
    {
        foreach (var ns in namespaces)
            AddUsing(ns);
    }

    protected void AddAlias(string aliasName, string aliasDefinition)
    {
        if (parent != null)
        {
            parent.AddAlias(aliasName, aliasDefinition);
            return;
        }

        var alias = $"using {aliasName} = {aliasDefinition};";
        if (!_aliases.Contains(alias))
            _aliases.Add(alias);
    }

    protected void AppendNamespace(string @namespace)
    {
        if (string.IsNullOrEmpty(@namespace) || @namespace == "<global namespace>")
            return;
        if (parent != null)
        {
            parent.AppendNamespace(@namespace);
            return;
        }

        AppendLine($"namespace {@namespace};");
    }

    // =============================================================================
    // Blocks
    // =============================================================================

    protected void Block(Action body, string? modifier = null)
    {
        if (parent != null)
        {
            parent.Block(body, modifier);
            return;
        }

        AppendLine(modifier != null ? $"{modifier} {{" : "{");
        IncreaseIndent();
        body();
        DecreaseIndent();
        AppendLine("}");
    }

    // =============================================================================
    // Comments
    // =============================================================================

    protected void Comment(string comment)
    {
        AppendLine($"// {comment}");
    }

    protected void XmlSummary(string summary)
    {
        AppendLine("/// <summary>");
        var normalized = summary.Replace("\r\n", "\n").Replace("\r", "\n");
        foreach (var line in normalized.Split('\n'))
            AppendLine($"/// {EscapeXml(line)}");
        AppendLine("/// </summary>");
    }

    /// <summary>
    ///     Emits a <c>&lt;remarks&gt;</c> block, one line per input line.
    /// </summary>
    /// <remarks>
    ///     For what a reader has to know that the signature does not say. A summary that grows a
    ///     warning stops being a summary, and the warning is the part that gets skipped.
    /// </remarks>
    protected void XmlRemarks(string remarks)
    {
        AppendLine("/// <remarks>");
        var normalized = remarks.Replace("\r\n", "\n").Replace("\r", "\n");
        foreach (var line in normalized.Split('\n'))
            AppendLine($"/// {EscapeXml(line)}");
        AppendLine("/// </remarks>");
    }

    protected void XmlInheritDoc()
    {
        AppendLine("/// <inheritdoc/>");
    }

    protected void XmlParam(string name, string description)
    {
        AppendLine($"/// <param name=\"{name}\">{EscapeXml(description)}</param>");
    }

    protected void XmlReturns(string description)
    {
        AppendLine($"/// <returns>{EscapeXml(description)}</returns>");
    }

    private static string EscapeXml(string text)
    {
        // Preserve standard XML doc tags verbatim, escape everything else.
        var sb = new StringBuilder(text.Length);
        for (var i = 0; i < text.Length; i++)
        {
            if (text[i] == '&')
            {
                sb.Append("&amp;");
            }
            else if (text[i] == '<')
            {
                // Check if this is a known XML doc tag
                var tagEnd = text.IndexOf('>', i);
                if (tagEnd > i)
                {
                    var tag = text.Substring(i, tagEnd - i + 1);
                    if (IsXmlDocTag(tag))
                    {
                        sb.Append(tag);
                        i = tagEnd;
                        continue;
                    }
                }

                sb.Append("&lt;");
            }
            else if (text[i] == '>')
            {
                sb.Append("&gt;");
            }
            else
            {
                sb.Append(text[i]);
            }
        }

        return sb.ToString();
    }

    /// <summary>
    ///     The XML documentation tags recognised by the C# compiler and by doc tooling
    ///     (ECMA-334 Annex D, plus the <c>inheritdoc</c>/<c>note</c> extensions in common use).
    /// </summary>
    private static readonly HashSet<string> XmlDocTagNames = new(StringComparer.Ordinal)
    {
        "b", "br", "c", "code", "description", "example", "exception", "i", "include", "inheritdoc",
        "item", "list", "listheader", "note", "para", "param", "paramref", "permission", "remarks",
        "returns", "see", "seealso", "summary", "term", "typeparam", "typeparamref", "value",
    };

    /// <summary>
    ///     True when <paramref name="tag" /> (a <c>&lt;…&gt;</c> span lifted verbatim out of the text)
    ///     is one of the standard XML doc tags, in opening, closing or self-closing form.
    /// </summary>
    /// <remarks>
    ///     Deliberately a closed set rather than "anything well-formed": a summary mentioning
    ///     <c>List&lt;string&gt;</c> or <c>IReadOnlyList&lt;T&gt;</c> also contains well-formed-looking
    ///     spans, and those must stay escaped or the doc comment becomes invalid XML.
    /// </remarks>
    private static bool IsXmlDocTag(string tag)
    {
        // tag is "<...>"; strip the delimiters and any leading '/' (closing) or trailing '/' (self-closing).
        if (tag.Length < 3 || tag[0] != '<' || tag[tag.Length - 1] != '>')
            return false;

        var inner = tag.Substring(1, tag.Length - 2);
        if (inner.Length > 0 && inner[0] == '/')
            inner = inner.Substring(1);
        if (inner.Length > 0 && inner[inner.Length - 1] == '/')
            inner = inner.Substring(0, inner.Length - 1);

        // The name ends at the first whitespace; the rest (if any) is the attribute list.
        var nameEnd = 0;
        while (nameEnd < inner.Length && !char.IsWhiteSpace(inner[nameEnd]))
            nameEnd++;

        return nameEnd != 0 && XmlDocTagNames.Contains(inner.Substring(0, nameEnd));
    }

    // =============================================================================
    // Rendering
    // =============================================================================

    private static readonly string GeneratorVersion = typeof(CSharpTemplate).Assembly.GetName().Version?.ToString(3) ?? "0.0.0";

    // The file lands in the consumer's project and is theirs (docs/LICENSING.md, "No lock-in"): the
    // header attributes the framework and claims nothing. A copyright line or a licence at the top of
    // a file reads as a claim on that file, to a reader and to every licence scanner. VerifyConfiguration.AttributionHeaderPattern
    // scrubs these lines from snapshots, so its pattern changes with them.
    protected virtual void RenderHeader()
    {
        if (parent != null)
            return;

        _headerBuilder.AppendLine("// <auto-generated/>");
        _headerBuilder.AppendLine("// Generated by Pragmatic.Design, a framework by Alessandro Saiani");
        _headerBuilder.AppendLine("// https://pragmaticdesign.net");
        _headerBuilder.AppendLine("// This file belongs to your project; no rights are claimed in it.");
        if (GeneratorName is not null)
            _headerBuilder.AppendLine($"// {GeneratorName} v{GeneratorVersion}");
        if (SourceInfo is not null)
            _headerBuilder.AppendLine($"// Source: {SourceInfo}");
        if (TriggerInfo is not null)
            _headerBuilder.AppendLine($"// Trigger: {TriggerInfo}");
        _headerBuilder.AppendLine("#nullable enable");
        _headerBuilder.AppendLine();

        foreach (var u in _usings.Where(k => k != "<global namespace>").Distinct())
            _headerBuilder.AppendLine($"using {u};");
        if (_usings.Count > 0)
            _headerBuilder.AppendLine();

        foreach (var a in _aliases)
            _headerBuilder.AppendLine(a);
        if (_aliases.Count > 0)
            _headerBuilder.AppendLine();
    }

    public SourceText ToSourceText()
    {
        var content = ToString() ?? string.Empty;
        // Normalize line endings to CRLF for consistent output on Windows
        content = content.Replace("\r\n", "\n").Replace("\r", "\n").Replace("\n", "\r\n");
        return SourceText.From(content, Encoding.UTF8);
    }

    public override string? ToString()
    {
        if (!Validate())
            return null;
        if (parent != null)
            return null;

        _headerBuilder.Clear();
        _codeBuilder.Clear();

        RenderFile();
        RenderHeader();

        _headerBuilder.Append(_codeBuilder);
        return _headerBuilder.ToString();
    }

    // =============================================================================
    // Nested types
    // =============================================================================

    protected struct MethodModifiers
    {
        public bool IsStatic { get; init; }
        public bool IsVirtual { get; init; }
        public bool IsOverride { get; init; }
        public bool IsAbstract { get; init; }
        public bool IsSealed { get; init; }
        public bool IsAsync { get; init; }
    }

    protected struct ClassModifiers
    {
        public bool Partial { get; init; }
        public bool Abstract { get; init; }
        public bool Sealed { get; init; }
        public bool IsStatic { get; init; }
        public bool IsReadOnly { get; init; }

        /// <summary>
        ///     Emits <c>new</c>: this nested type deliberately hides one of the same name on a base type.
        /// </summary>
        /// <remarks>
        ///     Needed by the per-entity nested types — <c>Repository</c> and its siblings — on an entity
        ///     that derives from another entity. The derived type's is a different type over a different
        ///     entity, so hiding is what is meant; without the keyword it is <c>CS0108</c>, which this
        ///     repository compiles as an error.
        /// </remarks>
        public bool New { get; init; }
    }

    protected readonly struct MethodParameter(string type, string name, bool nullable = false)
    {
        public string Type { get; init; } = type;
        public string Name { get; init; } = name;
        public bool Nullable { get; init; } = nullable;
        public bool IsExtension { get; init; } = false;
        public string? DefaultValue { get; init; } = null;
        public string? Attribute { get; init; } = null;
        public bool IsRef { get; init; } = false;
        public bool IsOut { get; init; } = false;

        public override string ToString()
        {
            var sb = new StringBuilder();

            if (!string.IsNullOrEmpty(Attribute))
                sb.Append($"[{Attribute}] ");
            if (IsExtension)
                sb.Append("this ");
            if (IsRef)
                sb.Append("ref ");
            if (IsOut)
                sb.Append("out ");

            sb.Append(Type);
            if (Nullable && !Type.Contains("?"))
                sb.Append('?');
            sb.Append(' ');
            // Camel-casing is what creates the hazard: a property named Event/Default/Class becomes the
            // keyword event/default/class, which does not compile as a parameter name.
            sb.Append(IdentifierHelper.EscapeIfKeyword(ToCamelCase(Name)));

            if (!string.IsNullOrEmpty(DefaultValue))
                sb.Append($" = {DefaultValue}");

            return sb.ToString();
        }

        private static string ToCamelCase(string name)
        {
            if (string.IsNullOrEmpty(name))
                return name;
            return char.ToLowerInvariant(name[0]) + name.Substring(1);
        }
    }
}