using System.Collections.Generic;
using System.Linq;

// ReSharper disable once CheckNamespace
namespace Pragmatic.SourceGen;

/// <summary>
///     Emits a hand-authored-style <c>JsonSerializerContext</c>
///     subclass covering the assembly's serializable boundary types via <c>JsonMetadataServices</c>.
///     Shape verified by <c>Pragmatic.Abstractions.Tests/HandAuthoredContextSpikeTests</c> (objects) and
///     <c>HandAuthoredCollectionSpikeTests</c> (collections). Does NOT rely on the STJ source generator.
/// </summary>
internal sealed class PragmaticJsonContextTemplate : CSharpTemplate
{
    private readonly JsonContextModel _model;
    private readonly string _hintName;

    /// <param name="model">The types the context covers.</param>
    /// <param name="hintName">
    ///     The generated file's hint name. A parameter because this template is shared: the module
    ///     generator names it by its virtual-folder convention, the client generator does not have one.
    /// </param>
    public PragmaticJsonContextTemplate(JsonContextModel model, string hintName)
    {
        _model = model;
        _hintName = hintName;
    }

    protected override string? GeneratorName => "Pragmatic.SourceGenerator/Serialization";
    protected override string? TriggerInfo => $"{_model.Objects.Count} object(s), {_model.Leaves.Count} leaf(s), {_model.Collections.Count} collection(s)";

    public override Artifact RenderOutput() => new(_hintName, ToSourceText());

    protected override bool Validate() => _model.Objects.Count > 0;

    public override void RenderFile()
    {
        AddUsing("System");
        AddUsing("System.Runtime.CompilerServices");
        AddUsing("System.Text.Json");
        AddUsing("System.Text.Json.Serialization");
        AddUsing("System.Text.Json.Serialization.Metadata");
        AppendLine();

        AppendLine($"namespace {_model.Namespace}.Generated;");
        AppendLine();

        XmlSummary("AOT-safe JSON context generated by Pragmatic. Covers this assembly's serializable boundary types.");
        // [JsonSerializable] markers are inert for the STJ generator (non-chainable — it never sees this
        // generated file) but are read by the PRAG2800 analyzer so it flags only the types we DIDN'T
        // cover (records / immutable / init-only, which the manual metadata API cannot construct).
        foreach (var obj in _model.Objects)
            AppendLine($"[JsonSerializable(typeof({obj.TypeExpr}))]");
        Class("PragmaticJsonContext", RenderBody,
            baseType: "JsonSerializerContext",
            interfaces: new List<string> { "IJsonTypeInfoResolver" },
            accessModifier: AccessModifier.Public,
            modifiers: new ClassModifiers { Sealed = true, Partial = true });
    }

    private void RenderBody()
    {
        AppendLine("/// <summary>Shared instance for registration into the seam (AddPragmaticJsonContext).</summary>");
        AppendLine("public static PragmaticJsonContext Default { get; } = new();");
        AppendLine();
        AppendLine("public PragmaticJsonContext() : base(null) { }");
        AppendLine();
        AppendLine("protected override JsonSerializerOptions? GeneratedSerializerOptions => null;");
        AppendLine();

        // Only when an enum is actually covered: an unused private helper in every generated context
        // is dead code the reader has to rule out.
        if (_model.Leaves.Any(l => l.ConverterExpr.StartsWith("EnumConverter<", StringComparison.Ordinal)))
        {
            RenderEnumConverterLookup();
            AppendLine();
        }
        AppendLine("public override JsonTypeInfo? GetTypeInfo(Type type)");
        IncreaseIndent();
        AppendLine("=> ((IJsonTypeInfoResolver)this).GetTypeInfo(type, Options);");
        DecreaseIndent();
        AppendLine();

        // Options-aware resolver — binds each JsonTypeInfo to the PASSED options (KEY #1).
        AppendLine("JsonTypeInfo? IJsonTypeInfoResolver.GetTypeInfo(Type type, JsonSerializerOptions options)");
        AppendLine("{");
        IncreaseIndent();
        foreach (var obj in _model.Objects)
            AppendLine($"if (type == typeof({obj.TypeExpr})) return Create_{obj.MethodToken}(options);");
        foreach (var leaf in _model.Leaves)
            AppendLine($"if (type == typeof({leaf.TypeExpr})) return JsonMetadataServices.CreateValueInfo<{leaf.TypeExpr}>(options, {leaf.ConverterExpr});");
        foreach (var coll in _model.Collections)
            AppendLine($"if (type == typeof({coll.TypeExpr})) return {coll.CreateInfoExpr};");
        AppendLine("return null;");
        DecreaseIndent();
        AppendLine("}");

        foreach (var obj in _model.Objects)
        {
            AppendLine();
            RenderCreateObject(obj);
        }
    }

    /// <summary>
    ///     Emits the helper that gives an enum the converter the host configured.
    /// </summary>
    /// <remarks>
    ///     <para>
    ///         Baking in <c>JsonMetadataServices.GetEnumConverter</c> would make this context disagree
    ///         with the reflection path: the generated entry point registers a <c>JsonStringEnumConverter</c>,
    ///         so the same enum would go out as <c>"Role"</c> without the context and <c>0</c> with it —
    ///         <c>&lt;PublishAot&gt;</c> silently changing the wire format of every enum in the API.
    ///     </para>
    ///     <para>
    ///         ⚠️ It walks <c>options.Converters</c> by hand rather than calling
    ///         <c>options.GetConverter</c>, which routes through <c>GetTypeInfo</c> — back into this
    ///         resolver, and into itself. That is a stack overflow on the first request, not a wrong
    ///         value, and it is why the obvious one-liner is wrong here.
    ///     </para>
    /// </remarks>
    private void RenderEnumConverterLookup()
    {
        AppendLine("/// <summary>The converter the host configured for this enum, or the default.</summary>");
        AppendLine("private static global::System.Text.Json.Serialization.JsonConverter EnumConverter<TEnum>(JsonSerializerOptions options)");
        AppendLine("    where TEnum : struct, global::System.Enum");
        AppendLine("{");
        IncreaseIndent();
        AppendLine("foreach (var candidate in options.Converters)");
        AppendLine("{");
        IncreaseIndent();
        AppendLine("if (!candidate.CanConvert(typeof(TEnum)))");
        AppendLine("    continue;");
        AppendLine();
        Comment("The string-enum factory by name, built generically. Its CreateConverter goes through");
        Comment("MakeGenericType — RequiresDynamicCode, and the reason a published AOT binary warned");
        Comment("about every enum the host configured. TEnum is concrete here, so this is not.");
        AppendLine("if (candidate is global::System.Text.Json.Serialization.JsonStringEnumConverter)");
        AppendLine("{");
        IncreaseIndent();
        Comment("CreateConverter, not the factory itself: JsonStringEnumConverter<TEnum> is a factory");
        Comment("too, and handing it back as the leaf converter sends STJ round again — the AOT smoke");
        Comment("died on a stack overflow the first time this was written the short way.");
        AppendLine("var stringEnum = new global::System.Text.Json.Serialization.JsonStringEnumConverter<TEnum>()");
        AppendLine("    .CreateConverter(typeof(TEnum), options);");
        AppendLine("if (stringEnum is not null)");
        AppendLine("    return stringEnum;");
        AppendLine();
        AppendLine("continue;");
        DecreaseIndent();
        AppendLine("}");
        AppendLine();
        AppendLine("if (candidate is global::System.Text.Json.Serialization.JsonConverterFactory factory)");
        AppendLine("{");
        IncreaseIndent();
        Comment("Any other factory: nothing here knows how to build it without reflection, so the");
        Comment("default converter is used rather than a call that fails only once published.");
        AppendLine("continue;");
        DecreaseIndent();
        AppendLine("}");
        AppendLine();
        AppendLine("return candidate;");
        DecreaseIndent();
        AppendLine("}");
        AppendLine();
        AppendLine("return JsonMetadataServices.GetEnumConverter<TEnum>(options);");
        DecreaseIndent();
        AppendLine("}");
    }

    private void RenderCreateObject(JsonObjectModel obj)
    {
        // CreateJsonTypeInfo/CreateJsonPropertyInfo are the only metadata-customization APIs that populate
        // through the seam's resolver chain (the typed CreateObjectInfo path does not). They carry
        // IL2026/IL3050, but for the shapes this generator supports (mutable DTOs, primitives, enums,
        // collections) the emitted code is verified to run under Native AOT (examples/aot-smoke).
        AppendLine("[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"Trimming\", \"IL2026\", Justification = \"Generated JsonTypeInfo verified under Native AOT; see examples/aot-smoke.\")]");
        AppendLine("[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"AOT\", \"IL3050\", Justification = \"Generated JsonTypeInfo verified under Native AOT; see examples/aot-smoke.\")]");
        AppendLine($"private static JsonTypeInfo<{obj.TypeExpr}> Create_{obj.MethodToken}(JsonSerializerOptions options)");
        AppendLine("{");
        IncreaseIndent();
        AppendLine($"var info = JsonTypeInfo.CreateJsonTypeInfo<{obj.TypeExpr}>(options);");

        // Abstract polymorphic bases are never instantiated directly (only via derived types).
        if (!obj.IsAbstract)
        {
            if (obj.NeedsUnsafeConstructor)
            {
                // No public parameterless ctor (a positional record): construct via the [UnsafeAccessor]
                // ctor with default args, then STJ overwrites the (init) properties during deserialization.
                var defaults = string.Join(", ", obj.ConstructorParamTypes.AsImmutableArray().Select(_ => "default!"));
                AppendLine($"info.CreateObject = static () => Ctor_{obj.MethodToken}({defaults});");
            }
            else
            {
                AppendLine($"info.CreateObject = static () => new {obj.TypeExpr}();");
            }
        }

        if (obj.DerivedTypes.Count > 0)
        {
            AppendLine("info.PolymorphismOptions = new JsonPolymorphismOptions");
            AppendLine("{");
            IncreaseIndent();
            AppendLine($"TypeDiscriminatorPropertyName = \"{obj.DiscriminatorName}\",");
            AppendLine("DerivedTypes =");
            AppendLine("{");
            IncreaseIndent();
            foreach (var derived in obj.DerivedTypes)
                AppendLine($"new JsonDerivedType(typeof({derived.TypeExpr}), {derived.DiscriminatorArg}),");
            DecreaseIndent();
            AppendLine("},");
            DecreaseIndent();
            AppendLine("};");
        }

        var i = 0;
        foreach (var prop in obj.Properties)
        {
            // Uniform null-forgiving cast works for value, reference and nullable types and avoids
            // CS8601 when assigning a deserialized value to a non-nullable property.
            var cast = $"({prop.TypeExpr})v!";
            AppendLine($"var p{i} = info.CreateJsonPropertyInfo(typeof({prop.TypeExpr}), \"{prop.JsonName}\");");
            AppendLine($"p{i}.Get = static o => (({obj.TypeExpr})o).{prop.ClrName};");
            // Init-only setters can't be assigned from C# post-construction; route through the
            // [UnsafeAccessor] setter (AOT-safe, reflection-free). Regular setters assign directly.
            if (prop.IsInitOnly)
                AppendLine($"p{i}.Set = static (o, v) => Set_{obj.MethodToken}_{prop.ClrName}(({prop.DeclaringTypeExpr})o, {cast});");
            else
                AppendLine($"p{i}.Set = static (o, v) => (({obj.TypeExpr})o).{prop.ClrName} = {cast};");
            if (ShouldSerialize(prop) is { } shouldSerialize)
                AppendLine($"p{i}.ShouldSerialize = {shouldSerialize};");
            AppendLine($"info.Properties.Add(p{i});");
            i++;
        }

        AppendLine("return info;");
        DecreaseIndent();
        AppendLine("}");

        RenderUnsafeAccessors(obj);
    }

    /// <summary>
    ///     The <c>ShouldSerialize</c> that reproduces a property's <c>[JsonIgnore(Condition = …)]</c>, or null when the
    ///     host's <c>DefaultIgnoreCondition</c> decides, as it does under reflection.
    /// </summary>
    private static string? ShouldSerialize(JsonPropertyModel prop) => prop.Ignore switch
    {
        JsonPropertyIgnore.Never => "static (_, _) => true",
        JsonPropertyIgnore.WhenWritingNull => "static (_, v) => v is not null",
        JsonPropertyIgnore.WhenWritingDefault when prop.IsValueType =>
            $"static (_, v) => !global::System.Collections.Generic.EqualityComparer<{prop.TypeExpr}>.Default.Equals(({prop.TypeExpr})v!, default)",
        JsonPropertyIgnore.WhenWritingDefault => "static (_, v) => v is not null",
        _ => null,
    };

    /// <summary>
    ///     Emits the <c>[UnsafeAccessor]</c> members backing an object's construction and init-only
    ///     property assignment — AOT-safe, reflection-free accessors the C# language can't express directly.
    /// </summary>
    private void RenderUnsafeAccessors(JsonObjectModel obj)
    {
        if (obj.NeedsUnsafeConstructor)
        {
            var parameters = string.Join(", ",
                obj.ConstructorParamTypes.AsImmutableArray().Select((t, idx) => $"{t} arg{idx}"));
            AppendLine();
            AppendLine("[UnsafeAccessor(UnsafeAccessorKind.Constructor)]");
            AppendLine($"private static extern {obj.TypeExpr} Ctor_{obj.MethodToken}({parameters});");
        }

        foreach (var prop in obj.Properties)
        {
            if (!prop.IsInitOnly)
                continue;
            AppendLine();
            AppendLine($"[UnsafeAccessor(UnsafeAccessorKind.Method, Name = \"set_{prop.ClrName}\")]");
            AppendLine($"private static extern void Set_{obj.MethodToken}_{prop.ClrName}({prop.DeclaringTypeExpr} instance, {prop.TypeExpr} value);");
        }
    }
}
