using Microsoft.CodeAnalysis;
using Pragmatic.Actions.Attributes;
using Pragmatic.Persistence.Entity;
using Pragmatic.SourceGen.Testing;
using Pragmatic.Testing.Assertions;
using Xunit;

namespace Pragmatic.SourceGenerator.Tests.Features.Persistence;

/// <summary>
///     <c>[Unique]</c>: the index it asks for, and <c>PRAG0627</c> when it names a property that is
///     not there.
/// </summary>
/// <remarks>
///     The property names arrive as strings, so <c>nameof</c> is a convention and not a guarantee.
///     Without the diagnostic a typo becomes a CS1061 inside a generated file, naming a property on a
///     type whose configuration the author never wrote.
/// </remarks>
public class UniqueIndexTests
{
    private static readonly MetadataReference[] References =
    [
        GeneratorTestHelper.FromType<IEntity>(),
        GeneratorTestHelper.FromType<EntityAttribute>(),
        GeneratorTestHelper.FromType<BoundaryAttribute>(),
        GeneratorTestHelper.FromType<Pragmatic.Persistence.EFCore.PragmaticDbContextAttribute>()
    ];

    private static SourceGenRunResult Run(string body)
        => GeneratorTestHelper.RunGenerator<PragmaticSourceGenerator>($$"""
            using Pragmatic.Actions.Attributes;
            using Pragmatic.Persistence.Entity;

            namespace Contoso.Members;

            [Boundary]
            public partial class MembersBoundary;

            {{body}}
            """, References);

    [Fact]
    public void AUniqueIndexNamingAPropertyTheEntityDoesNotHave_IsReported()
    {
        var result = Run("""
            [Entity]
            [Unique("Emial")]
            public partial class Member : IEntity
            {
                public string Email { get; private set; } = "";
            }
            """);

        GeneratorTestHelper.HasDiagnostic(result, "PRAG0627").Should().BeTrue(
            "the names are strings, so a typo would otherwise surface as a compile error inside a "
            + "generated file");
    }

    [Fact]
    public void AUniqueIndexOverRealProperties_IsSilent()
    {
        var result = Run("""
            [Entity]
            [Unique("Country", "TaxCode")]
            public partial class Member : IEntity
            {
                public string Country { get; private set; } = "";
                public string TaxCode { get; private set; } = "";
            }
            """);

        GeneratorTestHelper.HasDiagnostic(result, "PRAG0627").Should().BeFalse();
    }

    /// <summary>
    ///     The control that keeps the rule from firing on a correct entity: <c>TenantId</c> is added by
    ///     the generator, so it is not among the declared properties.
    /// </summary>
    [Fact]
    public void AUniqueIndexOverTenantId_IsSilent()
    {
        var result = Run("""
            [Entity]
            [Unique("TenantId", "Email")]
            public partial class Member : IEntity, ITenantEntity
            {
                public string Email { get; private set; } = "";
            }
            """);

        GeneratorTestHelper.HasDiagnostic(result, "PRAG0627").Should().BeFalse(
            "TenantId is generated, not declared, so it is not in the entity's own properties");
    }

    /// <summary>
    ///     The second control: a foreign key the generator creates is a property too, and naming it is
    ///     the ordinary way to make a child unique within its parent.
    /// </summary>
    [Fact]
    public void AUniqueIndexOverAGeneratedForeignKey_IsSilent()
    {
        var result = Run("""
            [Entity]
            public partial class Team : IEntity { }

            [Entity]
            [Relation.ManyToOne<Team>]
            [Unique("TeamId", "Nickname")]
            public partial class Member : IEntity
            {
                public string Nickname { get; private set; } = "";
            }
            """);

        GeneratorTestHelper.HasDiagnostic(result, "PRAG0627").Should().BeFalse(
            "TeamId is generated by the relation, and unique-within-the-parent is why [Unique] exists");
    }
}
