using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Pragmatic.Telemetry.Conventions;

namespace Pragmatic.Mapping.EFCore.Extensions;

/// <summary>
///     Zero-allocation cache for the simple type names used in activity tags.
///     Initialized once per generic instantiation by the CLR.
/// </summary>
internal static class MappingTypeNameCache<TSource, TDto>
{
    internal static readonly string SourceName = typeof(TSource).Name;
    internal static readonly string DtoName = typeof(TDto).Name;
}

/// <summary>
///     Extension methods for <see cref="IQueryable{T}" /> to work with DTOs that have projections.
/// </summary>
/// <remarks>
///     These extensions use the static Projection property generated by Pragmatic.Mapping
///     to create optimized SQL queries. EF Core translates the projection expression
///     directly to SQL, avoiding N+1 problems and unnecessary data loading.
/// </remarks>
public static class QueryableExtensions
{
    /// <param name="query">The source query.</param>
    /// <typeparam name="TSource">The source entity type.</typeparam>
    extension<TSource>(IQueryable<TSource> query)
    {
        /// <summary>
        ///     Projects the query to a DTO type using the DTO's static Projection property.
        /// </summary>
        /// <typeparam name="TDto">The target DTO type with a static Projection property.</typeparam>
        /// <param name="projection">The projection expression (typically DtoType.Projection).</param>
        /// <returns>A query projecting to the DTO type.</returns>
        /// <example>
        ///     <code>
        ///     var users = await _db.Users
        ///         .Where(u => u.IsActive)
        ///         .SelectDto(UserDto.Projection)
        ///         .ToListAsync();
        ///     </code>
        /// </example>
        public IQueryable<TDto> SelectDto<TDto>(Expression<Func<TSource, TDto>> projection)
        {
            return query.Select(projection);
        }

        /// <summary>
        ///     Projects the query to a DTO type and materializes to a list asynchronously.
        /// </summary>
        /// <typeparam name="TDto">The target DTO type.</typeparam>
        /// <param name="projection">The projection expression.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>A list of projected DTOs.</returns>
        public async Task<List<TDto>> ToListDtoAsync<TDto>(Expression<Func<TSource, TDto>> projection,
            CancellationToken cancellationToken = default)
        {
            using var activity = MappingActivitySource.Instance.StartActivity("mapping.projection.to_list");
            activity?.SetTag(MappingTags.SourceType, MappingTypeNameCache<TSource, TDto>.SourceName);
            activity?.SetTag(MappingTags.DtoType, MappingTypeNameCache<TSource, TDto>.DtoName);

            var result = await query.Select(projection).ToListAsync(cancellationToken).ConfigureAwait(false);

            activity?.SetTag(MappingTags.ResultCount, result.Count);
            return result;
        }

        /// <summary>
        ///     Projects the query to a DTO type and returns the first element or default asynchronously.
        /// </summary>
        /// <typeparam name="TDto">The target DTO type.</typeparam>
        /// <param name="projection">The projection expression.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The first projected DTO or default.</returns>
        public async Task<TDto?> FirstOrDefaultDtoAsync<TDto>(Expression<Func<TSource, TDto>> projection,
            CancellationToken cancellationToken = default)
        {
            using var activity = MappingActivitySource.Instance.StartActivity("mapping.projection.first_or_default");
            activity?.SetTag(MappingTags.SourceType, MappingTypeNameCache<TSource, TDto>.SourceName);
            activity?.SetTag(MappingTags.DtoType, MappingTypeNameCache<TSource, TDto>.DtoName);

            var result = await query.Select(projection).FirstOrDefaultAsync(cancellationToken).ConfigureAwait(false);

            activity?.SetTag(MappingTags.Found, result is not null);
            return result;
        }

        /// <summary>
        ///     Projects the query to a DTO type and returns a single element or default asynchronously.
        /// </summary>
        /// <typeparam name="TDto">The target DTO type.</typeparam>
        /// <param name="projection">The projection expression.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The single projected DTO or default.</returns>
        public async Task<TDto?> SingleOrDefaultDtoAsync<TDto>(Expression<Func<TSource, TDto>> projection,
            CancellationToken cancellationToken = default)
        {
            using var activity = MappingActivitySource.Instance.StartActivity("mapping.projection.single_or_default");
            activity?.SetTag(MappingTags.SourceType, MappingTypeNameCache<TSource, TDto>.SourceName);
            activity?.SetTag(MappingTags.DtoType, MappingTypeNameCache<TSource, TDto>.DtoName);

            var result = await query.Select(projection).SingleOrDefaultAsync(cancellationToken).ConfigureAwait(false);

            activity?.SetTag(MappingTags.Found, result is not null);
            return result;
        }

        /// <summary>
        ///     Projects the query to a DTO type and materializes to an array asynchronously.
        /// </summary>
        /// <typeparam name="TDto">The target DTO type.</typeparam>
        /// <param name="projection">The projection expression.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>An array of projected DTOs.</returns>
        public async Task<TDto[]> ToArrayDtoAsync<TDto>(Expression<Func<TSource, TDto>> projection,
            CancellationToken cancellationToken = default)
        {
            using var activity = MappingActivitySource.Instance.StartActivity("mapping.projection.to_array");
            activity?.SetTag(MappingTags.SourceType, MappingTypeNameCache<TSource, TDto>.SourceName);
            activity?.SetTag(MappingTags.DtoType, MappingTypeNameCache<TSource, TDto>.DtoName);

            var result = await query.Select(projection).ToArrayAsync(cancellationToken).ConfigureAwait(false);

            activity?.SetTag(MappingTags.ResultCount, result.Length);
            return result;
        }
    }
}