using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using Pragmatic.Testing.Assertions;
using Showcase.IntegrationTests.Infrastructure;

namespace Showcase.IntegrationTests.EntityPersistence;

/// <summary>
///     Tests advanced entity features via HTTP endpoints.
///     Covers matrix features:
///       - Soft Delete Cascade [SoftDelete(Cascade=true)]
///       - GeneratedValue [GeneratedValue]
///       - ComputedDefault [ComputedDefault]
///       - MapProperty (navigation flattening)
///       - MapIgnore (computed StatusLabel)
///       - GenerateProjection [GenerateProjection]
/// </summary>
public class AdvancedEntityTests(PostgresFixture fixture) : IntegrationTestBase(fixture)
{
    // =========================================================================
    // Soft Delete Cascade: delete Property → RoomTypes excluded from search
    // =========================================================================

    [Fact]
    public async Task SoftDeleteCascade_DeleteProperty_RoomTypesExcludedFromSearch()
    {
        // Create property + room type
        var property = await CreatePropertyAsync();
        var propertyId = property.GetProperty("id").GetGuid();

        var rtBody = new
        {
            propertyId,
            name = $"CascadeRT-{Guid.NewGuid():N}"[..15],
            code = "CRT",
            baseRate = 100m,
            totalRooms = 5
        };
        var roomType = await PostAsync<JsonElement>("/api/room-types", rtBody);
        var roomTypeId = roomType.GetProperty("id").GetGuid();

        // Verify room type visible in search before delete
        var beforeSearch = await GetAsync<JsonElement>($"/api/room-types/search?propertyId={propertyId}");
        ContainsId(beforeSearch, roomTypeId).Should().BeTrue("RoomType should be visible before property deletion");

        // Delete property (cascade soft delete)
        var deleteResponse = await DeleteAsync($"/api/properties/{propertyId}");
        deleteResponse.StatusCode.Should().Be(HttpStatusCode.NoContent, "a delete answers 204 and no body");

        // RoomType should be excluded from search (soft-delete cascaded)
        var afterSearch = await GetAsync<JsonElement>($"/api/room-types/search?propertyId={propertyId}&pageSize=50");
        ContainsId(afterSearch, roomTypeId).Should().BeFalse(
            "RoomType should be excluded by soft-delete cascade when parent Property is deleted");
    }

    [Fact]
    public async Task SoftDeleteCascade_DeleteProperty_CancellationPolicyExcluded()
    {
        // Create property + cancellation policy
        var property = await CreatePropertyAsync();
        var propertyId = property.GetProperty("id").GetGuid();

        var policyBody = new
        {
            propertyId,
            name = "Cascade Policy",
            hoursBeforeCheckIn = 48,
            penaltyPercentage = 25.0m,
            isDefault = true
        };
        var policyResponse = await PostAsync("/api/cancellation-policies", policyBody);
        policyResponse.StatusCode.Should().Be(HttpStatusCode.Created);

        // Delete property (cascade)
        var deleteResponse = await DeleteAsync($"/api/properties/{propertyId}");
        deleteResponse.StatusCode.Should().Be(HttpStatusCode.NoContent, "a delete answers 204 and no body");

        // Property is deleted → cascaded entities should also be soft-deleted
        // Verify by restoring property and checking that child entities are still deleted
        var restoreResponse = await PostAsync($"/api/properties/{propertyId}/restore", new { });
        restoreResponse.StatusCode.Should().Be(HttpStatusCode.NoContent);

        // After restoring only the property, the cascaded children remain soft-deleted
        // The parent is visible again but children are still deleted
        var restored = await GetRawAsync($"/api/properties/{propertyId}");
        restored.StatusCode.Should().Be(HttpStatusCode.OK,
            "Property should be restored: a soft-deleted row is filtered out of the read");
    }

    // =========================================================================
    // GeneratedValue + ComputedDefault: Invoice.InvoiceNumber auto-generated
    // =========================================================================

    [Fact]
    public async Task GeneratedValue_Invoice_HasAutoGeneratedInvoiceNumber()
    {
        var reservationId = await CreateAndConfirmReservationAsync();

        // Get invoice created by domain event
        var invoiceSearch = await GetAsync<JsonElement>(
            $"/api/invoices/search?reservationId={reservationId}");
        var items = invoiceSearch.GetProperty("items");
        items.GetArrayLength().Should().BeGreaterOrEqualTo(1, "Invoice should be auto-created on confirmation");

        var invoice = items[0];
        var invoiceNumber = invoice.GetProperty("invoiceNumber").GetString();

        // The declared format is INV-{YYYY}{MM}-{SEQ:5}, so the whole shape is asserted rather than
        // the prefix. StartWith("INV-") was true of a number hand-written by CreateInvoiceWithFees
        // too, in a different format and with no sequence — an assertion that could not tell the
        // generator from a workaround around it.
        invoiceNumber.Should().MatchRegex(@"^INV-\d{6}-\d{5}$",
            "the format on [GeneratedValue] is INV-{YYYY}{MM}-{SEQ:5}, and the sequence is five digits");
    }

    // =========================================================================
    // MapProperty (navigation flattening): ReservationSummaryDto
    // =========================================================================

    [Fact]
    public async Task MapProperty_ReservationDto_FlattensNavigationProperties()
    {
        // Create full reservation with guest + property
        var guestBody = new
        {
            firstName = "MapProp",
            lastName = "Test",
            email = $"mapprop.{Guid.NewGuid():N}@test.com"
        };
        var guest = await PostAsync<JsonElement>("/api/guests", guestBody);
        var guestId = guest.GetProperty("id").GetGuid();

        var property = await CreatePropertyAsync("MapProp Hotel");
        var propertyId = property.GetProperty("id").GetGuid();

        var rtBody = new
        {
            propertyId,
            name = "MP Room",
            code = "MPR",
            baseRate = 100m,
            totalRooms = 5
        };
        var roomType = await PostAsync<JsonElement>("/api/room-types", rtBody);
        var roomTypeId = roomType.GetProperty("id").GetGuid();

        var reservationBody = new
        {
            request = new
            {
                guestId,
                propertyId,
                roomTypeId,
                checkIn = DateTimeOffset.UtcNow.AddDays(7).ToString("O"),
                checkOut = DateTimeOffset.UtcNow.AddDays(10).ToString("O"),
                numberOfGuests = 2
            }
        };
        var resResponse = await PostAsync("/api/reservations?api-version=1.0", reservationBody);
        resResponse.StatusCode.Should().Be(HttpStatusCode.Created);
        var reservationId = await resResponse.Content.ReadFromJsonAsync<Guid>(JsonOptions);

        // Get reservation DTO — should have flattened navigation properties
        var dto = await GetAsync<JsonElement>($"/api/reservations/{reservationId}");

        // [MapProperty("Guest.FirstName")] → GuestFirstName
        dto.GetProperty("guestFirstName").GetString().Should().Be("MapProp",
            "GuestFirstName should be flattened from Guest.FirstName via [MapProperty]");

        // [MapProperty("Guest.LastName")] → GuestLastName
        dto.GetProperty("guestLastName").GetString().Should().Be("Test",
            "GuestLastName should be flattened from Guest.LastName via [MapProperty]");

        // [MapProperty("Property.Name")] → PropertyName
        dto.GetProperty("propertyName").GetString().Should().Contain("MapProp",
            "PropertyName should be flattened from Property.Name via [MapProperty]");
    }

    // =========================================================================
    // MapIgnore: StatusLabel computed at runtime, not from DB
    // =========================================================================

    [Fact]
    public async Task MapIgnore_ReservationDto_StatusLabelComputed()
    {
        var reservationId = await CreateFullReservationAsync();

        var dto = await GetAsync<JsonElement>($"/api/reservations/{reservationId}");

        // Status should be "Pending" (initial state)
        dto.GetProperty("status").GetString().Should().Be("Pending");

        // StatusLabel is [MapIgnore] — computed from Status via T.xxx translation keys
        dto.TryGetProperty("statusLabel", out var statusLabel).Should().BeTrue(
            "StatusLabel should be in the response (computed via [MapIgnore])");
        statusLabel.GetString().Should().NotBeNullOrWhiteSpace(
            "StatusLabel should be a non-empty localized string");
    }

    // =========================================================================
    // GenerateProjection: InvoiceSummaryDto has formatted fields
    // =========================================================================

    [Fact]
    public async Task MapFromEntity_Invoice_HasFormattedFields()
    {
        var reservationId = await CreateAndConfirmReservationAsync();

        // Get invoice ID from search
        var invoiceSearch = await GetAsync<JsonElement>(
            $"/api/invoices/search?reservationId={reservationId}");
        var items = invoiceSearch.GetProperty("items");
        items.GetArrayLength().Should().BeGreaterOrEqualTo(1);
        var invoiceId = items[0].GetProperty("id").GetGuid();

        // Use GetInvoice endpoint (calls FromEntity() — supports MapProperty Format + MapConverter)
        var invoice = await GetAsync<JsonElement>($"/api/invoices/{invoiceId}");

        // IssuedDate is [MapProperty(Format = "yyyy-MM-dd")] — formatted date via FromEntity()
        invoice.TryGetProperty("issuedDate", out var issuedDate).Should().BeTrue(
            "IssuedDate should be present (MapProperty with Format)");
        issuedDate.GetString().Should().MatchRegex(@"\d{4}-\d{2}-\d{2}",
            "IssuedDate should be formatted as yyyy-MM-dd");

        // TotalFormatted is [MapConverter<MoneyToStringConverter>]
        invoice.TryGetProperty("totalFormatted", out var totalFormatted).Should().BeTrue(
            "TotalFormatted should be present (MapConverter)");
        totalFormatted.GetString().Should().NotBeNullOrWhiteSpace(
            "TotalFormatted should be a formatted money string");
    }

    /// <summary>
    ///     The search is a query, and its projection carries the formatted and converted members
    ///     exactly as <c>FromEntity</c> computes them: it answered <c>""</c> for both.
    /// </summary>
    [Fact]
    public async Task SearchInvoices_CarriesTheFormattedFields_AsTheInMemoryMappingDoes()
    {
        var reservationId = await CreateAndConfirmReservationAsync();

        var searched = (await GetAsync<JsonElement>($"/api/invoices/search?reservationId={reservationId}"))
            .GetProperty("items")[0];
        var read = await GetAsync<JsonElement>($"/api/invoices/{searched.GetProperty("id").GetGuid()}");

        searched.GetProperty("issuedDate").GetString().Should().MatchRegex(@"^\d{4}-\d{2}-\d{2}$");
        searched.GetProperty("issuedDate").GetString().Should().Be(read.GetProperty("issuedDate").GetString());
        searched.GetProperty("totalFormatted").GetString().Should().NotBeNullOrWhiteSpace();
        searched.GetProperty("totalFormatted").GetString().Should().Be(read.GetProperty("totalFormatted").GetString());
    }

    // =========================================================================
    // Helpers
    // =========================================================================

    private async Task<JsonElement> CreatePropertyAsync(string? name = null)
    {
        var body = new
        {
            code = $"AE-{Guid.NewGuid():N}"[..12],
            name = name ?? $"AdvEnt-{Guid.NewGuid():N}"[..20],
            city = "Rome",
            country = "IT",
            starRating = 3
        };
        var response = await PostAsync("/api/properties", body);
        response.StatusCode.Should().Be(HttpStatusCode.Created);
        return await response.Content.ReadFromJsonAsync<JsonElement>(JsonOptions);
    }

    private async Task<Guid> CreateFullReservationAsync()
    {
        var guestBody = new
        {
            firstName = "AE",
            lastName = "Guest",
            email = $"ae.{Guid.NewGuid():N}@test.com"
        };
        var guest = await PostAsync<JsonElement>("/api/guests", guestBody);
        var guestId = guest.GetProperty("id").GetGuid();

        var property = await CreatePropertyAsync();
        var propertyId = property.GetProperty("id").GetGuid();

        var rtBody = new
        {
            propertyId,
            name = "AE Room",
            code = "AER",
            baseRate = 100m,
            totalRooms = 5
        };
        var roomType = await PostAsync<JsonElement>("/api/room-types", rtBody);
        var roomTypeId = roomType.GetProperty("id").GetGuid();

        var body = new
        {
            request = new
            {
                guestId,
                propertyId,
                roomTypeId,
                checkIn = DateTimeOffset.UtcNow.AddDays(7).ToString("O"),
                checkOut = DateTimeOffset.UtcNow.AddDays(10).ToString("O"),
                numberOfGuests = 2
            }
        };
        var response = await PostAsync("/api/reservations?api-version=1.0", body);
        response.StatusCode.Should().Be(HttpStatusCode.Created);
        return await response.Content.ReadFromJsonAsync<Guid>(JsonOptions);
    }

    private async Task<Guid> CreateAndConfirmReservationAsync()
    {
        var reservationId = await CreateFullReservationAsync();
        var confirmResponse = await PostAsync($"/api/reservations/{reservationId}/confirm", new { });
        confirmResponse.StatusCode.Should().Be(HttpStatusCode.NoContent);
        return reservationId;
    }

    private static bool ContainsId(JsonElement pagedResult, Guid id)
    {
        return pagedResult.GetProperty("items").EnumerateArray()
            .Any(item => item.GetProperty("id").GetGuid() == id);
    }
}
