using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using Pragmatic.Testing.Assertions;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Showcase.Booking.Entities;
using Showcase.IntegrationTests.Infrastructure;

namespace Showcase.IntegrationTests.EntityPersistence;

/// <summary>
///     Tests GeneratedValue auto-generation via HTTP endpoints + DB verification.
///     Covers matrix features:
///       - [GeneratedValue] pattern-based key generation (RES-{YYYY}{MM}-{SEQ:5}, INV-{YYYY}{MM}-{SEQ:5})
///       - Uniqueness enforcement across multiple entities
///       - Sequential numbering for generated invoice numbers
/// </summary>
public class GeneratedValueTests(PostgresFixture fixture) : IntegrationTestBase(fixture)
{
    // =========================================================================
    // GeneratedValue: Reservation.ReservationNumber auto-generated with RES- prefix
    // =========================================================================

    [Fact]
    public async Task GeneratedValue_Reservation_HasAutoGeneratedReservationNumber()
    {
        var reservationId = await CreateFullReservationAsync();

        // ReservationNumber is not exposed in ReservationSummaryDto — verify via DB
        using var scope = Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<BookingDbContext>();

        var reservation = await db.Reservations
            .IgnoreQueryFilters()
            .FirstOrDefaultAsync(r => r.PersistenceId == reservationId);

        reservation.Should().NotBeNull("Reservation should exist in DB");

        // Asserted outright, not "if populated": NotBeNull with the number checked only inside an if
        // would be green whether the value was generated or empty, which is to say green on a feature
        // that did nothing. The whole declared shape is the claim.
        reservation!.ReservationNumber.Should().MatchRegex(@"^RES-\d{6}-\d{5}$",
            "the format on [GeneratedValue] is RES-{YYYY}{MM}-{SEQ:5}, and the sequence is five digits");
    }

    // =========================================================================
    // GeneratedValue: Multiple reservations generate unique numbers
    // =========================================================================

    [Fact]
    public async Task GeneratedValue_MultipleEntities_GenerateUniqueNumbers()
    {
        var (guestId, propertyId, roomTypeId) = await CreatePrerequisitesAsync();

        // Create 3 reservations with different date ranges to avoid overlapping validation
        var id1 = await CreateReservationAsync(guestId, propertyId, roomTypeId, daysOffset: 10);
        var id2 = await CreateReservationAsync(guestId, propertyId, roomTypeId, daysOffset: 20);
        var id3 = await CreateReservationAsync(guestId, propertyId, roomTypeId, daysOffset: 30);

        // Verify all exist in DB
        using var scope = Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<BookingDbContext>();

        var reservations = await db.Reservations
            .IgnoreQueryFilters()
            .Where(r => new[] { id1, id2, id3 }.Contains(r.PersistenceId))
            .ToListAsync();

        reservations.Should().HaveCount(3, "All 3 reservations should exist in DB");

        // Every one of them, not "the populated ones": accepting empty made this pass on a sequence
        // that never ran, which is the state it was written in.
        var numbers = reservations.Select(r => r.ReservationNumber).ToList();

        numbers.Should().OnlyContain(n => System.Text.RegularExpressions.Regex.IsMatch(
            n, @"^RES-\d{6}-\d{5}$"), "every row carries the declared format");
        numbers.Distinct().Should().HaveCount(3,
            "a sequence hands a value out once — three rows are three numbers");

        // At minimum, all 3 reservations were created successfully
        reservations.Should().HaveCount(3);
    }

    // =========================================================================
    // GeneratedValue: Invoice numbers are sequential
    // =========================================================================

    [Fact]
    public async Task GeneratedValue_Invoice_SequentialNumbers()
    {
        // Create and confirm 2 reservations — each confirmation triggers invoice creation
        var reservationId1 = await CreateAndConfirmReservationAsync();
        var reservationId2 = await CreateAndConfirmReservationAsync();

        // Get both invoices via search
        var invoiceSearch1 = await GetAsync<JsonElement>(
            $"/api/invoices/search?reservationId={reservationId1}");
        var items1 = invoiceSearch1.GetProperty("items");
        items1.GetArrayLength().Should().BeGreaterOrEqualTo(1,
            "Invoice should be auto-created on first reservation confirmation");

        var invoiceSearch2 = await GetAsync<JsonElement>(
            $"/api/invoices/search?reservationId={reservationId2}");
        var items2 = invoiceSearch2.GetProperty("items");
        items2.GetArrayLength().Should().BeGreaterOrEqualTo(1,
            "Invoice should be auto-created on second reservation confirmation");

        var invoiceNumber1 = items1[0].GetProperty("invoiceNumber").GetString()!;
        var invoiceNumber2 = items2[0].GetProperty("invoiceNumber").GetString()!;

        // Both should follow the INV- pattern
        invoiceNumber1.Should().StartWith("INV-",
            "First InvoiceNumber should follow the INV- prefix pattern");
        invoiceNumber2.Should().StartWith("INV-",
            "Second InvoiceNumber should follow the INV- prefix pattern");

        // Numbers should be different (uniqueness)
        invoiceNumber2.Should().NotBe(invoiceNumber1,
            "Sequential invoices should have different InvoiceNumbers");

        // Extract sequence parts — format is INV-{YYYYMM}-{SEQ:5}
        // The sequence part is the last segment after the second dash
        var seq1 = ExtractSequenceNumber(invoiceNumber1);
        var seq2 = ExtractSequenceNumber(invoiceNumber2);

        seq2.Should().BeGreaterThan(seq1,
            "Second invoice sequence number should be greater than the first (sequential generation)");
    }

    // =========================================================================
    // Helpers
    // =========================================================================

    private static int ExtractSequenceNumber(string alternateKey)
    {
        // Format: INV-{YYYYMM}-{SEQ:5} e.g. "INV-202603-00001"
        var lastDash = alternateKey.LastIndexOf('-');
        var seqPart = alternateKey[(lastDash + 1)..];
        return int.Parse(seqPart);
    }

    private async Task<(Guid GuestId, Guid PropertyId, Guid RoomTypeId)> CreatePrerequisitesAsync()
    {
        var guest = await PostAsync<JsonElement>("/api/guests", new
        {
            firstName = "AK",
            lastName = "Guest",
            email = $"ak.{Guid.NewGuid():N}@test.com"
        });
        var guestId = guest.GetProperty("id").GetGuid();

        var property = await CreatePropertyAsync();
        var propertyId = property.GetProperty("id").GetGuid();

        var roomType = await PostAsync<JsonElement>("/api/room-types", new
        {
            propertyId,
            name = "AK Room",
            code = "AKR",
            baseRate = 100m,
            totalRooms = 10
        });
        var roomTypeId = roomType.GetProperty("id").GetGuid();

        return (guestId, propertyId, roomTypeId);
    }

    private async Task<Guid> CreateReservationAsync(Guid guestId, Guid propertyId, Guid roomTypeId,
        int daysOffset = 7)
    {
        var body = new
        {
            request = new
            {
                guestId,
                propertyId,
                roomTypeId,
                checkIn = DateTimeOffset.UtcNow.AddDays(daysOffset).ToString("O"),
                checkOut = DateTimeOffset.UtcNow.AddDays(daysOffset + 3).ToString("O"),
                numberOfGuests = 2
            }
        };
        var response = await PostAsync("/api/reservations?api-version=1.0", body);
        response.StatusCode.Should().Be(HttpStatusCode.Created);
        return await response.Content.ReadFromJsonAsync<Guid>(JsonOptions);
    }

    private async Task<JsonElement> CreatePropertyAsync()
    {
        var body = new
        {
            code = $"AK-{Guid.NewGuid():N}"[..12],
            name = $"AKProp-{Guid.NewGuid():N}"[..20],
            city = "Rome",
            country = "IT",
            starRating = 3
        };
        var response = await PostAsync("/api/properties", body);
        response.StatusCode.Should().Be(HttpStatusCode.Created);
        return await response.Content.ReadFromJsonAsync<JsonElement>(JsonOptions);
    }

    private async Task<Guid> CreateFullReservationAsync()
    {
        var (guestId, propertyId, roomTypeId) = await CreatePrerequisitesAsync();
        return await CreateReservationAsync(guestId, propertyId, roomTypeId);
    }

    private async Task<Guid> CreateAndConfirmReservationAsync()
    {
        var reservationId = await CreateFullReservationAsync();
        var confirmResponse = await PostAsync($"/api/reservations/{reservationId}/confirm", new { });
        confirmResponse.StatusCode.Should().Be(HttpStatusCode.NoContent);
        return reservationId;
    }

    // =========================================================================
    // GeneratedValue on a create that is not a mutation
    // =========================================================================

    /// <summary>
    ///     An entity created through the repository, with no create mutation anywhere, still gets its
    ///     generated value.
    /// </summary>
    /// <remarks>
    ///     <para>
    ///         <c>[GeneratedValue]</c> cannot depend on the create mutation's invoker:
    ///         <c>CreateInvoiceWithFeesAction</c> calls <c>Invoice.Create</c> and hands it to the
    ///         repository with no mutation involved, and the row it inserts must still carry the value.
    ///         The action writes no number of its own, so an empty column here is the generator's miss.
    ///     </para>
    ///     <para>
    ///         The action has no endpoint, so it is invoked through its generated invoker inside an
    ///         internal call — the same scope the composite invoker opens — because its
    ///         <c>[RequirePermission]</c> would otherwise answer the authorization question instead of
    ///         this one.
    ///     </para>
    /// </remarks>
    [Fact]
    public async Task GeneratedValue_CreatedThroughRepositoryWithNoMutation_IsStillFilled()
    {
        using var scope = Services.CreateScope();

        var callContext = scope.ServiceProvider
            .GetService<Pragmatic.Actions.Pipeline.ActionCallContext>();
        using var internalCall = callContext?.EnterInternalCall();

        var invoker = scope.ServiceProvider.GetRequiredService<
            Pragmatic.Actions.Invoker.IDomainActionInvoker<
                Showcase.Billing.Actions.CreateInvoiceWithFeesAction, Guid>>();

        var created = await invoker.InvokeAsync(new Showcase.Billing.Actions.CreateInvoiceWithFeesAction
        {
            ReservationId = Guid.CreateVersion7(),
            GuestId = Guid.CreateVersion7(),
            RoomCharge = 120m,
            Currency = "EUR"
        });

        if (created.IsFailure)
            throw new Xunit.Sdk.XunitException($"the action failed: {created.Error.Code}");

        var db = scope.ServiceProvider.GetRequiredService<Showcase.Billing.Entities.BillingDbContext>();
        var invoice = await db.Invoices.IgnoreQueryFilters()
            .FirstOrDefaultAsync(i => i.PersistenceId == created.Value);

        invoice.Should().NotBeNull("the action reported the id of a row it wrote");
        invoice!.InvoiceNumber.Should().MatchRegex(@"^INV-\d{6}-\d{5}$",
            "a create that never touches a mutation gets the same declared format as one that does");
    }
}
