namespace Pragmatic.Authorization;

/// <summary>
///     Describes a known permission for registry/admin purposes.
///     Generated by the SG from every permission the assembly declares with <see cref="PermissionAttribute"/>.
/// </summary>
/// <param name="Name">The permission name (e.g., "booking.guests.create").</param>
/// <param name="Description">Optional human-readable description.</param>
/// <param name="Category">Optional logical category.</param>
public sealed record PermissionInfo(string Name, string? Description, string? Category);
