namespace Pragmatic.Authorization;

/// <summary>
///     Describes a known role for registry/admin purposes.
///     Generated by the SG from all <see cref="IRole"/> implementations.
/// </summary>
/// <param name="Name">The role name.</param>
/// <param name="Description">Optional human-readable description.</param>
/// <param name="DefaultPermissions">Default permissions assigned to this role.</param>
public sealed record RoleInfo(string Name, string? Description, IReadOnlyList<string> DefaultPermissions);
