using Conformance.Catalog.Entities;
using Conformance.Tests.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Pragmatic.Testing.Assertions;
using Xunit;

namespace Conformance.Tests.Cases;

/// <summary>
///     The recursive query generated by <c>[GenerateHierarchy]</c>, executed.
/// </summary>
/// <remarks>
///     <para>
///         The snapshots already say that the generator emits <c>GetDescendantsByParent</c>. That the CTE
///         returns <b>the whole subtree</b>, and not only the direct children, only a database can say: the
///         deciding case is the grandchild.
///     </para>
///     <para>
///         ⚠️ The last test is the control: the rows must be mapped entities, with a loadable navigation.
///         Materialized with <c>SqlQuery&lt;T&gt;</c> the provider would refuse the type — «navigations are
///         not supported» — and every tree has a navigation.
///     </para>
/// </remarks>
public class TheWholeSubtree(PostgresFixture fixture) : E2ETestBase(fixture)
{
    private sealed record Tree(Guid Root, Guid A, Guid A1, Guid A2, Guid B);

    /// <summary>root → a → (a1, a2); root → b.</summary>
    private async Task<Tree> ATreeAsync()
    {
        await using var scope = Services.CreateAsyncScope();
        var db = scope.ServiceProvider.GetRequiredService<CatalogDbContext>();

        var root = Named(db, "root", parent: null);
        var a = Named(db, "a", root);
        var a1 = Named(db, "a1", a);
        var a2 = Named(db, "a2", a);
        var b = Named(db, "b", root);
        await db.SaveChangesAsync();

        return new Tree(root.PersistenceId, a.PersistenceId, a1.PersistenceId, a2.PersistenceId, b.PersistenceId);
    }

    /// <remarks>
    ///     The name has a private setter: written through the entry, like <c>TheLinkedRows</c>. The edge
    ///     goes through the generated navigation, and EF derives the key.
    /// </remarks>
    private static Category Named(CatalogDbContext db, string name, Category? parent)
    {
        var category = Category.Create();
        category.Parent = parent;
        db.Add(category);
        db.Entry(category).Property(nameof(Category.Name)).CurrentValue = name;
        return category;
    }

    /// <summary>
    ///     The grandchild is in the result, the root is not.
    /// </summary>
    [Fact]
    public async Task Descendants_AreTheWholeSubtree()
    {
        var tree = await ATreeAsync();

        await using var scope = Services.CreateAsyncScope();
        var db = scope.ServiceProvider.GetRequiredService<CatalogDbContext>();

        var descendants = await db.GetDescendantsByParent(tree.Root)
            .Select(c => c.PersistenceId)
            .ToListAsync();

        descendants.Should().BeEquivalentTo(new[] { tree.A, tree.A1, tree.A2, tree.B },
            "the CTE goes down to the leaves and does not include the root");
    }

    /// <summary>
    ///     From the grandchild to the root, without the grandchild.
    /// </summary>
    [Fact]
    public async Task Ancestors_AreThePathToTheRoot()
    {
        var tree = await ATreeAsync();

        await using var scope = Services.CreateAsyncScope();
        var db = scope.ServiceProvider.GetRequiredService<CatalogDbContext>();

        var ancestors = await db.GetAncestorsByParent(tree.A1)
            .Select(c => c.PersistenceId)
            .ToListAsync();

        ancestors.Should().BeEquivalentTo(new[] { tree.A, tree.Root },
            "the CTE goes up to the root and does not include the starting child");
    }

    /// <summary>
    ///     ⚠️ A cycle between parents terminates: recursion is bounded inside the CTE even where the
    ///     provider does not bound it, and every row appears once.
    /// </summary>
    /// <remarks>
    ///     The bound must hold for the generated query too, which projects <c>*</c>: on PostgreSQL an
    ///     unbounded <c>WITH RECURSIVE</c> over a cycle does not finish. The cycle is built in two saves
    ///     because EF cannot insert two rows pointing at each other in a single one.
    /// </remarks>
    [Fact]
    public async Task ACycleTerminates_AndEveryRowComesOnce()
    {
        Guid a, b;
        await using (var scope = Services.CreateAsyncScope())
        {
            var db = scope.ServiceProvider.GetRequiredService<CatalogDbContext>();
            var first = Named(db, "cycle-a", parent: null);
            var second = Named(db, "cycle-b", first);
            await db.SaveChangesAsync();

            first.Parent = second;
            await db.SaveChangesAsync();
            (a, b) = (first.PersistenceId, second.PersistenceId);
        }

        await using var read = Services.CreateAsyncScope();
        var catalog = read.ServiceProvider.GetRequiredService<CatalogDbContext>();

        var descendants = await catalog.GetDescendantsByParent(a)
            .Select(c => c.PersistenceId)
            .ToListAsync()
            .WaitAsync(TimeSpan.FromSeconds(30));

        descendants.Should().BeEquivalentTo(new[] { b },
            "the cycle a → b → a leads back to a, which is the excluded root, and b once");

        var ancestors = await catalog.GetAncestorsByParent(b)
            .Select(c => c.PersistenceId)
            .ToListAsync()
            .WaitAsync(TimeSpan.FromSeconds(30));

        ancestors.Should().BeEquivalentTo(new[] { a });
    }

    /// <summary>
    ///     ⚠️ The control: the query is on the <c>DbSet</c>, so it composes with <c>Include</c> and the
    ///     rows are entities with the navigation.
    /// </summary>
    [Fact]
    public async Task TheRowsAreEntities_AndTheParentLoadsWithThem()
    {
        var tree = await ATreeAsync();

        await using var scope = Services.CreateAsyncScope();
        var db = scope.ServiceProvider.GetRequiredService<CatalogDbContext>();

        var grandchild = await db.GetDescendantsByParent(tree.Root)
            .Include(c => c.Parent)
            .SingleAsync(c => c.PersistenceId == tree.A1);

        grandchild.Name.Should().Be("a1");
        grandchild.Parent.Should().NotBeNull("Include composes with the CTE because the query is on the DbSet");
        grandchild.Parent!.PersistenceId.Should().Be(tree.A);
    }
}
