using Microsoft.CodeAnalysis.Testing;
using Xunit;
using AnalyzerVerifier = Microsoft.CodeAnalysis.CSharp.Testing.CSharpAnalyzerVerifier<
    Pragmatic.Persistence.Analyzers.EntityConstructorAnalyzer,
    Microsoft.CodeAnalysis.Testing.DefaultVerifier>;

namespace Pragmatic.Persistence.Analyzers.Tests;

/// <summary>
///     Tests for <see cref="EntityConstructorAnalyzer"/> (PRAG0680).
///     Uses inline entity attribute stubs so the analyzer resolves Pragmatic.Persistence types
///     without requiring a full project reference in the test compilation.
/// </summary>
public class EntityConstructorAnalyzerTests
{
    /// <summary>
    ///     Minimal [Entity] attribute stubs matching the real Pragmatic.Persistence.Entity namespace.
    /// </summary>
    private const string EntityStub = @"
namespace Pragmatic.Persistence.Entity
{
    [System.AttributeUsage(System.AttributeTargets.Class)]
    public class EntityAttribute : System.Attribute { }

}
";

    private static DiagnosticResult ExpectDiagnostic()
        => AnalyzerVerifier.Diagnostic("PRAG0680");

    // =========================================================================
    // PRAG0680 — should be reported
    // =========================================================================

    [Fact]
    public async Task NewEntity_WithEntityAttribute_ReportsDiagnostic()
    {
        var test = EntityStub + @"
[Pragmatic.Persistence.Entity.Entity]
public partial class Order
{
    public string OrderNumber { get; set; }
}

class TestClass
{
    void Method()
    {
        var order = {|#0:new Order()|};
    }
}";
        await AnalyzerVerifier.VerifyAnalyzerAsync(
            test,
            ExpectDiagnostic().WithLocation(0).WithArguments("Order"));
    }

    [Fact]
    public async Task NewDerivedEntity_BaseHasEntityAttribute_ReportsDiagnostic()
    {
        var test = EntityStub + @"
[Pragmatic.Persistence.Entity.Entity]
public partial class Fee
{
    public decimal Amount { get; set; }
}

public class ServiceFee : Fee
{
    public string ServiceName { get; set; }
}

class TestClass
{
    void Method()
    {
        var fee = {|#0:new ServiceFee()|};
    }
}";
        await AnalyzerVerifier.VerifyAnalyzerAsync(
            test,
            ExpectDiagnostic().WithLocation(0).WithArguments("ServiceFee"));
    }

    [Fact]
    public async Task NewEntity_WithNonGenericEntityAttribute_ReportsDiagnostic()
    {
        var test = EntityStub + @"
[Pragmatic.Persistence.Entity.Entity]
public partial class Product
{
    public string Name { get; set; }
}

class TestClass
{
    void Method()
    {
        var product = {|#0:new Product()|};
    }
}";
        await AnalyzerVerifier.VerifyAnalyzerAsync(
            test,
            ExpectDiagnostic().WithLocation(0).WithArguments("Product"));
    }

    // =========================================================================
    // Safe patterns — NO diagnostic expected
    // =========================================================================

    [Fact]
    public async Task NewRegularClass_NoDiagnostic()
    {
        var test = EntityStub + @"
public class RegularClass
{
    public string Name { get; set; }
}

class TestClass
{
    void Method()
    {
        var obj = new RegularClass();
    }
}";
        await AnalyzerVerifier.VerifyAnalyzerAsync(test);
    }

    [Fact]
    public async Task EntityCreateCall_NoDiagnostic()
    {
        // Calling Entity.Create() is a method invocation, not a constructor — no diagnostic.
        //
        // ⚠️ The 'new Order()' inside Create() is not flagged either, though it is user code: flagging
        // it would tell the author of a hand-written factory to call the factory they are writing,
        // which is advice nobody can take. The exemption is narrow (see the two controls below: a static helper
        // on another type, and an instance method on this one, are both still flagged).
        var test = EntityStub + @"
[Pragmatic.Persistence.Entity.Entity]
public partial class Order
{
    public string OrderNumber { get; set; }

    public static Order Create() => new Order();
}

class TestClass
{
    void Method()
    {
        var order = Order.Create();
    }
}";
        await AnalyzerVerifier.VerifyAnalyzerAsync(test);
    }

    [Fact]
    public async Task GeneratedCode_NewEntity_NoDiagnostic()
    {
        // The <auto-generated/> comment must be at the top of a file to mark it as generated.
        // In a single-source test, mid-file comments don't count, so the 'new Order()' IS flagged.
        // ConfigureGeneratedCodeAnalysis(None) is validated implicitly by the framework
        // when actual generated files (from SG) are present — not testable with inline stubs.
        var test = EntityStub + @"
[Pragmatic.Persistence.Entity.Entity]
public partial class Order
{
    public string OrderNumber { get; set; }
}

class GeneratedFactory
{
    static Order CreateOrder() => {|#0:new Order()|};
}
";
        await AnalyzerVerifier.VerifyAnalyzerAsync(
            test,
            ExpectDiagnostic().WithLocation(0).WithArguments("Order"));
    }

    [Fact]
    public async Task NewEntity_DeepInheritanceChain_ReportsDiagnostic()
    {
        var test = EntityStub + @"
[Pragmatic.Persistence.Entity.Entity]
public partial class BaseEntity
{
    public string Name { get; set; }
}

public class MiddleEntity : BaseEntity
{
    public int Level { get; set; }
}

public class LeafEntity : MiddleEntity
{
    public string Detail { get; set; }
}

class TestClass
{
    void Method()
    {
        var leaf = {|#0:new LeafEntity()|};
    }
}";
        await AnalyzerVerifier.VerifyAnalyzerAsync(
            test,
            ExpectDiagnostic().WithLocation(0).WithArguments("LeafEntity"));
    }

    [Fact]
    public async Task NewEntity_DifferentNamespace_NoDiagnostic()
    {
        // An [Entity] attribute from a different namespace should NOT trigger the diagnostic
        var test = @"
namespace SomeOther.Namespace
{
    [System.AttributeUsage(System.AttributeTargets.Class)]
    public class EntityAttribute : System.Attribute { }
}

[SomeOther.Namespace.Entity]
public class MyClass
{
    public string Name { get; set; }
}

class TestClass
{
    void Method()
    {
        var obj = new MyClass();
    }
}";
        await AnalyzerVerifier.VerifyAnalyzerAsync(test);
    }

    // =========================================================================
    // PRAG0680 — the type's own factory, which has to use 'new'
    // =========================================================================

    /// <summary>The factory the diagnostic recommends is not itself a violation of it.</summary>
    /// <remarks>
    ///     Generated factories are exempt through the generated-code flag. A hand-written one is not
    ///     generated code, so without its own exemption it would take the warning for doing exactly
    ///     what the message asks for, and the author would have no way to satisfy it.
    /// </remarks>
    [Fact]
    public async Task NewEntity_InsideItsOwnStaticFactory_ReportsNothing()
    {
        var test = EntityStub + @"
[Pragmatic.Persistence.Entity.Entity]
public partial class Order
{
    public string OrderNumber { get; set; }

    public static Order Create(string number) => new Order { OrderNumber = number };
}";
        await AnalyzerVerifier.VerifyAnalyzerAsync(test);
    }

    /// <summary>Target-typed new, which is what a factory usually writes.</summary>
    [Fact]
    public async Task ImplicitNew_InsideItsOwnStaticFactory_ReportsNothing()
    {
        var test = EntityStub + @"
[Pragmatic.Persistence.Entity.Entity]
public partial class Order
{
    public string OrderNumber { get; set; }

    public static Order Create(string number) => new() { OrderNumber = number };
}";
        await AnalyzerVerifier.VerifyAnalyzerAsync(test);
    }

    /// <summary>A factory that builds several, or asynchronously, is still a factory.</summary>
    [Fact]
    public async Task NewEntity_InsideAFactoryReturningACollection_ReportsNothing()
    {
        var test = EntityStub + @"
[Pragmatic.Persistence.Entity.Entity]
public partial class Order
{
    public string OrderNumber { get; set; }

    public static System.Collections.Generic.List<Order> CreateMany(string number)
        => new System.Collections.Generic.List<Order> { new Order { OrderNumber = number } };
}";
        await AnalyzerVerifier.VerifyAnalyzerAsync(test);
    }

    /// <summary>⚠️ The control: a static helper on ANOTHER type is still the case this exists for.</summary>
    /// <remarks>
    ///     Without this, the exemption could be written as "any static method" and every test above
    ///     would still pass while the diagnostic stopped catching the thing it is for.
    /// </remarks>
    [Fact]
    public async Task NewEntity_InAStaticHelperOnAnotherType_StillReportsDiagnostic()
    {
        var test = EntityStub + @"
[Pragmatic.Persistence.Entity.Entity]
public partial class Order
{
    public string OrderNumber { get; set; }
}

public static class OrderBuilder
{
    public static Order Build(string number) => {|#0:new Order { OrderNumber = number }|};
}";
        await AnalyzerVerifier.VerifyAnalyzerAsync(
            test,
            ExpectDiagnostic().WithLocation(0).WithArguments("Order"));
    }

    /// <summary>The second control: an instance method on the type itself is not a factory.</summary>
    [Fact]
    public async Task NewEntity_InAnInstanceMethodOfTheType_StillReportsDiagnostic()
    {
        var test = EntityStub + @"
[Pragmatic.Persistence.Entity.Entity]
public partial class Order
{
    public string OrderNumber { get; set; }

    public Order Duplicate() => {|#0:new Order { OrderNumber = OrderNumber }|};
}";
        await AnalyzerVerifier.VerifyAnalyzerAsync(
            test,
            ExpectDiagnostic().WithLocation(0).WithArguments("Order"));
    }
}
