using Pragmatic.SourceGen;
using Pragmatic.SourceGenerator.Core;
using Pragmatic.SourceGenerator.Features.Traits.Models;
using Pragmatic.SourceGenerator.Features.Traits;

namespace Pragmatic.SourceGenerator.Features.Traits.Templates;

/// <summary>
/// Generates comment DomainAction classes (Add, Update, Delete, Moderate).
/// The Invoker + SetDependencies are generated by ActionsFeature from the corresponding ActionModel.
/// </summary>
internal sealed partial class CommentActionsTemplate : CSharpTemplate
{
    private readonly CommentTraitModel _model;
    private readonly string _actionTypeName;
    private readonly CommentActionKind _kind;

    public CommentActionsTemplate(CommentTraitModel model, CommentActionKind kind)
    {
        _model = model;
        _kind = kind;
        _actionTypeName = kind switch
        {
            CommentActionKind.Add => $"Add{model.ParentTypeName}CommentAction",
            CommentActionKind.GetById => $"Get{model.ParentTypeName}CommentAction",
            CommentActionKind.Update => $"Update{model.ParentTypeName}CommentAction",
            CommentActionKind.Delete => $"Delete{model.ParentTypeName}CommentAction",
            CommentActionKind.Moderate => $"Moderate{model.ParentTypeName}CommentAction",
            CommentActionKind.ListPending => $"ListPending{model.ParentTypeName}CommentsAction",
            _ => throw new ArgumentOutOfRangeException(nameof(kind))
        };
    }

    protected override string? GeneratorName => "Pragmatic.SourceGenerator/Traits";
    protected override string? TriggerInfo => $"[HasComments] {_kind} action for {_model.ParentTypeName}";

    public override Artifact RenderOutput()
        => new(VirtualFolderHints.ForType(_actionTypeName, "Action", _model.ParentNamespace), ToSourceText());

    public override void RenderFile()
    {
        AddUsing("System.Linq");
        AddUsing("Microsoft.EntityFrameworkCore");
        AddUsing("Microsoft.Extensions.DependencyInjection");
        AddUsing("Pragmatic.Actions.Abstractions");
        AddUsing("Pragmatic.Actions.Attributes");
        // [BelongsTo<T>] lives in Persistence, not beside [DomainAction].
        AddUsing("Pragmatic.Persistence.Entity");
        AddUsing("Pragmatic.Identity");
        AddUsing("Pragmatic.Comments");
        AddUsing("Pragmatic.Result");
        AddUsing("Pragmatic.Result.Http");
        AddUsing("Pragmatic.Temporal.Clock");

        AppendNamespace(_model.ParentNamespace);
        AppendLine();

        var dtoName = $"{_model.CommentTypeName}Dto";
        var baseType = _kind switch
        {
            CommentActionKind.Add => "DomainAction<Guid>",
            CommentActionKind.GetById => $"DomainAction<{dtoName}>",
            CommentActionKind.ListPending => $"DomainAction<global::System.Collections.Generic.IReadOnlyList<{dtoName}>>",
            _ => "VoidDomainAction"
        };

        XmlSummary($"SG-generated action: {DescribeKind()} a comment on <see cref=\"{_model.ParentTypeName}\"/>.");
        AppendLine("[DomainAction]");
        if (_model.BoundaryFullTypeName is not null)
            AppendLine($"[BelongsTo<global::{_model.BoundaryFullTypeName}>]");

        Class(_actionTypeName, RenderBody,
            accessModifier: AccessModifier.Public,
            modifiers: new ClassModifiers { Partial = true, Sealed = true },
            baseType: baseType);
    }

    private string ViewInternalPermission => TraitPermissions.Slug(
        _model.BoundaryName, _model.ParentTypeName, TraitPermissions.CommentsGroup, TraitPermissions.ViewInternal);

    private string DescribeKind() => _kind switch
    {
        CommentActionKind.Add => "adds",
        CommentActionKind.GetById => "reads",
        CommentActionKind.Update => "updates",
        CommentActionKind.Delete => "soft-deletes",
        CommentActionKind.Moderate => "moderates",
        CommentActionKind.ListPending => "lists what awaits approval, as",
        _ => "manages"
    };

    private void RenderBody()
    {
        AppendLine("private DbContext _db = null!;");
        AppendLine("private ICurrentUser _currentUser = null!;");
        AppendLine("private IClock _clock = null!;");
        // The policy is optional, so it is resolved on demand from the application service
        // provider — injecting it directly would make it a required constructor dependency.
        AppendLine("private global::System.IServiceProvider _services = null!;");
        AppendLine();

        switch (_kind)
        {
            case CommentActionKind.Add: RenderAddBody(); break;
            case CommentActionKind.GetById: RenderGetByIdBody(); break;
            case CommentActionKind.Update: RenderUpdateBody(); break;
            case CommentActionKind.Delete: RenderDeleteBody(); break;
            case CommentActionKind.Moderate: RenderModerateBody(); break;
            case CommentActionKind.ListPending: RenderListPendingBody(); break;
        }

        if (_kind is CommentActionKind.Update or CommentActionKind.Delete)
            RenderCanModerate();
    }

    private void RenderAddBody()
    {
        AppendLine($"public required {_model.SimpleIdType} {_model.ParentTypeName}Id {{ get; init; }}");
        AppendLine("public required string Content { get; init; }");
        if (_model.AllowReplies)
            AppendLine("public Guid? ReplyToId { get; init; }");
        if (_model.SupportInternalNotes)
            AppendLine("public CommentVisibility Visibility { get; init; } = CommentVisibility.Public;");
        AppendLine();

        AppendLine("public override async Task<Result<Guid, IError>> Execute(CancellationToken ct = default)");
        Block(() =>
        {
            // MaxLength was only ever a column width, so an over-long body reached the database and
            // came back as a 500 (or a silent truncation) instead of a 400 naming the limit.
            AppendLine($"if (Content.Length > {_model.MaxLength})");
            IncreaseIndent();
            AppendLine($"return Result<Guid, IError>.Failure(new BadRequestError {{ Reason = \"Content exceeds the maximum length of {_model.MaxLength} characters.\" }});");
            DecreaseIndent();
            AppendLine();

            // Marking a comment Internal is writing to the staff's channel: without this anyone who
            // could comment could put a note there, and the readers of that channel would trust it.
            if (_model.SupportInternalNotes)
            {
                AppendLine("if (Visibility == CommentVisibility.Internal");
                AppendLine($"    && !await _currentUser.Authorization.HasPermissionAsync(\"{ViewInternalPermission}\", ct).ConfigureAwait(false))");
                IncreaseIndent();
                AppendLine($"return Result<Guid, IError>.Failure(ForbiddenError.MissingPermission(\"{ViewInternalPermission}\"));");
                DecreaseIndent();
                AppendLine();
            }

            RenderPolicyResolve();
            // The policy's own CommentRejectedError carries the reason and maps to 422; collapsing it
            // into a bare ForbiddenError told the caller only "forbidden", throwing away the one thing
            // the policy existed to say.
            AppendLine($"if (_policy is not null)");
            Block(() =>
            {
                AppendLine($"var _verdict = await _policy.CanAddAsync({_model.ParentTypeName}Id, Content, _currentUser.Id, ct);");
                AppendLine("if (_verdict.IsFailure)");
                IncreaseIndent();
                AppendLine("return Result<Guid, IError>.Failure(_verdict.Error);");
                DecreaseIndent();
            });
            AppendLine();
            AppendLine($"var comment = new {_model.CommentTypeName}");
            AppendLine("{");
            IncreaseIndent();
            AppendLine($"{_model.ParentFkPropertyName} = {_model.ParentTypeName}Id,");
            AppendLine("Content = Content,");
            AppendLine("AuthorId = _currentUser.Id,");
            AppendLine("AuthorName = _currentUser.DisplayName,");
            if (_model.AllowReplies) AppendLine("ReplyToId = ReplyToId,");
            AppendLine(_model.RequireApproval
                ? "Status = CommentStatus.PendingApproval,"
                : "Status = CommentStatus.Visible,");
            if (_model.SupportInternalNotes) AppendLine("Visibility = Visibility,");
            AppendLine("CreatedAt = _clock.UtcNow,");
            DecreaseIndent();
            AppendLine("};");
            AppendLine();
            AppendLine($"_db.Set<{_model.CommentTypeName}>().Add(comment);");
            AppendLine();
            AppendLine($"if (_policy is not null) await _policy.OnAddedAsync({_model.ParentTypeName}Id, comment.Id, ct);");
            AppendLine();
            AppendLine("return comment.Id;");
        });
    }

    private void RenderGetByIdBody()
    {
        var dtoName = $"{_model.CommentTypeName}Dto";
        // Parent FK is part of object-level auth: the comment must belong to the parent in the route.
        AppendLine($"public required {_model.SimpleIdType} {_model.ParentFkPropertyName} {{ get; init; }}");
        AppendLine("public required Guid CommentId { get; init; }");
        AppendLine();
        AppendLine($"public override async Task<Result<{dtoName}, IError>> Execute(CancellationToken ct = default)");
        Block(() =>
        {
            // The DbSet does not pass through the repository's row filters, so the InternalVisibility
            // filter the list relies on does not reach this read: it is applied here, or reading by id
            // is the way around it. Not found, rather than forbidden — the row is not there for them.
            var visibility = "";
            if (_model.SupportInternalNotes)
            {
                AppendLine($"var canViewInternal = await _currentUser.Authorization.HasPermissionAsync(\"{ViewInternalPermission}\", ct).ConfigureAwait(false);");
                visibility = " && (canViewInternal || e.Visibility != CommentVisibility.Internal)";
            }

            AppendLine($"var comment = await _db.Set<{_model.CommentTypeName}>()");
            AppendLine($"    .Where(e => e.Id == CommentId && e.{_model.ParentFkPropertyName} == {_model.ParentFkPropertyName} && !e.IsDeleted{visibility})");
            AppendLine($"    .Select({dtoName}.Projection)");
            AppendLine("    .FirstOrDefaultAsync(ct).ConfigureAwait(false);");
            AppendLine($"if (comment is null)");
            IncreaseIndent();
            AppendLine($"return Result<{dtoName}, IError>.Failure(NotFoundError.For(\"{_model.CommentTypeName}\", CommentId.ToString()));");
            DecreaseIndent();
            AppendLine("return comment;");
        });
    }

    private void RenderUpdateBody()
    {
        AppendLine($"public required {_model.SimpleIdType} {_model.ParentFkPropertyName} {{ get; init; }}");
        AppendLine("public required Guid CommentId { get; init; }");
        AppendLine("public required string Content { get; init; }");
        AppendLine();

        AppendLine("public override async Task<VoidResult<IError>> Execute(CancellationToken ct = default)");
        Block(() =>
        {
            AppendLine($"if (Content.Length > {_model.MaxLength})");
            IncreaseIndent();
            AppendLine($"return VoidResult<IError>.Failure(new BadRequestError {{ Reason = \"Content exceeds the maximum length of {_model.MaxLength} characters.\" }});");
            DecreaseIndent();
            AppendLine();

            RenderPolicyResolve();
            RenderFindComment();

            // Policy check
            AppendLine("if (_policy is not null)");
            Block(() =>
            {
                AppendLine("var _verdict = await _policy.CanEditAsync(CommentId, _currentUser.Id, ct);");
                AppendLine("if (_verdict.IsFailure)");
                IncreaseIndent();
                AppendLine("return VoidResult<IError>.Failure(_verdict.Error);");
                DecreaseIndent();
            });
            AppendLine();

            // Ownership, unless the caller can moderate. Without the bypass the update permission was
            // insufficient by definition: whoever held it and was not the author always got a 403.
            AppendLine("if (_policy is null && comment.AuthorId != _currentUser.Id && !await CanModerateAsync(ct))");
            IncreaseIndent();
            AppendLine("return VoidResult<IError>.Failure(new ForbiddenError { Resource = \"Comment\" });");
            DecreaseIndent();
            AppendLine();

            // Edit window check
            if (_model.EditWindowMinutes >= 0)
            {
                AppendLine($"var editDeadline = comment.CreatedAt.AddMinutes({_model.EditWindowMinutes});");
                AppendLine("if (_clock.UtcNow > editDeadline)");
                IncreaseIndent();
                AppendLine("return VoidResult<IError>.Failure(new ForbiddenError { Resource = \"Comment edit window\" });");
                DecreaseIndent();
                AppendLine();
            }

            AppendLine("comment.Content = Content;");
            AppendLine("comment.IsEdited = true;");
            AppendLine("comment.UpdatedAt = _clock.UtcNow;");
            AppendLine("comment.UpdatedBy = _currentUser.Id;");
            AppendLine("return Success;");
        });
    }

    private void RenderDeleteBody()
    {
        AppendLine($"public required {_model.SimpleIdType} {_model.ParentFkPropertyName} {{ get; init; }}");
        AppendLine("public required Guid CommentId { get; init; }");
        AppendLine();

        AppendLine("public override async Task<VoidResult<IError>> Execute(CancellationToken ct = default)");
        Block(() =>
        {
            RenderPolicyResolve();
            RenderFindComment();
            AppendLine("if (_policy is not null)");
            Block(() =>
            {
                AppendLine("var _verdict = await _policy.CanDeleteAsync(CommentId, _currentUser.Id, ct);");
                AppendLine("if (_verdict.IsFailure)");
                IncreaseIndent();
                AppendLine("return VoidResult<IError>.Failure(_verdict.Error);");
                DecreaseIndent();
            });
            AppendLine();

            // Same rule as the update: the author, or someone who can moderate. Gated by the delete
            // permission alone, deletion would let anyone holding it remove another author's
            // comment — asymmetric with editing, and surprising.
            AppendLine("if (_policy is null && comment.AuthorId != _currentUser.Id && !await CanModerateAsync(ct))");
            IncreaseIndent();
            AppendLine("return VoidResult<IError>.Failure(new ForbiddenError { Resource = \"Comment\" });");
            DecreaseIndent();
            AppendLine();
            AppendLine("comment.IsDeleted = true;");
            AppendLine("comment.DeletedAt = _clock.UtcNow;");
            AppendLine("comment.DeletedBy = _currentUser.Id;");
            AppendLine("return Success;");
        });
    }

    /// <summary>
    ///     Emits the moderator check used by update and delete. <c>IPermissionChecker</c> is optional —
    ///     it only exists when Identity is in play — and its absence simply means nobody is a moderator,
    ///     which leaves the author-only rule intact.
    /// </summary>
    private void RenderCanModerate()
    {
        AppendLine();
        XmlSummary("True when the caller holds the moderate permission for these comments.");
        AppendLine("private async Task<bool> CanModerateAsync(CancellationToken ct)");
        Block(() =>
        {
            AppendLine("var checker = (global::Pragmatic.Authorization.IPermissionChecker?)_services.GetService(typeof(global::Pragmatic.Authorization.IPermissionChecker));");
            AppendLine("if (checker is null) return false;");
            AppendLine($"return await checker.HasPermissionAsync(\"{TraitPermissions.Slug(_model.BoundaryName, _model.ParentTypeName, TraitPermissions.CommentsGroup, TraitPermissions.Moderate)}\", ct).ConfigureAwait(false);");
        });
    }

    private void RenderPolicyResolve()
    {
        // Must come from the application container: the DbContext's IInfrastructure provider is
        // EF Core's *internal* one, where a consumer's AddScoped<ICommentPolicy<T>,…> never lands.
        AppendLine($"var _policy = (ICommentPolicy<{_model.SimpleIdType}>?)_services.GetService(typeof(ICommentPolicy<{_model.SimpleIdType}>));");
    }

    private void RenderFindComment(bool ignoreQueryFilters = false)
    {
        // Object-level auth: scope the lookup to the parent in the route, not just the child id.
        AppendLine($"var comment = await _db.Set<{_model.CommentTypeName}>()");
        if (ignoreQueryFilters)
        {
            // A moderator must reach exactly the comments the filter hides — a pending one to approve,
            // a rejected one to reinstate. Soft-deleted ones stay out: undelete is not moderation.
            AppendLine("    .IgnoreQueryFilters()");
            AppendLine("    .Where(e => !e.IsDeleted)");
        }

        AppendLine($"    .Where(e => e.Id == CommentId && e.{_model.ParentFkPropertyName} == {_model.ParentFkPropertyName})");
        AppendLine("    .FirstOrDefaultAsync(ct).ConfigureAwait(false);");
        AppendLine("if (comment is null)");
        IncreaseIndent();
        AppendLine($"return VoidResult<IError>.Failure(NotFoundError.For(\"{_model.CommentTypeName}\", CommentId.ToString()));");
        DecreaseIndent();
        AppendLine();
    }
}

internal enum CommentActionKind
{
    Add,
    GetById,
    Update,
    Delete,
    Moderate,
    ListPending,
}
