using Pragmatic.SourceGen;
using Pragmatic.SourceGenerator.Core;
using Pragmatic.SourceGenerator.Features.Traits.Models;

namespace Pragmatic.SourceGenerator.Features.Traits.Templates;

/// <summary>
/// Generates a partial class on the parent entity with <c>ICollection&lt;{Parent}Comment&gt; Comments</c> navigation.
/// </summary>
internal sealed class ParentTraitNavigationTemplate : CSharpTemplate
{
    private readonly CommentTraitModel _model;

    public ParentTraitNavigationTemplate(CommentTraitModel model) => _model = model;

    protected override string? GeneratorName => "Pragmatic.SourceGenerator/Traits";
    protected override string? TriggerInfo => $"[HasComments] navigation on {_model.ParentTypeName}";

    public override Artifact RenderOutput()
        => new(VirtualFolderHints.ForType(_model.ParentTypeName, "TraitNavigations", _model.ParentNamespace), ToSourceText());

    public override void RenderFile()
    {
        AppendNamespace(_model.ParentNamespace);
        AppendLine();

        Class(_model.ParentTypeName, RenderBody,
            accessModifier: AccessModifier.Public,
            modifiers: new ClassModifiers { Partial = true });
    }

    private void RenderBody()
    {
        XmlSummary($"Comments on this {_model.ParentTypeName}. Auto-generated by [HasComments] trait.");
        AppendLine($"public ICollection<{_model.CommentTypeName}> Comments {{ get; set; }} = new List<{_model.CommentTypeName}>();");
    }
}
