using Pragmatic.SourceGen;
using Pragmatic.SourceGenerator.Core;
using Pragmatic.SourceGenerator.Features.Traits.Models;

namespace Pragmatic.SourceGenerator.Features.Traits.Templates;

/// <summary>
/// Generates tag DomainAction classes (Add, Remove).
/// The Invoker + SetDependencies are generated by ActionsFeature from the corresponding ActionModel.
/// </summary>
internal sealed class TagActionsTemplate : CSharpTemplate
{
    private readonly TagTraitModel _model;
    private readonly string _actionTypeName;
    private readonly TagActionKind _kind;

    public TagActionsTemplate(TagTraitModel model, TagActionKind kind)
    {
        _model = model;
        _kind = kind;
        _actionTypeName = kind switch
        {
            TagActionKind.Add => $"Add{model.ParentTypeName}TagAction",
            TagActionKind.Remove => $"Remove{model.ParentTypeName}TagAction",
            _ => throw new ArgumentOutOfRangeException(nameof(kind))
        };
    }

    protected override string? GeneratorName => "Pragmatic.SourceGenerator/Traits";
    protected override string? TriggerInfo => $"[HasTags] {_kind} action for {_model.ParentTypeName}";

    public override Artifact RenderOutput()
        => new(VirtualFolderHints.ForType(_actionTypeName, "Action", _model.ParentNamespace), ToSourceText());

    public override void RenderFile()
    {
        AddUsing("System.Linq");
        AddUsing("Microsoft.EntityFrameworkCore");
        AddUsing("Microsoft.Extensions.DependencyInjection");
        AddUsing("Pragmatic.Actions.Abstractions");
        AddUsing("Pragmatic.Actions.Attributes");
        // [BelongsTo<T>] lives in Persistence, not beside [DomainAction].
        AddUsing("Pragmatic.Persistence.Entity");
        AddUsing("Pragmatic.Identity");
        AddUsing("Pragmatic.Tags");
        AddUsing("Pragmatic.Result");
        AddUsing("Pragmatic.Result.Http");
        AddUsing("Pragmatic.Temporal.Clock");

        AppendNamespace(_model.ParentNamespace);
        AppendLine();

        var baseType = _kind == TagActionKind.Add
            ? "DomainAction<Guid>"
            : "VoidDomainAction";

        XmlSummary($"SG-generated action: {(_kind == TagActionKind.Add ? "adds" : "removes")} a tag on <see cref=\"{_model.ParentTypeName}\"/>.");
        AppendLine("[DomainAction]");
        if (_model.BoundaryFullTypeName is not null)
            AppendLine($"[BelongsTo<global::{_model.BoundaryFullTypeName}>]");

        Class(_actionTypeName, RenderBody,
            accessModifier: AccessModifier.Public,
            modifiers: new ClassModifiers { Partial = true, Sealed = true },
            baseType: baseType);
    }

    private void RenderBody()
    {
        AppendLine("private DbContext _db = null!;");
        if (_kind == TagActionKind.Add)
        {
            AppendLine("private ICurrentUser _currentUser = null!;");
            AppendLine("private IClock _clock = null!;");
        }

        // The policy is optional, so it is resolved on demand from the application service
        // provider — injecting it directly would make it a required constructor dependency.
        AppendLine("private global::System.IServiceProvider _services = null!;");
        AppendLine();

        switch (_kind)
        {
            case TagActionKind.Add: RenderAddBody(); break;
            case TagActionKind.Remove: RenderRemoveBody(); break;
        }

        if (_kind == TagActionKind.Add && _model.MaxPerEntity > 0)
            RenderSerializationConflictDetector();
    }

    /// <summary>
    ///     Emits the predicate that tells a lost serialization race from a genuine failure. SQLSTATE
    ///     40001 (serialization_failure) and 40P01 (deadlock_detected) are the standard codes a
    ///     database uses to say "you two collided, one of you must retry"; anything else is rethrown
    ///     rather than dressed up as a conflict.
    /// </summary>
    private void RenderSerializationConflictDetector()
    {
        AppendLine();
        XmlSummary("True when the exception is the database refusing one of two colliding transactions.");
        AppendLine("private static bool IsSerializationConflict(global::System.Exception? ex)");
        Block(() =>
        {
            AppendLine("for (var e = ex; e is not null; e = e.InnerException)");
            IncreaseIndent();
            AppendLine("if (e is global::System.Data.Common.DbException db && db.SqlState is \"40001\" or \"40P01\")");
            IncreaseIndent();
            AppendLine("return true;");
            DecreaseIndent();
            DecreaseIndent();
            AppendLine("return false;");
        });
    }

    /// <summary>
    ///     Emits <c>Execute</c> as the body run inside the context's execution strategy, and opens the
    ///     body's own method, <c>ExecuteOnceAsync</c>, for the caller to fill.
    /// </summary>
    /// <remarks>
    ///     Both bodies open a transaction of their own, and an execution strategy that retries — a generated
    ///     host configures one for every server provider — refuses a transaction opened outside
    ///     it. The whole body can run again: nothing in it reaches outside the database before the commit,
    ///     re-applying a tag the entity already carries is a no-op, and a retry starts from a cleared change
    ///     tracker so the failed attempt's link is not written twice. Inside a unit already running, the
    ///     strategy passes through and there is no retry of its own.
    /// </remarks>
    private void RenderRetriableExecute(string returnType)
    {
        AppendLine($"public override Task<{returnType}> Execute(CancellationToken ct = default)");
        Block(() =>
        {
            AppendLine("var attempts = 0;");
            AppendLine("return _db.Database.CreateExecutionStrategy().ExecuteAsync(token =>");
            AppendLine("{");
            IncreaseIndent();
            AppendLine("if (attempts++ > 0)");
            AppendLine("    _db.ChangeTracker.Clear();");
            AppendLine("return ExecuteOnceAsync(token);");
            DecreaseIndent();
            AppendLine("}, ct);");
        });
        AppendLine();
        AppendLine($"private async Task<{returnType}> ExecuteOnceAsync(CancellationToken ct)");
    }

    private void RenderAddBody()
    {
        AppendLine($"public required {_model.SimpleIdType} {_model.ParentFkPropertyName} {{ get; init; }}");
        AppendLine("public required string TagValue { get; init; }");
        AppendLine();

        RenderRetriableExecute("Result<Guid, IError>");
        Block(() =>
        {
            RenderPolicyResolve();

            // Validation gate — reject disallowed tag values (ITagPolicy.IsAllowedAsync).
            AppendLine("if (_policy is not null && !await _policy.IsAllowedAsync(TagValue, ct).ConfigureAwait(false))");
            IncreaseIndent();
            AppendLine("return Result<Guid, IError>.Failure(new ForbiddenError { Resource = \"Tag value not allowed\" });");
            DecreaseIndent();
            AppendLine();

            // Normalize tag value — policy override wins, else default trim/lowercase.
            var defaultNormalize = _model.CaseSensitive
                ? "TagValue.Trim()"
                : "TagValue.Trim().ToLowerInvariant()";
            if (_model.CaseSensitive)
            {
                // ITagPolicy.Normalize lower-cases by default, so ANY registered policy that does not
                // override it silently undid CaseSensitive = true. The option is the entity's decision
                // and wins: a policy that genuinely wants to fold case must do it in its own Normalize
                // and the entity must not ask for case sensitivity.
                AppendLine($"var normalizedValue = {defaultNormalize};");
            }
            else
            {
                AppendLine($"var normalizedValue = _policy is not null ? _policy.Normalize(TagValue) : {defaultNormalize};");
            }
            AppendLine("var displayValue = TagValue.Trim();");
            AppendLine();

            RenderLimitTransactionOpen();

            // Find or create tag
            var scope = _model.ScopeOverride is not null
                ? $"\"{_model.ScopeOverride}\""
                : $"\"{_model.ParentTypeName}\"";

            AppendLine($"var tag = await _db.Set<{_model.TagTypeName}>()");
            AppendLine($"    .FirstOrDefaultAsync(t => t.Value == normalizedValue && t.Scope == {scope}, ct).ConfigureAwait(false);");
            AppendLine("var isNewTag = tag is null;");
            AppendLine();

            // Idempotency is checked BEFORE the per-entity limit: re-applying a tag the entity already
            // carries adds nothing, so an entity sitting exactly at the limit must still answer with the
            // existing tag id instead of a 403 about a limit this call would not cross.
            AppendLine("if (tag is not null)");
            Block(() =>
            {
                AppendLine($"var alreadyTagged = await _db.Set<{_model.JunctionTypeName}>()");
                AppendLine($"    .AnyAsync(j => j.{_model.ParentFkPropertyName} == {_model.ParentFkPropertyName} && j.TagId == tag.Id, ct).ConfigureAwait(false);");
                AppendLine("if (alreadyTagged)");
                IncreaseIndent();
                AppendLine("return tag.Id; // idempotent — already tagged");
                DecreaseIndent();
            });
            AppendLine();

            // Check max per entity — only now, when the call would genuinely add one.
            if (_model.MaxPerEntity > 0)
            {
                AppendLine($"var currentCount = await _db.Set<{_model.JunctionTypeName}>()");
                AppendLine($"    .CountAsync(j => j.{_model.ParentFkPropertyName} == {_model.ParentFkPropertyName}, ct).ConfigureAwait(false);");
                AppendLine($"if (currentCount >= {_model.MaxPerEntity})");
                IncreaseIndent();
                AppendLine($"return Result<Guid, IError>.Failure(new ForbiddenError {{ Resource = \"Tag limit ({_model.MaxPerEntity})\" }});");
                DecreaseIndent();
                AppendLine();
            }

            AppendLine("if (tag is null)");
            Block(() =>
            {
                // AllowCustom == false → curated taxonomy: never mint tags on the fly.
                if (!_model.AllowCustom)
                {
                    AppendLine($"return Result<Guid, IError>.Failure(NotFoundError.For(\"{_model.TagTypeName}\", normalizedValue));");
                    return;
                }

                AppendLine($"tag = new {_model.TagTypeName}");
                AppendLine("{");
                IncreaseIndent();
                AppendLine("Value = normalizedValue,");
                AppendLine("DisplayValue = displayValue,");
                AppendLine($"Scope = {scope},");
                AppendLine("CreatedAt = _clock.UtcNow,");
                AppendLine("CreatedBy = _currentUser.Id,");
                AppendLine("UsageCount = 1, // first usage — the junction below is created in the same commit");
                DecreaseIndent();
                AppendLine("};");
                AppendLine($"_db.Set<{_model.TagTypeName}>().Add(tag);");
            });
            AppendLine();

            // Create junction
            AppendLine($"var junction = new {_model.JunctionTypeName}");
            AppendLine("{");
            IncreaseIndent();
            AppendLine($"{_model.ParentFkPropertyName} = {_model.ParentFkPropertyName},");
            AppendLine("TagId = tag.Id,");
            AppendLine("AddedAt = _clock.UtcNow,");
            AppendLine("AddedBy = _currentUser.Id,");
            DecreaseIndent();
            AppendLine("};");
            AppendLine($"_db.Set<{_model.JunctionTypeName}>().Add(junction);");
            AppendLine();
            // An in-memory `UsageCount++` on the tracked entity is a read-modify-write that loses
            // updates under concurrent tagging, so an existing tag is incremented DB-side. That
            // statement executes immediately, while the junction row would only be written by the
            // invoker's SaveChanges afterwards: if that commit failed, the counter stayed raised
            // forever. Both now run inside one transaction owned by this action.
            if (_model.MaxPerEntity > 0)
            {
                // Serializable turns a lost race into a refusal by the database. Surfacing it as a 409
                // rather than a 500 is the difference between "retry this" and "something broke".
                AppendLine("try");
                Block(() =>
                {
                    RenderTransactionalCommit(
                        () =>
                        {
                            AppendLine("if (!isNewTag)");
                            Block(() =>
                            {
                                AppendLine($"await _db.Set<{_model.TagTypeName}>().Where(t => t.Id == tag.Id)");
                                AppendLine("    .ExecuteUpdateAsync(s => s.SetProperty(t => t.UsageCount, t => t.UsageCount + 1), ct).ConfigureAwait(false);");
                            });
                        });
                });
                AppendLine("catch (global::System.Exception ex) when (IsSerializationConflict(ex))");
                Block(() =>
                {
                    AppendLine($"return Result<Guid, IError>.Failure(new ConflictError {{ EntityType = \"{_model.JunctionTypeName}\", EntityId = {_model.ParentFkPropertyName}.ToString() }});");
                });
                AppendLine();
            }
            else
            {
                RenderTransactionalCommit(
                    () =>
                    {
                        AppendLine("if (!isNewTag)");
                        Block(() =>
                        {
                            AppendLine($"await _db.Set<{_model.TagTypeName}>().Where(t => t.Id == tag.Id)");
                            AppendLine("    .ExecuteUpdateAsync(s => s.SetProperty(t => t.UsageCount, t => t.UsageCount + 1), ct).ConfigureAwait(false);");
                        });
                    });
            }
            AppendLine();
            AppendLine($"if (_policy is not null) await _policy.OnTagAddedAsync({_model.ParentFkPropertyName}, tag.Id, normalizedValue, ct).ConfigureAwait(false);");
            AppendLine("return tag.Id;");
        });
    }

    private void RenderRemoveBody()
    {
        AppendLine($"public required {_model.SimpleIdType} {_model.ParentFkPropertyName} {{ get; init; }}");
        AppendLine("public required Guid TagId { get; init; }");
        AppendLine();

        RenderRetriableExecute("VoidResult<IError>");
        Block(() =>
        {
            RenderPolicyResolveVoid();

            AppendLine($"var junction = await _db.Set<{_model.JunctionTypeName}>()");
            AppendLine($"    .FirstOrDefaultAsync(j => j.{_model.ParentFkPropertyName} == {_model.ParentFkPropertyName} && j.TagId == TagId, ct).ConfigureAwait(false);");
            AppendLine();
            AppendLine("if (junction is null)");
            IncreaseIndent();
            AppendLine($"return VoidResult<IError>.Failure(NotFoundError.For(\"{_model.JunctionTypeName}\", $\"{{TagId}}\"));");
            DecreaseIndent();
            AppendLine();
            AppendLine($"_db.Set<{_model.JunctionTypeName}>().Remove(junction);");
            AppendLine();
            AppendLine($"var tag = await _db.Set<{_model.TagTypeName}>().FindAsync(new object[] {{ TagId }}, ct).ConfigureAwait(false);");
            AppendLine();
            // Same reasoning as the add: the DB-side decrement and the junction removal must land
            // together, or a failed commit leaves the counter permanently below the real usage.
            RenderTransactionalCommit(
                () =>
                {
                    AppendLine($"await _db.Set<{_model.TagTypeName}>().Where(t => t.Id == TagId && t.UsageCount > 0)");
                    AppendLine("    .ExecuteUpdateAsync(s => s.SetProperty(t => t.UsageCount, t => t.UsageCount - 1), ct).ConfigureAwait(false);");
                },
                () =>
                {
                    // A curated taxonomy (AllowCustom = false) is seeded by the application and recreated by
                    // no endpoint: deleting a tag whose last link went would erode it for good.
                    if (!_model.AllowCustom)
                        return;

                    // A tag nobody uses is noise: with AllowCustom on every typo would otherwise leave a
                    // permanent row, and no endpoint curates the catalogue. This runs AFTER the save —
                    // the junction row must already be gone for the check to mean anything — but still
                    // inside the transaction, so unlink and cleanup commit together.
                    AppendLine($"var stillLinked = await _db.Set<{_model.JunctionTypeName}>()");
                    AppendLine("    .AnyAsync(j => j.TagId == TagId, ct).ConfigureAwait(false);");
                    AppendLine("if (!stillLinked)");
                    Block(() =>
                    {
                        AppendLine($"await _db.Set<{_model.TagTypeName}>().Where(t => t.Id == TagId && t.UsageCount <= 0)");
                        AppendLine("    .ExecuteDeleteAsync(ct).ConfigureAwait(false);");
                    });
                });
            AppendLine();
            // Commit is owned by the DomainActionInvoker (single SaveChangesAsync after Execute). Do NOT save here.
            AppendLine($"if (_policy is not null) await _policy.OnTagRemovedAsync({_model.ParentFkPropertyName}, TagId, tag?.Value ?? string.Empty, ct).ConfigureAwait(false);");
            AppendLine("return Success;");
        });
    }


    /// <summary>
    ///     Opens the transaction that makes the per-entity limit enforceable.
    ///     <para>
    ///     Counting and inserting are two statements: under READ COMMITTED two concurrent callers both
    ///     read "one below the limit" and both insert, so the limit could be crossed. Serializable is
    ///     what makes the pair indivisible — the database refuses one of them rather than letting both
    ///     through. It is scoped to the add path and only when a limit is configured, because that is
    ///     the only place where the read has to stay true until the write lands.
    ///     </para>
    /// </summary>
    private void RenderLimitTransactionOpen()
    {
        if (_model.MaxPerEntity <= 0)
            return;

        AppendLine("await using var _tx = await _db.Database.BeginTransactionAsync(");
        AppendLine("    global::System.Data.IsolationLevel.Serializable, ct).ConfigureAwait(false);");
        AppendLine();
    }

    /// <summary>
    ///     Renders the pending changes and <paramref name="renderSideEffects"/> as one transaction.
    ///     <para>
    ///     `ExecuteUpdate` runs immediately in its own implicit transaction, while entities added to the
    ///     change tracker are written by the invoker's single <c>SaveChangesAsync</c> after
    ///     <c>Execute</c> returns. Those two are not atomic with respect to each other, which is how a
    ///     usage counter could be raised for a link that was never inserted.
    ///     </para>
    /// </summary>
    /// <param name="renderSideEffects">Statements that must land with the pending changes.</param>
    /// <param name="renderAfterSave">Statements that need the save to have happened first.</param>
    private void RenderTransactionalCommit(Action renderSideEffects, Action? renderAfterSave = null)
    {
        // The add path already opened one for the limit; opening a second here would nest.
        if (!(_kind == TagActionKind.Add && _model.MaxPerEntity > 0))
            AppendLine("await using var _tx = await _db.Database.BeginTransactionAsync(ct).ConfigureAwait(false);");
        renderSideEffects();
        AppendLine("await _db.SaveChangesAsync(ct).ConfigureAwait(false);");
        if (renderAfterSave is not null)
        {
            AppendLine();
            renderAfterSave();
            AppendLine();
        }

        AppendLine("await _tx.CommitAsync(ct).ConfigureAwait(false);");
    }

    private void RenderPolicyResolve()
        // Must come from the application container: the DbContext's IInfrastructure provider is
        // EF Core's *internal* one, where a consumer's AddScoped<ITagPolicy<T>,…> never lands.
        => AppendLine($"var _policy = (ITagPolicy<{_model.SimpleIdType}>?)_services.GetService(typeof(ITagPolicy<{_model.SimpleIdType}>));");

    private void RenderPolicyResolveVoid() => RenderPolicyResolve();
}

internal enum TagActionKind
{
    Add,
    Remove
}
