<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- Exclude shared testing code (no generator in this module) -->
    <ExcludeSharedTesting>true</ExcludeSharedTesting>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Pragmatic.Ensure.Result\Pragmatic.Ensure.Result.csproj" />
  </ItemGroup>

</Project>
