using Pragmatic.Persistence.Entity;

namespace Pragmatic.Persistence.EFCore.Samples.Attachments;

/// <summary>
///     A comment that can hang off different owner entity types.
///     <c>[PolymorphicAttachment]</c> makes the SG add <c>OwnerType</c> / <c>OwnerId</c> columns
///     and a <c>CommentNoteAttachmentExtensions</c> static class. Each <c>[Attachable&lt;T&gt;]</c>
///     adds a typed filter — here <c>ForTicket()</c> and <c>ForArticle()</c>, plus the generic
///     <c>ForOwner&lt;TOwner&gt;()</c>.
/// </summary>
[Entity]
[PolymorphicAttachment]
[Attachable<Ticket>]
[Attachable<Article>]
public partial class CommentNote : IEntity
{
    public Guid PersistenceId { get; set; } = Guid.CreateVersion7();

    public Guid Id => PersistenceId;

    public string Text { get; set; } = "";

    // OwnerType (e.g. "Ticket") and OwnerId are generated by [PolymorphicAttachment],
    // together with the CommentNoteAttachmentExtensions filters (ForOwner<T>/ForTicket/ForArticle).
}
