using System.Collections.Immutable;
using Pragmatic.SourceGen;
using Pragmatic.SourceGenerator.Core;
using Pragmatic.SourceGenerator.Features.Persistence.Models;
using Pragmatic.SourceGenerator.Features.Resource.Models;

namespace Pragmatic.SourceGenerator.Features.Resource.Templates;

/// <summary>
/// Generates the query class declaration for Resource Read/List.
/// The Apply() method is generated by QueryFeature from the injected QueryModel.
/// </summary>
internal sealed class ResourceQueryTemplate : CSharpTemplate
{
    private readonly ResourceCrudModel _model;
    private readonly ResourceQueryKind _kind;
    private readonly string _queryTypeName;

    public ResourceQueryTemplate(ResourceCrudModel model, ResourceQueryKind kind)
    {
        _model = model;
        _kind = kind;
        _queryTypeName = kind switch
        {
            ResourceQueryKind.List => $"ResourceList{model.Resource.TypeName}Query",
            ResourceQueryKind.Search => $"ResourceSearch{model.Resource.TypeName}Query",
            ResourceQueryKind.Read => ReadTypeName(model.Resource.TypeName),
            ResourceQueryKind.ReadByLogicKey => ReadByLogicKeyTypeName(model),
            _ => $"ResourceList{model.Resource.TypeName}Query"
        };
    }

    protected override string? GeneratorName => "Pragmatic.SourceGenerator/Resource";
    protected override string? TriggerInfo => $"[Resource] {_kind} query for {_model.Resource.TypeName}";

    public override Artifact RenderOutput()
        => new($"_Resource.{_model.Resource.TypeName}.{HintSuffix}.g.cs", ToSourceText());

    /// <summary>
    ///     The hint carries the logic key's name rather than the kind.
    /// </summary>
    /// <remarks>
    ///     Two reads coexist for one entity, by id and by key. A duplicate hint is not an error Roslyn
    ///     stops on: it discards the <b>entire</b> output of the generator and reports CS8785 as a
    ///     warning, so the build passes with every generated file missing.
    /// </remarks>
    private string HintSuffix => _kind == ResourceQueryKind.ReadByLogicKey
        ? $"ReadBy{_model.LogicKeyName}"
        : _kind.ToString();

    public override void RenderFile()
    {
        AddUsing("Pragmatic.Persistence.Query");
        AddUsing("Pragmatic.Persistence.Query.Attributes");
        AppendNamespace(_model.Resource.Namespace);
        AppendLine();

        var entityName = _model.Resource.TypeName;

        switch (_kind)
        {
            case ResourceQueryKind.List: RenderListQuery(entityName); break;
            case ResourceQueryKind.Search: RenderSearchQuery(entityName); break;
            case ResourceQueryKind.Read: RenderReadQuery(entityName); break;
            case ResourceQueryKind.ReadByLogicKey: RenderReadByLogicKeyQuery(entityName); break;
        }
    }

    /// <summary>
    ///     States the permission and the shape in force, and whether either is the developer's own.
    /// </summary>
    private void RenderDecorationRemark(ResourceDtoRef answersWith)
    {
        var scaffolded = new[]
        {
            PermissionNaming.ValueForEntityMember(
                _model.Resource.BoundaryName?.ToLowerInvariant(), _model.Resource.TypeName, "read"),
        };

        foreach (var line in ResourceDecorationRemark.Lines(
                     _model.DecorationOf(_queryTypeName), _queryTypeName, scaffolded,
                     answersWith.FullTypeName))
            AppendLine(line);
    }

    /// <summary>The type name of the by-id read query, so the endpoint and the model agree on it.</summary>
    public static string ReadTypeName(string entityTypeName) => $"ResourceRead{entityTypeName}Query";

    /// <summary>The type name of the by-logic-key read query.</summary>
    public static string ReadByLogicKeyTypeName(ResourceCrudModel model)
        => $"ResourceReadBy{model.LogicKeyName}{model.Resource.TypeName}Query";

    private void RenderReadQuery(string entityName)
    {
        var dto = _model.DtoFor(_queryTypeName, _model.ScaffoldedReadDto);
        var idType = SimpleName(_model.Resource.IdType);

        XmlSummary($"SG-generated: reads one <see cref=\"{entityName}\"/> by id.");
        RenderDecorationRemark(dto);
        AppendLine($"[Query<{entityName}, {dto.Qualified}>(Single = true)]");
        Class(_queryTypeName, () => AppendLine($"public {idType} Id {{ get; init; }}"),
            accessModifier: AccessModifier.Public,
            modifiers: new ClassModifiers { Partial = true });
    }

    private void RenderReadByLogicKeyQuery(string entityName)
    {
        var dto = _model.DtoFor(_queryTypeName, _model.ScaffoldedReadDto);

        XmlSummary($"SG-generated: reads one <see cref=\"{entityName}\"/> by {_model.LogicKeyName}.");
        RenderDecorationRemark(dto);
        AppendLine($"[Query<{entityName}, {dto.Qualified}>(Single = true)]");
        Class(_queryTypeName,
            () => AppendLine($"public {_model.LogicKeyType ?? "string"} {_model.LogicKeyName} {{ get; init; }} = default!;"),
            accessModifier: AccessModifier.Public,
            modifiers: new ClassModifiers { Partial = true });
    }

    private static string SimpleName(string typeName)
    {
        var dot = typeName.LastIndexOf('.');
        return dot < 0 ? typeName : typeName.Substring(dot + 1);
    }

    private void RenderListQuery(string entityName)
    {
        var dto = _model.DtoFor(_queryTypeName, _model.ScaffoldedListItemDto);

        XmlSummary($"SG-generated: lists <see cref=\"{entityName}\"/> with pagination.");
        RenderDecorationRemark(dto);
        AppendLine($"[Query<{entityName}, {dto.Qualified}>]");
        Class(_queryTypeName, () =>
        {
            AppendLine("public int Page { get; init; } = 1;");
            AppendLine("public int PageSize { get; init; } = 20;");
        },
        accessModifier: AccessModifier.Public,
        modifiers: new ClassModifiers { Partial = true });
    }

    private void RenderSearchQuery(string entityName)
    {
        var dto = _model.DtoFor(_queryTypeName, _model.ScaffoldedListItemDto);

        XmlSummary($"SG-generated: searches <see cref=\"{entityName}\"/> by text fields with pagination.");
        RenderDecorationRemark(dto);
        AppendLine($"[Query<{entityName}, {dto.Qualified}>]");
        Class(_queryTypeName, () =>
        {
            // Only the ones this generator still owns. A developer who declared filters on their own
            // part declared the properties too, so emitting them here would be the same member twice.
            foreach (var filter in ScaffoldedSearchFilters(_model))
            {
                AppendLine($"[Filter(Operator = FilterOperator.{filter.Operator})]");
                AppendLine($"public {filter.PropertyType} {filter.PropertyName} {{ get; init; }}");
                AppendLine();
            }

            AppendLine("[Sort(DefaultDirection = global::Pragmatic.Persistence.Query.SortDirection.Ascending)]");
            AppendLine("public SortDirection? IdSort { get; init; }");
            AppendLine();
            AppendLine("public int Page { get; init; } = 1;");
            AppendLine("public int PageSize { get; init; } = 20;");
        },
        accessModifier: AccessModifier.Public,
        modifiers: new ClassModifiers { Partial = true });
    }

    /// <summary>
    ///     The search filters this generator declares itself — none, once the developer has declared
    ///     their own, because those are properties on their part of the same class.
    /// </summary>
    private static IEnumerable<QueryPropertyModel> ScaffoldedSearchFilters(ResourceCrudModel model)
        => model.DeclaredSearchFilters is { IsDefaultOrEmpty: false }
            ? ImmutableArray<QueryPropertyModel>.Empty
            : model.SearchFilters.AsImmutableArray();

    /// <summary>
    /// Builds a QueryModel for the List query.
    /// </summary>
    public static QueryModel BuildListQueryModel(ResourceCrudModel model)
    {
        var entityName = model.Resource.TypeName;
        var typeName = $"ResourceList{entityName}Query";
        var dto = model.DtoFor(typeName, model.ScaffoldedListItemDto);

        return new QueryModel
        {
            Namespace = model.Resource.Namespace,
            TypeName = typeName,
            Accessibility = "public",
            TypeKind = "class",
            EntityTypeFullName = string.IsNullOrEmpty(model.Resource.Namespace)
                ? entityName : $"{model.Resource.Namespace}.{entityName}",
            // The boundary whose keyed context the generated invoker reads from. Without it the invoker
            // resolves an unkeyed DbContext, which a host that registers one context per boundary does
            // not have — every read through this query answered 500.
            BoundaryTypeName = model.Resource.BoundaryFullTypeName,
            // The group its hand-written neighbours are in; the entity namespace it
            // borrows cannot say it.
            SubBoundaryName = model.GroupName,
            EntityTypeName = entityName,
            ResultTypeFullName = dto.FullTypeName,
            ResultTypeName = dto.TypeName,
            Properties = ImmutableArray.Create(
                new QueryPropertyModel
                {
                    PropertyName = "Page",
                    PropertyType = "int",
                    IsPageProperty = true,
                },
                new QueryPropertyModel
                {
                    PropertyName = "PageSize",
                    PropertyType = "int",
                    IsPageSizeProperty = true,
                }),
        };
    }

    /// <summary>
    ///     Builds the QueryModel for reading one row by id.
    /// </summary>
    /// <remarks>
    ///     No paging: the endpoint declares <c>QueryIsSingle</c>, and the handler calls
    ///     <c>ExecuteSingleAsync</c> — which answers 404 when nothing matches, where a list query would
    ///     answer 200 with nothing in it. "Not there" and "there but empty" are different answers.
    /// </remarks>
    public static QueryModel BuildReadQueryModel(ResourceCrudModel model)
        => ReadModel(
            model, ReadTypeName(model.Resource.TypeName), "Id", SimpleName(model.Resource.IdType),
            // The filter must name the mapped column. An entity's Id is `Id => PersistenceId`, a
            // computed property EF Core cannot translate: `Where(e => e.Id == …)` compiles, ships, and
            // answers 500 on the first call. PersistenceId is what carries the key.
            mapTo: "PersistenceId");

    /// <summary>Builds the QueryModel for reading one row by the entity's logic key.</summary>
    /// <remarks>A logic key is a real column, so it needs no remapping.</remarks>
    public static QueryModel BuildReadByLogicKeyQueryModel(ResourceCrudModel model)
        => ReadModel(model, ReadByLogicKeyTypeName(model), model.LogicKeyName!, model.LogicKeyType ?? "string");

    private static QueryModel ReadModel(
        ResourceCrudModel model, string typeName, string filterName, string filterType,
        string? mapTo = null)
    {
        var entityName = model.Resource.TypeName;
        var dto = model.DtoFor(typeName, model.ScaffoldedReadDto);
        var ns = model.Resource.Namespace;

        return new QueryModel
        {
            Namespace = ns,
            TypeName = typeName,
            Accessibility = "public",
            TypeKind = "class",
            EntityTypeFullName = string.IsNullOrEmpty(ns) ? entityName : $"{ns}.{entityName}",
            // The boundary whose keyed context the generated invoker reads from. Without it the invoker
            // resolves an unkeyed DbContext, which a host that registers one context per boundary does
            // not have — every read through this query answered 500.
            BoundaryTypeName = model.Resource.BoundaryFullTypeName,
            // The group its hand-written neighbours are in; the entity namespace it
            // borrows cannot say it.
            SubBoundaryName = model.GroupName,
            EntityTypeName = entityName,
            ResultTypeFullName = dto.FullTypeName,
            ResultTypeName = dto.TypeName,
            // The endpoint declares QueryIsSingle for this one, and the invoker has to agree: the shape
            // decides which executor overload runs and what the handler unwraps, and two answers to that
            // question produce a generated file that does not compile.
            IsSingle = true,
            Properties = ImmutableArray.Create(new QueryPropertyModel
            {
                PropertyName = filterName,
                PropertyType = filterType,
                IsFilter = true,
                Operator = FilterOperatorKind.Equals,
                MapTo = mapTo,
            }),
        };
    }

    /// <summary>
    /// Builds a QueryModel for the Search query (string filters + paging).
    /// </summary>
    public static QueryModel BuildSearchQueryModel(ResourceCrudModel model)
    {
        var entityName = model.Resource.TypeName;
        var typeName = $"ResourceSearch{entityName}Query";
        var dto = model.DtoFor(typeName, model.ScaffoldedListItemDto);

        var props = ImmutableArray.CreateBuilder<QueryPropertyModel>();

        props.AddRange(model.SearchFilters.AsImmutableArray());

        // Sort + Paging
        props.Add(new QueryPropertyModel
        {
            PropertyName = "IdSort",
            PropertyType = "SortDirection?",
                    QualifiedPropertyType = "global::Pragmatic.Persistence.Query.SortDirection?",
            IsSort = true,
            IsNullable = true,
            DefaultSortDirection = SortDirectionKind.Ascending,
            // The sort has to name the mapped column, exactly as the by-id read's filter does. An
            // entity's Id is `Id => PersistenceId`, unmapped, so `OrderBy(e => e.Id)` compiles and then
            // fails to translate: every call to the scaffolded search answered 500. It went unnoticed
            // because no test ever executed this endpoint — the snapshots read the text and agreed
            // with it.
            MapTo = "PersistenceId",
        });
        props.Add(new QueryPropertyModel { PropertyName = "Page", PropertyType = "int", IsPageProperty = true });
        props.Add(new QueryPropertyModel { PropertyName = "PageSize", PropertyType = "int", IsPageSizeProperty = true });

        return new QueryModel
        {
            Namespace = model.Resource.Namespace,
            TypeName = typeName,
            Accessibility = "public",
            TypeKind = "class",
            EntityTypeFullName = string.IsNullOrEmpty(model.Resource.Namespace)
                ? entityName : $"{model.Resource.Namespace}.{entityName}",
            // The boundary whose keyed context the generated invoker reads from. Without it the invoker
            // resolves an unkeyed DbContext, which a host that registers one context per boundary does
            // not have — every read through this query answered 500.
            BoundaryTypeName = model.Resource.BoundaryFullTypeName,
            // The group its hand-written neighbours are in; the entity namespace it
            // borrows cannot say it.
            SubBoundaryName = model.GroupName,
            EntityTypeName = entityName,
            ResultTypeFullName = dto.FullTypeName,
            ResultTypeName = dto.TypeName,
            Properties = props.ToImmutable(),
        };
    }
}

/// <summary>
///     The query kinds <c>ResourceFeature.GenerateCrud</c> emits. Reading a single resource by id is
///     deliberately absent: it is served by the generated <c>Resource{Entity}ReadAction</c> DomainAction,
///     which owns the not-found <c>Result</c> and the authorization filters. A query would only duplicate
///     that and needs no filtering, sorting or paging of its own.
/// </summary>
internal enum ResourceQueryKind
{
    List,
    Search,

    /// <summary>One row by id. <c>Single = true</c>, so nothing found is a 404 and not an empty list.</summary>
    Read,

    /// <summary>One row by the entity's <c>[GeneratedValue]</c>/<c>[LogicKey]</c>.</summary>
    ReadByLogicKey,
}
