using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.Extensions.Logging;
using Pragmatic.Logging.CallSites;
using Pragmatic.Logging.Providers;
using Pragmatic.Logging.Tests.Generated;
using Pragmatic.Redaction;
using Pragmatic.Testing.Assertions;
using Xunit;

namespace Pragmatic.Logging.Tests.CallSites;

/// <summary>
///     A call site whose argument is an application type with declared members writes that argument itself:
///     masked where the type declared it, the same in every view, and for nothing per call.
/// </summary>
/// <remarks>
///     Before, an argument of an application type made the whole call site not self-contained: the JSON
///     provider rendered it the classic way (a <c>LogEntry</c>, a message string, the serialized JSON, the
///     masked copy), and a third-party provider reading the list view got the record itself, whose
///     <c>ToString()</c> prints every member.
/// </remarks>
public partial class AGeneratedCallSiteWritesALoggedTypeTests
{
    private const string Email = "alice@example.com";
    private const string Street = "1 Hidden Lane";

    private static readonly Customer Alice = new("C-42", Email, CustomerTier.Gold, new Address("Turin", Street));

    [Fact]
    public void TheCallSiteIsSelfContained()
    {
        IUtf8LogState? state = null;
        using var factory = LoggerFactory.Create(builder => builder.AddProvider(new StateCapture(s => state = s)));

        OrderLog.Registered(factory.CreateLogger("Customers"), Alice);

        state.Should().NotBeNull("the call site is generated by Pragmatic");
        state!.IsSelfContained.Should().BeTrue("the argument's type is written by a generated writer");
    }

    /// <summary>
    ///     The control: a type a writer cannot describe (a dictionary member) keeps the classic path, decided at
    ///     compile time, and the declared redactor still masks it.
    /// </summary>
    [Fact]
    public void ATypeTheWriterCannotDescribe_KeepsTheClassicPath()
    {
        IUtf8LogState? state = null;
        var ledger = new Ledger("A-1", "DE89370400440532013000", new Dictionary<string, string> { ["k"] = "v" });
        using (var factory = LoggerFactory.Create(builder => builder.AddProvider(new StateCapture(s => state = s))))
            OrderLog.Booked(factory.CreateLogger("Ledgers"), ledger);

        state!.IsSelfContained.Should().BeFalse("no writer was generated for a type with a dictionary member");

        var line = JsonLine(logger => OrderLog.Booked(logger, ledger));
        line.Should().NotContain("DE89370400440532013000").And.Contain("A-1");
    }

    [Theory]
    [InlineData(false)]
    [InlineData(true)]
    public void ThroughTheJsonProvider_ACallAllocatesNothingAtSteadyState(bool declaredRedactor)
    {
        using var provider = new PragmaticJsonProvider("json", JsonConfiguration(), Stream.Null);
        if (declaredRedactor)
            provider.DeclaredRedactor = new DeclaredRedactor([new GeneratedRedactionMap()]);

        using var factory = LoggerFactory.Create(builder => builder.AddProvider(provider));
        var logger = factory.CreateLogger("Customers");

        for (var i = 0; i < 200; i++)
            OrderLog.Registered(logger, Alice);

        var before = GC.GetAllocatedBytesForCurrentThread();
        for (var i = 0; i < 1000; i++)
            OrderLog.Registered(logger, Alice);
        var allocated = GC.GetAllocatedBytesForCurrentThread() - before;

        allocated.Should().Be(0, "the argument is written by the call site's own writer, not serialized and masked");
    }

    [Fact]
    public void TheDeclaredMembersAreInClearInNoView()
    {
        var json = new MemoryStream();
        var memory = new PragmaticMemoryProvider("memory", PragmaticMemoryConfiguration.ForMemory());
        var thirdParty = new ThirdPartyProvider();

        using (var jsonProvider = new PragmaticJsonProvider("json", JsonConfiguration(), json))
        using (var factory = LoggerFactory.Create(builder => builder
                   .SetMinimumLevel(LogLevel.Trace)
                   .AddProvider(jsonProvider)
                   .AddProvider(memory)
                   .AddProvider(thirdParty)))
        {
            OrderLog.Registered(factory.CreateLogger("Customers"), Alice);
        }

        var entry = memory.GetLogEntries().Should().ContainSingle().Which;
        string[] outputs =
        [
            Encoding.UTF8.GetString(json.ToArray()),
            entry.Message,
            string.Join(";", entry.Properties.Select(p => $"{p.Key}={p.Value}")),
            thirdParty.Written.Should().ContainSingle().Which,
        ];

        foreach (var output in outputs)
        {
            output.Should().NotContain(Email).And.NotContain(Street, "the nested declaration is masked too");
            output.Should().Contain("C-42", "what was not declared survives").And.Contain("Turin");
        }
    }

    /// <summary>
    ///     The oracle is the classic path with the assembly's generated redaction map: the same value, logged
    ///     through the formatter and the declared redactor. Anything else would be a second output format.
    /// </summary>
    [Fact]
    public void TheJsonLineIsTheOneTheClassicPathWritesForTheSameValue()
    {
        var generated = JsonLine(logger => OrderLog.Registered(logger, Alice));
        var classic = JsonLine(logger => logger.Log(
            LogLevel.Information, new EventId(1003, "Registered"), OrderLog.RegisteredTemplate, Alice));

        generated.Should().Be(classic);
    }

    /// <summary>
    ///     Every kind of member a writer handles, against the same oracle: a GUID, both kinds of date, a time
    ///     span, a char, numbers, a nullable, a list of children with a personal-data member each, an array,
    ///     and an array declared not logged as a whole. Values chosen to need escaping and trimming.
    /// </summary>
    [Fact]
    public void EveryKindOfMemberIsWrittenAsTheClassicPathWritesIt()
    {
        var shipment = new Shipment(
            Guid.Parse("6f1c0a9e-3b2d-4c5e-8f70-112233445566"),
            new DateTimeOffset(2026, 10, 7, 9, 30, 15, 120, TimeSpan.FromHours(2)),
            new DateTime(2026, 10, 9, 0, 0, 0, DateTimeKind.Utc),
            new TimeSpan(1, 2, 3, 4, 500),
            'B',
            12.50m,
            0.1 + 0.2,
            Parcels: null,
            Fragile: true,
            [new ShipmentLine("SKU-<1>", Email), new ShipmentLine("SKU-\"2\"", "bob@example.com")],
            ["fragile", "è caro"],
            ["secret-1", "secret-2"]);

        var generated = JsonLine(logger => OrderLog.Shipped(logger, shipment));
        var classic = JsonLine(logger => logger.Log(
            LogLevel.Information, new EventId(1004, "Shipped"), OrderLog.ShippedTemplate, shipment));

        generated.Should().Be(classic);
        generated.Should().NotContain(Email).And.NotContain("secret-1");
    }

    [Fact]
    public void ANullArgumentIsWrittenAsTheClassicPathWritesIt()
    {
        var generated = JsonLine(logger => OrderLog.Registered(logger, null!));
        var classic = JsonLine(logger => logger.Log(
            LogLevel.Information, new EventId(1003, "Registered"), OrderLog.RegisteredTemplate, (Customer?)null));

        generated.Should().Be(classic);
    }

    private static PragmaticProviderConfiguration JsonConfiguration()
    {
        var config = PragmaticJsonConfiguration.ForJson();
        config.IncludeContextEnrichment = false;
        return config;
    }

    private static string JsonLine(Action<ILogger> log)
    {
        var previous = CultureInfo.CurrentCulture;
        CultureInfo.CurrentCulture = CultureInfo.InvariantCulture;

        var output = new MemoryStream();
        try
        {
            using var provider = new PragmaticJsonProvider("json", JsonConfiguration(), output)
            {
                DeclaredRedactor = new DeclaredRedactor([new GeneratedRedactionMap()]),
            };
            log(provider.CreateLogger("Customers"));
        }
        finally
        {
            CultureInfo.CurrentCulture = previous;
        }

        return Timestamp().Replace(Encoding.UTF8.GetString(output.ToArray()).Trim(), "\"@timestamp\":\"T\"");
    }

    [GeneratedRegex("\"@timestamp\":\"[^\"]*\"")]
    private static partial Regex Timestamp();

    private sealed class StateCapture(Action<IUtf8LogState> capture) : ILoggerProvider
    {
        public ILogger CreateLogger(string categoryName) => new Logger(capture);

        public void Dispose()
        {
        }

        private sealed class Logger(Action<IUtf8LogState> capture) : ILogger
        {
            public IDisposable? BeginScope<TState>(TState state) where TState : notnull => null;

            public bool IsEnabled(LogLevel logLevel) => true;

            public void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception? exception, Func<TState, Exception?, string> formatter)
            {
                if (state is IUtf8LogState utf8)
                    capture(utf8);
            }
        }
    }
}
