using Pragmatic.SourceGen;

namespace Pragmatic.SourceGenerator.Features.Persistence.Models;

/// <summary>
///     Model for an entity to include in a DbContext.
/// </summary>
internal sealed record DbContextEntityModel
{
    /// <summary>
    ///     The fully qualified type name of the entity.
    /// </summary>
    public required string FullTypeName { get; init; }

    /// <summary>
    ///     The simple type name of the entity.
    /// </summary>
    public required string TypeName { get; init; }

    /// <summary>
    ///     The DbSet property name (typically pluralized entity name).
    /// </summary>
    public required string DbSetName { get; init; }

    /// <summary>
    ///     The fully qualified type name of the entity configuration class.
    /// </summary>
    public required string ConfigurationTypeName { get; init; }

    /// <summary>
    ///     Whether this entity is abstract (no DbSet, but needs configuration for TPH).
    /// </summary>
    public bool IsAbstract { get; init; }

    /// <summary>
    ///     For a <c>[ReadAccess]</c> entity: the many-to-many navigations pointing back at itself, which
    ///     the reading context has to drop.
    /// </summary>
    /// <remarks>
    ///     <para>
    ///         <c>[ReadAccess]</c> brings the owner's whole per-entity configuration, and with it the
    ///         closure of its graph; the types the reader does not own go into
    ///         <c>modelBuilder.Ignore&lt;T&gt;()</c>. That closes a many-to-many towards <b>another</b>
    ///         type, because ignoring the target takes the skip navigation with it.
    ///     </para>
    ///     <para>
    ///         A <b>self-referential</b> one does not close: the target is the read entity itself, so it
    ///         survives, while its join entity is ignored — and EF Core rejects the model at first use
    ///         with "the skip navigation … doesn't have a foreign key". Not at build: every request of
    ///         the boundary answers 500 over a clean compilation. So the navigation itself is ignored,
    ///         by name, after the configuration that declared it.
    ///     </para>
    /// </remarks>
    public EquatableArray<string> SelfReferentialSkipNavigations { get; init; } =
        EquatableArray<string>.Empty;

    /// <summary>
    ///     Whether this entity has [ConcurrencyAware] for optimistic concurrency.
    ///     Concurrency configuration is applied at Host level (BoundaryDbContext.OnModelCreating)
    ///     where the EF Core provider is known.
    /// </summary>
    public bool IsConcurrencyAware { get; init; }

    /// <summary>
    ///     Whether this entity was generated by a trait (e.g. [HasComments]).
    ///     Trait entities have their EntityConfig in the module (public), not generated at host level.
    /// </summary>
    public bool IsTraitEntity { get; init; }

    /// <summary>
    ///     Whether this entity implements <c>ITenantEntity</c>. When true the generated DbContext emits a
    ///     named EF Core global query filter (<c>"Tenant"</c>) referencing the injected <c>ITenantContext</c>,
    ///     so even raw <c>Set&lt;T&gt;()</c> queries are tenant-isolated (defence-in-depth, fail-closed).
    /// </summary>
    public bool IsTenantEntity { get; init; }

    /// <summary>
    ///     For a trait child with no tenant column of its own: the reference navigation to its
    ///     tenant-scoped parent. <c>null</c> everywhere else.
    /// </summary>
    /// <remarks>
    ///     Its tenancy is the parent's, and the generated list query filters by the parent id alone —
    ///     so without lifting the parent's filter through this navigation, a caller holding an id from
    ///     another tenant reads the whole collection.
    /// </remarks>
    public string? ParentTenantNavigation { get; init; }

    /// <summary>
    ///     Whether the entity has [Audited] — the boundary DbContext maps the __AuditLog table and wires
    ///     the AuditLogInterceptor.
    /// </summary>
    public bool IsAudited { get; init; }

    /// <summary>
    ///     Whether the entity is a <c>[DataSubject]</c> — the boundary DbContext maps the subject
    ///     registry's tables, when the registry package is referenced.
    /// </summary>
    public bool IsDataSubject { get; init; }

    /// <summary>
    ///     Logic-key property name ([LogicKey]) — drives a unique index. When the entity is also
    ///     soft-delete the index filter (raw SQL, provider-specific) is applied at Host level
    ///     where <c>EfCoreProvider</c> is known; the EntityConfig only emits the bare unique index.
    /// </summary>
    public string? LogicKeyPropertyName { get; init; }

    /// <summary>
    ///     The lambda that selects the whole domain key, carried from
    ///     <c>EntityMetadataModel.LogicKeySelector</c> so the filtered index here and the bare one in
    ///     the EntityConfig cover the same columns. Two indexes over different columns is not a compile
    ///     error — it is a uniqueness rule the database enforces in one place and not the other.
    /// </summary>
    public string? LogicKeySelector { get; init; }

    /// <summary>Whether the entity uses soft delete (drives the partial unique index on the logic key).</summary>
    public bool IsSoftDelete { get; init; }

    /// <summary>
    ///     The parent key a <c>[TemporalRelation&lt;TParent&gt;(MaxActive = 1)]</c> is scoped to, when
    ///     the constraint can be expressed as a partial unique index.
    /// </summary>
    /// <remarks>
    ///     ⚠️ Enforced by the database, not only by the generated mutation invoker. An action writing
    ///     the same entity through the same repository never reaches the invoker's check, so on its own
    ///     the constraint holds on one write path and not the other: two overlapping open stretches
    ///     written with a 200 where a mutation answers 409. An invariant that reads as a
    ///     property of the entity has to hold wherever the entity is written, and the only place that
    ///     is true of is the database.
    /// </remarks>
    public string? TemporalMaxOneParentKey { get; init; }
}
