namespace Pragmatic.Caching;

/// <summary>
///     Interface implemented by types marked with [Cacheable].
///     Generated by source generator.
/// </summary>
public interface ICacheable
{
    /// <summary>
    ///     Gets the cache key for this instance.
    ///     Generated from public properties.
    /// </summary>
    string GetCacheKey();

    /// <summary>
    ///     Gets the cache options for this instance.
    /// </summary>
    CacheEntryOptions GetCacheOptions();

    /// <summary>
    ///     Gets the cache category type for routing, or <c>null</c> for the default category.
    ///     Generated from <c>[Cacheable(Category = typeof(...))]</c>.
    /// </summary>
    /// <remarks>
    ///     Implementations generated by the source generator return a compile-time constant
    ///     (e.g. <c>typeof(MyCacheCategory)</c>) and must NOT use runtime reflection
    ///     (<c>GetType()</c>, <c>GetCustomAttributes</c>, etc.). The <see cref="CacheStackProvider"/>
    ///     consumes this value as a keyed-DI lookup key; it will never invoke reflection on it.
    /// </remarks>
    Type? CacheCategory => null;
}