using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Pragmatic.SourceGen;
using Pragmatic.SourceGenerator.Core;
using Pragmatic.SourceGenerator.Features.Actions.Models;
using Pragmatic.SourceGenerator.Features.Traits.Diagnostics;
using Pragmatic.SourceGenerator.Features.Traits.Models;
using Pragmatic.SourceGenerator.Features.Traits.Templates;
using Pragmatic.SourceGenerator.Features.Traits.Transforms;

namespace Pragmatic.SourceGenerator.Features.Traits;

/// <summary>
/// Orchestrates trait generation ([HasComments], future [HasTags] etc.).
/// Returns <see cref="TraitOutput"/> for downstream features (DbContext, Actions).
/// </summary>
internal static class TraitFeature
{
    public static TraitOutput Register(
        IncrementalGeneratorInitializationContext context,
        IncrementalValueProvider<DetectedFeatures> features)
    {
        // ── [HasComments] pipeline ──────────────────────────────────────

        var commentModels = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeNames.HasComments,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: CommentTraitTransform.Transform)
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        var allComments = commentModels.Collect();

        // Per-comment: entity + config + parent navigation + action classes + permissions
        var commentsWithFeatures = commentModels.Combine(features);
        context.RegisterSourceOutputSafe(commentsWithFeatures, static (ctx, pair) =>
        {
            var (model, detectedFeatures) = pair;
            if (!detectedFeatures.HasPersistenceEFCore) return;

            GenerateCommentEntity(ctx, model);
            GenerateCommentEntityConfig(ctx, model);
            GenerateParentNavigation(ctx, model);

            // Action classes (Execute body) — Invoker + SetDependencies come from ActionsFeature
            if (detectedFeatures.HasActions)
            {
                GenerateCommentAction(ctx, model, CommentActionKind.Add);
                GenerateCommentAction(ctx, model, CommentActionKind.GetById);
                if (model.AllowEditing)
                    GenerateCommentAction(ctx, model, CommentActionKind.Update);
                GenerateCommentAction(ctx, model, CommentActionKind.Delete);
                if (model.RequireApproval)
                {
                    GenerateCommentAction(ctx, model, CommentActionKind.Moderate);
                    GenerateCommentAction(ctx, model, CommentActionKind.ListPending);
                }
                GenerateCommentPermissions(ctx, model);
                GenerateCommentDto(ctx, model);
                GenerateCommentListQuery(ctx, model);

                // The list query filters by parent id and nothing else, so the parent's own row
                // restriction is lifted onto the child through its navigation.
                if (model.ParentIsRowProtected)
                    GenerateParentVisibilityFilter(ctx, model.ParentNamespace, model.CommentTypeName,
                        model.ParentTypeName, model.BoundaryName, model.ParentIsOwned, model.ParentIsScoped);

                if (model.SupportInternalNotes)
                    GenerateCommentInternalVisibilityFilter(ctx, model);

                // Endpoints are generated by EndpointsFeature from injected EndpointModels
            }
        });

        // Aggregate: validation + metadata generation
        var commentsWithRootNs = allComments.Combine(
            context.CompilationProvider.Select(static (c, _) => c.AssemblyName ?? "Global"));

        context.RegisterSourceOutputSafe(commentsWithRootNs, static (ctx, pair) =>
        {
            var (models, rootNs) = pair;

            foreach (var model in models)
            {
                // PRAG2601: warn if no [Resource] — endpoints won't be generated
                if (model.ResourceSegment is null)
                {
                    ctx.ReportDiagnostic(
                        TraitDiagnostics.TraitRequiresResource,
                        model.Location,
                        model.ParentTypeName,
                        "HasComments");
                }
            }

            // Generate trait entity metadata for host DbContext discovery
            if (models.Length > 0)
            {
                var infos = models.Select(CommentEntityInfo).ToImmutableArray();

                var metadataTemplate = new TraitEntityMetadataTemplate(infos, rootNs);
                var artifact = metadataTemplate.RenderOutput();
                if (!artifact.IsEmpty)
                    ctx.AddSource(artifact);
            }
        });

        // Build TraitEntityInfo for DbContext injection
        var traitEntities = allComments.Select(static (models, _) =>
        {
            var builder = ImmutableArray.CreateBuilder<TraitEntityInfo>(models.Length);
            foreach (var m in models)
            {
                builder.Add(CommentEntityInfo(m));
            }

            return builder.ToImmutable();
        });

        // Build ActionModels for ActionsFeature pipeline injection
        var traitActionModels = allComments.Combine(features).Select(static (pair, _) =>
        {
            var (models, detectedFeatures) = pair;
            // Without Actions the action CLASSES are not generated, so injecting their models would make
            // ActionsFeature/EndpointsFeature emit invokers and handlers for types that do not exist.
            if (!detectedFeatures.HasActions)
                return ImmutableArray<ActionModel>.Empty;

            var builder = ImmutableArray.CreateBuilder<ActionModel>();
            foreach (var m in models)
            {
                builder.AddRange(TraitActionModelBuilder.BuildCommentActions(m));
            }

            return builder.ToImmutable();
        });

        // Build QueryModels for QueryFeature injection (ListComments)
        var traitQueryModels = allComments.Select(static (models, _) =>
        {
            var builder = ImmutableArray.CreateBuilder<Persistence.Models.QueryModel>();
            foreach (var m in models)
            {
                builder.Add(BuildListCommentsQueryModel(m));
            }

            return builder.ToImmutable();
        });

        // Build EndpointModels for EndpointsFeature injection
        var traitEndpointModels = allComments.Combine(features).Select(static (pair, _) =>
        {
            var (models, detectedFeatures) = pair;
            // Without Actions the action CLASSES are not generated, so injecting their models would make
            // ActionsFeature/EndpointsFeature emit invokers and handlers for types that do not exist.
            if (!detectedFeatures.HasActions)
                return ImmutableArray<Endpoints.Models.EndpointModel>.Empty;

            var builder = ImmutableArray.CreateBuilder<Endpoints.Models.EndpointModel>();
            foreach (var m in models)
            {
                builder.AddRange(TraitEndpointModelBuilder.BuildCommentEndpoints(m));
            }

            return builder.ToImmutable();
        });

        // ── [HasTags] pipeline ─────────────────────────────────────────

        var tagModels = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeNames.HasTags,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: TagTraitTransform.Transform)
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        var allTags = tagModels.Collect();

        // Per-tag: junction entity + config + parent navigation + action classes + permissions
        var tagsWithFeatures = tagModels.Combine(features);
        context.RegisterSourceOutputSafe(tagsWithFeatures, static (ctx, pair) =>
        {
            var (model, detectedFeatures) = pair;
            if (!detectedFeatures.HasPersistenceEFCore) return;

            // The shared tag entity and its config are emitted once per boundary from the aggregate
            // stage below — emitting them here would repeat the same hint name for every entity that
            // carries [HasTags], and a duplicate hint costs the whole generator's output.
            GenerateTagJunction(ctx, model);
            GenerateTagJunctionConfig(ctx, model);
            GenerateParentTagNavigation(ctx, model);

            if (detectedFeatures.HasActions)
            {
                GenerateTagAction(ctx, model, TagActionKind.Add);
                GenerateTagAction(ctx, model, TagActionKind.Remove);
                GenerateTagPermissions(ctx, model);
                GenerateTagDto(ctx, model);
                GenerateTagListQuery(ctx, model);

                // The list query filters by parent id and nothing else, so the parent's own row
                // restriction is lifted onto the child through its navigation.
                if (model.ParentIsRowProtected)
                    GenerateParentVisibilityFilter(ctx, model.ParentNamespace, model.JunctionTypeName,
                        model.ParentTypeName, model.BoundaryName, model.ParentIsOwned, model.ParentIsScoped);
            }
        });

        // Shared tag entity + config: one per distinct tag type, not one per annotated entity.
        var sharedTagEntities = allTags.Combine(features);
        context.RegisterSourceOutputSafe(sharedTagEntities, static (ctx, pair) =>
        {
            var (models, detectedFeatures) = pair;
            if (!detectedFeatures.HasPersistenceEFCore) return;

            var emitted = new HashSet<string>();
            foreach (var model in models)
            {
                // Keyed on the full name: the type is named after the boundary, so two entities in the
                // same boundary share it, while two boundaries keep their own.
                if (!emitted.Add(model.TagFullTypeName))
                    continue;

                GenerateTagEntity(ctx, model);
                GenerateTagEntityConfig(ctx, model);
            }
        });

        // Tag validation + metadata
        var tagsWithRootNs = allTags.Combine(
            context.CompilationProvider.Select(static (c, _) => c.AssemblyName ?? "Global"));

        context.RegisterSourceOutputSafe(tagsWithRootNs, static (ctx, pair) =>
        {
            var (models, rootNs) = pair;

            foreach (var model in models)
            {
                if (model.ResourceSegment is null)
                {
                    ctx.ReportDiagnostic(
                        TraitDiagnostics.TraitRequiresResource,
                        model.Location,
                        model.ParentTypeName,
                        "HasTags");
                }
            }

            if (models.Length > 0)
            {
                // Generate metadata for both Tag and Junction entities
                var infos = ImmutableArray.CreateBuilder<TraitEntityInfo>();
                var emittedTagTypes = new HashSet<string>();

                foreach (var m in models)
                {
                    // Tag entity (once per boundary)
                    if (emittedTagTypes.Add(m.TagTypeName))
                    {
                        infos.Add(TagEntityInfo(m));
                    }

                    // Junction entity (one per parent). Keyed on its two FKs — see TagJunctionConfigTemplate.
                    infos.Add(TagJunctionEntityInfo(m));
                }

                var metadataTemplate = new TraitEntityMetadataTemplate(infos.ToImmutable(), rootNs, "TagEntities");
                var artifact = metadataTemplate.RenderOutput();
                if (!artifact.IsEmpty)
                    ctx.AddSource(artifact);
            }
        });

        // Build Tag entity infos for DbContext injection
        var tagTraitEntities = allTags.Select(static (models, _) =>
        {
            var builder = ImmutableArray.CreateBuilder<TraitEntityInfo>();
            var emittedTagTypes = new HashSet<string>();

            foreach (var m in models)
            {
                if (emittedTagTypes.Add(m.TagTypeName))
                {
                    builder.Add(TagEntityInfo(m));
                }

                builder.Add(TagJunctionEntityInfo(m));
            }

            return builder.ToImmutable();
        });

        // Build tag ActionModels for ActionsFeature injection
        var tagActionModels = allTags.Combine(features).Select(static (pair, _) =>
        {
            var (models, detectedFeatures) = pair;
            // Without Actions the action CLASSES are not generated, so injecting their models would make
            // ActionsFeature/EndpointsFeature emit invokers and handlers for types that do not exist.
            if (!detectedFeatures.HasActions)
                return ImmutableArray<ActionModel>.Empty;

            var builder = ImmutableArray.CreateBuilder<ActionModel>();
            foreach (var m in models)
            {
                builder.AddRange(TraitActionModelBuilder.BuildTagActions(m));
            }
            return builder.ToImmutable();
        });

        // Build tag QueryModels for QueryFeature injection
        var tagQueryModels = allTags.Select(static (models, _) =>
        {
            var builder = ImmutableArray.CreateBuilder<Persistence.Models.QueryModel>();
            foreach (var m in models)
                builder.Add(BuildListTagsQueryModel(m));
            return builder.ToImmutable();
        });

        // Build tag EndpointModels for EndpointsFeature injection
        var tagEndpointModels = allTags.Combine(features).Select(static (pair, _) =>
        {
            var (models, detectedFeatures) = pair;
            // Without Actions the action CLASSES are not generated, so injecting their models would make
            // ActionsFeature/EndpointsFeature emit invokers and handlers for types that do not exist.
            if (!detectedFeatures.HasActions)
                return ImmutableArray<Endpoints.Models.EndpointModel>.Empty;

            var builder = ImmutableArray.CreateBuilder<Endpoints.Models.EndpointModel>();
            foreach (var m in models)
            {
                builder.AddRange(TraitEndpointModelBuilder.BuildTagEndpoints(m));
            }
            return builder.ToImmutable();
        });

        // ── [HasNotes] pipeline ───────────────────────────────────────

        var noteModels = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeNames.HasNotes,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: NoteTraitTransform.Transform)
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        var allNotes = noteModels.Collect();

        var notesWithFeatures = noteModels.Combine(features);
        context.RegisterSourceOutputSafe(notesWithFeatures, static (ctx, pair) =>
        {
            var (model, detectedFeatures) = pair;
            if (!detectedFeatures.HasPersistenceEFCore) return;

            GenerateNoteEntity(ctx, model);
            GenerateNoteEntityConfig(ctx, model);
            GenerateParentNoteNavigation(ctx, model);

            if (detectedFeatures.HasActions)
            {
                GenerateNoteAction(ctx, model, NoteActionKind.Add);
                GenerateNoteAction(ctx, model, NoteActionKind.GetById);
                if (model.AllowEditing)
                    GenerateNoteAction(ctx, model, NoteActionKind.Update);
                GenerateNoteAction(ctx, model, NoteActionKind.Delete);
                GenerateNotePermissions(ctx, model);
                GenerateNoteDto(ctx, model);
                GenerateNoteListQuery(ctx, model);

                // The list query filters by parent id and nothing else, so the parent's own row
                // restriction is lifted onto the child through its navigation.
                if (model.ParentIsRowProtected)
                    GenerateParentVisibilityFilter(ctx, model.ParentNamespace, model.NoteTypeName,
                        model.ParentTypeName, model.BoundaryName, model.ParentIsOwned, model.ParentIsScoped);
            }
        });

        // Note validation + metadata
        var notesWithRootNs = allNotes.Combine(
            context.CompilationProvider.Select(static (c, _) => c.AssemblyName ?? "Global"));

        context.RegisterSourceOutputSafe(notesWithRootNs, static (ctx, pair) =>
        {
            var (models, rootNs) = pair;
            foreach (var model in models)
            {
                if (model.ResourceSegment is null)
                    ctx.ReportDiagnostic(TraitDiagnostics.TraitRequiresResource, model.Location, model.ParentTypeName, "HasNotes");

            }

            if (models.Length > 0)
            {
                var infos = models.Select(NoteEntityInfo).ToImmutableArray();

                var metadataTemplate = new TraitEntityMetadataTemplate(infos, rootNs, "NoteEntities");
                var artifact = metadataTemplate.RenderOutput();
                if (!artifact.IsEmpty)
                    ctx.AddSource(artifact);
            }
        });

        var noteTraitEntities = allNotes.Select(static (models, _) =>
        {
            var builder = ImmutableArray.CreateBuilder<TraitEntityInfo>(models.Length);
            foreach (var m in models)
            {
                builder.Add(NoteEntityInfo(m));
            }
            return builder.ToImmutable();
        });

        var noteActionModels = allNotes.Combine(features).Select(static (pair, _) =>
        {
            var (models, detectedFeatures) = pair;
            // Without Actions the action CLASSES are not generated, so injecting their models would make
            // ActionsFeature/EndpointsFeature emit invokers and handlers for types that do not exist.
            if (!detectedFeatures.HasActions)
                return ImmutableArray<ActionModel>.Empty;

            var builder = ImmutableArray.CreateBuilder<ActionModel>();
            foreach (var m in models)
                builder.AddRange(TraitActionModelBuilder.BuildNoteActions(m));
            return builder.ToImmutable();
        });

        var noteQueryModels = allNotes.Select(static (models, _) =>
        {
            var builder = ImmutableArray.CreateBuilder<Persistence.Models.QueryModel>();
            foreach (var m in models)
                builder.Add(BuildListNotesQueryModel(m));
            return builder.ToImmutable();
        });

        var noteEndpointModels = allNotes.Combine(features).Select(static (pair, _) =>
        {
            var (models, detectedFeatures) = pair;
            // Without Actions the action CLASSES are not generated, so injecting their models would make
            // ActionsFeature/EndpointsFeature emit invokers and handlers for types that do not exist.
            if (!detectedFeatures.HasActions)
                return ImmutableArray<Endpoints.Models.EndpointModel>.Empty;

            var builder = ImmutableArray.CreateBuilder<Endpoints.Models.EndpointModel>();
            foreach (var m in models)
                builder.AddRange(TraitEndpointModelBuilder.BuildNoteEndpoints(m));
            return builder.ToImmutable();
        });

        // ── [HasAttachments] pipeline ────────────────────────────────

        var attachmentModels = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeNames.HasAttachments,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: AttachmentTraitTransform.Transform)
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        var allAttachments = attachmentModels.Collect();

        var attachmentsWithFeatures = attachmentModels.Combine(features);
        context.RegisterSourceOutputSafe(attachmentsWithFeatures, static (ctx, pair) =>
        {
            var (model, detectedFeatures) = pair;
            if (!detectedFeatures.HasPersistenceEFCore) return;

            GenerateAttachmentEntity(ctx, model);
            GenerateAttachmentEntityConfig(ctx, model);
            GenerateParentAttachmentNavigation(ctx, model);

            if (detectedFeatures.HasActions)
            {
                // The generated actions stamp their rows through IClock, and only Pragmatic.Temporal
                // (or Jobs, which registers the same instance) supplies one. Without it the field
                // stays null and the first upload fails at runtime with nothing at compile time
                // pointing at the cause.
                if (!detectedFeatures.HasTemporal && !detectedFeatures.HasJobs)
                    ctx.ReportDiagnostic(TraitDiagnostics.TraitRequiresClock, model.Location,
                        model.ParentTypeName, "HasAttachments");

                // Asked for and unreachable is the one outcome worth a word: nothing is generated, and
                // without this the attribute reads as configured while every upload keeps storing the
                // original whole.
                if (model.ThumbnailRequested && !detectedFeatures.HasImaging)
                    ctx.ReportDiagnostic(TraitDiagnostics.TraitThumbnailRequiresImaging, model.Location,
                        model.ParentTypeName, model.ThumbnailMaxWidth, model.ThumbnailMaxHeight);

                GenerateAttachmentAction(ctx, model, AttachmentActionKind.Upload, detectedFeatures.HasImaging);
                GenerateAttachmentAction(ctx, model, AttachmentActionKind.GetById);
                // The download action returns Pragmatic.Endpoints' FileResponse; a module that
                // references Actions but not Endpoints would not be able to bind it.
                if (detectedFeatures.HasEndpoints)
                {
                    GenerateAttachmentAction(ctx, model, AttachmentActionKind.Download);
                    if (model.ThumbnailRequested && detectedFeatures.HasImaging)
                        GenerateAttachmentAction(ctx, model, AttachmentActionKind.DownloadThumbnail, true);
                }
                GenerateAttachmentAction(ctx, model, AttachmentActionKind.Delete);
                GenerateAttachmentPermissions(ctx, model);
                GenerateAttachmentDto(ctx, model);
                GenerateAttachmentListQuery(ctx, model);

                // The list query filters by parent id and nothing else, so the parent's own row
                // restriction is lifted onto the child through its navigation.
                if (model.ParentIsRowProtected)
                    GenerateParentVisibilityFilter(ctx, model.ParentNamespace, model.AttachmentTypeName,
                        model.ParentTypeName, model.BoundaryName, model.ParentIsOwned, model.ParentIsScoped);
            }

            // Retention job — opt-in via [HasAttachments(PurgeDeletedAfterDays = N)].
            if (detectedFeatures.HasJobs)
                GenerateAttachmentPurgeJob(ctx, model);
        });

        var attachmentWithRootNs = allAttachments.Combine(
            context.CompilationProvider.Select(static (c, _) => c.AssemblyName ?? "Global"));
        context.RegisterSourceOutputSafe(attachmentWithRootNs, static (ctx, pair) =>
        {
            var (models, rootNs) = pair;
            foreach (var model in models)
                if (model.ResourceSegment is null)
                    ctx.ReportDiagnostic(TraitDiagnostics.TraitRequiresResource, model.Location, model.ParentTypeName, "HasAttachments");

            if (models.Length > 0)
            {
                var infos = models.Select(AttachmentEntityInfo).ToImmutableArray();
                var template = new TraitEntityMetadataTemplate(infos, rootNs, "AttachmentEntities");
                var artifact = template.RenderOutput();
                if (!artifact.IsEmpty)
                    ctx.AddSource(artifact);
            }
        });

        var attachmentTraitEntities = allAttachments.Select(static (models, _) =>
        {
            var builder = ImmutableArray.CreateBuilder<TraitEntityInfo>(models.Length);
            foreach (var m in models)
                builder.Add(AttachmentEntityInfo(m));
            return builder.ToImmutable();
        });

        var attachmentActionModels = allAttachments.Combine(features).Select(static (pair, _) =>
        {
            var (models, detectedFeatures) = pair;
            var builder = ImmutableArray.CreateBuilder<ActionModel>();
            foreach (var m in models)
                builder.AddRange(TraitActionModelBuilder.BuildAttachmentActions(
                    m, detectedFeatures.HasEndpoints,
                    detectedFeatures.HasEndpoints && detectedFeatures.HasImaging && m.ThumbnailRequested));
            return builder.ToImmutable();
        });

        // Purge jobs, injected into JobsFeature: a generator cannot discover the [RecurringJob]
        // attribute on a class it generates itself.
        var attachmentJobModels = allAttachments.Combine(features).Select(static (pair, _) =>
        {
            var (models, detectedFeatures) = pair;
            var builder = ImmutableArray.CreateBuilder<Jobs.Models.JobModel>();
            if (!detectedFeatures.HasJobs) return builder.ToImmutable();

            foreach (var m in models)
            {
                var job = TraitJobModelBuilder.BuildAttachmentPurgeJob(m);
                if (job is not null) builder.Add(job);
            }

            return builder.ToImmutable();
        });

        var attachmentQueryModels = allAttachments.Select(static (models, _) =>
        {
            var builder = ImmutableArray.CreateBuilder<Persistence.Models.QueryModel>();
            foreach (var m in models)
                builder.Add(BuildListAttachmentsQueryModel(m));
            return builder.ToImmutable();
        });

        var attachmentEndpointModels = allAttachments.Combine(features).Select(static (pair, _) =>
        {
            var (models, detected) = pair;
            var builder = ImmutableArray.CreateBuilder<Endpoints.Models.EndpointModel>();
            foreach (var m in models)
                builder.AddRange(TraitEndpointModelBuilder.BuildAttachmentEndpoints(m, detected.HasImaging));
            return builder.ToImmutable();
        });

        // ── Combine all trait outputs ──────────────────────────────────

        var combinedTraitEntities = traitEntities.Combine(tagTraitEntities)
            .Select(static (pair, _) => pair.Left.AddRange(pair.Right))
            .Combine(noteTraitEntities)
            .Select(static (pair, _) => pair.Left.AddRange(pair.Right))
            .Combine(attachmentTraitEntities)
            .Select(static (pair, _) => pair.Left.AddRange(pair.Right));

        var combinedActions = traitActionModels.Combine(tagActionModels)
            .Select(static (pair, _) => pair.Left.AddRange(pair.Right))
            .Combine(noteActionModels)
            .Select(static (pair, _) => pair.Left.AddRange(pair.Right))
            .Combine(attachmentActionModels)
            .Select(static (pair, _) => pair.Left.AddRange(pair.Right));

        var combinedQueries = traitQueryModels.Combine(tagQueryModels)
            .Select(static (pair, _) => pair.Left.AddRange(pair.Right))
            .Combine(noteQueryModels)
            .Select(static (pair, _) => pair.Left.AddRange(pair.Right))
            .Combine(attachmentQueryModels)
            .Select(static (pair, _) => pair.Left.AddRange(pair.Right));

        var combinedEndpoints = traitEndpointModels.Combine(tagEndpointModels)
            .Select(static (pair, _) => pair.Left.AddRange(pair.Right))
            .Combine(noteEndpointModels)
            .Select(static (pair, _) => pair.Left.AddRange(pair.Right))
            .Combine(attachmentEndpointModels)
            .Select(static (pair, _) => pair.Left.AddRange(pair.Right))
            // A trait's endpoints are gated exactly like a hand-written one, and that is a single
            // shape: the requirement is in the policy whatever the compilation references, so there
            // is no per-endpoint flag to set here.
            ;

        ReportTraitsOnNonEntities(context);

        // Descriptions of the DTOs generated above, for the manifest. Without them the manifest names those
        // types on its endpoints but cannot say what is in them, and a generated client falls back to object.
        var manifestTypes = allComments.Select(static (models, _) => TraitManifestTypeBuilder.BuildCommentDtos(models))
            .Combine(allTags.Select(static (models, _) => TraitManifestTypeBuilder.BuildTagDtos(models)))
            .Select(static (pair, _) => pair.Left.AddRange(pair.Right))
            .Combine(allNotes.Select(static (models, _) => TraitManifestTypeBuilder.BuildNoteDtos(models)))
            .Select(static (pair, _) => pair.Left.AddRange(pair.Right))
            .Combine(allAttachments.Select(static (models, _) => TraitManifestTypeBuilder.BuildAttachmentDtos(models)))
            .Select(static (pair, _) => pair.Left.AddRange(pair.Right));

        return new TraitOutput
        {
            TraitEntities = combinedTraitEntities,
            Actions = combinedActions,
            Queries = combinedQueries,
            Endpoints = combinedEndpoints,
            ManifestTypes = manifestTypes,
            Jobs = attachmentJobModels,
        };
    }

    /// <summary>
    ///     Reports PRAG2600 for a trait applied to a class that is not an entity.
    /// </summary>
    /// <remarks>
    ///     This cannot live in the four trait pipelines above: they drop the type by returning no
    ///     model, so by the time anything downstream could iterate, the offending type is gone. Without
    ///     it, <c>[HasComments]</c> on a class without <c>[Entity]</c> would generate nothing at all and
    ///     say nothing about it.
    /// </remarks>
    private static void ReportTraitsOnNonEntities(IncrementalGeneratorInitializationContext context)
    {
        RegisterFor(AttributeNames.HasComments, "HasComments");
        RegisterFor(AttributeNames.HasTags, "HasTags");
        RegisterFor(AttributeNames.HasNotes, "HasNotes");
        RegisterFor(AttributeNames.HasAttachments, "HasAttachments");

        void RegisterFor(string attributeName, string traitName)
        {
            var provider = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    attributeName,
                    predicate: static (node, _) => node is ClassDeclarationSyntax,
                    transform: (ctx, ct) => MissingEntityTraitTransform.Transform(ctx, traitName, ct))
                .Where(static m => m is not null)
                .Select(static (m, _) => m!.Value);

            context.RegisterSourceOutputSafe(provider, static (ctx, problem) =>
            {
                if (problem.CollidingMember is null)
                {
                    ctx.ReportDiagnostic(
                        TraitDiagnostics.TraitRequiresEntity,
                        problem.Location?.ToLocation(),
                        problem.TypeName,
                        problem.TraitName);
                    return;
                }

                ctx.ReportDiagnostic(
                    TraitDiagnostics.TraitNavigationCollides,
                    problem.Location?.ToLocation(),
                    problem.TypeName,
                    problem.CollidingMember,
                    problem.TraitName);
            });
        }
    }

    private static void GenerateCommentEntity(SourceProductionContext ctx, CommentTraitModel model)
    {
        var template = new CommentEntityTemplate(model);
        var artifact = template.RenderOutput();
        if (!artifact.IsEmpty)
            ctx.AddSource(artifact);
    }

    private static void GenerateCommentEntityConfig(SourceProductionContext ctx, CommentTraitModel model)
    {
        var template = new CommentEntityConfigTemplate(model);
        var artifact = template.RenderOutput();
        if (!artifact.IsEmpty)
            ctx.AddSource(artifact);
    }

    private static void GenerateParentNavigation(SourceProductionContext ctx, CommentTraitModel model)
    {
        var template = new ParentTraitNavigationTemplate(model);
        var artifact = template.RenderOutput();
        if (!artifact.IsEmpty)
            ctx.AddSource(artifact);
    }

    private static Persistence.Models.QueryModel BuildListCommentsQueryModel(CommentTraitModel model)
    {
        var dtoTypeName = $"{model.CommentTypeName}Dto";
        return new Persistence.Models.QueryModel
        {
            Namespace = model.ParentNamespace,
            TypeName = $"List{model.ParentTypeName}CommentsQuery",
            Accessibility = "public",
            TypeKind = "class",
            // The boundary whose keyed context the generated invoker reads from. Without it the invoker
            // resolves an unkeyed DbContext, which a host that registers one context per boundary does
            // not have — every read through this query answered 500.
            BoundaryTypeName = model.BoundaryFullTypeName,
            EntityTypeFullName = model.CommentFullTypeName,
            EntityTypeName = model.CommentTypeName,
            ResultTypeFullName = string.IsNullOrEmpty(model.ParentNamespace) ? dtoTypeName : $"{model.ParentNamespace}.{dtoTypeName}",
            ResultTypeName = dtoTypeName,
            Properties = ImmutableArray.Create(
                new Persistence.Models.QueryPropertyModel
                {
                    PropertyName = $"{model.ParentTypeName}Id",
                    PropertyType = model.SimpleIdType,
                    IsRequired = true,
                    IsFilter = true,
                    Operator = Persistence.Models.FilterOperatorKind.Equals,
                    MapTo = model.ParentFkPropertyName,
                },
                new Persistence.Models.QueryPropertyModel
                {
                    PropertyName = "Page",
                    PropertyType = "int",
                    IsPageProperty = true,
                },
                new Persistence.Models.QueryPropertyModel
                {
                    PropertyName = "PageSize",
                    PropertyType = "int",
                    IsPageSizeProperty = true,
                },
                // Deterministic default order: paging without one can repeat or skip rows between pages.
                new Persistence.Models.QueryPropertyModel
                {
                    PropertyName = "CreatedAtSort",
                    PropertyType = "SortDirection?",
                    QualifiedPropertyType = "global::Pragmatic.Persistence.Query.SortDirection?",
                    IsSort = true,
                    DefaultSortDirection = Persistence.Models.SortDirectionKind.Descending,
                    MapTo = "CreatedAt",
                }),
        };
    }

    private static void GenerateCommentDto(SourceProductionContext ctx, CommentTraitModel model)
    {
        var template = new CommentDtoTemplate(model);
        var artifact = template.RenderOutput();
        if (!artifact.IsEmpty)
            ctx.AddSource(artifact);
    }

    private static void GenerateCommentListQuery(SourceProductionContext ctx, CommentTraitModel model)
    {
        var template = new CommentListQueryTemplate(model);
        var artifact = template.RenderOutput();
        if (!artifact.IsEmpty)
            ctx.AddSource(artifact);
    }

    private static void GenerateCommentAction(SourceProductionContext ctx, CommentTraitModel model, CommentActionKind kind)
    {
        var template = new CommentActionsTemplate(model, kind);
        var artifact = template.RenderOutput();
        if (!artifact.IsEmpty)
            ctx.AddSource(artifact);
    }

    private static void GenerateCommentInternalVisibilityFilter(SourceProductionContext ctx, CommentTraitModel model)
    {
        var template = new CommentInternalVisibilityFilterTemplate(model);
        var artifact = template.RenderOutput();
        if (!artifact.IsEmpty)
            ctx.AddSource(artifact);
    }

    private static void GenerateCommentPermissions(SourceProductionContext ctx, CommentTraitModel model)
    {
        var template = new CommentPermissionsTemplate(model);
        var artifact = template.RenderOutput();
        if (!artifact.IsEmpty)
            ctx.AddSource(artifact);
    }

    // ── Tag helpers ────────────────────────────────────────────────────

    // ── Note helpers ────────────────────────────────────────────────────

    private static void GenerateNoteEntity(SourceProductionContext ctx, NoteTraitModel model)
    {
        var template = new NoteEntityTemplate(model);
        var artifact = template.RenderOutput();
        if (!artifact.IsEmpty) ctx.AddSource(artifact);
    }

    private static void GenerateNoteEntityConfig(SourceProductionContext ctx, NoteTraitModel model)
    {
        var template = new NoteEntityConfigTemplate(model);
        var artifact = template.RenderOutput();
        if (!artifact.IsEmpty) ctx.AddSource(artifact);
    }

    private static void GenerateParentNoteNavigation(SourceProductionContext ctx, NoteTraitModel model)
    {
        var template = new ParentNoteNavigationTemplate(model);
        var artifact = template.RenderOutput();
        if (!artifact.IsEmpty) ctx.AddSource(artifact);
    }

    private static void GenerateNoteAction(SourceProductionContext ctx, NoteTraitModel model, NoteActionKind kind)
    {
        var template = new NoteActionsTemplate(model, kind);
        var artifact = template.RenderOutput();
        if (!artifact.IsEmpty) ctx.AddSource(artifact);
    }

    private static void GenerateNotePermissions(SourceProductionContext ctx, NoteTraitModel model)
    {
        var template = new NotePermissionsTemplate(model);
        var artifact = template.RenderOutput();
        if (!artifact.IsEmpty) ctx.AddSource(artifact);
    }

    private static void GenerateNoteDto(SourceProductionContext ctx, NoteTraitModel model)
    {
        var template = new NoteDtoTemplate(model);
        var artifact = template.RenderOutput();
        if (!artifact.IsEmpty) ctx.AddSource(artifact);
    }

    private static void GenerateNoteListQuery(SourceProductionContext ctx, NoteTraitModel model)
    {
        var template = new NoteListQueryTemplate(model);
        var artifact = template.RenderOutput();
        if (!artifact.IsEmpty) ctx.AddSource(artifact);
    }

    private static Persistence.Models.QueryModel BuildListNotesQueryModel(NoteTraitModel model)
    {
        var dtoTypeName = $"{model.NoteTypeName}Dto";
        return new Persistence.Models.QueryModel
        {
            Namespace = model.ParentNamespace,
            TypeName = $"List{model.ParentTypeName}NotesQuery",
            Accessibility = "public",
            TypeKind = "class",
            // The boundary whose keyed context the generated invoker reads from. Without it the invoker
            // resolves an unkeyed DbContext, which a host that registers one context per boundary does
            // not have — every read through this query answered 500.
            BoundaryTypeName = model.BoundaryFullTypeName,
            EntityTypeFullName = model.NoteFullTypeName,
            EntityTypeName = model.NoteTypeName,
            ResultTypeFullName = string.IsNullOrEmpty(model.ParentNamespace) ? dtoTypeName : $"{model.ParentNamespace}.{dtoTypeName}",
            ResultTypeName = dtoTypeName,
            Properties = ImmutableArray.Create(
                new Persistence.Models.QueryPropertyModel
                {
                    PropertyName = $"{model.ParentTypeName}Id",
                    PropertyType = model.SimpleIdType,
                    IsRequired = true,
                    IsFilter = true,
                    Operator = Persistence.Models.FilterOperatorKind.Equals,
                    MapTo = model.ParentFkPropertyName,
                },
                new Persistence.Models.QueryPropertyModel
                {
                    PropertyName = "Page",
                    PropertyType = "int",
                    IsPageProperty = true,
                },
                new Persistence.Models.QueryPropertyModel
                {
                    PropertyName = "PageSize",
                    PropertyType = "int",
                    IsPageSizeProperty = true,
                },
                // Deterministic default order: paging without one can repeat or skip rows between pages.
                new Persistence.Models.QueryPropertyModel
                {
                    PropertyName = "CreatedAtSort",
                    PropertyType = "SortDirection?",
                    QualifiedPropertyType = "global::Pragmatic.Persistence.Query.SortDirection?",
                    IsSort = true,
                    DefaultSortDirection = Persistence.Models.SortDirectionKind.Descending,
                    MapTo = "CreatedAt",
                }),
        };
    }

    // ── Attachment helpers ────────────────────────────────────────────

    private static void GenerateAttachmentEntity(SourceProductionContext ctx, AttachmentTraitModel model)
    { var t = new AttachmentEntityTemplate(model); var a = t.RenderOutput(); if (!a.IsEmpty) ctx.AddSource(a); }

    private static void GenerateAttachmentEntityConfig(SourceProductionContext ctx, AttachmentTraitModel model)
    { var t = new AttachmentEntityConfigTemplate(model); var a = t.RenderOutput(); if (!a.IsEmpty) ctx.AddSource(a); }

    private static void GenerateParentAttachmentNavigation(SourceProductionContext ctx, AttachmentTraitModel model)
    { var t = new ParentAttachmentNavigationTemplate(model); var a = t.RenderOutput(); if (!a.IsEmpty) ctx.AddSource(a); }

    private static void GenerateAttachmentAction(SourceProductionContext ctx, AttachmentTraitModel model, AttachmentActionKind kind, bool imagingAvailable = false)
    { var t = new AttachmentActionsTemplate(model, kind, imagingAvailable); var a = t.RenderOutput(); if (!a.IsEmpty) ctx.AddSource(a); }

    private static void GenerateAttachmentPurgeJob(SourceProductionContext ctx, AttachmentTraitModel model)
    { var t = new AttachmentPurgeJobTemplate(model); var a = t.RenderOutput(); if (!a.IsEmpty) ctx.AddSource(a); }

    private static void GenerateAttachmentPermissions(SourceProductionContext ctx, AttachmentTraitModel model)
    { var t = new AttachmentPermissionsTemplate(model); var a = t.RenderOutput(); if (!a.IsEmpty) ctx.AddSource(a); }

    private static void GenerateAttachmentDto(SourceProductionContext ctx, AttachmentTraitModel model)
    { var t = new AttachmentDtoTemplate(model); var a = t.RenderOutput(); if (!a.IsEmpty) ctx.AddSource(a); }

    private static void GenerateAttachmentListQuery(SourceProductionContext ctx, AttachmentTraitModel model)
    { var t = new AttachmentListQueryTemplate(model); var a = t.RenderOutput(); if (!a.IsEmpty) ctx.AddSource(a); }

    private static Persistence.Models.QueryModel BuildListAttachmentsQueryModel(AttachmentTraitModel model)
    {
        var dtoTypeName = $"{model.AttachmentTypeName}Dto";
        return new Persistence.Models.QueryModel
        {
            Namespace = model.ParentNamespace,
            TypeName = $"List{model.ParentTypeName}AttachmentsQuery",
            Accessibility = "public", TypeKind = "class",
            // The boundary whose keyed context the generated invoker reads from. Without it the invoker
            // resolves an unkeyed DbContext, which a host that registers one context per boundary does
            // not have — every read through this query answered 500.
            BoundaryTypeName = model.BoundaryFullTypeName,
            EntityTypeFullName = model.AttachmentFullTypeName,
            EntityTypeName = model.AttachmentTypeName,
            ResultTypeFullName = string.IsNullOrEmpty(model.ParentNamespace) ? dtoTypeName : $"{model.ParentNamespace}.{dtoTypeName}",
            ResultTypeName = dtoTypeName,
            Properties = ImmutableArray.Create(
                new Persistence.Models.QueryPropertyModel { PropertyName = $"{model.ParentTypeName}Id", PropertyType = model.SimpleIdType, IsRequired = true, IsFilter = true, Operator = Persistence.Models.FilterOperatorKind.Equals, MapTo = model.ParentFkPropertyName },
                new Persistence.Models.QueryPropertyModel { PropertyName = "Page", PropertyType = "int", IsPageProperty = true },
                new Persistence.Models.QueryPropertyModel { PropertyName = "PageSize", PropertyType = "int", IsPageSizeProperty = true },
                // Deterministic default order: paging without one can repeat or skip rows between pages.
                new Persistence.Models.QueryPropertyModel
                {
                    PropertyName = "UploadedAtSort",
                    PropertyType = "SortDirection?",
                    QualifiedPropertyType = "global::Pragmatic.Persistence.Query.SortDirection?",
                    IsSort = true,
                    DefaultSortDirection = Persistence.Models.SortDirectionKind.Descending,
                    MapTo = "UploadedAt",
                }),
        };
    }

    // ── Tag helpers ────────────────────────────────────────────────────

    private static void GenerateTagEntityConfig(SourceProductionContext ctx, TagTraitModel model)
    {
        var template = new TagEntityConfigTemplate(model);
        var artifact = template.RenderOutput();
        if (!artifact.IsEmpty)
            ctx.AddSource(artifact);
    }

    private static void GenerateTagEntity(SourceProductionContext ctx, TagTraitModel model)
    {
        var template = new TagEntityTemplate(model);
        var artifact = template.RenderOutput();
        if (!artifact.IsEmpty)
            ctx.AddSource(artifact);
    }

    private static void GenerateTagJunction(SourceProductionContext ctx, TagTraitModel model)
    {
        var template = new TagJunctionTemplate(model);
        var artifact = template.RenderOutput();
        if (!artifact.IsEmpty)
            ctx.AddSource(artifact);
    }

    private static void GenerateTagJunctionConfig(SourceProductionContext ctx, TagTraitModel model)
    {
        var template = new TagJunctionConfigTemplate(model);
        var artifact = template.RenderOutput();
        if (!artifact.IsEmpty)
            ctx.AddSource(artifact);
    }

    private static void GenerateParentTagNavigation(SourceProductionContext ctx, TagTraitModel model)
    {
        var template = new ParentTagNavigationTemplate(model);
        var artifact = template.RenderOutput();
        if (!artifact.IsEmpty)
            ctx.AddSource(artifact);
    }

    private static void GenerateTagAction(SourceProductionContext ctx, TagTraitModel model, TagActionKind kind)
    {
        var template = new TagActionsTemplate(model, kind);
        var artifact = template.RenderOutput();
        if (!artifact.IsEmpty)
            ctx.AddSource(artifact);
    }

    private static void GenerateTagPermissions(SourceProductionContext ctx, TagTraitModel model)
    {
        var template = new TagPermissionsTemplate(model);
        var artifact = template.RenderOutput();
        if (!artifact.IsEmpty)
            ctx.AddSource(artifact);
    }

    private static void GenerateTagDto(SourceProductionContext ctx, TagTraitModel model)
    {
        var template = new TagDtoTemplate(model);
        var artifact = template.RenderOutput();
        if (!artifact.IsEmpty)
            ctx.AddSource(artifact);
    }

    private static void GenerateTagListQuery(SourceProductionContext ctx, TagTraitModel model)
    {
        var template = new TagListQueryTemplate(model);
        var artifact = template.RenderOutput();
        if (!artifact.IsEmpty)
            ctx.AddSource(artifact);
    }

    private static Persistence.Models.QueryModel BuildListTagsQueryModel(TagTraitModel model)
    {
        var dtoTypeName = model.TagDtoTypeName;
        return new Persistence.Models.QueryModel
        {
            Namespace = model.ParentNamespace,
            TypeName = model.ListQueryTypeName,
            Accessibility = "public",
            TypeKind = "class",
            // The boundary whose keyed context the generated invoker reads from — see the other three.
            BoundaryTypeName = model.BoundaryFullTypeName,
            EntityTypeFullName = model.JunctionFullTypeName,
            EntityTypeName = model.JunctionTypeName,
            ResultTypeFullName = string.IsNullOrEmpty(model.ParentNamespace) ? dtoTypeName : $"{model.ParentNamespace}.{dtoTypeName}",
            ResultTypeName = dtoTypeName,
            Properties = ImmutableArray.Create(
                new Persistence.Models.QueryPropertyModel
                {
                    PropertyName = model.ParentFkPropertyName,
                    PropertyType = model.SimpleIdType,
                    IsRequired = true,
                    IsFilter = true,
                    Operator = Persistence.Models.FilterOperatorKind.Equals,
                    MapTo = model.ParentFkPropertyName,
                },
                new Persistence.Models.QueryPropertyModel
                {
                    PropertyName = "Page",
                    PropertyType = "int",
                    IsPageProperty = true,
                },
                new Persistence.Models.QueryPropertyModel
                {
                    PropertyName = "PageSize",
                    PropertyType = "int",
                    IsPageSizeProperty = true,
                },
                // Deterministic default order: paging without one can repeat or skip rows between pages.
                new Persistence.Models.QueryPropertyModel
                {
                    PropertyName = "AddedAtSort",
                    PropertyType = "SortDirection?",
                    QualifiedPropertyType = "global::Pragmatic.Persistence.Query.SortDirection?",
                    IsSort = true,
                    DefaultSortDirection = Persistence.Models.SortDirectionKind.Descending,
                    MapTo = "AddedAt",
                }),
        };
    }

    // ── Trait entity descriptions ──────────────────────────────────────
    //
    // One builder per trait entity, used by BOTH the assembly-metadata output and the DbContext
    // injection, so the two cannot drift. They describe the same relationships and constraints the
    // EntityConfig templates declare: without that description the emitted schema would have no
    // foreign keys and no indexes at all, and the tag uniqueness the docs present as a guarantee would
    // not exist in the database.

    private static TraitEntityInfo CommentEntityInfo(CommentTraitModel m) => new()
    {
        TypeName = m.CommentTypeName,
        Namespace = m.ParentNamespace,
        BoundaryName = m.BoundaryName,
        TraitKind = "Comment",
        HasParentVisibilityFilter = m.ParentIsRowProtected,
        HasInternalVisibilityFilter = m.SupportInternalNotes,
        ParentTenantNavigation = m.ParentIsTenantScoped ? m.ParentTypeName : null,
        IsSoftDelete = true,
        Relations = ImmutableArray.Create(ParentRelation(m.ParentFkPropertyName, m.ParentTypeName)),
    };

    private static TraitEntityInfo NoteEntityInfo(NoteTraitModel m) => new()
    {
        TypeName = m.NoteTypeName,
        Namespace = m.ParentNamespace,
        BoundaryName = m.BoundaryName,
        TraitKind = "Note",
        HasParentVisibilityFilter = m.ParentIsRowProtected,
        ParentTenantNavigation = m.ParentIsTenantScoped ? m.ParentTypeName : null,
        IsSoftDelete = true,
        Relations = ImmutableArray.Create(ParentRelation(m.ParentFkPropertyName, m.ParentTypeName)),
    };

    /// <summary>
    ///     Emits <c>ParentVisibilityFilter</c> on a trait child whose parent restricts rows.
    /// </summary>
    private static void GenerateParentVisibilityFilter(
        SourceProductionContext ctx,
        string parentNamespace,
        string childTypeName,
        string parentTypeName,
        string? boundaryName,
        bool isOwned,
        bool isScoped)
    {
        var template = new Templates.TraitParentVisibilityFilterTemplate(
            new Templates.TraitParentVisibilityModel(
                parentNamespace,
                childTypeName,
                parentTypeName,
                parentTypeName,                       // the reference navigation is named after the parent
                BypassPermissionFor(boundaryName, parentTypeName),
                isOwned,
                isScoped));

        var artifact = template.RenderOutput();
        if (!artifact.IsEmpty)
            ctx.AddSource(artifact);
    }

    /// <summary>
    ///     The parent's own bypass permission, rebuilt exactly as <c>DataAccessFilterTemplate</c>
    ///     builds it: whoever may see every parent may list every child.
    /// </summary>
    private static string BypassPermissionFor(string? boundaryName, string parentTypeName)
    {
        var kebab = PermissionNaming.ToKebabCase(parentTypeName);
        return string.IsNullOrEmpty(boundaryName)
            ? $"{kebab}.view-all"
            : $"{boundaryName!.ToLowerInvariant()}.{kebab}.view-all";
    }

    private static TraitEntityInfo AttachmentEntityInfo(AttachmentTraitModel m) => new()
    {
        TypeName = m.AttachmentTypeName,
        Namespace = m.ParentNamespace,
        BoundaryName = m.BoundaryName,
        TraitKind = "Attachment",
        IsSoftDelete = true,
        HasParentVisibilityFilter = m.ParentIsRowProtected,
        ParentTenantNavigation = m.ParentIsTenantScoped ? m.ParentTypeName : null,
        Relations = ImmutableArray.Create(ParentRelation(m.ParentFkPropertyName, m.ParentTypeName)),
    };

    /// <summary>The shared tag: no soft delete (TagBase has no such columns), unique on (Value, Scope).</summary>
    private static TraitEntityInfo TagEntityInfo(TagTraitModel m) => new()
    {
        TypeName = m.TagTypeName,
        Namespace = m.ParentNamespace,
        BoundaryName = m.BoundaryName,
        TraitKind = "Tag",
        IsSoftDelete = false,
        UniqueColumns = "Value,Scope",
    };

    /// <summary>The junction: keyed on its two FKs, restrict towards the tag so a used tag cannot vanish.</summary>
    private static TraitEntityInfo TagJunctionEntityInfo(TagTraitModel m) => new()
    {
        TypeName = m.JunctionTypeName,
        Namespace = m.ParentNamespace,
        BoundaryName = m.BoundaryName,
        TraitKind = "TagJunction",
        HasParentVisibilityFilter = m.ParentIsRowProtected,
        ParentTenantNavigation = m.ParentIsTenantScoped ? m.ParentTypeName : null,
        KeyColumns = $"{m.ParentFkPropertyName},TagId",
        IsSoftDelete = false,
        Relations = ImmutableArray.Create(
            ParentRelation(m.ParentFkPropertyName, m.ParentTypeName),
            new TraitRelationInfo
            {
                ForeignKeyColumn = "TagId",
                ReferencedTypeName = m.TagTypeName,
                OnDelete = "Restrict",
            }),
    };

    private static TraitRelationInfo ParentRelation(string fkColumn, string parentTypeName) => new()
    {
        ForeignKeyColumn = fkColumn,
        ReferencedTypeName = parentTypeName,
        OnDelete = "Cascade",
    };
}
