<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ExcludeSharedTesting>true</ExcludeSharedTesting>
    <NoWarn>$(NoWarn);CA2007</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Pragmatic.Imaging\Pragmatic.Imaging.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Fixtures\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
