using System.Collections.Concurrent;
using System.Runtime.CompilerServices;
using System.Text;

namespace Pragmatic.Logging;

/// <summary>
/// Provides high-performance message formatting with zero-allocation patterns.
/// This is a transitional implementation using reflection - will be replaced by source generators for optimal performance.
/// </summary>
/// <remarks>
/// <para><strong>PERFORMANCE NOTE:</strong> This implementation uses reflection for property access which impacts performance.
/// The final implementation will use source generators to create compile-time property accessors for zero-allocation hot paths.</para>
/// <para>
/// Current implementation provides:
/// - Stack allocation for small messages (&lt; 1024 chars)
/// - StringBuilder fallback for larger messages
/// - Aggressive inlining for critical paths
/// </para>
/// <para>
/// Future source generator implementation will provide:
/// - Compile-time property resolution (no reflection)
/// - Direct span formatting without intermediate string allocations
/// - Specialized formatters for common types (DateTime, numbers, etc.)
/// </para>
/// </remarks>
/// <example>
/// <code>
/// // Current usage (works but uses reflection)
/// var formatted = MessageFormatter.Format("User {UserId} logged in", new { UserId = "john.doe" });
/// 
/// // Future generated usage (compile-time optimized)
/// // Will be generated by LoggerMethodGenerator for each LoggerMethod
/// </code>
/// </example>
internal static class MessageFormatter
{
    private const int DefaultBufferSize = 256;
    private const int MaxStackBufferSize = 1024;

    /// <summary>
    /// Formats a message template with the provided properties.
    /// </summary>
    /// <typeparam name="T">The type of the properties object</typeparam>
    /// <param name="template">The message template</param>
    /// <param name="properties">The properties object</param>
    /// <returns>The formatted message</returns>
    public static string Format<T>(string template, T properties)
    {
        if (string.IsNullOrEmpty(template))
        {
            return string.Empty;
        }

        // Try to format using stack-allocated buffer first
        Span<char> stackBuffer = stackalloc char[MaxStackBufferSize];
        if (TryFormat(template, properties, stackBuffer, out int charsWritten))
        {
            return stackBuffer[..charsWritten].ToString();
        }

        // Fall back to StringBuilder for larger messages
        StringBuilder sb = new StringBuilder(template.Length * 2);
        FormatToStringBuilder(template, properties, sb);
        return sb.ToString();
    }

    /// <summary>
    /// Tries to format a message template into the provided span.
    /// </summary>
    /// <typeparam name="T">The type of the properties object</typeparam>
    /// <param name="template">The message template</param>
    /// <param name="properties">The properties object</param>
    /// <param name="destination">The destination span</param>
    /// <param name="charsWritten">The number of characters written</param>
    /// <returns>True if formatting succeeded, false if the destination was too small</returns>
    public static bool TryFormat<T>(string template, T properties, Span<char> destination, out int charsWritten)
    {
        charsWritten = 0;

        if (string.IsNullOrEmpty(template))
        {
            return true;
        }

        ReadOnlySpan<char> reader = template.AsSpan();
        Span<char> writer = destination;
        int written = 0;

        while (reader.Length > 0)
        {
            int placeholderStart = reader.IndexOf('{');
            if (placeholderStart == -1)
            {
                // No more placeholders, copy rest of template
                if (reader.Length > writer.Length)
                {
                    return false;
                }

                reader.CopyTo(writer);
                written += reader.Length;
                break;
            }

            // Copy text before placeholder
            if (placeholderStart > 0)
            {
                ReadOnlySpan<char> beforePlaceholder = reader[..placeholderStart];
                if (beforePlaceholder.Length > writer.Length)
                {
                    return false;
                }

                beforePlaceholder.CopyTo(writer);
                writer = writer[beforePlaceholder.Length..];
                written += beforePlaceholder.Length;
            }

            reader = reader[placeholderStart..];
            int placeholderEnd = reader.IndexOf('}');
            if (placeholderEnd == -1)
            {
                // Malformed placeholder, copy rest as-is
                if (reader.Length > writer.Length)
                {
                    return false;
                }

                reader.CopyTo(writer);
                written += reader.Length;
                break;
            }

            // Extract property name
            ReadOnlySpan<char> propertyName = reader[1..placeholderEnd];

            // Try to format property value
            if (!TryFormatProperty(propertyName, properties, writer, out int propertyCharsWritten))
            {
                return false;
            }

            writer = writer[propertyCharsWritten..];
            written += propertyCharsWritten;
            reader = reader[(placeholderEnd + 1)..];
        }

        charsWritten = written;
        return true;
    }

    private static void FormatToStringBuilder<T>(string template, T properties, StringBuilder sb)
    {
        ReadOnlySpan<char> reader = template.AsSpan();

        while (reader.Length > 0)
        {
            int placeholderStart = reader.IndexOf('{');
            if (placeholderStart == -1)
            {
                _ = sb.Append(reader);
                break;
            }

            if (placeholderStart > 0)
            {
                _ = sb.Append(reader[..placeholderStart]);
            }

            reader = reader[placeholderStart..];
            int placeholderEnd = reader.IndexOf('}');
            if (placeholderEnd == -1)
            {
                _ = sb.Append(reader);
                break;
            }

            ReadOnlySpan<char> propertyName = reader[1..placeholderEnd];
            string? propertyValue = GetPropertyValue(propertyName, properties);
            _ = sb.Append(propertyValue);

            reader = reader[(placeholderEnd + 1)..];
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static bool TryFormatProperty<T>(ReadOnlySpan<char> propertyName, T properties, Span<char> destination, out int charsWritten)
    {
        charsWritten = 0;

        string? propertyValue = GetPropertyValue(propertyName, properties);
        if (propertyValue == null)
        {
            ReadOnlySpan<char> nullText = "null";
            if (nullText.Length > destination.Length)
            {
                return false;
            }

            nullText.CopyTo(destination);
            charsWritten = nullText.Length;
            return true;
        }

        ReadOnlySpan<char> valueSpan = propertyValue.AsSpan();
        if (valueSpan.Length > destination.Length)
        {
            return false;
        }

        valueSpan.CopyTo(destination);
        charsWritten = valueSpan.Length;
        return true;
    }

    // Zero-reflection property accessor — M.E.L log states implement IReadOnlyList<KVP>,
    private static string? GetPropertyValue<T>(ReadOnlySpan<char> propertyName, T properties)
    {
        if (properties == null)
            return null;

        string propertyNameString = propertyName.ToString();

        // All M.E.L structured log states implement IReadOnlyList<KeyValuePair<string, object?>>
        if (properties is IReadOnlyList<KeyValuePair<string, object?>> kvpList)
        {
            for (var i = 0; i < kvpList.Count; i++)
            {
                if (string.Equals(kvpList[i].Key, propertyNameString, StringComparison.Ordinal))
                    return kvpList[i].Value?.ToString();
            }
            return $"{{{propertyNameString}}}";
        }

        // Dictionary-based states
        if (properties is IReadOnlyDictionary<string, object?> dict)
        {
            return dict.TryGetValue(propertyNameString, out var val) ? val?.ToString() : $"{{{propertyNameString}}}";
        }

        // Unrecognized state type — render placeholder (zero reflection)
        return $"{{{propertyNameString}}}";
    }
}