// Linked into Pragmatic.Persistence (net10.0) and Pragmatic.SourceGenerator (netstandard2.0).
// One list, two readers — see the remarks below before adding a copy anywhere.

// ReSharper disable once CheckNamespace
namespace Pragmatic.Contracts;

/// <summary>
///     The property names the framework never puts on the wire: change tracking, tenancy, the
///     authorization shape, and the persistence keys.
/// </summary>
/// <remarks>
///     <para>
///         <b>Two ends of one channel.</b> The runtime strips these during serialization
///         (<c>EntityJsonModifier</c>) and the generator must not publish them in the API manifest or
///         the OpenAPI document (<c>ManifestTransform</c>). Writer and reader were each correct on
///         their own and disagreed with each other: the document announced <c>ownerId</c> on a DTO the
///         wire never carries it on, so a generated client read a silent default. Only comparing the
///         document against the wire shows it, which is why this file exists instead of two lists.
///     </para>
///     <para>
///         <b>Why a linked source file.</b> The two assemblies cannot reference each other — the
///         generator is netstandard2.0 and loads inside the compiler — and a shared package for nine
///         strings is worse than the problem. A linked file is the one shape where the correspondence
///         cannot drift, because there is nothing to keep in step.
///     </para>
///     <para>
///         <b>Internal on purpose.</b> Public would put the same type in two assemblies that some test
///         projects reference together, which is CS0433 — the reason
///         <c>Pragmatic.SourceGenerator.csproj</c> deliberately does not link
///         <c>MetadataCategory</c>. Internal types do not collide.
///     </para>
///     <para>
///         Not to be confused with the grid denylist (<c>SensitiveFieldNames</c> /
///         <c>AdapterFieldPolicy</c>), which answers a different question — what a client may
///         <em>name</em> in a filter — and carries credential column names this list has no reason to.
///     </para>
/// </remarks>
internal static class ReservedWireNames
{
    /// <summary>
    ///     Change tracking, which belongs to the types that do it: <c>IChangeTracking</c> and
    ///     <c>IHasDomainEvents</c>.
    /// </summary>
    /// <remarks>
    ///     ⚠️ Not matched by name on every object type: that takes the member away from an application
    ///     that has one of its own — the Showcase's
    ///     <c>PatchAmenityResult(Guid Id, List&lt;string&gt; ModifiedProperties)</c> answered <c>{"id": …}</c>
    ///     and the generated client had only <c>Id</c>. The framework does not own these names — it owns
    ///     the types that declare them.
    /// </remarks>
    private static readonly System.Collections.Generic.HashSet<string> ChangeTracking =
        new(System.StringComparer.OrdinalIgnoreCase)
        {
            "ModifiedProperties",
            "CollectionsModified",
            "IsNew",
            "DomainEvents",
        };

    /// <summary>
    ///     Tenancy, the authorization shape generated by <c>[HasOwner]</c> / <c>[HasAccessScopes]</c>, the
    ///     concurrency token and the persistence key.
    /// </summary>
    /// <remarks>
    ///     Stripped from <b>every</b> type, and deliberately so: a projection carries these by accident,
    ///     and leaking them lets a client read who owns a record and the scopes that make it visible
    ///     ("user:{id}", "scope:billing-eu") — reconnaissance for privilege escalation. That is a property
    ///     of the response, not of the type that produced it, so narrowing it to entities would give the
    ///     leak back through any DTO that projects them.
    /// </remarks>
    private static readonly System.Collections.Generic.HashSet<string> Infrastructure =
        new(System.StringComparer.OrdinalIgnoreCase)
        {
            "TenantId",
            "OwnerId",
            "AccessScopes",
            "RowVersion",
            "PersistenceId",
        };

    /// <summary>
    ///     Whether a property of this name is stripped from the wire whatever type declares it, and so
    ///     must not be published on any type.
    /// </summary>
    /// <remarks>
    ///     Case-insensitive: the runtime matches both the CLR name, as the reflection resolver sees it,
    ///     and the camelCased name a generated JSON context emits.
    /// </remarks>
    public static bool IsAlwaysStripped(string propertyName) => Infrastructure.Contains(propertyName);

    /// <summary>
    ///     Whether a property of this name is the framework's change tracking, stripped on the types that
    ///     declare it — an entity — and left alone on an application's own type.
    /// </summary>
    public static bool IsChangeTracking(string propertyName) => ChangeTracking.Contains(propertyName);

    /// <summary>
    ///     Whether a property of this name is stripped on a type that tracks its changes — an entity.
    /// </summary>
    public static bool IsReserved(string propertyName)
        => IsAlwaysStripped(propertyName) || IsChangeTracking(propertyName);
}
