// Linked into Pragmatic.Persistence (net10.0) and Pragmatic.SourceGenerator (netstandard2.0).
// One list, two readers — see the remarks below before adding a copy anywhere.

// ReSharper disable once CheckNamespace
namespace Pragmatic.Contracts;

/// <summary>
///     The property names a client may never <b>name</b> in a grid filter or sort: credential columns,
///     and the authorization shape the framework generates.
/// </summary>
/// <remarks>
///     <para>
///         <b>Two paths, one question.</b> The generator decides which fields
///         <c>[GenerateGridBridge]</c> and <c>[GridAdapter&lt;T&gt;]</c> may switch on; the runtime
///         <c>AdapterFieldPolicy</c> decides what a PrimeNG or DevExpress request may resolve. Both are
///         answering «may a client name this column», so they read one list rather than two
///         hand-maintained copies.
///     </para>
///     <para>
///         <b>Why it is a file and not a convention.</b> Two copies of the wire-name list produce a real
///         defect — a name stripped by one end and published by the other, both sides correct on their
///         own, and only a comparison of the two showing it. A linked file is the one shape where the
///         correspondence cannot drift, because there is nothing to keep in step. Sharing across
///         netstandard2.0 and net10.0 is possible: a plain static class of strings compiles in both, as
///         <c>ReservedWireNames</c> shows.
///     </para>
///     <para>
///         <b>Internal on purpose.</b> Public would put the same type in two assemblies that some test
///         projects reference together, which is <c>CS0433</c>. Internal types do not collide.
///     </para>
///     <para>
///         <b>Not the wire list.</b> <c>ReservedWireNames</c> answers what the serializer strips; this
///         answers what a client may ask about. They overlap on the authorization shape and diverge on
///         credentials — a password hash is on no DTO, so the wire list has no reason to carry it,
///         while a filter could still name the column. One direction must hold between them: everything
///         the wire strips is also refused here, or the stripping is decoration.
///     </para>
///     <para>
///         ⚠️ Why a filter over these is not a small leak: filtering makes a column talk without
///         returning it. <c>startswith</c> over a hash turns the presence of rows into an oracle that
///         reads the value one character at a time, and ordering by it ranks the page by a value nobody
///         published.
///     </para>
/// </remarks>
internal static class SensitiveGridFieldNames
{
    private static readonly System.Collections.Generic.HashSet<string> Names =
        new(System.StringComparer.OrdinalIgnoreCase)
        {
            // Credential-bearing columns.
            "Password", "PasswordHash", "PasswordSalt", "SecurityStamp",
            "ResetToken", "ResetTokenHash", "RefreshToken", "RefreshTokenHash",
            "ApiKey", "ApiKeyHash", "Secret", "SecretHash", "PrivateKey",
            // Authorization / infrastructure columns generated by the framework. These are also
            // ReservedWireNames: what the serializer refuses to carry must not be readable through a
            // filter instead.
            "OwnerId", "TenantId", "AccessScopes", "PersistenceId", "RowVersion",
        };

    /// <summary>
    ///     Whether a column of this name must be withheld from client-driven grid filter and sort.
    /// </summary>
    /// <param name="propertyName">The property name, as the entity or the client spells it.</param>
    /// <remarks>
    ///     Case-insensitive: a grid client sends the column key it was given, and a denylist that only
    ///     matches <c>PasswordHash</c> is lifted by asking for <c>passwordhash</c>.
    /// </remarks>
    public static bool IsSensitive(string propertyName) => Names.Contains(propertyName);
}
