using Microsoft.EntityFrameworkCore;

namespace Pragmatic.Persistence.EFCore.Samples.Inheritance;

/// <summary>
///     DbContext for the TPH inheritance demo. Calls the generated
///     <c>ChargeInheritanceConfiguration.Configure</c> to wire the discriminator.
/// </summary>
public sealed class InheritanceDbContext(DbContextOptions<InheritanceDbContext> options) : DbContext(options)
{
    public DbSet<Charge> Charges => Set<Charge>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.Entity<Charge>(e =>
        {
            e.HasKey(c => c.PersistenceId);
            e.Property(c => c.Amount).HasPrecision(18, 2);
        });

        // Generated by [Inheritance(Tph)] — registers HasDiscriminator("ChargeType") + HasValue per type.
        ChargeInheritanceConfiguration.Configure(modelBuilder);
    }
}
