using Pragmatic.Actions.Boundary;

namespace Pragmatic.Actions.Metadata;

/// <summary>
///     Assembly-level attribute that declares a boundary for cross-assembly discovery.
/// </summary>
/// <remarks>
///     <para>
///         Generated by the source generator, one per <c>[Boundary]</c>, and read by the generator of a host
///         that references the module, at compile time — which boundaries the assembly declares, and which
///         other boundaries' entities each reads.
///     </para>
///     <para>
///         What a module contains — its actions, mutations, repositories, validators, and the modules it
///         depends on — travels in the module's <c>[PragmaticMetadata]</c>, which is where the host reads it,
///         not here.
///     </para>
/// </remarks>
/// <example>
///     <code>
/// // Generated in each module assembly
/// [assembly: PragmaticModuleMetadata(
///     BoundaryType = typeof(BookingBoundary),
///     ReadAccessTypes = new[] { typeof(Property) }   // only with [ReadAccess&lt;T&gt;]
/// )]
/// </code>
/// </example>
[AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true)]
public sealed class PragmaticModuleMetadataAttribute : Attribute
{
    /// <summary>
    ///     Gets or sets the boundary marker type for this module.
    /// </summary>
    /// <remarks>
    ///     The boundary type must implement <see cref="IBoundary" />. The module's name is derived from it
    ///     — <c>BookingBoundary</c> → <c>Booking</c> — the same derivation the boundary's own generated
    ///     registration is named after.
    /// </remarks>
    public Type BoundaryType { get; set; } = null!;

    /// <summary>
    ///     Gets or sets entity types declared with <c>[ReadAccess&lt;T&gt;]</c> on this boundary.
    ///     These entities belong to other boundaries but are read via SQL join in this context.
    /// </summary>
    public Type[] ReadAccessTypes { get; set; } = [];
}
