<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <NoWarn>$(NoWarn);CA2007</NoWarn>
    <ExcludeSharedTesting>true</ExcludeSharedTesting>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Pragmatic.Configuration.Kubernetes\Pragmatic.Configuration.Kubernetes.csproj" />
  </ItemGroup>

</Project>
