<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- No source generator in this module, exclude generator test base -->
    <ExcludeSharedTesting>true</ExcludeSharedTesting>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Pragmatic.Temporal\Pragmatic.Temporal.csproj" />
    <ProjectReference Include="..\..\src\Pragmatic.Temporal.Internationalization\Pragmatic.Temporal.Internationalization.csproj" />
  </ItemGroup>

</Project>
