using System.Collections.Immutable;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Pragmatic.SourceGen;
using Pragmatic.SourceGenerator.Features.Composition;
using Pragmatic.SourceGenerator.Features.Traits.Models;

namespace Pragmatic.SourceGenerator.Features.Traits.Transforms;

/// <summary>
/// Reads trait entity metadata from referenced assemblies.
/// Scans for [PragmaticMetadata(19, ...)] attributes generated by <see cref="Templates.TraitEntityMetadataTemplate"/>.
/// </summary>
internal static class TraitEntityMetadataReader
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNameCaseInsensitive = true
    };

    /// <remarks>
    ///     Returns an <see cref="EquatableArray{T}" />: this read is driven by the
    ///     <c>CompilationProvider</c>, and a raw <c>ImmutableArray</c> compares by backing-array reference,
    ///     so a non-empty result would mark the step Modified on every edit even when the referenced
    ///     assemblies have not changed.
    /// </remarks>
    public static EquatableArray<TraitEntityInfo> ReadFromReferencedAssemblies(Compilation compilation, CancellationToken ct)
    {
        var builder = ImmutableArray.CreateBuilder<TraitEntityInfo>();

        foreach (var reference in compilation.SourceModule.ReferencedAssemblySymbols)
        {
            ct.ThrowIfCancellationRequested();

            foreach (var attr in reference.GetAttributes())
            {
                if (attr.AttributeClass?.Name != "PragmaticMetadataAttribute")
                    continue;
                if (attr.ConstructorArguments.Length < 3)
                    continue;
                if (attr.ConstructorArguments[0].Value is not int category || category.ToString() != MetadataCategoryIds.TraitEntities)
                    continue;

                var json = attr.ConstructorArguments[2].Value as string;
                if (string.IsNullOrEmpty(json))
                    continue;

                try
                {
                    var entries = JsonSerializer.Deserialize<TraitEntityEntry[]>(json!, JsonOptions);
                    if (entries is null) continue;

                    foreach (var entry in entries)
                    {
                        if (entry.TypeName is null || entry.Namespace is null) continue;
                        builder.Add(new TraitEntityInfo
                        {
                            TypeName = entry.TypeName,
                            Namespace = entry.Namespace,
                            BoundaryName = string.IsNullOrEmpty(entry.BoundaryName) ? null : entry.BoundaryName,
                            TraitKind = entry.TraitKind ?? "Unknown",
                            KeyColumns = string.IsNullOrEmpty(entry.KeyColumns) ? null : entry.KeyColumns,
                            UniqueColumns = string.IsNullOrEmpty(entry.UniqueColumns) ? null : entry.UniqueColumns,
                            IsSoftDelete = entry.IsSoftDelete,
                            HasParentVisibilityFilter = entry.HasParentVisibilityFilter,
                            HasInternalVisibilityFilter = entry.HasInternalVisibilityFilter,
                            ParentTenantNavigation = string.IsNullOrEmpty(entry.ParentTenantNavigation)
                                ? null
                                : entry.ParentTenantNavigation,
                            Relations = entry.Relations is null
                                ? EquatableArray<TraitRelationInfo>.Empty
                                : entry.Relations
                                    .Where(static r => !string.IsNullOrEmpty(r.Column) && !string.IsNullOrEmpty(r.References))
                                    .Select(static r => new TraitRelationInfo
                                    {
                                        ForeignKeyColumn = r.Column!,
                                        ReferencedTypeName = r.References!,
                                        OnDelete = string.IsNullOrEmpty(r.OnDelete) ? "NoAction" : r.OnDelete!,
                                    })
                                    .ToImmutableArray(),
                        });
                    }
                }
                catch
                {
                    // Skip malformed metadata
                }
            }
        }

        return builder.ToImmutable();
    }

    private sealed class TraitEntityEntry
    {
        public string? TypeName { get; set; }
        public string? Namespace { get; set; }
        public string? BoundaryName { get; set; }
        public string? TraitKind { get; set; }
        public string? KeyColumns { get; set; }
        public string? UniqueColumns { get; set; }
        public bool IsSoftDelete { get; set; }
        public bool HasParentVisibilityFilter { get; set; }
        public bool HasInternalVisibilityFilter { get; set; }
        public string? ParentTenantNavigation { get; set; }
        public TraitRelationEntry[]? Relations { get; set; }
        public string? ConfigTypeName { get; set; }
    }

    private sealed class TraitRelationEntry
    {
        public string? Column { get; set; }
        public string? References { get; set; }
        public string? OnDelete { get; set; }
    }
}
