<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>EF Core persistence for Pragmatic.Jobs. Job store and recurring job store backed by database.</Description>
    <PackageTags>jobs;efcore;persistence;scheduling</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pragmatic.Jobs\Pragmatic.Jobs.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

</Project>
