namespace Pragmatic.Actions.Boundary;

/// <summary>
///     Marker interface for bounded context types.
/// </summary>
/// <remarks>
///     <para>
///         Boundaries are typed markers that identify a bounded context within the domain.
///         Each boundary can be configured as either local (in-process) or remote (via HTTP).
///     </para>
///     <para>
///         Boundaries are typically generated by the source generator, but can also be
///         manually defined when more control is needed.
///     </para>
/// </remarks>
/// <example>
///     <code>
/// // Define a boundary
/// public sealed class StudentsBoundary : IBoundary { }
///
/// // Register it with configuration
/// services.AddStudentsModule(cfg => cfg.UseLocal().UseDatabase(opt => opt.UseNpgsql(cs)));
/// </code>
/// </example>
public interface IBoundary;
