<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>EF Core persistence for Pragmatic.Notifications. Notification tracking store backed by database (__Notifications table).</Description>
    <PackageTags>notifications;efcore;persistence;tracking</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pragmatic.Notifications\Pragmatic.Notifications.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

</Project>
