using System.Linq;
using Pragmatic.SourceGen.Testing;
using Pragmatic.Testing.Assertions;
using Xunit;

namespace Pragmatic.SourceGenerator.Tests.Features.Privacy;

/// <summary>
///     An action that reaches personal data through a boundary interface says which, and the register
///     lists it.
/// </summary>
/// <remarks>
///     <para>
///         ⚠️ The register derives an action's reach from the <b>types of its dependencies</b>:
///         <c>IRepository&lt;TEntity&gt;</c> or <c>IMutationInvoker&lt;TMutation, TEntity&gt;</c>. A
///         boundary interface names no entity, so an action composing through <c>I{Boundary}Actions</c>
///         — the form this codebase requires — <b>disappeared from the Article 30 register</b>, and
///         nothing said so. Measured: converting four of the consumer application's actions to the
///         boundary form turned two of its register tests red.
///     </para>
///     <para>
///         Both inference routes were rejected. Reading the boundary interface's operations
///         over-reports — it says the action <em>can</em> reach every entity of the boundary, not that
///         it does. Walking the call sites is exact only for the calls it can see, so an action
///         reaching data another way goes on disappearing while the register looks complete. What is
///         determinable at compile time is <b>stated</b>, not looked up.
///     </para>
///     <para>
///         ⚠️ <b>The boundary interface is never in this compilation, and these tests are written that
///         way on purpose.</b> It is generated by this same generator in this same pass, so the user's
///         compilation does not contain it — a generator cannot see another generator's output, its own
///         included. An earlier version of this file declared the interface as a stub and every test
///         passed while asserting behaviour that existed in no real module. The field below is
///         deliberately of an unresolved type.
///     </para>
/// </remarks>
public class AnActionDeclaresThePersonalDataItReachesTests
{
    private const string Subject = """
        namespace App
        {
            using Pragmatic.Privacy;

            [DataSubject("Email")]
            public class Customer
            {
                [PersonalData(DataCategory.Contact, Erasure = ErasureStrategy.Null)]
                public string Email { get; set; } = "";
            }

            public class UpsertCustomerMutation { }
        }
        """;

    /// <summary>The attribute as a stub; the real one ships in Pragmatic.Privacy.Abstractions.</summary>
    private const string DeclarationStub = """
        namespace Pragmatic.Privacy
        {
            [System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = true)]
            public sealed class ProcessesDataAttribute<TEntity> : System.Attribute { }
        }
        """;

    private static string Register(string action)
        => GeneratorTestHelper.GetGeneratedSourcesAsDictionary(
                GeneratorTestHelper.RunGenerator<PragmaticSourceGenerator>(
                    PrivacyTestSources.Stubs + PrivacyTestSources.AdapterStubs
                    + PrivacyTestSources.OperationStubs + DeclarationStub + Subject + action,
                    []))
            .Where(kv => kv.Key.Contains("_Infra.Privacy.ProcessingActivities"))
            .Select(kv => kv.Value)
            .FirstOrDefault() ?? string.Empty;

    /// <summary>
    ///     An action whose only dependency this compilation cannot resolve is listed by what it
    ///     declares.
    /// </summary>
    /// <remarks>
    ///     The whole point in one case: <c>IAppInternalActions</c> is declared nowhere here, which is
    ///     exactly what a generated boundary interface looks like from inside the module that uses it.
    ///     Nothing about the field can be read, and the attribute is what carries the answer.
    /// </remarks>
    [Fact]
    public void AnActionComposingAnUnresolvableInterface_IsListedByWhatItDeclares()
    {
        Register("""

            namespace App
            {
                [Pragmatic.Actions.Attributes.DomainAction]
                [Pragmatic.Privacy.ProcessesData<Customer>]
                [Pragmatic.Endpoints.Attributes.Endpoint(Pragmatic.Endpoints.HttpVerb.Post, "api/customers/import")]
                public partial class ImportCustomersAction : Pragmatic.Actions.Abstractions.VoidDomainAction
                {
                    private IAppInternalActions _app = null!;
                }
            }
            """)
            .Should().Contain("\"App.ImportCustomersAction\"").And.Contain("\"App.Customer\"",
                "the declaration is the only thing that can name the entity here");
    }

    /// <summary>Several entities, because an action composing three operations reaches three.</summary>
    [Fact]
    public void AnActionDeclaringSeveralEntities_IsListedAgainstEachOfThem()
    {
        var register = Register("""

            namespace App
            {
                using Pragmatic.Privacy;

                [DataSubject("Reference")]
                public class Supplier
                {
                    [PersonalData(DataCategory.Contact, Erasure = ErasureStrategy.Null)]
                    public string Reference { get; set; } = "";
                }

                [Pragmatic.Actions.Attributes.DomainAction]
                [ProcessesData<Customer>]
                [ProcessesData<Supplier>]
                [Pragmatic.Endpoints.Attributes.Endpoint(Pragmatic.Endpoints.HttpVerb.Post, "api/import")]
                public partial class ImportEverythingAction : Pragmatic.Actions.Abstractions.VoidDomainAction
                {
                    private IAppInternalActions _app = null!;
                }
            }
            """);

        register.Should().Contain("\"App.Customer\"").And.Contain("\"App.Supplier\"",
            "the attribute repeats, and listing only the first would understate the processing");
    }

    /// <summary>The control: the derivation that already worked keeps working, with nothing declared.</summary>
    /// <remarks>
    ///     The attribute is an addition, not a replacement. Without this, the change would quietly make
    ///     every existing action need an attribute to stay in the register — the same silent loss with
    ///     the blame moved.
    /// </remarks>
    [Fact]
    public void AnActionHoldingARepository_IsStillListed_WithNothingDeclared()
    {
        Register("""

            namespace App
            {
                [Pragmatic.Actions.Attributes.DomainAction]
                [Pragmatic.Endpoints.Attributes.Endpoint(Pragmatic.Endpoints.HttpVerb.Post, "api/customers/purge")]
                public partial class PurgeCustomersAction : Pragmatic.Actions.Abstractions.VoidDomainAction
                {
                    private Pragmatic.Persistence.Repository.IRepository<Customer> _customers = null!;
                }
            }
            """)
            .Should().Contain("\"App.PurgeCustomersAction\"").And.Contain("\"App.Customer\"");
    }

    /// <summary>The second control: nothing derivable and nothing declared stays out.</summary>
    /// <remarks>
    ///     ⚠️ And it is <b>not reported</b>, which is the half of this story that is not delivered: the
    ///     omission is still silent. Noticing it needs the boundary interface, and this compilation does
    ///     not have it. The register's value is that every row in it is derived or declared; what is
    ///     missing is a way to see the operation that is in neither.
    /// </remarks>
    [Fact]
    public void AnActionWithNothingDerivableAndNothingDeclared_StaysOut()
    {
        Register("""

            namespace App
            {
                public interface ISearchIndex { }

                [Pragmatic.Actions.Attributes.DomainAction]
                [Pragmatic.Endpoints.Attributes.Endpoint(Pragmatic.Endpoints.HttpVerb.Post, "api/index/rebuild")]
                public partial class RebuildIndexAction : Pragmatic.Actions.Abstractions.VoidDomainAction
                {
                    private ISearchIndex _index = null!;
                }
            }
            """)
            .Should().NotContain("RebuildIndexAction",
                "not listed against a guess: every row is derived or declared");
    }
}
