using System.Security.Cryptography;
using System.Text;

namespace Pragmatic.Client.Cli;

/// <summary>
///     Emits the TypeScript client for one manifest module: types.ts (DTOs + enums),
///     errors.ts (ApiError + code union), client.ts (fetch-based, discriminated result),
///     paging.ts (PagedResult). Output is deterministic; every file carries the manifest hash.
/// </summary>
public static class TsEmitter
{
    /// <summary>Emits all files for a module; key = relative file name, value = content.</summary>
    public static IReadOnlyDictionary<string, string> Emit(ManifestJson.ManifestDoc module, string manifestJson)
    {
        var header = Header(manifestJson);
        var boundary = module.BoundaryName;

        return new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["types.ts"] = header + EmitTypes(module),
            ["errors.ts"] = header + EmitErrors(module),
            ["paging.ts"] = header + EmitPaging(),
            ["client.ts"] = header + EmitClient(module, boundary)
        };
    }

    private static string Header(string manifestJson)
    {
        var hash = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(manifestJson)))[..16];
        return $"// pragmatic-manifest/v1 sha256:{hash}\n// Generated by pragmatic-client — do not edit.\n\n";
    }

    private static string EmitTypes(ManifestJson.ManifestDoc module)
    {
        var sb = new StringBuilder();

        foreach (var type in (module.Types ?? []).Where(t => t.SimpleName is not null))
        {
            switch (type.Kind)
            {
                case "enum" when type.Values is { Count: > 0 }:
                    sb.Append("export type ").Append(type.SimpleName).Append(" = ");
                    sb.AppendJoin(" | ", type.Values.Select(v => $"'{v}'"));
                    sb.AppendLine(";");
                    sb.AppendLine();
                    break;

                case "dto" or "entity" when type.Properties is { Count: > 0 }:
                    sb.Append("export interface ").Append(type.SimpleName).AppendLine(" {");
                    foreach (var prop in type.Properties.Where(p => p.Name is not null))
                    {
                        var optional = prop.IsNullable || !prop.IsRequired ? "?" : "";
                        sb.Append("  ").Append(CamelCase(prop.Name!)).Append(optional).Append(": ")
                            .Append(TsType(prop.Type, module)).AppendLine(";");
                    }

                    sb.AppendLine("}");
                    sb.AppendLine();
                    break;
            }
        }

        return sb.ToString();
    }

    private static string EmitErrors(ManifestJson.ManifestDoc module)
    {
        var sb = new StringBuilder();

        var codes = (module.Types ?? [])
            .Where(t => t.Kind == "error" && t.ErrorCode is not null)
            .Select(t => t.ErrorCode!)
            .Concat((module.Endpoints ?? []).SelectMany(e => e.Errors ?? []).Select(e => e.Code!)
                .Where(c => c is not null))
            .Distinct(StringComparer.Ordinal)
            .OrderBy(c => c, StringComparer.Ordinal)
            .ToList();

        sb.AppendLine("/** Machine-readable error codes this API can produce. */");
        sb.Append("export type ApiErrorCode = ");
        sb.AppendJoin(" | ", codes.Count > 0 ? codes.Select(c => $"'{c}'") : ["string"]);
        sb.AppendLine(";");
        sb.AppendLine();
        sb.AppendLine("/** ProblemDetails-shaped API error. */");
        sb.AppendLine("export interface ApiError {");
        sb.AppendLine("  code: ApiErrorCode | string;");
        sb.AppendLine("  title?: string;");
        sb.AppendLine("  detail?: string;");
        sb.AppendLine("  status: number;");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string EmitPaging() =>
        """
        /** Paged response payload (mirrors the server's PagedResult wire shape). */
        export interface PagedResult<T> {
          items: T[];
          totalCount: number;
          page: number;
          pageSize: number;
        }
        """ + "\n";

    private static string EmitClient(ManifestJson.ManifestDoc module, string boundary)
    {
        var sb = new StringBuilder();
        sb.AppendLine("import type { ApiError } from './errors';");
        sb.AppendLine("import type { PagedResult } from './paging';");
        sb.AppendLine("import type * as T from './types';");
        sb.AppendLine();
        sb.AppendLine("/** Discriminated result: check `ok` before reading `value`/`error`. */");
        sb.AppendLine("export type ApiResult<TValue> =");
        sb.AppendLine("  | { ok: true; value: TValue; status: number }");
        sb.AppendLine("  | { ok: false; error: ApiError; status: number };");
        sb.AppendLine();
        sb.Append("export class ").Append(boundary).AppendLine("Client {");
        sb.AppendLine("  constructor(");
        sb.AppendLine("    private readonly baseUrl: string,");
        sb.AppendLine("    private readonly options?: { headers?: Record<string, string>; fetchImpl?: typeof fetch },");
        sb.AppendLine("  ) {}");

        foreach (var endpoint in (module.Endpoints ?? [])
                     .Where(e => e is { OperationId: not null, FullRoute: not null, Response.IsStream: not true })
                     .OrderBy(e => e.OperationId, StringComparer.Ordinal))
            EmitOperation(sb, endpoint, module);

        sb.AppendLine();
        sb.AppendLine("  private async send<TValue>(method: string, url: string, body?: unknown): Promise<ApiResult<TValue>> {");
        sb.AppendLine("    const doFetch = this.options?.fetchImpl ?? fetch;");
        sb.AppendLine("    const response = await doFetch(this.baseUrl + url, {");
        sb.AppendLine("      method,");
        sb.AppendLine("      headers: { 'content-type': 'application/json', ...this.options?.headers },");
        sb.AppendLine("      body: body === undefined ? undefined : JSON.stringify(body),");
        sb.AppendLine("    });");
        sb.AppendLine("    const text = await response.text();");
        sb.AppendLine("    const payload = text.length > 0 ? JSON.parse(text) : undefined;");
        sb.AppendLine("    if (response.ok) return { ok: true, value: payload as TValue, status: response.status };");
        sb.AppendLine("    const problem = (payload ?? {}) as Partial<ApiError>;");
        sb.AppendLine("    return {");
        sb.AppendLine("      ok: false,");
        sb.AppendLine("      status: response.status,");
        sb.AppendLine("      error: { code: problem.code ?? 'unknown', title: problem.title, detail: problem.detail, status: response.status },");
        sb.AppendLine("    };");
        sb.AppendLine("  }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitOperation(StringBuilder sb, ManifestJson.EndpointDoc endpoint, ManifestJson.ManifestDoc module)
    {
        var name = CamelCase(endpoint.OperationId!.Split('.').Last());
        var routeParams = (endpoint.Parameters ?? []).Where(p => p.In == "path" && p.Name is not null).ToList();
        var queryParams = (endpoint.Parameters ?? []).Where(p => p.In == "query" && p.Name is not null).ToList();
        var hasBody = endpoint.RequestBody?.Properties is { Count: > 0 };

        var responseType = endpoint.IsVoid ? "void" : TsType(endpoint.Response?.Type, module);

        var args = new List<string>();
        foreach (var routeParam in routeParams)
            args.Add($"{CamelCase(routeParam.Name!)}: {TsType(routeParam.Type, module)}");
        if (hasBody)
            args.Add($"body: {{ {string.Join("; ", endpoint.RequestBody!.Properties!
                .Where(p => p.Name is not null)
                .Select(p => $"{CamelCase(p.Name!)}{(p.IsRequired ? "" : "?")}: {TsType(p.Type, module)}"))} }}");
        if (queryParams.Count > 0)
            args.Add($"query?: {{ {string.Join("; ", queryParams
                .Select(p => $"{CamelCase(p.Name!)}?: {TsType(p.Type, module)}"))} }}");

        sb.AppendLine();
        if (endpoint.Summary is not null)
            sb.Append("  /** ").Append(endpoint.Summary.Replace("*/", "*\\/")).AppendLine(" */");
        sb.Append("  ").Append(name).Append('(').Append(string.Join(", ", args))
            .Append("): Promise<ApiResult<").Append(responseType).AppendLine(">> {");

        // Route: /api/orders/{id} → `/api/orders/${encodeURIComponent(String(id))}`
        var route = endpoint.FullRoute!;
        foreach (var routeParam in routeParams)
            route = System.Text.RegularExpressions.Regex.Replace(
                route,
                $@"\{{{routeParam.Name}(:[^}}]*)?\??\}}",
                $"${{encodeURIComponent(String({CamelCase(routeParam.Name!)}))}}",
                System.Text.RegularExpressions.RegexOptions.IgnoreCase);

        sb.Append("    let url = `").Append(route).AppendLine("`;");
        if (queryParams.Count > 0)
        {
            sb.AppendLine("    const qs = new URLSearchParams();");
            foreach (var queryParam in queryParams)
            {
                var prop = CamelCase(queryParam.Name!);
                sb.Append("    if (query?.").Append(prop).Append(" !== undefined) qs.set('")
                    .Append(queryParam.Name).Append("', String(query.").Append(prop).AppendLine("));");
            }

            sb.AppendLine("    const qsText = qs.toString();");
            sb.AppendLine("    if (qsText.length > 0) url += `?${qsText}`;");
        }

        sb.Append("    return this.send<").Append(responseType).Append(">('")
            .Append(endpoint.HttpMethod?.ToUpperInvariant() ?? "GET").Append("', url")
            .Append(hasBody ? ", body" : "").AppendLine(");");
        sb.AppendLine("  }");
    }

    private static string TsType(string? clrType, ManifestJson.ManifestDoc module)
    {
        if (clrType is null) return "unknown";

        var type = clrType.Replace("global::", "");

        // Generic wrappers
        var open = type.IndexOf('<');
        if (open >= 0 && type.EndsWith(">", StringComparison.Ordinal))
        {
            var outer = Simple(type[..open]);
            var inner = type[(open + 1)..^1];
            if (inner.Contains(',')) return "unknown";
            return outer switch
            {
                "PagedResult" => $"PagedResult<{TsType(inner, module)}>",
                "List" or "IList" or "IReadOnlyList" or "ICollection" or "IReadOnlyCollection" or "IEnumerable"
                    => $"{TsType(inner, module)}[]",
                _ => "unknown"
            };
        }

        if (type.EndsWith("[]", StringComparison.Ordinal))
            return $"{TsType(type[..^2], module)}[]";

        var simple = Simple(type).TrimEnd('?');
        var known = simple switch
        {
            "String" or "string" or "Guid" or "DateOnly" or "TimeOnly" or "DateTime" or "DateTimeOffset" or "TimeSpan"
                => "string",
            "Int32" or "int" or "Int64" or "long" or "Int16" or "short" or "Byte" or "byte"
                or "Decimal" or "decimal" or "Double" or "double" or "Single" or "float"
                => "number",
            "Boolean" or "bool" => "boolean",
            _ => null
        };
        if (known is not null) return known;

        // Domain types resolved through the manifest type table (namespaced via the types import)
        var declared = (module.Types ?? []).FirstOrDefault(t => t.SimpleName == simple);
        return declared is not null ? $"T.{simple}" : "unknown";
    }

    private static string Simple(string type)
    {
        var lastDot = type.LastIndexOf('.');
        return lastDot >= 0 ? type[(lastDot + 1)..] : type;
    }

    private static string CamelCase(string name)
        => string.IsNullOrEmpty(name) ? name : char.ToLowerInvariant(name[0]) + name[1..];
}
