namespace Pragmatic.Serialization;

/// <summary>
///     Compile-time map of the members a type declared must not be logged, generated by the source
///     generator — one implementation per module assembly, resolved as an enumerable.
/// </summary>
/// <remarks>
///     <para>
///         It exists so that a component writing a value into a log line or an audit payload can
///         redact the declared members without reflection.
///     </para>
///     <para>
///         <b>This is the extension point.</b> Implementations are resolved as
///         <c>IEnumerable&lt;IRedactionMap&gt;</c> and the generator registers its own with
///         <c>TryAddEnumerable</c>, which de-duplicates by implementation type — so an application
///         that registers a map of its own <i>composes</i> with the generated ones rather than
///         replacing them:
///     </para>
///     <code>
///     services.AddSingleton&lt;IRedactionMap, MyOwnRedactionMap&gt;();
///     </code>
///     <para>
///         That is also how a future attribute joins: contribute a map, and every consumer of the
///         channel honours it with no further change. Nothing here knows which attribute a member
///         came from except <see cref="RedactedMember.Reason" />, which travels with it.
///     </para>
/// </remarks>
public interface IRedactionMap
{
    /// <summary>
    ///     The members <paramref name="type" /> declared must not be logged, with the declaration
    ///     each came from.
    /// </summary>
    /// <param name="type">The type about to be written out.</param>
    /// <param name="members">The members to redact; empty when this map does not know the type.</param>
    /// <returns><see langword="true" /> when this map knows the type and it has declared members.</returns>
    bool TryGetRedactedMembers(Type type, out IReadOnlyList<RedactedMember> members);

    /// <summary>
    ///     The JSON metadata for the types this map knows, or <see langword="null" /> when it has none.
    /// </summary>
    /// <remarks>
    ///     The redactor serializes a value before masking it. Without metadata it can only reflect,
    ///     which Native AOT refuses. The generated map returns the assembly's generated JSON context
    ///     when the assembly emits one (<c>PublishAot</c> or <c>PragmaticGenerateJsonContext</c>), and
    ///     that context covers every type in the map.
    /// </remarks>
    System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver? TypeInfoResolver => null;
}
