<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ExcludeSharedTesting>true</ExcludeSharedTesting>
    <NoWarn>$(NoWarn);CA2007</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Pragmatic.Documents.Csv\Pragmatic.Documents.Csv.csproj" />
  </ItemGroup>

</Project>
