<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <ExcludeSharedTesting>true</ExcludeSharedTesting>
    <!-- CA2007 conflicts with xUnit1030 in test projects -->
    <NoWarn>$(NoWarn);CA2007</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Pragmatic.Discovery\Pragmatic.Discovery.csproj" />
  </ItemGroup>

</Project>
