using Pragmatic.Composition.Abstractions;
using Pragmatic.Configuration.Extensions;
using Pragmatic.Documents.Markup;
using Pragmatic.Persistence.Lifecycle;
using Pragmatic.Persistence.Query.Filters;
using Pragmatic.Persistence.Scopes;
using Pragmatic.Internationalization.AspNetCore.Endpoints;
using Pragmatic.Result.AspNetCore.OpenApi;
using Pragmatic.Endpoints.OpenApi;
using Showcase.Billing.Entities;
using Showcase.Catalog;
using Showcase.Host.AgentDemo;
using Showcase.Host.Configuration;
using Showcase.Host.FeatureFlags;
using Showcase.Host.Pipeline;

namespace Showcase.Host;

/// <summary>
/// Configures app-specific business services and HTTP pipeline for the Showcase app.
/// Infrastructure module strategies (auth, multi-tenancy, logging, storage) are configured
/// in Program.cs via IPragmaticBuilder. Infrastructure defaults (resilience, caching, i18n,
/// identity, feature flags, discovery, clock) are auto-registered by the SG.
/// </summary>
[StartupStep]
[RequiresConfig("ConnectionStrings:App")]
public class ShowcaseStartupStep : IStartupStep
{
    public int Order => 60; // After RoutingStep(50) — UseAuthorization must come after UseRouting

    public void ConfigureServices(
        IServiceCollection services,
        IConfiguration configuration,
        IHostEnvironment environment)
    {
        // [Configuration] binding and validation are registered by the generated host, from the catalogue
        // (AddGeneratedConfiguration). Calling AddShowcaseConfiguration here as well would register every
        // section twice.

        // Runtime configuration — dynamic stores with multi-tenant cascade resolution
        services.AddPragmaticConfiguration(options =>
        {
            options.MultiTenant.Enabled = true;
            options.MultiTenant.FallbackToBase = true;
        });
        services.AddHostedService<ShowcaseConfigurationSeeder>();

        // Query filters and lookup caches are registered by the generated host, from the Persistence
        // metadata, not by calling AddShowcaseQueryFilters() and AddShowcaseLookupCaches() here: that
        // hand-wiring would hide from the suite whether any other application gets row-level filters,
        // an ILookupCache, or a lookup preload at all.

        // Cascade handlers — [CascadeOn] generated domain-event handlers (e.g. RoomType.BaseRate → LineItem.UnitPrice)
        Showcase.Billing.Entities.ShowcaseCascadeHandlerRegistrationExtensions.AddShowcaseCascadeHandlers(services);

        // Row-level security — generated by [HasOwner] on Reservation: Reservation.OwnershipFilter,
        // registered by the generated query-filter registration with the other filters

        // Data ownership scope resolver ([HasAccessScopes]) is auto-registered by UseAuthorization()

        // Billing data scope rules — EUR/USD currency-based scope materialization.
        // ⚠️ IScopeMaterializer is NOT registered here, on purpose: the generated query-filter
        // registration registers it, and the step that runs it, for every [HasAccessScopes] entity.
        // Registering it by hand as well would mean these tests pass whether or not the generated
        // wiring does its job, so a materializer that is registered and never invoked would go unseen.
        services.AddDataScopeRule<Showcase.Billing.Infrastructure.Scopes.EurInvoiceScopeRule, Invoice>();
        services.AddDataScopeRule<Showcase.Billing.Infrastructure.Scopes.UsdInvoiceScopeRule, Invoice>();

        // Billing services — registered via [Service] in Showcase.Billing module
        // Note: IDefaultValueGenerator<Invoice, string> is auto-registered by SG host aggregation

        // Saga DI is auto-wired: PragmaticSagaRegistration.AddPragmaticSagas() is invoked by
        // the SG-generated host via MetadataCategory.Sagas aggregation, which also registers the
        // SG-generated IMessageHandler<TEvent> bridges so events dispatched through IMessageBus
        // advance the saga orchestrator automatically.

        // Feature Flags — app-specific context provider and seeder
        services.AddScoped<IFeatureFlagContextProvider, ShowcaseFeatureFlagContextProvider>();
        services.AddHostedService<ShowcaseFeatureFlagSeeder>();

        // Pre/Post processors
        services.AddScoped<IEndpointPreProcessor, TenantValidationPreProcessor>();
        services.AddScoped<IEndpointPostProcessor, AuditLogPostProcessor>();

        // OpenAPI — typed error responses + manifest enrichment (permissions, errors from compile-time manifest)
        services.AddOpenApi(options => options.AddResultTypeSupport());
        services.AddPragmaticOpenApi();
    }

    public void ConfigurePipeline(IApplicationBuilder app)
    {
        // Identity from headers (development/test) — an application choice, not framework wiring.
        // Runs before AuthenticationStep (91), which this step (60) precedes.
        app.UseMiddleware<Pragmatic.Identity.HeaderUserMiddleware>();

        // Tenant resolution, authentication and authorization are not added here by hand: they are
        // shipped — TenantResolutionStep (92) and AuthenticationStep (91) — and adding them here would
        // hide from the suite whether they are missing for everyone else.
        // I18n and Routing come from [NeedsStep<T>] on ShowcaseHostModule.

        if (app is WebApplication webApp)
        {
            // The compile-time document (/openapi/v1.json) and Scalar over it are published by the
            // generated host; Program.cs publishes the document outside Development too.

            // Dev-only: runtime OpenAPI comparison, config diagnostics
            if (webApp.Environment.IsDevelopment())
            {
                webApp.MapOpenApi("/openapi/runtime.json");
                webApp.MapConfigurationDiagnostics();
            }

            // Translation endpoint — frontend can load translations via GET /api/i18n/{culture}
            webApp.MapPragmaticTranslations();

            // Agent demo endpoints — config push, feature flags, tenants, health, secrets
            webApp.MapAgentDemoEndpoints();
        }
    }
}
