/**
 * What each line of a C# file is — code, comment, preprocessor directive or blank — and how much of a
 * generated file is its header.
 *
 * A lexer, not a pattern on the trimmed line: `var url = "https://…";` is code although it contains
 * `//`, a line inside a `/* … *\/` block is a comment although it starts with a letter, and a line of a
 * verbatim or raw string is code whatever it holds. Only the states that change what a line is are
 * tracked; anything else — identifiers, operators, a string's contents — is simply "code".
 *
 * ⚠️ One approximation, kept on purpose: an interpolation hole that itself contains a string
 * (`$"{(a ? "x" : "y")}"`) ends the outer string early. The line is code either way, and a regular or
 * interpolated string cannot span lines, so the error never leaks into the next line's kind.
 */

/**
 * The kind of every line: `code`, `comment`, `directive` or `blank`.
 * A line with code and a trailing comment is `code`; a line inside a multi-line string is `code`.
 */
export function classifyLines(text) {
  const lines = splitLines(text);
  const kinds = [];
  let block = false; // inside /* … */
  let verbatim = false; // inside @"…" spanning lines
  let raw = 0; // inside a raw string literal spanning lines: the length of its closing quote run

  for (const line of lines) {
    // A line that opens inside a multi-line string is part of a literal, even when it is empty.
    let code = verbatim || raw > 0;
    let comment = block;
    let directive = false;
    let i = 0;

    while (i < line.length) {
      if (block) {
        const end = line.indexOf('*/', i);
        comment = true;
        if (end === -1) { i = line.length; break; }
        block = false;
        i = end + 2;
        continue;
      }
      if (verbatim) {
        code = true;
        const end = closeVerbatim(line, i);
        if (end === -1) { i = line.length; break; }
        verbatim = false;
        i = end;
        continue;
      }
      if (raw) {
        code = true;
        const end = line.indexOf('"'.repeat(raw), i);
        if (end === -1) { i = line.length; break; }
        i = end + raw;
        raw = 0;
        continue;
      }

      const c = line[i];
      if (c === ' ' || c === '\t') { i++; continue; }
      if (c === '#' && !code && line.slice(0, i).trim() === '') { directive = true; break; }
      if (c === '/' && line[i + 1] === '/') { comment = true; break; }
      if (c === '/' && line[i + 1] === '*') { block = true; comment = true; i += 2; continue; }

      code = true;
      const literal = stringAt(line, i);
      if (literal === null) {
        i += c === "'" ? charLiteralLength(line, i) : 1;
        continue;
      }
      if (literal.kind === 'raw') {
        const quotes = literal.quotes;
        const opened = literal.contentStart;
        const end = line.indexOf('"'.repeat(quotes), opened);
        if (end === -1) { raw = quotes; i = line.length; break; }
        i = end + quotes;
      } else if (literal.kind === 'verbatim') {
        const end = closeVerbatim(line, literal.contentStart);
        if (end === -1) { verbatim = true; i = line.length; break; }
        i = end;
      } else {
        i = closeRegular(line, literal.contentStart);
      }
    }

    kinds.push(directive ? 'directive' : code ? 'code' : comment ? 'comment' : 'blank');
  }

  return { lines, kinds };
}

/**
 * How many lines open the file as its header: blank lines, preprocessor directives, and `//` comments
 * that are not XML documentation. That is the block `CSharpTemplate.RenderHeader` writes — from
 * `// <auto-generated/>` to `#nullable enable` — and the one other generators write the same way. A
 * `///` line stops it: it documents the declaration below, it is not the file's banner.
 */
export function headerLength({ lines, kinds }) {
  let n = 0;
  while (n < lines.length) {
    const kind = kinds[n];
    const isBanner = kind === 'comment' && lines[n].trim().startsWith('//') && !lines[n].trim().startsWith('///');
    if (kind !== 'blank' && kind !== 'directive' && !isBanner) break;
    n++;
  }
  return n;
}

/**
 * Counts for one file. With `{ header: true }` the header is left out of every count and reported on
 * its own. Characters exclude line breaks, so a file checked out with CRLF counts as it does with LF.
 */
export function measureSource(text, { header = false } = {}) {
  const classified = classifyLines(text);
  const skip = header ? headerLength(classified) : 0;
  const m = { files: 1, lines: 0, code: 0, comment: 0, directive: 0, blank: 0, chars: 0, headerLines: 0, headerChars: 0 };

  classified.lines.forEach((line, n) => {
    if (n < skip) {
      m.headerLines++;
      m.headerChars += line.length;
      return;
    }
    m.lines++;
    m.chars += line.length;
    m[classified.kinds[n]]++;
  });

  return m;
}

/** Adds the counts of `b` into `a`, and returns `a`. */
export function addMeasures(a, b) {
  for (const key of Object.keys(b)) a[key] = (a[key] ?? 0) + b[key];
  return a;
}

export const emptyMeasure = () =>
  ({ files: 0, lines: 0, code: 0, comment: 0, directive: 0, blank: 0, chars: 0, headerLines: 0, headerChars: 0 });

function splitLines(text) {
  const lines = text.replace(/^﻿/, '').split(/\r\n|\n|\r/);
  if (lines.length > 0 && lines.at(-1) === '') lines.pop();
  return lines;
}

/**
 * The string literal opening at `i`, or null. Prefixes are `$` (any number, for raw interpolation) and
 * `@`, in either order; three or more quotes make it raw.
 */
function stringAt(line, i) {
  let j = i;
  let at = false;
  while (line[j] === '$' || line[j] === '@') {
    if (line[j] === '@') at = true;
    j++;
  }
  if (line[j] !== '"') return null;

  let quotes = 0;
  while (line[j + quotes] === '"') quotes++;
  if (quotes >= 3) return { kind: 'raw', quotes, contentStart: j + quotes };
  // One quote opens the literal; two are an empty one, which the closing scan finds at once.
  return { kind: at ? 'verbatim' : 'regular', contentStart: j + 1 };
}

/** The index just past the closing quote of a verbatim string, or -1 when it continues on the next line. */
function closeVerbatim(line, i) {
  for (let j = i; j < line.length; j++) {
    if (line[j] !== '"') continue;
    if (line[j + 1] === '"') { j++; continue; }
    return j + 1;
  }
  return -1;
}

/** The index just past the closing quote of a regular string (or the end of the line). */
function closeRegular(line, i) {
  for (let j = i; j < line.length; j++) {
    if (line[j] === '\\') { j++; continue; }
    if (line[j] === '"') return j + 1;
  }
  return line.length;
}

function charLiteralLength(line, i) {
  for (let j = i + 1; j < line.length; j++) {
    if (line[j] === '\\') { j++; continue; }
    if (line[j] === "'") return j + 1 - i;
  }
  return line.length - i;
}
