using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Pragmatic.Messaging;
using Pragmatic.Testing.Assertions;
using Warehouse.IntegrationTests.Infrastructure;
using Warehouse.Orders.Contracts.Events;

namespace Warehouse.IntegrationTests;

/// <summary>
///     An application's own <c>[LoggerMessage]</c> is generated by Pragmatic: the entry a running host writes
///     carries the call site's UTF-8 state, not the state Microsoft's generator builds.
/// </summary>
/// <remarks>
///     Proved where it ends up, in a running Stock host: its cancellation handler logs a repeat, and the
///     entry is read off the host's own logger factory. A project the alias does not reach compiles the same
///     source with Microsoft's generator, and this is where that difference shows.
/// </remarks>
[Collection(WarehouseCollection.Name)]
public sealed class AHandlerLogsThroughAGeneratedCallSite(WarehouseFixture warehouse)
{
    [Fact]
    public async Task ACancellationDeliveredTwice_IsLoggedThroughThePragmaticCallSite()
    {
        var order = Guid.NewGuid();
        var recorder = new LogStateRecorder(order.ToString());
        warehouse.StockA.Services.GetRequiredService<ILoggerFactory>().AddProvider(recorder);

        // No such order holds anything: the first delivery records the restoration, the second finds it
        // there and logs that nothing was written.
        for (var delivery = 0; delivery < 2; delivery++)
        {
            using var scope = warehouse.StockA.Services.CreateScope();
            await scope.ServiceProvider.GetRequiredService<IMessageHandler<OrderCancelled>>()
                .HandleAsync(new OrderCancelled(order, DateTimeOffset.UtcNow), MessageContext.New());
        }

        var entry = recorder.Entries.Should().ContainSingle(
            e => e.Message.Contains("was already restored", StringComparison.Ordinal),
            "the second delivery is a repeat, and the handler logs it").Subject;
        entry.FromGeneratedCallSite.Should().BeTrue(
            $"the handler's [LoggerMessage] is generated by Pragmatic in this host (entry: {entry})");
    }
}
