using System.Diagnostics;
using Microsoft.Extensions.DependencyInjection;
using Pragmatic.Actions.Abstractions;
using Pragmatic.Actions.Compensation;
using Pragmatic.Actions.Diagnostics;
using Pragmatic.Actions.Pipeline;
using Pragmatic.Pipeline;
using Pragmatic.Result;
using static Pragmatic.Ensure.Ensure;
using Pragmatic.Telemetry.Conventions;

namespace Pragmatic.Actions.Invoker;

/// <summary>
///     Abstract base class for DomainAction invokers.
///     Handles filter execution, logging, and telemetry.
/// </summary>
/// <typeparam name="TAction">The action type.</typeparam>
/// <typeparam name="TReturn">The return type.</typeparam>
/// <remarks>
///     <para>
///         Derived classes are generated by the source generator. They provide:
///     </para>
///     <list type="bullet">
///         <item>Constructor injection of action dependencies</item>
///         <item>Implementation of <see cref="InjectDependencies" /></item>
///     </list>
///     <para>
///         The pipeline execution order is:
///     </para>
///     <list type="number">
///         <item>BeforeExecute filters (in order)</item>
///         <item>Action.Execute()</item>
///         <item>AfterExecute filters (reverse order)</item>
///     </list>
///     <para>
///         <b>Architecture note:</b> this class and <see cref="VoidDomainActionInvoker{TAction}" /> share
///         a similar pipeline structure. The duplication is intentional: the return types differ fundamentally
///         (<c>Result&lt;TReturn, IError&gt;</c> vs <c>VoidResult&lt;IError&gt;</c>), the filter adapters
///         have different type constraints, and extracting a generic base would add complexity without
///         reducing the maintenance surface. Shared infrastructure lives in <see cref="ActionInvokerBase" />.
///     </para>
/// </remarks>
public abstract partial class DomainActionInvoker<TAction, TReturn> : ActionInvokerBase, IDomainActionInvoker<TAction, TReturn>
    where TAction : DomainAction<TReturn>
{
    private readonly IEnumerable<IActionFilter<TAction>> _actionFilters;
    private readonly IEnumerable<IActionFilter<TAction, TReturn>> _typedFilters;

    /// <summary>
    ///     Creates a new invoker instance.
    /// </summary>
    /// <param name="serviceProvider">The service provider for resolving filters.</param>
    protected DomainActionInvoker(IServiceProvider serviceProvider)
        : base(serviceProvider, typeof(DomainActionInvoker<TAction, TReturn>))
    {
        _actionFilters = serviceProvider.GetService<IEnumerable<IActionFilter<TAction>>>() ?? [];
        _typedFilters = serviceProvider.GetService<IEnumerable<IActionFilter<TAction, TReturn>>>() ?? [];
    }

    // Cached at JIT time per TAction closed generic; avoids two reflection-style
    // Type.Name / Type.FullName lookups on every invocation.
    private static readonly string SActionName = typeof(TAction).Name;
    private static readonly string SActionFullName = typeof(TAction).FullName!;

    /// <inheritdoc />
    /// <remarks>
    ///     <para>
    ///         <c>[Transactional]</c> runs the whole invocation inside the unit of work's execution strategy,
    ///         because a strategy that retries refuses a transaction opened outside it. On a transient failure
    ///         before the commit <b>the invocation runs again</b> — filters, loading, the body, the save — from
    ///         a cleared change tracker. The body must therefore have no effect outside its transaction: mail,
    ///         messages and events go through the outbox, which is transactional; a direct HTTP call or file
    ///         write runs again, and so does a call into another boundary, which commits on its own. What runs
    ///         after the commit — events, cache invalidation, the after-filters — runs once.
    ///     </para>
    ///     <para>
    ///         Without <c>[Transactional]</c> there is no unit to re-run: each query and the closing save are
    ///         retried by EF on their own.
    ///     </para>
    /// </remarks>
    public Task<Result<TReturn, IError>> InvokeAsync(TAction action, CancellationToken ct = default)
    {
        ThrowIfNull(action);

        return IsTransactional && UnitOfWork is { } unitOfWork
            ? unitOfWork.ExecuteAsync(token => InvokeOnceAsync(action, token), ct)
            : InvokeOnceAsync(action, ct);
    }

    private async Task<Result<TReturn, IError>> InvokeOnceAsync(TAction action, CancellationToken ct)
    {
        var actionName = SActionName;

        using var activity = ActionsDiagnostics.ActivitySource.StartActivity($"Action.{actionName}");
        ConfigureActivity(activity, SActionFullName, "action");

        // See MutationInvoker: the activity is null with no listener, and the audit trail cannot depend
        // on tracing being switched on.
        using var operation = OperationScope.Enter(SActionFullName);

        ActionsDiagnostics.ActionInvocations.Add(1,
            new KeyValuePair<string, object?>("action.name", actionName));

        LogStart("Action", actionName);
        var stopwatch = Stopwatch.StartNew();

        // Taken before anything runs, so this invocation compensates only what it caused: an inner
        // boundary that committed before this action started belongs to whoever called it.
        var compensationMark = Compensation.Mark();

        // [Transactional]: one transaction around the whole body, opened before anything runs so every
        // nested save lands inside it.
        global::Pragmatic.Persistence.Repository.ITransaction? transaction = null;
        if (IsTransactional && UnitOfWork is not null)
            transaction = await UnitOfWork.BeginTransactionAsync(ct).ConfigureAwait(false);

        // Who commits, decided by unit of work identity rather than by reading the call graph.
        //
        // Nothing is claimed for a composite. CommitsItsOwnWork says its CompositeInvoker owns the unit
        // of work, and claiming here first would make that one look nested — its claim would find this
        // entry, return without a batch, and the semantics it asked for (steps that save as they go,
        // under [Transactional]) would never reach one. The symptom was a composite whose second step
        // could not see what the first wrote, with every generated line correct.
        using var commitOwnership = CommitsItsOwnWork
            ? default
            : global::Pragmatic.Actions.Commit.CommitScope.Claim(UnitOfWork, CommitMode, IsTransactional);

        try
        {
            // Inject dependencies
            InjectDependencies(action);

            // Get all applicable filters, ordered
            var filters = GetOrderedFilters();

            ConfigureActivity(activity, typeof(TAction).FullName!, "action", filters.Count);
            LogFilters("Action", actionName, filters.Count);

            // 1. Execute BeforeExecute filters (in order)
            foreach (var filter in filters)
            {
                var filterName = filter.GetType().Name;
                LogBeforeFilter("Action", actionName, filterName);

                var beforeResult = await filter.BeforeExecuteAsync<TAction, TReturn>(action, ct).ConfigureAwait(false);

                if (beforeResult.IsFailure)
                {
                    LogShortCircuit("Action", actionName, filterName, beforeResult.Error.Code);
                    SetActivityShortCircuit(activity, beforeResult.Error.Code);

                    ActionsDiagnostics.FilterShortCircuits.Add(1,
                        new KeyValuePair<string, object?>("action.name", actionName),
                        new KeyValuePair<string, object?>("filter.name", filterName));

                    return Result<TReturn, IError>.Failure(beforeResult.Error);
                }
            }

            // The ambient scopes that must outlive the body — the delegation. Here and not inside
            // ExecuteActionAsync because the save below is what attributes the row, and
            // after the filters above because the action's own permission is the caller's.
            using var invocationScope = BeginInvocationScope(action);

            // [Cacheable]: read after the permission filters above, so a cached answer is never handed to
            // a caller who may not have it, and inside the invocation scope, so the key sees the authority
            // the body would run with. A hit skips the loads and the body and ends like any answer.
            var cacheEntry = OpenCacheEntry(action);
            if (cacheEntry is not null)
            {
                var (found, cached) = await cacheEntry.Stack
                    .TryGetAsync<TReturn>(cacheEntry.Key, ct).ConfigureAwait(false);
                if (found)
                {
                    LogServedFromCache("Action", actionName);
                    return await CompleteAsync(action, Result<TReturn, IError>.Success(cached!), filters,
                        activity, stopwatch, ct).ConfigureAwait(false);
                }
            }

            // Prepare action (load [LoadEntity] entities, etc.) — AFTER the authorization filters
            // so an unauthorized caller is denied before any entity load hits the database and
            // cannot probe entity existence via 404-vs-403. Matches the mutation pipeline (authz → load).
            LogPreparingAction("Action", actionName);
            var prepareError = await PrepareActionAsync(action, ct).ConfigureAwait(false);
            if (prepareError is not null)
            {
                LogPreparationFailed("Action", actionName, prepareError.Code);
                return Result<TReturn, IError>.Failure(prepareError);
            }

            // [TransitionsTo] with BeforeBody: after the loads, before the body — which builds the
            // response, so it has to see the state the operation ends in.
            if (TransitionBeforeBody(action) is { } refused)
            {
                LogPreparationFailed("Action", actionName, refused.Code);
                return Result<TReturn, IError>.Failure(refused);
            }

            // 2. Execute the action (virtual dispatch for versioning support)
            LogExecuting("Action", actionName);
            var result = await ExecuteActionAsync(action, ct).ConfigureAwait(false);

            if (result.IsSuccess)
                EnsureTheBodyTransitioned(action);

            // 3. Persist any pending changes if the action succeeded.
            //    SaveChanges runs BEFORE AfterExecute filters so that side effects
            //    (cache invalidation, event dispatch) are only triggered after a
            //    successful commit — preserving atomicity.
            if (result.IsSuccess)
            {
                // The loaded aggregate's rules, after the body and before the write — the same place in
                // the same order the mutation pipeline checks them. An aggregate moved by an action — which is
                // how a state machine is moved — has its rules evaluated here or on no path at all.
                //
                // ⚠️ Only the rules this operation can answer: the generated override leaves out any
                // rule whose body reads a navigation the action did not Include, because evaluating one
                // against an empty collection is a refusal of a legitimate write, not a safeguard.
                if (CheckLoadedInvariants(action) is { } invariantError)
                {
                    LogPreparationFailed("Action", actionName, invariantError.Code);
                    return Result<TReturn, IError>.Failure(invariantError);
                }

                // A composite of mutation steps has already committed them, in one transaction of its
                // own. Committing again here writes nothing — but it is a second round trip per
                // composite, and it makes "one SaveChanges" false where the documentation says it.
                // Saves when it owns the commit — or when it is nested inside an explicit transaction,
                // where the whole point is that a later step can read what this one wrote. Implementing
                // this only for nested mutations left an action step invisible to the next one, and the
                // batch check is what tells the two situations apart.
                var savesHere = commitOwnership.CommitsHere
                    || global::Pragmatic.Actions.Commit.CommitScope.BatchFor(UnitOfWork)
                        is { DefersSave: false };

                if (!CommitsItsOwnWork && savesHere)
                {
                    LogSavingChanges("Action", actionName);
                    await SaveChangesAsync(ct).ConfigureAwait(false);
                }

                // The commit, and only now: everything deferred below is flushed after it, never before.
                if (transaction is not null)
                    await transaction.CommitAsync(ct).ConfigureAwait(false); // commit — a failure here IS a real failure and propagates

                // 3b. Post-commit side effects. The commit already happened, so a failure here must NOT
                //     turn the committed success into a thrown failure — that would make callers retry and
                //     double-run the operation. Log at Error and carry on.
                try
                {
                    // Outside every claim: the commit has happened, so a handler writing through this
                    // unit of work is its own operation. Left inside, it was read as another nested step
                    // and staged writes that nobody would save. See CommitScope.Suspend.
                    using var outsideTheCommit = global::Pragmatic.Actions.Commit.CommitScope.Suspend();

                    await DispatchRaisedEventsAsync(CollectRaisedEvents(action, result.Value), ct).ConfigureAwait(false);

                    // What the nested invocations could not dispatch themselves, now that their writes
                    // are committed. Without it a mutation invoked from here succeeds silently and its
                    // handler never runs. The batch is the one captured before suspending.
                    await global::Pragmatic.Actions.Commit.DeferredEventFlush
                        .FlushAsync(commitOwnership.Batch, ServiceProvider, ct).ConfigureAwait(false);

                    // Last, and only on success: the rows this action wrote are committed, so the
                    // [Cacheable] reads of them are the ones now stale. Before this the generated
                    // ICacheInvalidator existed and nobody called it.
                    await InvalidateCacheAsync(action, "Action", actionName, ct).ConfigureAwait(false);

                    // Kept only now: a success, committed. A failure is this call's answer and never
                    // anyone else's — a transient one would otherwise last the whole duration.
                    if (cacheEntry is not null)
                        await cacheEntry.Stack.SetAsync(cacheEntry.Key, result.Value, cacheEntry.Options, ct)
                            .ConfigureAwait(false);
                }
                catch (Exception postCommitEx)
                {
                    LogPostCommitSideEffectFailed("Action", actionName, postCommitEx);
                    activity?.SetTag(ActionTags.PostCommitFailed, true);
                }

                // 3c. Registered only after the commit: before it there is nothing to undo, and an undo
                //     of work that never landed would be a second defect rather than a repair.
                if (IsCompensable)
                    Compensation.Register(actionName, undoCt => CompensateAsync(result.Value, undoCt));
            }
            else
            {
                // The action failed, so nothing it wrote survives — that is what the transaction was
                // asked for. Rolled back before the compensation runs: a step in another boundary is
                // not covered by it, which is exactly what PRAG0426 refuses to let happen silently.
                if (transaction is not null)
                    await transaction.RollbackAsync(ct).ConfigureAwait(false);

                // The action failed. Whatever committed inside it — another boundary's action, already
                // saved — is undone here, most recent first. Its own writes need nothing: this
                // boundary's SaveChanges never ran.
                var compensationFailure =
                    await Compensation.CompensateFromAsync(compensationMark, ct).ConfigureAwait(false);

                if (compensationFailure is not null)
                {
                    LogCompensationFailed("Action", actionName, compensationFailure.ActionName,
                        compensationFailure.Error.Code);
                    activity?.SetTag(ActionTags.CompensationFailed, true);

                    result = Result<TReturn, IError>.Failure(new CompensationFailedError
                    {
                        OriginalError = result.Error,
                        CompensationError = compensationFailure.Error,
                        UncompensatedAction = compensationFailure.ActionName
                    });
                }
            }

            return await CompleteAsync(action, result, filters, activity, stopwatch, ct).ConfigureAwait(false);
        }
        catch (Exception ex)
        {
            stopwatch.Stop();

            if (transaction is not null)
                await transaction.RollbackAsync(ct).ConfigureAwait(false);

            ActionsDiagnostics.ActionDuration.Record(stopwatch.Elapsed.TotalMilliseconds,
                new KeyValuePair<string, object?>("action.name", actionName),
                new KeyValuePair<string, object?>("action.result", "exception"));

            ActionsDiagnostics.ActionFailures.Add(1,
                new KeyValuePair<string, object?>("action.name", actionName),
                new KeyValuePair<string, object?>("error.code", ex.GetType().Name));

            LogException("Action", actionName, stopwatch.ElapsedMilliseconds, ex);
            SetActivityException(activity, ex);
            throw;
        }
        finally
        {
            if (transaction is not null)
                await transaction.DisposeAsync().ConfigureAwait(false);
        }
    }

    /// <summary>
    ///     Executes the action. Override in generated invokers to support
    ///     versioned dispatch (ExecuteV2, ExecuteV3, etc.).
    /// </summary>
    /// <param name="action">The action to execute.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>The action result.</returns>
    protected virtual Task<Result<TReturn, IError>> ExecuteActionAsync(TAction action, CancellationToken ct)
        => action.Execute(ct);

    /// <summary>
    ///     Opens an ambient scope that has to outlive the body — the delegation
    ///     <c>[StartsDelegation]</c> declares. Disposed after the save, the commit and the post-commit
    ///     side effects.
    /// </summary>
    /// <remarks>
    ///     <para>
    ///         ⚠️ <b>Not <c>ExecuteActionAsync</c>.</b> The row is attributed at <c>SaveChanges</c>,
    ///         which this pipeline runs <em>after</em> the body returns. A scope opened there would have
    ///         disposed by then, <c>OwnershipInterceptor</c> and <c>AuditingInterceptor</c> would read the
    ///         caller, and a guest registered on behalf of someone would come back owned by the front desk.
    ///     </para>
    ///     <para>
    ///         Opened after the BeforeExecute filters, deliberately: the action's own
    ///         <c>[RequirePermission]</c> is a question about the <b>caller</b>, and who may open a
    ///         delegation is not the same question as what may be done inside one. Everything from the
    ///         <c>[LoadEntity]</c> loads onward is inside, so the row filters that pick what the body
    ///         works on already see the composed authority.
    ///     </para>
    /// </remarks>
    /// <param name="action">The action being invoked; the subject is read off it.</param>
    /// <returns>The scope to hold for the rest of the invocation, or <c>null</c> when there is none.</returns>
    protected virtual IDisposable? BeginInvocationScope(TAction action) => null;

    /// <summary>
    ///     Whether the action commits its own work, so this pipeline must not commit again.
    /// </summary>
    /// <remarks>
    ///     True for a <c>[CompositeAction]</c> of mutation steps: its generated invoker runs the steps
    ///     with the commit suppressed and then performs the single transaction itself. The commit here
    ///     would find nothing pending — it is a wasted round trip, and it contradicts the one guarantee
    ///     the composite makes.
    /// </remarks>
    protected virtual bool CommitsItsOwnWork => false;

    /// <summary>
    ///     Whether this action declared <c>[Transactional]</c>. Overridden by the generated invoker.
    /// </summary>
    protected virtual bool IsTransactional => false;

    /// <summary>
    ///     The unit of work this invoker commits through, or <c>null</c> when the action has no boundary.
    ///     Overridden by the generated invoker; it is the identity <c>CommitScope</c> keys ownership on.
    /// </summary>
    protected virtual global::Pragmatic.Persistence.Repository.IUnitOfWork? UnitOfWork => null;

    /// <summary>
    ///     The strategy declared by <c>[CommitStrategy]</c>. Overridden by the generated invoker.
    /// </summary>
    protected virtual global::Pragmatic.Actions.Commit.CommitMode CommitMode
        => global::Pragmatic.Actions.Commit.CommitMode.Once;

    /// <summary>
    ///     Whether this action declared <c>[UndoWith&lt;T&gt;]</c>. Overridden by the generated invoker.
    /// </summary>
    protected virtual bool IsCompensable => false;

    /// <summary>
    ///     Runs the declared compensator and commits it through this invoker's unit of work, so the undo
    ///     lands in the boundary that owns the data. Overridden by the generated invoker; the default
    ///     succeeds without doing anything, which is correct for an action that declared no compensator.
    /// </summary>
    /// <param name="committed">What this action returned when it succeeded.</param>
    /// <param name="ct">Cancellation token.</param>
    protected virtual Task<VoidResult<IError>> CompensateAsync(TReturn committed, CancellationToken ct)
        => Task.FromResult(VoidResult<IError>.Success());

    /// <summary>
    ///     The domain events this action declared via <c>[Raises&lt;T&gt;]</c>, built from the action's inputs.
    ///     Overridden by the generated invoker; the default raises nothing.
    /// </summary>
    protected virtual IReadOnlyList<Pragmatic.Events.IDomainEvent> CollectRaisedEvents(TAction action, TReturn result)
        => [];

    /// <summary>
    ///     Checks the <c>[Invariant]</c> rules of the entities this operation loaded, and returns the
    ///     first violation. Overridden by the generated invoker; null means there is nothing to check.
    /// </summary>
    /// <remarks>
    ///     The override calls only the rules the operation <b>can answer</b> — those whose body reads no
    ///     navigation outside its <c>Include</c> list. A rule over a navigation nobody loaded would read
    ///     an empty collection and refuse a write that is correct, which is a worse failure than the one
    ///     the rule exists to catch.
    /// </remarks>
    /// <param name="action">The operation, holding the entities its preload assigned.</param>
    protected virtual IError? CheckLoadedInvariants(TAction action) => null;

    /// <summary>
    ///     Injects dependencies into the action instance.
    ///     Implemented by generated derived classes.
    /// </summary>
    /// <param name="action">The action to inject dependencies into.</param>
    protected abstract void InjectDependencies(TAction action);

    /// <summary>
    ///     Prepares the action before filter and execution phases.
    ///     Override to load entities, validate preconditions, etc.
    /// </summary>
    /// <param name="action">The action to prepare.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>An error if preparation failed, null if successful.</returns>
    protected virtual Task<IError?> PrepareActionAsync(TAction action, CancellationToken ct)
        => Task.FromResult<IError?>(null);

    /// <summary>
    ///     Persists any pending changes after successful action execution.
    ///     Overridden by generated invokers that have a boundary-keyed IUnitOfWork.
    /// </summary>
    protected virtual Task SaveChangesAsync(CancellationToken ct) => Task.CompletedTask;

    private List<IActionFilter> GetOrderedFilters()
    {
        var result = GetSortedGlobalFilters();

        // Add single-type-param action filters (adapted to IActionFilter)
        foreach (var actionFilter in _actionFilters)
            result.Add(new ActionFilterAdapter(actionFilter));

        // Add typed filters with return type (adapted to IActionFilter)
        foreach (var typedFilter in _typedFilters)
            result.Add(new TypedFilterAdapter(typedFilter));

        // Re-sort after adding typed filters
        result.Sort((a, b) => a.Order.CompareTo(b.Order));

        return result;
    }

    // =========================================================================
    // Filter Adapters
    // =========================================================================

    /// <summary>
    ///     Adapts <see cref="IActionFilter{TAction}" /> (single param) to <see cref="IActionFilter" />.
    /// </summary>
    private sealed class ActionFilterAdapter(IActionFilter<TAction> inner) : IActionFilter
    {
        public int Order => inner.Order;

        public Task<VoidResult<IError>> BeforeExecuteAsync<TActionInner, TReturnInner>(
            TActionInner action,
            CancellationToken ct)
            where TActionInner : DomainAction<TReturnInner>
        {
            if (action is TAction typedAction)
                return inner.BeforeExecuteAsync(typedAction, ct);
            return Task.FromResult(VoidResult<IError>.Success());
        }

        public Task AfterExecuteAsync<TActionInner, TReturnInner>(
            TActionInner action,
            Result<TReturnInner, IError> result,
            CancellationToken ct)
            where TActionInner : DomainAction<TReturnInner>
        {
            if (action is TAction typedAction)
                return inner.AfterExecuteAsync(typedAction, ct);
            return Task.CompletedTask;
        }
    }

    /// <summary>
    ///     Adapts <see cref="IActionFilter{TAction, TReturn}" /> (two params) to <see cref="IActionFilter" />.
    /// </summary>
    private sealed class TypedFilterAdapter(IActionFilter<TAction, TReturn> inner) : IActionFilter
    {
        public int Order => inner.Order;

        public Task<VoidResult<IError>> BeforeExecuteAsync<TActionInner, TReturnInner>(
            TActionInner action,
            CancellationToken ct)
            where TActionInner : DomainAction<TReturnInner>
        {
            if (action is TAction typedAction)
                return inner.BeforeExecuteAsync(typedAction, ct);
            return Task.FromResult(VoidResult<IError>.Success());
        }

        public Task AfterExecuteAsync<TActionInner, TReturnInner>(
            TActionInner action,
            Result<TReturnInner, IError> result,
            CancellationToken ct)
            where TActionInner : DomainAction<TReturnInner>
        {
            if (action is TAction typedAction && result is Result<TReturn, IError> typedResult)
                return inner.AfterExecuteAsync(typedAction, typedResult, ct);
            return Task.CompletedTask;
        }
    }
}
