using System.Diagnostics;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;
using Pragmatic.Actions.Diagnostics;
using Pragmatic.Identity;
using Pragmatic.Actions.Mutation;
using Pragmatic.Actions.Pipeline;
using Pragmatic.Persistence.Entity;
using Pragmatic.Pipeline;
using Pragmatic.Result;
using Pragmatic.Telemetry;
using Pragmatic.Telemetry.Conventions;
using Pragmatic.Validation;
using static Pragmatic.Ensure.Ensure;

namespace Pragmatic.Actions.Invoker;

/// <summary>
///     Abstract base class for mutation invokers.
///     Handles the full pipeline: validate → load/create → apply → entity validate → persist → events.
/// </summary>
/// <typeparam name="TMutation">The mutation type.</typeparam>
/// <typeparam name="TEntity">The entity type being modified.</typeparam>
/// <remarks>
///     <para>
///         Derived classes are generated by the source generator. They provide:
///     </para>
///     <list type="bullet">
///         <item>Constructor injection of mutation dependencies</item>
///         <item>Implementation of abstract methods for entity loading, creation, and persistence</item>
///     </list>
///     <para>
///         The pipeline execution order is:
///     </para>
///     <list type="number">
///         <item>Inject dependencies into mutation</item>
///         <item>Level 1 sync validation (ISyncValidator on mutation)</item>
///         <item>Level 1 async validation (IAsyncValidator on mutation)</item>
///         <item>Load existing entity (Update) or create new (Create)</item>
///         <item>ApplyAsync (manual) or ApplyToEntity (auto-mapped)</item>
///         <item>Level 2 unified entity validation via IValidator&lt;TEntity&gt; (sync + async, change-aware)</item>
///         <item>Persist (Add if new, SaveChanges)</item>
///         <item>Dispatch domain events</item>
///     </list>
///     <para>
///         Pipeline stages (Delete, Restore, CreateUpdate) are in <c>MutationInvoker.Pipeline.cs</c>.
///     </para>
/// </remarks>
public abstract partial class MutationInvoker<TMutation, TEntity> : IMutationInvoker<TMutation, TEntity>
    where TMutation : Mutation<TEntity>
    where TEntity : class
{
    /// <summary>
    ///     Service provider for resolving services in derived classes.
    /// </summary>
    protected readonly IServiceProvider _serviceProvider;

    // Named _logger so [LoggerMessage] source generator can locate it automatically
    protected readonly ILogger _logger;

    // Typed filters resolved and sorted once per invoker instance to avoid per-invocation allocation.
    private readonly IActionFilter<TMutation>[] _sortedTypedFilters;

    /// <summary>
    ///     Creates a new mutation invoker instance.
    /// </summary>
    /// <param name="serviceProvider">The service provider for resolving services.</param>
    protected MutationInvoker(IServiceProvider serviceProvider)
    {
        _serviceProvider = serviceProvider;
        var loggerFactory = serviceProvider.GetService<ILoggerFactory>();
        _logger = loggerFactory?.CreateLogger(GetType()) ?? NullLogger.Instance;

        // Resolve and sort typed filters once — they are scoped to this DI scope.
        var typedFilters = serviceProvider.GetServices<IActionFilter<TMutation>>();
        _sortedTypedFilters = [.. typedFilters.OrderBy(f => f.Order)];

        Compensation = new Compensation.CompensationCoordinator(serviceProvider);
    }

    /// <summary>Resolves the request's compensation scope and holds the undos this invoker registers.</summary>
    protected readonly Compensation.CompensationCoordinator Compensation;

    /// <inheritdoc />
    /// <remarks>
    ///     Wraps the pipeline rather than threading the compensation through it: the core method exits
    ///     from three mode-specific branches, and a mark opened in one of them would be a fourth place
    ///     to keep in step with the other three.
    /// </remarks>
    public Task<Result<TEntity, IError>> InvokeAsync(TMutation mutation, CancellationToken ct = default)
        => RunAsync(mutation, preloaded: null, ct);

    /// <inheritdoc />
    public Task<Result<TEntity, IError>> InvokeAsync(
        TMutation mutation, TEntity entity, CancellationToken ct = default)
    {
        ArgumentNullException.ThrowIfNull(entity);

        // Create builds the entity; being handed one means the caller expected a different mode. Loudly,
        // because the alternative is updating a row where the author asked for an insert.
        if (GetMode() == MutationMode.Create)
            throw new InvalidOperationException(
                $"{typeof(TMutation).Name} is a Create mutation, so it has no entity to be given. Use " +
                "InvokeAsync(mutation, ct), or declare the mutation as Update or CreateOrUpdate.");

        return RunAsync(mutation, entity, ct);
    }

    private async Task<Result<TEntity, IError>> RunAsync(
        TMutation mutation, TEntity? preloaded, CancellationToken ct)
    {
        var mark = Compensation.Mark();

        // Same ownership rule as the action pipeline: a mutation nested inside an invoker that holds
        // the same unit of work stages its writes and lets that one save.
        using var commitOwnership = global::Pragmatic.Actions.Commit.CommitScope.Claim(UnitOfWork, CommitMode);

        var result = commitOwnership.CommitsHere
            ? await RunAttemptsAsync(AttemptFor(mutation, preloaded), ct).ConfigureAwait(false)
            : await InvokeCoreAsync(mutation, commitsHere: false, preloaded, ct).ConfigureAwait(false);

        if (result.IsSuccess)
        {
            // After the commit: before it there is nothing to undo.
            if (IsCompensable)
                Compensation.Register(typeof(TMutation).Name, undoCt => CompensateAsync(result.Value, undoCt));

            return result;
        }

        var compensationFailure = await Compensation.CompensateFromAsync(mark, ct).ConfigureAwait(false);
        if (compensationFailure is null)
            return result;

        LogMutationCompensationFailed(typeof(TMutation).Name, compensationFailure.ActionName,
            compensationFailure.Error.Code);

        return Result<TEntity, IError>.Failure(new Compensation.CompensationFailedError
        {
            OriginalError = result.Error,
            CompensationError = compensationFailure.Error,
            UncompensatedAction = compensationFailure.ActionName
        });
    }

    /// <summary>Whether this mutation declared <c>[UndoWith&lt;T&gt;]</c>. Overridden by the generated invoker.</summary>
    protected virtual bool IsCompensable => false;

    /// <summary>
    ///     Whether this mutation answers for the permissions of what it invokes.
    /// </summary>
    /// <remarks>
    ///     Set by the generated invoker from <c>[AbsorbsChildPermissions]</c>. Its own
    ///     <c>[RequirePermission]</c> is unaffected — that check runs before the body does.
    /// </remarks>
    protected virtual bool AbsorbsChildPermissions => false;

    /// <summary>
    ///     The unit of work this invoker commits through. Overridden by the generated invoker; it is the
    ///     identity <c>CommitScope</c> keys ownership on.
    /// </summary>
    protected virtual global::Pragmatic.Persistence.Repository.IUnitOfWork? UnitOfWork => null;

    /// <summary>
    ///     The strategy declared by <c>[CommitStrategy]</c>. Overridden by the generated invoker.
    /// </summary>
    protected virtual global::Pragmatic.Actions.Commit.CommitMode CommitMode
        => global::Pragmatic.Actions.Commit.CommitMode.Once;

    /// <summary>
    ///     Runs the declared compensator and commits it through this invoker's unit of work. Overridden
    ///     by the generated invoker; the default succeeds without doing anything.
    /// </summary>
    /// <param name="committed">The entity this mutation committed.</param>
    /// <param name="ct">Cancellation token.</param>
    protected virtual Task<VoidResult<IError>> CompensateAsync(TEntity committed, CancellationToken ct)
        => Task.FromResult(VoidResult<IError>.Success());

    private async Task<Result<TEntity, IError>> InvokeCoreAsync(
        TMutation mutation, bool commitsHere, TEntity? preloaded, CancellationToken ct)
    {
        ThrowIfNull(mutation);

        var mutationType = typeof(TMutation).Name;
        var entityType = typeof(TEntity).Name;
        var mode = GetMode();

        using var activity = ActionsDiagnostics.ActivitySource.StartActivity($"Mutation.{mutationType}");
        ConfigureMutationActivity(activity, mutationType, entityType, mode);

        // Separate from the activity, which is null whenever nothing is listening. The audit interceptor
        // reads this to say which operation changed the row, and that must not depend on whether tracing
        // is switched on. Full name, because the Article 30 register joins on it.
        using var operation = OperationScope.Enter(typeof(TMutation).FullName);

        ActionsDiagnostics.MutationInvocations.Add(1,
            new KeyValuePair<string, object?>("mutation.name", mutationType),
            new KeyValuePair<string, object?>("mutation.mode", mode.ToString()));

        LogStart(mutationType);
        var stopwatch = Stopwatch.StartNew();

        try
        {
            // 0. Inject dependencies into mutation
            InjectDependencies(mutation);

            // 0b. Permission check (async — awaits a DB/cache-backed permission store instead of blocking)
            var permError = await CheckPermissionsAsync(mutationType, activity, ct).ConfigureAwait(false);
            if (permError is not null)
                return Result<TEntity, IError>.Failure(permError);

            // 0c. Policy + resource authorization. Mutations bypass the global IActionFilter chain, so
            //     [RequirePolicy<T>] and IResourceAuthorizer<T> are enforced here explicitly (was a gap).
            var authzError = await CheckPolicyAndResourceAsync(mutation, mutationType, activity, ct).ConfigureAwait(false);
            if (authzError is not null)
                return Result<TEntity, IError>.Failure(authzError);

            // 1. Level 1 sync validation (on mutation input)
            var l1Error = RunL1SyncValidation(mutation, mutationType, activity);
            if (l1Error is not null)
                return Result<TEntity, IError>.Failure(l1Error);

            // 2. Level 1 async validation (on mutation input)
            var l1AsyncError = await RunL1AsyncValidationAsync(mutation, mutationType, activity, ct).ConfigureAwait(false);
            if (l1AsyncError is not null)
                return Result<TEntity, IError>.Failure(l1AsyncError);

            // 2b. Typed action filters (IActionFilter<TMutation>) — business policies
            var filterError = await RunTypedFiltersAsync(mutation, mutationType, activity, ct).ConfigureAwait(false);
            if (filterError is not null)
                return Result<TEntity, IError>.Failure(filterError);

            // 2c. [LoadEntity] — after authorization, as on an action, so a caller who may not run the
            //     mutation cannot tell an existing row from a missing one by 404-vs-403.
            var prepareError = await PrepareMutationAsync(mutation, ct).ConfigureAwait(false);
            if (prepareError is not null)
                return Result<TEntity, IError>.Failure(prepareError);

            // 3. Load or Create entity — unless the caller handed us one it had already read through
            //    the repository, in which case the load is a round trip for a row we are holding.
            var (entity, isCreate, loadError) = preloaded is not null
                ? (preloaded, false, null)
                : await LoadOrCreateEntityAsync(mutation, mode, mutationType, ct).ConfigureAwait(false);
            if (loadError is not null)
                return Result<TEntity, IError>.Failure(loadError);

            // The load path does this after reading; a handed-over entity has to get the same treatment,
            // or "what changed" is computed against whatever the caller happened to touch first.
            if (preloaded is IChangeTracking preloadedTracking)
                preloadedTracking.ResetModifiedProperties();

            // …and the same goes for the graph. The load path includes what the mutation writes; a
            // handed-over entity carries whatever the caller happened to read, which for a merge is
            // the difference between removing nothing and removing what is gone.
            if (preloaded is not null)
                await EnsureWrittenGraphLoadedAsync(preloaded, ct).ConfigureAwait(false);

            // 4+. Dispatch to mode-specific pipeline
            var isDelete = mode == MutationMode.Delete;
            var isRestore = mode == MutationMode.Restore;

            if (isDelete)
                return await ExecuteDeletePipelineAsync(mutation, entity!, mutationType, commitsHere, stopwatch, activity, ct).ConfigureAwait(false);

            if (isRestore)
                return await ExecuteRestorePipelineAsync(mutation, entity!, mutationType, commitsHere, stopwatch, activity, ct).ConfigureAwait(false);

            return await ExecuteCreateUpdatePipelineAsync(mutation, entity!, isCreate, mutationType, commitsHere, stopwatch, activity, ct).ConfigureAwait(false);
        }
        catch (Exception ex)
        {
            stopwatch.Stop();
            RecordMutationException(activity, mutationType, stopwatch, ex);
            throw;
        }
    }

    // =========================================================================
    // Entity Loading
    // =========================================================================

    private async Task<(TEntity? Entity, bool IsCreate, IError? Error)> LoadOrCreateEntityAsync(
        TMutation mutation, MutationMode mode, string mutationType, CancellationToken ct)
    {
        var isDelete = mode == MutationMode.Delete;
        var isRestore = mode == MutationMode.Restore;

        LogLoadingEntity(mutationType, mode.ToString());

        if (isDelete || isRestore || mode.HasFlag(MutationMode.Update))
        {
            var loaded = await LoadEntityAsync(mutation, ct).ConfigureAwait(false);
            if (loaded is not null)
            {
                if (loaded is IChangeTracking changeTracking)
                    changeTracking.ResetModifiedProperties();
                return (loaded, false, null);
            }

            // Creation is the fallback of a missing id, not of a failed load. ⚠️ This asked only
            // whether the mode carried Create, so an id the caller sent that named nothing answered
            // 200 and wrote a new row — with an id different from the one sent, because the fallback
            // builds a fresh entity. An id wrong by one letter, or a row retired since the client
            // last read it, lost the refinement and fabricated a copy in silence.
            if (!isDelete && mode.HasFlag(MutationMode.Create) && !HasEntityId(mutation))
            {
                LogCreatingEntity(mutationType);
                var created = await CreateAndPrepareEntityAsync(mutationType, ct).ConfigureAwait(false);
                return (created, true, null);
            }

            var entityId = GetEntityIdString(mutation);
            LogEntityNotFound(mutationType, entityId);
            return (null, false, new Result.Http.NotFoundError
            {
                EntityType = typeof(TEntity).Name,
                EntityId = entityId
            });
        }

        // Create mode
        LogCreatingEntity(mutationType);
        var newEntity = await CreateAndPrepareEntityAsync(mutationType, ct).ConfigureAwait(false);
        return (newEntity, true, null);
    }

    private async Task<TEntity> CreateAndPrepareEntityAsync(string mutationType, CancellationToken ct)
    {
        var entity = CreateEntity();

        if (entity is IChangeTracking newTracking)
            newTracking.IsNew = true;

        var lifecycleContext = BuildLifecycleContext();
        await ApplyComputedDefaultsAsync(entity, lifecycleContext, ct).ConfigureAwait(false);

        // IEntityLifecycle<TEntity>.OnCreating — after construction/defaults, before validation.
        InvokeOnCreatingHooks(entity, lifecycleContext);

        return entity;
    }

    // =========================================================================
    // Abstract Methods — Entity Load/Create/Persist
    // =========================================================================

    /// <summary>
    ///     Injects dependencies into the mutation instance.
    ///     Implemented by generated derived classes.
    /// </summary>
    protected abstract void InjectDependencies(TMutation mutation);

    /// <summary>
    ///     Loads an existing entity for update. Returns null if not found.
    ///     Implemented by generated derived classes with proper repository and includes.
    /// </summary>
    protected abstract Task<TEntity?> LoadEntityAsync(TMutation mutation, CancellationToken ct);

    /// <summary>
    ///     Loads what the mutation declares with <c>[LoadEntity]</c> besides its own entity, and hands it
    ///     to the mutation. Overridden by the generated invoker when there is any.
    /// </summary>
    /// <returns>The error to answer with — a <c>NotFoundError</c> for a key that names nothing — or <c>null</c>.</returns>
    protected virtual Task<IError?> PrepareMutationAsync(TMutation mutation, CancellationToken ct)
        => Task.FromResult<IError?>(null);

    /// <summary>
    ///     Creates a new entity instance.
    ///     Default: parameterless constructor. Override for factory pattern.
    /// </summary>
    protected abstract TEntity CreateEntity();

    /// <summary>
    ///     Makes sure the navigations this mutation writes are loaded on an entity the caller handed
    ///     over, and loads only the ones that are not.
    /// </summary>
    /// <param name="entity">The entity the caller passed in.</param>
    /// <param name="ct">Cancellation.</param>
    /// <remarks>
    ///     <para>
    ///         ⚠️ Only for the handed-over path. When this invoker reads the row itself it includes
    ///         what it writes; when a caller hands one over — a domain action that already had it —
    ///         nothing says how much of the graph came with it.
    ///     </para>
    ///     <para>
    ///         Skipping the load there is silent data loss: a merge decides what to remove by looking
    ///         at what is there, and EF cannot tell an empty collection from one never loaded, so it
    ///         removes nothing and adds everything. Loading it all again is the opposite waste — a
    ///         round trip for rows already in hand.
    ///     </para>
    ///     <para>
    ///         The generated override asks the change tracker which paths are missing, which costs no
    ///         query, and reads once with exactly those includes. No children to write, no override.
    ///     </para>
    /// </remarks>
    protected virtual Task EnsureWrittenGraphLoadedAsync(TEntity entity, CancellationToken ct)
        => Task.CompletedTask;

    /// <summary>
    ///     Links the rows this mutation chose by key — <c>[LinkIds]</c>.
    /// </summary>
    /// <remarks>
    ///     Empty unless the mutation carries a list of keys; the generator overrides it when one does.
    ///     Separate from <see cref="EnsureWrittenGraphLoadedAsync" /> because it runs <b>after</b> the
    ///     auto-map rather than before: nothing about the links depends on what the mapping wrote, and
    ///     a link is a write, not a preparation for one.
    /// </remarks>
    protected virtual Task LinkChosenRowsAsync(TMutation mutation, TEntity entity, CancellationToken ct)
        => Task.CompletedTask;

    /// <summary>
    ///     Gets the mutation mode (Create, Update, or CreateOrUpdate).
    ///     Set by the generated derived class based on attribute or naming convention.
    /// </summary>
    protected abstract MutationMode GetMode();

    /// <summary>
    ///     Gets the entity ID as string for error messages.
    /// </summary>
    protected abstract string? GetEntityIdString(TMutation mutation);

    /// <summary>
    ///     Whether the caller supplied an entity id — the difference between "refine this row" and
    ///     "make one".
    /// </summary>
    /// <remarks>
    ///     <para>
    ///         It decides the <c>CreateOrUpdate</c> fallback: with an id, a load that finds nothing is
    ///         a <c>NotFoundError</c>; without one, there was no row to refine and creating is the
    ///         answer.
    ///     </para>
    ///     <para>
    ///         Virtual with a string-based default so a hand-written invoker keeps working. The
    ///         generated override is typed — <c>mutation.Id != default</c> — because the default of a
    ///         <c>Guid</c> is not an empty string, and asking the string would read an unsent id as
    ///         sent.
    ///     </para>
    /// </remarks>
    protected virtual bool HasEntityId(TMutation mutation)
        => GetEntityIdString(mutation) is { Length: > 0 } id
           && id != Guid.Empty.ToString()
           && id != "0";

    /// <summary>
    ///     Adds a new entity to the repository.
    /// </summary>
    protected abstract void PersistNew(TEntity entity);

    /// <summary>
    ///     Saves all changes via the unit of work.
    /// </summary>
    protected abstract Task SaveChangesAsync(CancellationToken ct);

    /// <summary>
    ///     Builds the domain events the mutation declared via <c>[Raises&lt;T&gt;]</c> (ctor filled by name from the
    ///     mutation's inputs and the entity's members). The pipeline dispatches them after a successful commit —
    ///     so behavior lives in the operation, not the entity. The generated invoker overrides this; the default
    ///     is empty. These are dispatched directly (not via the entity, whose RaiseEvent is protected).
    /// </summary>
    protected virtual IReadOnlyList<Pragmatic.Events.IDomainEvent> CollectRaisedEvents(TMutation mutation, TEntity entity) => [];

    /// <summary>Dispatches the mutation's <c>[Raises&lt;T&gt;]</c> events via the domain-event dispatcher (resolved from DI).</summary>
    protected async Task DispatchRaisedEventsAsync(IReadOnlyList<Pragmatic.Events.IDomainEvent> events, CancellationToken ct)
    {
        if (events.Count == 0)
            return;

        var dispatcher = _serviceProvider.GetService<Pragmatic.Events.IDomainEventDispatcher>();
        if (dispatcher is null)
        {
            // Surface a missing dispatcher instead of silently dropping declared [Raises<T>] events.
            LogRaisedEventsDropped(typeof(TMutation).Name, events.Count);
            return;
        }

        await dispatcher.DispatchAsync(events, ct).ConfigureAwait(false);
    }
}
