using System.Diagnostics;
using Microsoft.Extensions.DependencyInjection;
using Pragmatic.Actions.Abstractions;
using Pragmatic.Actions.Compensation;
using Pragmatic.Actions.Diagnostics;
using Pragmatic.Actions.Pipeline;
using Pragmatic.Pipeline;
using Pragmatic.Result;
using static Pragmatic.Ensure.Ensure;
using Pragmatic.Telemetry.Conventions;

namespace Pragmatic.Actions.Invoker;

/// <summary>
///     Abstract base class for VoidDomainAction invokers.
///     Handles filter execution, logging, and telemetry for void actions.
/// </summary>
/// <typeparam name="TAction">The void action type.</typeparam>
/// <remarks>
///     <para>
///         Derived classes are generated by the source generator. They provide:
///     </para>
///     <list type="bullet">
///         <item>Constructor injection of action dependencies</item>
///         <item>Implementation of <see cref="InjectDependencies" /></item>
///     </list>
///     <para>
///         The pipeline execution order is:
///     </para>
///     <list type="number">
///         <item>BeforeExecute filters (in order)</item>
///         <item>Action.Execute()</item>
///         <item>AfterExecute filters (reverse order)</item>
///     </list>
/// </remarks>
public abstract partial class VoidDomainActionInvoker<TAction> : ActionInvokerBase, IVoidDomainActionInvoker<TAction>
    where TAction : VoidDomainAction
{
    private readonly IEnumerable<IActionFilter<TAction>> _actionFilters;

    /// <summary>
    ///     Creates a new invoker instance.
    /// </summary>
    /// <param name="serviceProvider">The service provider for resolving filters.</param>
    protected VoidDomainActionInvoker(IServiceProvider serviceProvider)
        : base(serviceProvider, typeof(VoidDomainActionInvoker<TAction>))
    {
        _actionFilters = serviceProvider.GetService<IEnumerable<IActionFilter<TAction>>>() ?? [];
    }

    /// <inheritdoc />
    /// <remarks>
    ///     <c>[Transactional]</c> runs the invocation inside the unit of work's execution strategy, and a
    ///     transient failure before the commit runs it again. The re-run rule is the same as
    ///     <see cref="DomainActionInvoker{TAction, TReturn}.InvokeAsync" />'s: no effect outside the transaction.
    /// </remarks>
    public Task<VoidResult<IError>> InvokeAsync(TAction action, CancellationToken ct = default)
    {
        ThrowIfNull(action);

        return IsTransactional && UnitOfWork is { } unitOfWork
            ? unitOfWork.ExecuteAsync(token => InvokeOnceAsync(action, token), ct)
            : InvokeOnceAsync(action, ct);
    }

    private async Task<VoidResult<IError>> InvokeOnceAsync(TAction action, CancellationToken ct)
    {
        var actionName = typeof(TAction).Name;

        using var activity = ActionsDiagnostics.ActivitySource.StartActivity($"Action.{actionName}");
        ConfigureActivity(activity, typeof(TAction).FullName!, "void_action");

        // See MutationInvoker: the activity is null with no listener, and the audit trail cannot depend
        // on tracing being switched on.
        using var operation = OperationScope.Enter(typeof(TAction).FullName);

        ActionsDiagnostics.ActionInvocations.Add(1,
            new KeyValuePair<string, object?>("action.name", actionName));

        LogStart("VoidAction", actionName);
        var stopwatch = Stopwatch.StartNew();

        // Taken before anything runs, so this invocation compensates only what it caused.
        var compensationMark = Compensation.Mark();

        // [Transactional]: one transaction around the whole body, opened before anything runs so every
        // nested save lands inside it.
        global::Pragmatic.Persistence.Repository.ITransaction? transaction = null;
        if (IsTransactional && UnitOfWork is not null)
            transaction = await UnitOfWork.BeginTransactionAsync(ct).ConfigureAwait(false);

        // Who commits, decided by unit of work identity rather than by reading the call graph.
        //
        // Nothing is claimed for a composite. CommitsItsOwnWork says its CompositeInvoker owns the unit
        // of work, and claiming here first would make that one look nested — its claim would find this
        // entry, return without a batch, and the semantics it asked for (steps that save as they go,
        // under [Transactional]) would never reach one. The symptom was a composite whose second step
        // could not see what the first wrote, with every generated line correct.
        using var commitOwnership = CommitsItsOwnWork
            ? default
            : global::Pragmatic.Actions.Commit.CommitScope.Claim(UnitOfWork, CommitMode, IsTransactional);

        try
        {
            // Inject dependencies
            InjectDependencies(action);

            // Get all applicable filters, ordered
            var filters = GetOrderedFilters();

            ConfigureActivity(activity, typeof(TAction).FullName!, "void_action", filters.Count);
            LogFilters("VoidAction", actionName, filters.Count);

            // 1. Execute BeforeExecute filters (in order)
            foreach (var filter in filters)
            {
                var filterName = filter.GetType().Name;
                LogBeforeFilter("VoidAction", actionName, filterName);

                var beforeResult = await filter.BeforeExecuteVoidAsync(action, ct).ConfigureAwait(false);

                if (beforeResult.IsFailure)
                {
                    LogShortCircuit("VoidAction", actionName, filterName, beforeResult.Error.Code);
                    SetActivityShortCircuit(activity, beforeResult.Error.Code);

                    ActionsDiagnostics.FilterShortCircuits.Add(1,
                        new KeyValuePair<string, object?>("action.name", actionName),
                        new KeyValuePair<string, object?>("filter.name", filterName));

                    return beforeResult;
                }
            }

            // The ambient scopes that must outlive the body — the delegation. Here and not inside
            // ExecuteActionAsync because the save below is what attributes the row, and
            // after the filters above because the action's own permission is the caller's.
            using var invocationScope = BeginInvocationScope(action);

            // Prepare action (load [LoadEntity] entities, etc.) — AFTER the authorization filters
            // so an unauthorized caller is denied before any entity load hits the database and
            // cannot probe entity existence via 404-vs-403. Matches the mutation pipeline (authz → load).
            LogPreparingAction("VoidAction", actionName);
            var prepareError = await PrepareActionAsync(action, ct).ConfigureAwait(false);
            if (prepareError is not null)
            {
                LogPreparationFailed("VoidAction", actionName, prepareError.Code);
                return VoidResult<IError>.Failure(prepareError);
            }

            // [TransitionsTo] with BeforeBody: after the loads, before the body.
            if (TransitionBeforeBody(action) is { } refused)
            {
                LogPreparationFailed("VoidAction", actionName, refused.Code);
                return VoidResult<IError>.Failure(refused);
            }

            // 2. Execute the action (virtual dispatch for versioning support)
            LogExecuting("VoidAction", actionName);
            var result = await ExecuteActionAsync(action, ct).ConfigureAwait(false);

            if (result.IsSuccess)
                EnsureTheBodyTransitioned(action);

            // 3. Persist any pending changes if the action succeeded.
            //    SaveChanges runs BEFORE AfterExecute filters so side effects
            //    (cache invalidation, event dispatch) only fire after a successful commit —
            //    matching DomainActionInvoker and preserving atomicity.
            if (result.IsSuccess)
            {
                // The loaded aggregate's rules, after the body and before the write — the same place the
                // typed invoker checks them. The generator emits the override for this shape too.
                if (CheckLoadedInvariants(action) is { } invariantError)
                {
                    LogPreparationFailed("VoidAction", actionName, invariantError.Code);
                    return VoidResult<IError>.Failure(invariantError);
                }

                // A composite of mutation steps has already committed them, in one transaction of its
                // own. Committing again here writes nothing — but it is a second round trip per
                // composite, and it makes "one SaveChanges" false where the documentation says it.
                // Saves when it owns the commit — or when it is nested inside an explicit transaction,
                // where the whole point is that a later step can read what this one wrote. Implementing
                // this only for nested mutations left an action step invisible to the next one, and the
                // batch check is what tells the two situations apart.
                var savesHere = commitOwnership.CommitsHere
                    || global::Pragmatic.Actions.Commit.CommitScope.BatchFor(UnitOfWork)
                        is { DefersSave: false };

                if (!CommitsItsOwnWork && savesHere)
                {
                    LogSavingChanges("VoidAction", actionName);
                    await SaveChangesAsync(ct).ConfigureAwait(false);
                }

                // The commit, and only now: everything deferred below is flushed after it, never before.
                if (transaction is not null)
                    await transaction.CommitAsync(ct).ConfigureAwait(false); // commit — a failure here IS a real failure and propagates

                // 3b. Post-commit side effects — isolated so a failure can't flip the committed success
                //     into a thrown failure (double-run risk). Log at Error and carry on.
                try
                {
                    // Outside every claim: see CommitScope.Suspend. A handler writing through this unit
                    // of work is its own operation once the commit has happened.
                    using var outsideTheCommit = global::Pragmatic.Actions.Commit.CommitScope.Suspend();

                    await DispatchRaisedEventsAsync(CollectRaisedEvents(action), ct).ConfigureAwait(false);

                    // What the nested invocations could not dispatch themselves, now that their writes
                    // are committed. Without it a mutation invoked from here succeeds silently and its
                    // handler never runs. The batch is the one captured before suspending.
                    await global::Pragmatic.Actions.Commit.DeferredEventFlush
                        .FlushAsync(commitOwnership.Batch, ServiceProvider, ct).ConfigureAwait(false);

                    // Last, and only on success: see DomainActionInvoker.
                    await InvalidateCacheAsync(action, "VoidAction", actionName, ct).ConfigureAwait(false);
                }
                catch (Exception postCommitEx)
                {
                    LogPostCommitSideEffectFailed("VoidAction", actionName, postCommitEx);
                    activity?.SetTag(ActionTags.PostCommitFailed, true);
                }

                // 3c. Registered only after the commit: before it there is nothing to undo.
                if (IsCompensable)
                    Compensation.Register(actionName, CompensateAsync);
            }
            else
            {
                // The action failed, so nothing it wrote survives — that is what the transaction was
                // asked for. Rolled back before the compensation runs: a step in another boundary is
                // not covered by it, which is exactly what PRAG0426 refuses to let happen silently.
                if (transaction is not null)
                    await transaction.RollbackAsync(ct).ConfigureAwait(false);

                // The action failed. Whatever committed inside it is undone here, most recent first.
                var compensationFailure =
                    await Compensation.CompensateFromAsync(compensationMark, ct).ConfigureAwait(false);

                if (compensationFailure is not null)
                {
                    LogCompensationFailed("VoidAction", actionName, compensationFailure.ActionName,
                        compensationFailure.Error.Code);
                    activity?.SetTag(ActionTags.CompensationFailed, true);

                    result = VoidResult<IError>.Failure(new CompensationFailedError
                    {
                        OriginalError = result.Error,
                        CompensationError = compensationFailure.Error,
                        UncompensatedAction = compensationFailure.ActionName
                    });
                }
            }

            // 4. Execute AfterExecute filters (reverse order) — after commit; isolate each call.
            foreach (var filter in filters.AsEnumerable().Reverse())
            {
                var filterName = filter.GetType().Name;
                LogAfterFilter("VoidAction", actionName, filterName);

                try
                {
                    await filter.AfterExecuteVoidAsync(action, result, ct).ConfigureAwait(false);
                }
                catch (Exception afterEx)
                {
                    LogPostCommitSideEffectFailed("VoidAction", actionName, afterEx);
                    activity?.SetTag(ActionTags.PostCommitFailed, true);
                }
            }

            stopwatch.Stop();

            ActionsDiagnostics.ActionDuration.Record(stopwatch.Elapsed.TotalMilliseconds,
                new KeyValuePair<string, object?>("action.name", actionName),
                new KeyValuePair<string, object?>("action.result", result.IsSuccess ? "success" : "failure"));

            if (result.IsSuccess)
            {
                LogSuccess("VoidAction", actionName, stopwatch.ElapsedMilliseconds);
                SetActivitySuccess(activity);
            }
            else
            {
                LogFailure("VoidAction", actionName, result.Error.Code, stopwatch.ElapsedMilliseconds);
                SetActivityFailure(activity, result.Error.Code);

                ActionsDiagnostics.ActionFailures.Add(1,
                    new KeyValuePair<string, object?>("action.name", actionName),
                    new KeyValuePair<string, object?>("error.code", result.Error.Code));
            }

            return result;
        }
        catch (Exception ex)
        {
            stopwatch.Stop();

            if (transaction is not null)
                await transaction.RollbackAsync(ct).ConfigureAwait(false);

            ActionsDiagnostics.ActionDuration.Record(stopwatch.Elapsed.TotalMilliseconds,
                new KeyValuePair<string, object?>("action.name", actionName),
                new KeyValuePair<string, object?>("action.result", "exception"));

            ActionsDiagnostics.ActionFailures.Add(1,
                new KeyValuePair<string, object?>("action.name", actionName),
                new KeyValuePair<string, object?>("error.code", ex.GetType().Name));

            LogException("VoidAction", actionName, stopwatch.ElapsedMilliseconds, ex);
            SetActivityException(activity, ex);
            throw;
        }
        finally
        {
            if (transaction is not null)
                await transaction.DisposeAsync().ConfigureAwait(false);
        }
    }

    /// <summary>
    ///     Executes the action. Override in generated invokers to support
    ///     versioned dispatch (ExecuteV2, ExecuteV3, etc.).
    /// </summary>
    /// <param name="action">The action to execute.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>The action result.</returns>
    protected virtual Task<VoidResult<IError>> ExecuteActionAsync(TAction action, CancellationToken ct)
        => action.Execute(ct);

    /// <summary>
    ///     Opens an ambient scope that has to outlive the body — the delegation
    ///     <c>[StartsDelegation]</c> declares. Disposed after the save and the post-commit side
    ///     effects. See <c>DomainActionInvoker.BeginInvocationScope</c> for why it is not
    ///     <c>ExecuteActionAsync</c>.
    /// </summary>
    /// <param name="action">The action being invoked; the subject is read off it.</param>
    /// <returns>The scope to hold for the rest of the invocation, or <c>null</c> when there is none.</returns>
    protected virtual IDisposable? BeginInvocationScope(TAction action) => null;

    /// <summary>
    ///     Whether the action commits its own work, so this pipeline must not commit again.
    /// </summary>
    /// <remarks>
    ///     True for a <c>[CompositeAction]</c> of mutation steps: its generated invoker runs the steps
    ///     with the commit suppressed and then performs the single transaction itself. The commit here
    ///     would find nothing pending — it is a wasted round trip, and it contradicts the one guarantee
    ///     the composite makes.
    /// </remarks>
    protected virtual bool CommitsItsOwnWork => false;

    /// <summary>
    ///     Whether this action declared <c>[Transactional]</c>. Overridden by the generated invoker.
    /// </summary>
    protected virtual bool IsTransactional => false;

    /// <summary>
    ///     The unit of work this invoker commits through, or <c>null</c> when the action has no boundary.
    ///     Overridden by the generated invoker; it is the identity <c>CommitScope</c> keys ownership on.
    /// </summary>
    protected virtual global::Pragmatic.Persistence.Repository.IUnitOfWork? UnitOfWork => null;

    /// <summary>
    ///     The strategy declared by <c>[CommitStrategy]</c>. Overridden by the generated invoker.
    /// </summary>
    protected virtual global::Pragmatic.Actions.Commit.CommitMode CommitMode
        => global::Pragmatic.Actions.Commit.CommitMode.Once;

    /// <summary>
    ///     Whether this action declared <c>[UndoWith&lt;T&gt;]</c>. Overridden by the generated invoker.
    /// </summary>
    protected virtual bool IsCompensable => false;

    /// <summary>
    ///     Runs the declared compensator and commits it through this invoker's unit of work. Overridden
    ///     by the generated invoker; the default succeeds without doing anything.
    /// </summary>
    /// <param name="ct">Cancellation token.</param>
    protected virtual Task<VoidResult<IError>> CompensateAsync(CancellationToken ct)
        => Task.FromResult(VoidResult<IError>.Success());

    /// <summary>
    ///     The domain events this action declared via <c>[Raises&lt;T&gt;]</c>, built from the action's inputs.
    ///     Overridden by the generated invoker; the default raises nothing.
    /// </summary>
    protected virtual IReadOnlyList<Pragmatic.Events.IDomainEvent> CollectRaisedEvents(TAction action)
        => [];

    /// <summary>
    ///     Injects dependencies into the action instance.
    ///     Implemented by generated derived classes.
    /// </summary>
    /// <param name="action">The action to inject dependencies into.</param>
    protected abstract void InjectDependencies(TAction action);

    /// <summary>
    ///     Prepares the action before filter and execution phases.
    ///     Override to load entities, validate preconditions, etc.
    /// </summary>
    /// <param name="action">The action to prepare.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>An error if preparation failed, null if successful.</returns>
    protected virtual Task<IError?> PrepareActionAsync(TAction action, CancellationToken ct)
        => Task.FromResult<IError?>(null);

    /// <summary>
    ///     Persists any pending changes after successful action execution.
    ///     Overridden by generated invokers that have a boundary-keyed IUnitOfWork.
    /// </summary>
    protected virtual Task SaveChangesAsync(CancellationToken ct) => Task.CompletedTask;

    private List<IActionFilter> GetOrderedFilters()
    {
        var result = GetSortedGlobalFilters();

        // Add single-type-param action filters (adapted to IActionFilter)
        foreach (var actionFilter in _actionFilters)
            result.Add(new ActionFilterAdapter(actionFilter));

        // Re-sort after adding typed filters
        result.Sort((a, b) => a.Order.CompareTo(b.Order));

        return result;
    }

    // =========================================================================
    // Filter Adapter
    // =========================================================================

    /// <summary>
    ///     Adapts <see cref="IActionFilter{TAction}" /> (single param) to <see cref="IActionFilter" />.
    /// </summary>
    private sealed class ActionFilterAdapter(IActionFilter<TAction> inner) : IActionFilter
    {
        public int Order => inner.Order;

        public Task<VoidResult<IError>> BeforeExecuteAsync<TActionInner, TReturnInner>(
            TActionInner action,
            CancellationToken ct)
            where TActionInner : DomainAction<TReturnInner>
            => Task.FromResult(VoidResult<IError>.Success());

        public Task AfterExecuteAsync<TActionInner, TReturnInner>(
            TActionInner action,
            Result<TReturnInner, IError> result,
            CancellationToken ct)
            where TActionInner : DomainAction<TReturnInner>
            => Task.CompletedTask;

        public Task<VoidResult<IError>> BeforeExecuteVoidAsync<TActionInner>(
            TActionInner action,
            CancellationToken ct)
            where TActionInner : VoidDomainAction
        {
            if (action is TAction typedAction)
                return inner.BeforeExecuteAsync(typedAction, ct);
            return Task.FromResult(VoidResult<IError>.Success());
        }

        public Task AfterExecuteVoidAsync<TActionInner>(
            TActionInner action,
            VoidResult<IError> result,
            CancellationToken ct)
            where TActionInner : VoidDomainAction
        {
            if (action is TAction typedAction)
                return inner.AfterExecuteAsync(typedAction, ct);
            return Task.CompletedTask;
        }
    }
}
