using Pragmatic.SourceGenerator.Features.Endpoints.Models;

namespace Pragmatic.SourceGenerator.Features.Endpoints.Templates;

/// <summary>
///     Centralised rate limiting code generation for endpoint templates.
///     Resolves the policy name — either explicit or SG-generated inline.
/// </summary>
internal static class RateLimitHelper
{
    /// <summary>
    ///     Returns the rate limit policy name for the given model, or null if no rate limiting is configured.
    /// </summary>
    public static string? GetPolicyName(EndpointModel model)
    {
        if (model.RateLimit is null)
            return null;

        // Explicit named policy
        if (!string.IsNullOrEmpty(model.RateLimit.Policy))
            return model.RateLimit.Policy;

        // Inline policy (generated by EndpointRegistrationTemplate)
        if (model.RateLimit.Requests > 0 && !string.IsNullOrEmpty(model.RateLimit.Window))
            return GetInlinePolicyName(model);

        return null;
    }

    /// <summary>
    ///     Deterministic inline rate-limit policy name, derived from the fully-qualified
    ///     type identity (not the simple <c>TypeName</c>) so two endpoints with the same simple name
    ///     in different namespaces don't collide on a shared policy. The registration site MUST use
    ///     this exact method so the mapped policy name matches the registered one.
    /// </summary>
    public static string GetInlinePolicyName(EndpointModel model)
        => $"__pragmatic_ratelimit_{SanitizeIdentity(model.FullTypeName)}";

    private static string SanitizeIdentity(string fullTypeName)
    {
        var trimmed = fullTypeName.Replace("global::", "");
        var chars = trimmed.ToCharArray();
        for (var i = 0; i < chars.Length; i++)
            if (!char.IsLetterOrDigit(chars[i]))
                chars[i] = '_';
        return new string(chars);
    }
}
