using System.Collections.Immutable;
using Pragmatic.SourceGen;
using Pragmatic.SourceGenerator.Core;
using Pragmatic.SourceGenerator.Features.Endpoints.Models;

namespace Pragmatic.SourceGenerator.Features.Manifest.Models;

/// <summary>
///     Complete endpoint contract for the manifest.
/// </summary>
internal sealed record ManifestEndpointModel
{
    public required string OperationId { get; init; }
    public required string HttpMethod { get; init; }
    public required string FullRoute { get; init; }
    public string? Summary { get; init; }
    public string? Description { get; init; }
    public EquatableArray<string> Tags { get; init; } = EquatableArray<string>.Empty;
    public int SuccessStatusCode { get; init; } = 200;
    public bool IsVoid { get; init; }
    public ManifestTypeRef? ResponseType { get; init; }
    public EquatableArray<ManifestParameterModel> Parameters { get; init; } = EquatableArray<ManifestParameterModel>.Empty;
    public ManifestRequestBodyModel? RequestBody { get; init; }
    public EquatableArray<ManifestErrorRefModel> Errors { get; init; } = EquatableArray<ManifestErrorRefModel>.Empty;

    /// <summary>
    ///     Statuses the pipeline can answer with that no declared error type names — validation,
    ///     authorization, not-found, conflict, the fallback.
    /// </summary>
    /// <remarks>
    ///     <see cref="Errors"/> carries the typed union a mutation declares on its base; this carries
    ///     what the pipeline adds. Both end up in the OpenAPI document.
    /// </remarks>
    public EquatableArray<int> ProblemStatusCodes { get; init; } = EquatableArray<int>.Empty;
    public ManifestAuthorizationModel? Authorization { get; init; }
    public ManifestDomainActionRefModel? DomainAction { get; init; }
    public EquatableArray<string> ApiVersions { get; init; } = EquatableArray<string>.Empty;

    // Surface the remaining endpoint attributes so OpenAPI generated from the manifest
    // reflects deprecation, rate limiting, response caching, and file-upload constraints.
    public bool IsDeprecated { get; init; }
    public string? RateLimitPolicy { get; init; }
    public int? CacheDurationSeconds { get; init; }
    public ManifestFileUploadModel? FileUpload { get; init; }
    public long? MaxBodySizeBytes { get; init; }
    public EquatableArray<ExampleModel> RequestExamples { get; init; } = EquatableArray<ExampleModel>.Empty;
    public EquatableArray<ResponseExampleModel> ResponseExamples { get; init; } = EquatableArray<ResponseExampleModel>.Empty;
    public string? IdempotencyHeader { get; init; }
    public McpToolModel? McpTool { get; init; }
}

/// <summary>
///     File-upload constraints for a multipart endpoint.
/// </summary>
internal sealed record ManifestFileUploadModel
{
    public long? MaxFileSizeBytes { get; init; }
    public EquatableArray<string> AllowedContentTypes { get; init; } = EquatableArray<string>.Empty;
}

internal sealed record ManifestParameterModel
{
    public required string Name { get; init; }
    public required string In { get; init; }
    public required string Type { get; init; }
    public bool IsRequired { get; init; }
    public bool IsNullable { get; init; }
    public string? Constraint { get; init; }
    public string? DefaultValue { get; init; }
}

internal sealed record ManifestRequestBodyModel
{
    public EquatableArray<ManifestPropertyModel> Properties { get; init; } = EquatableArray<ManifestPropertyModel>.Empty;

    /// <summary>
    ///     Whether the body <em>is</em> the single property's type, rather than a record containing it.
    /// </summary>
    /// <remarks>
    ///     Mutations and domain actions bind a single complex body directly, and
    ///     <c>[Endpoint(BindBodyDirectly = true)]</c> lets a hand-written endpoint do the same. Without
    ///     carrying it here the document would publish an envelope the server does not accept — a
    ///     contract that lies, which is worse than a surprising shape.
    /// </remarks>
    public bool IsDirect { get; init; }
}

internal sealed record ManifestPropertyModel
{
    public required string Name { get; init; }

    /// <summary>
    ///     What this property is called on the wire, when that is not its own name camel-cased.
    /// </summary>
    /// <remarks>
    ///     Carried because the document and the deserializer are generated by different code from the
    ///     same declaration, and only one of them was reading <c>[JsonPropertyName]</c>. The body DTO
    ///     honoured the name and the published schema kept advertising the property's own — so a
    ///     client generated from the contract posted a field the endpoint would reject, and the
    ///     application it was generated against worked. Null means the camel-cased name is right.
    /// </remarks>
    public string? WireName { get; init; }

    public required string Type { get; init; }
    public bool IsRequired { get; init; }
    public bool IsNullable { get; init; }
    public bool IsEnum { get; init; }

    /// <summary>The validation rules the contract can spell, in JSON Schema keywords.</summary>
    public WireConstraints Constraints { get; init; } = WireConstraints.Empty;

    public int? Precision { get; init; }
    public int? Scale { get; init; }
    public string? Summary { get; init; }
    public EquatableArray<ManifestValidationRuleModel> Validation { get; init; } = EquatableArray<ManifestValidationRuleModel>.Empty;
}

internal sealed record ManifestErrorRefModel
{
    public required string Type { get; init; }
    public required string Code { get; init; }
    public required int StatusCode { get; init; }
    public string? Title { get; init; }
    public EquatableArray<ManifestErrorExtensionModel> Extensions { get; init; } = EquatableArray<ManifestErrorExtensionModel>.Empty;
}

internal sealed record ManifestErrorExtensionModel
{
    public required string Name { get; init; }
    public required string Type { get; init; }
}

internal sealed record ManifestAuthorizationModel
{
    public bool AllowAnonymous { get; init; }
    public EquatableArray<string> RequiredPermissions { get; init; } = EquatableArray<string>.Empty;
    public EquatableArray<string> AnyPermissions { get; init; } = EquatableArray<string>.Empty;
    public EquatableArray<string> RequiredRoles { get; init; } = EquatableArray<string>.Empty;
    public string? PolicyName { get; init; }
}

internal sealed record ManifestDomainActionRefModel
{
    public bool IsDomainAction { get; init; }
    public bool IsMutation { get; init; }
    public bool IsQuery { get; init; }
    public string? ActionType { get; init; }
    public string? EntityType { get; init; }
    public string? ReturnType { get; init; }
}

internal sealed record ManifestTypeRef
{
    public required string Type { get; init; }
    public bool IsNullable { get; init; }
    public bool IsArray { get; init; }
    public bool IsPaged { get; init; }
    public bool IsStream { get; init; }
}
