using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Pragmatic.SourceGenerator.Features.Composition.Models;

namespace Pragmatic.SourceGenerator.Features.Composition.Generators;

/// <summary>
///     Emits <c>PragmaticMigrationCoordinator : IHostMigrationCoordinator</c>: the on-demand twin of the
///     startup migration block, so a <c>MigrateCommand</c> can re-run migrations. It delegates to the
///     Migrations runner (whose DB advisory lock already elects a single migrator), mirroring the per-database
///     <c>MigrateAsync(new MigrationContext(config[key], {Db}Schema.Current, options))</c> the entry point does.
/// </summary>
internal static partial class HostModeGenerator
{
    private static void GenerateMigrationCoordinator(
        SourceProductionContext context, HostAggregationModel model, string rootNamespace)
    {
        // A database with no entity behind it has no schema to migrate to: the persistence generator
        // writes none, and its migration context is null for the same reason.
        var dbGroups = model.HostIncludes
            .Where(i => i.MigrationDbContextFqn is not null)
            .GroupBy(i => i.DatabaseTypeName!)
            .ToList();

        if (dbGroups.Count == 0)
            return;

        var ns = string.IsNullOrWhiteSpace(rootNamespace) ? "PragmaticGenerated" : rootNamespace;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// On-demand host migration coordinator — cabled to MigrateCommand (FU2).");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("internal sealed class PragmaticMigrationCoordinator(");
        sb.AppendLine("    global::System.IServiceProvider services,");
        sb.AppendLine("    global::Microsoft.Extensions.Configuration.IConfiguration configuration)");
        sb.AppendLine("    : global::Pragmatic.ControlPlane.IHostMigrationCoordinator");
        sb.AppendLine("{");
        sb.AppendLine("    public async global::System.Threading.Tasks.Task MigrateAllAsync(global::System.Threading.CancellationToken ct = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        var migrationRunner = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService<global::Pragmatic.Migrations.Runner.IMigrationRunner>(services);");
        sb.AppendLine("        if (migrationRunner is null) return;");
        sb.AppendLine("        var migrationOptions = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService<global::Pragmatic.Migrations.Runner.MigrationOptions>(services) ?? new global::Pragmatic.Migrations.Runner.MigrationOptions();");
        sb.AppendLine();

        foreach (var group in dbGroups)
        {
            var rep = group.First();
            var migrationKey = rep.MigrationConfigKey ?? rep.DatabaseConfigKey;
            if (migrationKey is null)
                continue;

            var dbSimpleName = SimpleName(group.Key);
            var resultVar = CamelCase(dbSimpleName) + "Result";
            var schemaClass = SchemaClassName(rep.ModuleTypeName, dbSimpleName);

            sb.AppendLine($"        var {resultVar} = await migrationRunner.MigrateAsync(");
            sb.AppendLine("            new global::Pragmatic.Migrations.Runner.MigrationContext(");
            sb.AppendLine($"                configuration[\"{migrationKey}\"] ?? \"\",");
            sb.AppendLine($"                {schemaClass}.Current,");
            sb.AppendLine("                migrationOptions),");
            sb.AppendLine("            ct).ConfigureAwait(false);");
            sb.AppendLine($"        if (!{resultVar}.Success)");
            sb.AppendLine($"            throw new global::System.InvalidOperationException(\"[{dbSimpleName}] Migration failed: \" + ({resultVar}.Error ?? \"unknown error\"));");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource(
            "_Migration.Coordinator.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string SimpleName(string typeName)
    {
        var t = typeName.Replace("global::", "");
        var dot = t.LastIndexOf('.');
        return dot < 0 ? t : t.Substring(dot + 1);
    }

    private static string CamelCase(string value)
        => string.IsNullOrEmpty(value) ? value : char.ToLowerInvariant(value[0]) + value.Substring(1);

    // Mirrors PragmaticEntryTemplate: schema metadata lives in the module's root namespace
    // (e.g. Showcase), two levels above the module type (e.g. Showcase.Booking.BookingModule).
    private static string SchemaClassName(string? moduleTypeName, string dbSimpleName)
    {
        var moduleNs = moduleTypeName?.Replace("global::", "") ?? "";
        var schemaNs = moduleNs.Contains('.') ? moduleNs.Substring(0, moduleNs.LastIndexOf('.')) : moduleNs;
        if (schemaNs.Contains('.'))
            schemaNs = schemaNs.Substring(0, schemaNs.LastIndexOf('.'));
        return $"global::{schemaNs}.{dbSimpleName}Schema";
    }
}
