using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.EntityFrameworkCore;
using Pragmatic.Integration.Tests.Domain.Actions;

namespace Pragmatic.Integration.Tests.Infrastructure;

/// <summary>
///     WebApplicationFactory that configures the full Pragmatic pipeline for integration testing.
///     Wires: Endpoints + Actions (invokers, filters) + Validation + EF Core InMemory.
/// </summary>
public sealed class IntegrationTestFactory : WebApplicationFactory<Program>
{
    private readonly string _dbName = $"IntegrationTest_{Guid.NewGuid():N}";

    protected override void ConfigureWebHost(IWebHostBuilder builder)
    {
        builder.ConfigureServices(services =>
        {
            // 1. EF Core InMemory database
            services.AddDbContext<TestDbContext>(options =>
                options.UseInMemoryDatabase(_dbName));

            // 2. Pragmatic.Actions runtime (pipeline filters: ValidationFilter, LoggingFilter)
            Pragmatic.Actions.Extensions.ServiceCollectionExtensions.AddPragmaticActions(services);

            // 3. Generated by Actions generator: registers concrete invokers
            //    (e.g., CreateOrderActionInvoker → IDomainActionInvoker<CreateOrderAction, OrderResponse>)
            PragmaticActionsRegistrationExtensions.AddPragmaticActions(services);

            // What the actions registered above inject: the host validates every registration at build.
            services.AddSingleton<IRateSource, CountingRateSource>();

            // 4. Generated by Endpoints generator: registers endpoint-specific services
            //    (invoker registration is delegated to Actions generator above).
            services.AddPragmaticEndpoints();

            // 5. Generated by Validation generator: the [Validator] classes of the test domain.
            Pragmatic.Integration.Tests.Domain.Validators.ValidatorRegistrationExtensions.AddGeneratedValidators(services);

            // This minimal host has no authorization middleware. Opt out of the secure-by-default root-group
            // RequireAuthorization (PragmaticEndpointsOptions.RequireAuthorizationByDefault is true by default)
            // so the root group doesn't throw "no middleware that supports authorization" — this pipeline
            // exercises actions/validation, not auth. (Registered last so it wins over any default options.)
            services.AddSingleton(new global::Pragmatic.Endpoints.Configuration.PragmaticEndpointsOptions
            {
                RequireAuthorizationByDefault = false
            });
        });

        builder.Configure(app =>
        {
            app.UseRouting();

            // Generated: maps all [Endpoint]-decorated classes to minimal API routes.
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapPragmaticEndpoints();
            });
        });
    }
}
