<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>EF Core integration for Pragmatic.Actions: database configuration for local boundaries.</Description>
    <PackageTags>ddd;domain;domain-action;efcore;boundary</PackageTags>
  </PropertyGroup>

  <!-- Core dependencies -->
  <ItemGroup>
    <ProjectReference Include="..\Pragmatic.Actions\Pragmatic.Actions.csproj" />
  </ItemGroup>

  <!-- Entity Framework Core -->
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>

</Project>
