// Tests for body DTO validation generation.
// The Validation SG predicts body DTOs that the Endpoints SG will generate,
// and produces ISyncValidator implementations for those body DTOs.
//
// Note: These tests verify the generated SOURCE TEXT is correct, not compilation.
// The generated partial record references properties that only exist in the other
// partial generated by the Endpoints SG (which doesn't run in these tests).

using Pragmatic.Testing.Assertions;
using Microsoft.CodeAnalysis;
using Pragmatic.Endpoints.Attributes;
using Pragmatic.SourceGen.Testing;
using Xunit;

namespace Pragmatic.Validation.Tests.Generator;

/// <summary>
///     Tests for endpoint body DTO validation generation.
/// </summary>
public class BodyDtoValidationGeneratorTests : ValidationGeneratorTestBase
{
    private static readonly MetadataReference[] EndpointReferences =
    [
        GeneratorTestHelper.FromType<EndpointAttribute>(),
        GeneratorTestHelper.FromTypeAssembly(typeof(Pragmatic.Endpoints.HttpVerb)),
        // ⚠️ The query attribute and the canonical grid request, so a [Query] in a test source resolves
        // to a symbol. Recognition is by symbol, as it is in QueryTransform, so an unresolved attribute
        // reads as "not a query" and the case would pass for the wrong reason.
        GeneratorTestHelper.FromTypeAssembly(typeof(Pragmatic.Persistence.Query.Adapters.GridFilterRequest))
    ];

    private static SourceGenRunResult RunBodyDtoGenerator(string source)
        => RunGenerator(source, EndpointReferences);

    [Fact]
    public void Endpoint_WithRequiredBodyProperties_GeneratesBodyDtoValidator()
    {
        var source = """
            using Pragmatic.Endpoints;
            using Pragmatic.Endpoints.Attributes;
            using Pragmatic.Validation.Attributes;

            namespace TestNs;

            [Endpoint(HttpVerb.Post, "/users")]
            public partial class CreateUserEndpoint
            {
                public required string FirstName { get; init; }
                public required string LastName { get; init; }
                public string? Email { get; init; }
            }
            """;

        var result = RunBodyDtoGenerator(source);

        var generated = GetGeneratedSource(result, "CreateUserEndpointBody.Validator");
        generated.Should().NotBeNull("body DTO validator should be generated");

        // Should generate ISyncValidator for the body DTO
        generated.Should().Contain("partial record CreateUserEndpointBody");
        generated.Should().Contain("ISyncValidator");
        generated.Should().Contain("Validate()");

        // Required string properties → validation checks
        generated.Should().Contain("FirstName");
        generated.Should().Contain("LastName");
    }

    [Fact]
    public void Endpoint_WithValidationAttributes_GeneratesBodyDtoValidator()
    {
        var source = """
            using Pragmatic.Endpoints;
            using Pragmatic.Endpoints.Attributes;
            using Pragmatic.Validation.Attributes;

            namespace TestNs;

            [Endpoint(HttpVerb.Post, "/orders")]
            public partial class CreateOrderEndpoint
            {
                [NotWhiteSpace]
                public string OrderNumber { get; init; } = "";

                [Range(0, 9999)]
                public decimal TotalAmount { get; init; }
            }
            """;

        var result = RunBodyDtoGenerator(source);

        var generated = GetGeneratedSource(result, "CreateOrderEndpointBody.Validator");
        generated.Should().NotBeNull("body DTO validator should be generated for validation attributes");

        generated.Should().Contain("partial record CreateOrderEndpointBody");
        generated.Should().Contain("OrderNumber");
        generated.Should().Contain("TotalAmount");
    }

    [Fact]
    public void Endpoint_WithNoBodyProperties_DoesNotGenerateValidator()
    {
        var source = """
            using System;
            using Pragmatic.Endpoints;
            using Pragmatic.Endpoints.Attributes;

            namespace TestNs;

            [Endpoint(HttpVerb.Get, "/users/{id}")]
            public partial class GetUserEndpoint
            {
                public Guid Id { get; init; }
            }
            """;

        var result = RunBodyDtoGenerator(source);

        // No body DTO → no validator
        var generated = GetGeneratedSource(result, "GetUserEndpointBody");
        generated.Should().BeNull("GET with only route params should not generate body DTO validator");
    }

    [Fact]
    public void Endpoint_WithNoValidation_DoesNotGenerateValidator()
    {
        var source = """
            using Pragmatic.Endpoints;
            using Pragmatic.Endpoints.Attributes;

            namespace TestNs;

            [Endpoint(HttpVerb.Post, "/items")]
            public partial class CreateItemEndpoint
            {
                public string Name { get; init; } = "";
                public int Quantity { get; init; }
            }
            """;

        var result = RunBodyDtoGenerator(source);

        // Body properties exist but no validation → no validator
        var generated = GetGeneratedSource(result, "CreateItemEndpointBody.Validator");
        generated.Should().BeNull("body properties without validation should not generate validator");
    }

    [Fact]
    public void Endpoint_WithRouteAndBodyProperties_ValidatesOnlyBodyProperties()
    {
        var source = """
            using System;
            using Pragmatic.Endpoints;
            using Pragmatic.Endpoints.Attributes;
            using Pragmatic.Validation.Attributes;

            namespace TestNs;

            [Endpoint(HttpVerb.Put, "/users/{id}")]
            public partial class UpdateUserEndpoint
            {
                public Guid Id { get; init; }

                [NotWhiteSpace]
                public required string Name { get; init; }

                [Email]
                public string? Email { get; init; }
            }
            """;

        var result = RunBodyDtoGenerator(source);

        var generated = GetGeneratedSource(result, "UpdateUserEndpointBody.Validator");
        generated.Should().NotBeNull("body DTO validator should be generated");

        // Should validate body properties
        generated.Should().Contain("Name");
        generated.Should().Contain("Email");

        // Should NOT validate route properties (Id is a route param from {id})
        generated.Should().NotContain("nameof(Id)");
    }

    /// <summary>A GET gets no body DTO, so it must get no validator for one either.</summary>
    /// <remarks>
    ///     <para>
    ///         An operation on GET binds from the query string and the Endpoints generator emits no body
    ///         envelope. This transform predicts that envelope independently, through a second copy of
    ///         the same decision — and when one copy changes without the other, the validator keeps
    ///         being generated, referring to properties of a type that does not exist.
    ///     </para>
    ///     <para>
    ///         ⚠️ The framework's own applications have no GET carrying validated properties, so only
    ///         this test sees the disagreement; an application would see it as a compile error in
    ///         generated code its author did not write. The comment beside the flag in the transform
    ///         describes this failure mode for a different input, which is what makes it worth a test
    ///         rather than another comment.
    ///     </para>
    /// </remarks>
    [Fact]
    public void GetEndpoint_WithValidatedProperties_GeneratesNoBodyValidator()
    {
        var source = """
            using Pragmatic.Endpoints;
            using Pragmatic.Endpoints.Attributes;
            using Pragmatic.Validation.Attributes;

            namespace TestNs;

            [Endpoint(HttpVerb.Get, "/reports")]
            public partial class ReadReportEndpoint
            {
                [Range(1, 100)]
                public int Page { get; init; }

                [Range(1, 200)]
                public int PageSize { get; init; }
            }
            """;

        var result = RunBodyDtoGenerator(source);

        GetGeneratedSource(result, "ReadReportEndpointBody.Validator").Should().BeNull(
            "a GET has no body DTO, so a validator for one refers to a type that does not exist");
    }

    /// <summary>⚠️ The control: the same properties on POST still get their validator.</summary>
    /// <remarks>
    ///     Without this, the assertion above would hold just as well on a transform that had stopped
    ///     generating body validators altogether — which would silently drop validation from every write
    ///     endpoint in the framework.
    /// </remarks>
    [Fact]
    public void PostEndpoint_WithTheSameProperties_StillGeneratesItsValidator()
    {
        var source = """
            using Pragmatic.Endpoints;
            using Pragmatic.Endpoints.Attributes;
            using Pragmatic.Validation.Attributes;

            namespace TestNs;

            [Endpoint(HttpVerb.Post, "/reports")]
            public partial class WriteReportEndpoint
            {
                [Range(1, 100)]
                public int Page { get; init; }

                [Range(1, 200)]
                public int PageSize { get; init; }
            }
            """;

        var result = RunBodyDtoGenerator(source);

        GetGeneratedSource(result, "WriteReportEndpointBody.Validator").Should().NotBeNull(
            "a POST carries a body, and its properties are validated as they always were");
    }

    /// <summary>A <c>[Query]</c> gets no body validator, because it gets no body record.</summary>
    /// <remarks>
    ///     ⚠️ This transform predicts the envelope the Endpoints feature will emit — the second copy of
    ///     "what is a body property", as the remark on <c>HasNonBodyBindingAttribute</c> says — so it
    ///     has to know about queries. A query never gets an envelope: its properties are filters and
    ///     paging, which travel in the query string, and the one thing it can carry in the body, a
    ///     canonical <c>GridFilterRequest</c>, is bound directly. A validator for it would be a
    ///     <c>partial record {Query}Body</c> whose other half nobody writes, and every property it named
    ///     would be <c>CS0103</c> inside a generated file.
    ///     <para>
    ///         ⚠️ <c>required</c> is what makes it visible: without a rule to carry, the transform
    ///         returns early on "nothing to validate" and the disagreement never reaches the compiler.
    ///         So an application meets it only when someone writes <c>required GridFilterRequest</c>.
    ///     </para>
    /// </remarks>
    [Fact]
    public void AQueryWithARequiredProperty_GetsNoBodyValidator()
    {
        var result = RunBodyDtoGenerator("""
            using System;
            using Pragmatic.Endpoints;
            using Pragmatic.Endpoints.Attributes;
            using Pragmatic.Persistence.Entity;
            using Pragmatic.Persistence.Query.Adapters;
            using Pragmatic.Persistence.Query.Attributes;

            namespace TestApp;

            public partial class Invoice : IEntity
            {
                public Guid PersistenceId { get; set; }
            }

            [Query<Invoice, Invoice>]
            [Endpoint(HttpVerb.Post, "api/invoices/grid")]
            public partial class InvoiceGridQuery
            {
                public required GridFilterRequest Request { get; init; }
            }
            """);

        GetGeneratedSource(result, "InvoiceGridQueryBody.Validator").Should().BeNull(
            "a query has no body record, so a validator for one names properties that do not exist");
    }

    /// <summary>
    ///     The control: the same shape on a <c>[DomainAction]</c> still gets its validator.
    /// </summary>
    /// <remarks>
    ///     Without it, "do not predict an envelope" is satisfied by never predicting one, which would
    ///     silently drop the validation of every action that carries a body — the thing this transform
    ///     exists to produce.
    /// </remarks>
    [Fact]
    public void AnActionWithTheSameShape_StillGetsOne()
    {
        var result = RunBodyDtoGenerator("""
            using System;
            using Pragmatic.Actions.Abstractions;
            using Pragmatic.Actions.Attributes;
            using Pragmatic.Endpoints;
            using Pragmatic.Endpoints.Attributes;
            using Pragmatic.Result;
            using System.Threading;
            using System.Threading.Tasks;

            namespace TestApp;

            public sealed class Payload { public string Name { get; init; } = ""; }

            [DomainAction]
            [Endpoint(HttpVerb.Post, "api/things")]
            public partial class CreateThingAction : DomainAction<int>
            {
                public required Payload Body { get; init; }
                public required string Note { get; init; }

                public override Task<Result<int, IError>> Execute(CancellationToken ct = default)
                    => Task.FromResult(Result<int, IError>.Success(0));
            }
            """);

        GetGeneratedSource(result, "CreateThingActionBody.Validator").Should().NotBeNull(
            "an action with a body envelope still has its rules validated");
    }
}
