namespace Pragmatic.Endpoints.Metadata;

/// <summary>
///     Assembly-level attribute that declares the full contract of a single endpoint.
///     Generated by the Endpoints source generator — one attribute per endpoint class.
/// </summary>
/// <remarks>
///     <para>
///         Where the assembly's <c>[PragmaticMetadata(MetadataCategory.Endpoints, …)]</c> document carries
///         the registration entry points, this attribute exposes the complete endpoint contract so that the
///         host SG and external tooling can reason about routes, error types, permissions, and response
///         shapes at compile time.
///     </para>
///     <para>
///         <see cref="ErrorTypes" /> and <see cref="ErrorStatusCodes" /> are parallel arrays:
///         <c>ErrorStatusCodes[i]</c> is the HTTP status code for <c>ErrorTypes[i]</c>.
///     </para>
/// </remarks>
/// <example>
///     <code>
/// // Generated per endpoint
/// [assembly: PragmaticEndpointContract(
///     EndpointType = typeof(global::MyApp.Endpoints.CreateOrderEndpoint),
///     HttpMethod = "POST",
///     Route = "/orders",
///     ResponseType = typeof(global::MyApp.Entities.OrderId),
///     SuccessStatusCode = 201,
///     ErrorTypes = new System.Type[] { typeof(global::MyApp.Errors.ValidationError) },
///     ErrorStatusCodes = new int[] { 400 },
///     RequiredPermissions = new string[] { "orders:write" },
///     Tags = new string[] { "orders" },
///     Summary = "Place a new order")]
/// </code>
/// </example>
[AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true)]
public sealed class PragmaticEndpointContractAttribute : Attribute
{
    /// <summary>The endpoint class type.</summary>
    public Type EndpointType { get; set; } = typeof(object);

    /// <summary>HTTP method in uppercase (e.g. "GET", "POST", "DELETE").</summary>
    public string HttpMethod { get; set; } = "GET";

    /// <summary>Route pattern (e.g. "/orders/{id}").</summary>
    public string Route { get; set; } = "/";

    /// <summary>
    ///     Response type for successful responses, or <c>null</c> when <see cref="IsVoid" /> is <c>true</c>.
    /// </summary>
    public Type? ResponseType { get; set; }

    /// <summary>Whether this endpoint returns no body (204 No Content).</summary>
    public bool IsVoid { get; set; }

    /// <summary>HTTP status code on success (e.g. 200, 201, 204).</summary>
    public int SuccessStatusCode { get; set; } = 200;

    /// <summary>
    ///     Error types this endpoint can produce.
    ///     Parallel to <see cref="ErrorStatusCodes" /> — <c>ErrorStatusCodes[i]</c> maps to <c>ErrorTypes[i]</c>.
    /// </summary>
    public Type[] ErrorTypes { get; set; } = [];

    /// <summary>
    ///     HTTP status codes for each error type.
    ///     Parallel to <see cref="ErrorTypes" /> — <c>ErrorStatusCodes[i]</c> maps to <c>ErrorTypes[i]</c>.
    /// </summary>
    public int[] ErrorStatusCodes { get; set; } = [];

    /// <summary>OpenAPI summary (short description).</summary>
    public string? Summary { get; set; }

    /// <summary>OpenAPI tags for grouping in API explorer.</summary>
    public string[] Tags { get; set; } = [];

    /// <summary>Permission strings required to call this endpoint.</summary>
    public string[] RequiredPermissions { get; set; } = [];

    /// <summary>Full route including group prefixes (e.g. "/api/orders/{id}").</summary>
    public string? FullRoute { get; set; }

    /// <summary>Operation name (endpoint Name or type name without suffix) — matches ApiRoutes members.</summary>
    public string? OperationName { get; set; }

    /// <summary>Boundary name — matches the ApiRoutes nested class.</summary>
    public string? Boundary { get; set; }

    /// <summary>Whether the endpoint accepts a JSON request body.</summary>
    public bool HasBody { get; set; }

    /// <summary>Whether the response is a paged list (PagedResult&lt;T&gt;).</summary>
    public bool IsPaged { get; set; }

    /// <summary>Whether the endpoint streams Server-Sent Events.</summary>
    public bool IsStreaming { get; set; }
}
