using Pragmatic.Testing.Assertions;
using Xunit;

namespace Pragmatic.Mapping.Tests.Generator;

/// <summary>
///     Snapshot tests for basic MappingSourceGenerator scenarios.
/// </summary>
public class BasicMappingGeneratorTests : MappingGeneratorTestBase
{
    // =========================================================================
    // Basic [MapFrom] Tests
    // =========================================================================

    [Fact]
    public void MapFrom_PositionalRecord_ConstructsViaPrimaryConstructor()
    {
        // A positional record has no parameterless ctor; the old object-initializer form
        // (new OrderLineDto { ... }) failed to compile (CS1729). FromEntity must call the primary ctor.
        var source = """
                     using Pragmatic.Mapping.Attributes;

                     namespace TestApp.Entities
                     {
                         public class OrderLine
                         {
                             public string Sku { get; set; } = "";
                             public int Quantity { get; set; }
                         }
                     }

                     namespace TestApp.Dtos
                     {
                         [MapFrom<TestApp.Entities.OrderLine>]
                         public partial record OrderLineDto(string Sku, int Quantity);
                     }
                     """;

        var result = RunGenerator(source);

        HasCompilationErrors(result).Should().BeFalse(
            string.Join(", ", GetCompilationErrors(result).Select(d => d.ToString())));

        var mapping = GetGeneratedSourcesAsDictionary(result)
            .First(kv => kv.Key.EndsWith("OrderLineDto.Mapping.g.cs")).Value;
        mapping.Should().Contain("new OrderLineDto(ctx.Sku, ctx.Quantity)")
            .And.NotContain("new OrderLineDto()");
    }

    /// <summary>
    ///     A DTO property named after a foreign key that <c>[Relation.*]</c> generates.
    /// </summary>
    /// <remarks>
    ///     The foreign key does not exist on the symbol during this pass, so the mapping resolved it
    ///     to nothing: PRAG0303, and the column dropped from the projection <i>silently</i> — the
    ///     client received an empty Guid. A consumer only noticed by reading the payload.
    /// </remarks>
    [Fact]
    public void MapFrom_RelationForeignKey_IsMappedNotDropped()
    {
        var source = """
                     using Pragmatic.Mapping.Attributes;
                     using Pragmatic.Persistence.Entity;

                     namespace TestApp.Entities
                     {
                         [Entity]
                         public partial class Supplier { public string Name { get; set; } = ""; }

                         [Entity]
                         [Relation.ManyToOne<Supplier>]
                         public partial class Assignment
                         {
                             public decimal Amount { get; set; }
                         }
                     }

                     namespace TestApp.Dtos
                     {
                         [MapFrom<TestApp.Entities.Assignment>]
                         public partial class AssignmentDto
                         {
                             public System.Guid SupplierId { get; set; }
                             public decimal Amount { get; set; }
                         }
                     }
                     """;

        var result = RunGenerator(source);

        GetGeneratorDiagnostics(result).Should().NotContain(d => d.Id == "PRAG0303",
            "SupplierId is generated by the relation, so it is not an unmapped property");

        var mapping = GetGeneratedSourcesAsDictionary(result)
            .First(kv => kv.Key.EndsWith("AssignmentDto.Mapping.g.cs")).Value;
        mapping.Should().Contain("SupplierId", "the foreign key belongs in the mapping, not dropped from it");
    }

    /// <summary>
    ///     A projection that flattens through a navigation <c>[Relation.*]</c> generates.
    /// </summary>
    /// <remarks>
    ///     The companion of the foreign-key case above: the navigation is generated too, so unless it is
    ///     predicted <c>WorkItem.Description</c> fails on its first segment and the property is dropped
    ///     without a diagnostic. Two things have to be true for this to work — the navigation has to be
    ///     predicted at all, and the path resolver has to be allowed to walk <i>through</i> it, although
    ///     it is generated.
    /// </remarks>
    [Fact]
    public void Projection_FlattensThroughGeneratedNavigation()
    {
        var source = """
                     using Pragmatic.Mapping.Attributes;
                     using Pragmatic.Persistence.Entity;

                     namespace TestApp.Entities
                     {
                         [Entity]
                         public partial class Worksite { public string Address { get; set; } = ""; }

                         [Entity]
                         [Relation.ManyToOne<Worksite>]
                         public partial class WorkItem { public string Description { get; set; } = ""; }

                         [Entity]
                         [Relation.ManyToOne<WorkItem>]
                         public partial class Assignment { public decimal Amount { get; set; } }
                     }

                     namespace TestApp.Dtos
                     {
                         [MapFrom<TestApp.Entities.Assignment>]
                         [GenerateProjection]
                         public partial class MyAssignmentDto
                         {
                             [MapProperty("WorkItem.Description")]
                             public string WorkItemDescription { get; set; } = "";

                             [MapProperty("WorkItem.Worksite.Address")]
                             public string WorksiteAddress { get; set; } = "";

                             public decimal Amount { get; set; }
                         }
                     }
                     """;

        var result = RunGenerator(source);

        // Deliberately not asserting on compilation: this harness runs the Mapping generator alone,
        // so the navigation the path walks through is never emitted and the generated projection
        // cannot compile here (CS1061 on WorkItem). What this test can prove is that the path
        // resolved instead of being dropped; that the result compiles and runs is proved by the
        // Showcase, where the whole generator runs against a real database.

        var mapping = GetGeneratedSourcesAsDictionary(result)
            .First(kv => kv.Key.EndsWith("MyAssignmentDto.Mapping.g.cs")).Value;

        mapping.Should().Contain("WorkItem.Description",
            "the first segment is a generated navigation, and the path has to walk into it");
        mapping.Should().Contain("WorkItem.Worksite.Address",
            "two generated navigations in one path: the resolver has to keep going past the first");
    }

    [Fact]
    public void MapTo_GeneratesWriteSideHooks()
    {
        var source = """
                     using Pragmatic.Mapping.Attributes;

                     namespace TestApp.Entities
                     {
                         public class Order { public string Description { get; set; } = ""; }
                     }
                     namespace TestApp.Dtos
                     {
                         [MapTo<TestApp.Entities.Order>]
                         public partial record UpdateOrderDto { public string Description { get; init; } = ""; }
                     }
                     """;

        var result = RunGenerator(source);
        HasCompilationErrors(result).Should().BeFalse(
            string.Join(", ", GetCompilationErrors(result).Select(d => d.ToString())));

        var mapping = GetGeneratedSourcesAsDictionary(result)
            .First(kv => kv.Key.EndsWith("UpdateOrderDto.Mapping.g.cs")).Value;

        // Write-side hooks, symmetric to the read-side BeforeMapping/CustomizeMapping.
        mapping.Should().Contain("BeforeToEntity(ref customResult);")
            .And.Contain("CustomizeToEntity(entity);")
            .And.Contain("CustomizeApplyTo(entity);")
            .And.Contain("partial void BeforeToEntity(ref global::TestApp.Entities.Order? result);")
            .And.Contain("partial void CustomizeToEntity(global::TestApp.Entities.Order entity);")
            .And.Contain("partial void CustomizeApplyTo(global::TestApp.Entities.Order entity);");
    }

    [Fact]
    public async Task MapFrom_SimpleRecord_GeneratesFromEntityMethod()
    {
        var source = """
                     using Pragmatic.Mapping.Attributes;

                     namespace TestApp.Entities
                     {
                         public class User
                         {
                             public int Id { get; set; }
                             public string Name { get; set; } = "";
                             public string Email { get; set; } = "";
                         }
                     }

                     namespace TestApp.Dtos
                     {
                         [MapFrom<TestApp.Entities.User>]
                         public partial record UserDto
                         {
                             public int Id { get; init; }
                             public string Name { get; init; } = "";
                             public string Email { get; init; } = "";
                         }
                     }
                     """;

        var result = RunGenerator(source);

        HasCompilationErrors(result).Should().BeFalse(
            string.Join(", ", GetCompilationErrors(result).Select(d => d.ToString())));

        var sources = GetGeneratedSourcesAsDictionary(result);
        // Hint names are namespace-qualified (VirtualFolderHints.ForType) — match by suffix.
        sources.Keys.Should().Contain(k => k.EndsWith("UserDto.Mapping.g.cs"));
        sources.Keys.Should().Contain(k => k.EndsWith("UserDto.Extensions.g.cs"));

        await Verify(sources);
    }

    [Fact]
    public async Task MapFrom_SimpleClass_GeneratesFromEntityMethod()
    {
        var source = """
                     using Pragmatic.Mapping.Attributes;

                     namespace TestApp.Entities
                     {
                         public class Product
                         {
                             public int Id { get; set; }
                             public string Name { get; set; } = "";
                             public decimal Price { get; set; }
                         }
                     }

                     namespace TestApp.Dtos
                     {
                         [MapFrom<TestApp.Entities.Product>]
                         public partial class ProductDto
                         {
                             public int Id { get; set; }
                             public string Name { get; set; } = "";
                             public decimal Price { get; set; }
                         }
                     }
                     """;

        var result = RunGenerator(source);

        HasCompilationErrors(result).Should().BeFalse(
            string.Join(", ", GetCompilationErrors(result).Select(d => d.ToString())));

        var sources = GetGeneratedSourcesAsDictionary(result);
        await Verify(sources);
    }

    // =========================================================================
    // Basic [MapTo] Tests
    // =========================================================================

    [Fact]
    public async Task MapTo_SimpleRecord_GeneratesToEntity()
    {
        var source = """
                     using Pragmatic.Mapping.Attributes;

                     namespace TestApp.Entities
                     {
                         public class Customer
                         {
                             public int Id { get; set; }
                             public string Name { get; set; } = "";
                             public string Phone { get; set; } = "";
                         }
                     }

                     namespace TestApp.Dtos
                     {
                         [MapTo<TestApp.Entities.Customer>]
                         public partial record CustomerDto
                         {
                             public int Id { get; init; }
                             public string Name { get; init; } = "";
                             public string Phone { get; init; } = "";
                         }
                     }
                     """;

        var result = RunGenerator(source);

        HasCompilationErrors(result).Should().BeFalse(
            string.Join(", ", GetCompilationErrors(result).Select(d => d.ToString())));

        var sources = GetGeneratedSourcesAsDictionary(result);
        sources.Keys.Should().Contain(k => k.EndsWith("CustomerDto.Mapping.g.cs"));

        await Verify(sources);
    }

    [Fact]
    public async Task MapTo_SimpleClass_GeneratesToEntity()
    {
        var source = """
                     using Pragmatic.Mapping.Attributes;

                     namespace TestApp.Entities
                     {
                         public class Employee
                         {
                             public int Id { get; set; }
                             public string FirstName { get; set; } = "";
                             public string LastName { get; set; } = "";
                             public decimal Salary { get; set; }
                         }
                     }

                     namespace TestApp.Dtos
                     {
                         [MapTo<TestApp.Entities.Employee>]
                         public partial class EmployeeDto
                         {
                             public int Id { get; set; }
                             public string FirstName { get; set; } = "";
                             public string LastName { get; set; } = "";
                             public decimal Salary { get; set; }
                         }
                     }
                     """;

        var result = RunGenerator(source);

        HasCompilationErrors(result).Should().BeFalse(
            string.Join(", ", GetCompilationErrors(result).Select(d => d.ToString())));

        var sources = GetGeneratedSourcesAsDictionary(result);
        sources.Keys.Should().Contain(k => k.EndsWith("EmployeeDto.Mapping.g.cs"));

        await Verify(sources);
    }

    // =========================================================================
    // [MapTo] + [Mutation] Integration Tests
    // =========================================================================

    [Fact]
    public void MapTo_WithPatchAttribute_SkipsApplyToGeneration()
    {
        var source = """
                     using Pragmatic.Mapping.Attributes;
                     using Pragmatic.Persistence.Patch;

                     namespace TestApp.Entities
                     {
                         public class Product
                         {
                             public int Id { get; set; }
                             public string Name { get; set; } = "";
                             public decimal Price { get; set; }
                         }
                     }

                     namespace TestApp.Dtos
                     {
                         // DTO has both [MapTo] and [Patch] - ApplyTo should NOT be generated by Mapping
                         // because Patch generator will handle update semantics
                         [MapTo<TestApp.Entities.Product>]
                         [Patch<TestApp.Entities.Product>]
                         public partial record UpdateProductDto
                         {
                             public string Name { get; init; } = "";
                             public decimal Price { get; init; }
                         }
                     }
                     """;

        var result = RunGenerator(source);

        HasCompilationErrors(result).Should().BeFalse(
            string.Join(", ", GetCompilationErrors(result).Select(d => d.ToString())));

        var mainSource = GetGeneratedSource(result, "UpdateProductDto.Mapping");
        mainSource.Should().NotBeNull();

        // Should have ToEntity (from [MapTo])
        mainSource.Should().Contain("ToEntity");

        // Should NOT have ApplyTo (because [Mutation] is present - Mutation generator handles this)
        mainSource.Should().NotContain("ApplyTo");
    }

    [Fact]
    public void MapTo_WithoutMutationAttribute_GeneratesApplyTo()
    {
        var source = """
                     using Pragmatic.Mapping.Attributes;

                     namespace TestApp.Entities
                     {
                         public class Product
                         {
                             public int Id { get; set; }
                             public string Name { get; set; } = "";
                             public decimal Price { get; set; }
                         }
                     }

                     namespace TestApp.Dtos
                     {
                         // DTO has only [MapTo] - ApplyTo SHOULD be generated
                         [MapTo<TestApp.Entities.Product>]
                         public partial record CreateProductDto
                         {
                             public string Name { get; init; } = "";
                             public decimal Price { get; init; }
                         }
                     }
                     """;

        var result = RunGenerator(source);

        HasCompilationErrors(result).Should().BeFalse(
            string.Join(", ", GetCompilationErrors(result).Select(d => d.ToString())));

        var mainSource = GetGeneratedSource(result, "CreateProductDto.Mapping");
        mainSource.Should().NotBeNull();

        // Should have ToEntity (from [MapTo])
        mainSource.Should().Contain("ToEntity");

        // Should have ApplyTo (because no [Mutation] attribute)
        mainSource.Should().Contain("ApplyTo");
    }

    // =========================================================================
    // Combined [MapFrom] + [MapTo] Tests
    // =========================================================================

    [Fact]
    public async Task MapFromAndMapTo_Combined_GeneratesAllMethods()
    {
        var source = """
                     using Pragmatic.Mapping.Attributes;

                     namespace TestApp.Entities
                     {
                         public class Order
                         {
                             public int Id { get; set; }
                             public string OrderNumber { get; set; } = "";
                             public decimal Total { get; set; }
                         }
                     }

                     namespace TestApp.Dtos
                     {
                         [MapFrom<TestApp.Entities.Order>]
                         [MapTo<TestApp.Entities.Order>]
                         public partial record OrderDto
                         {
                             public int Id { get; init; }
                             public string OrderNumber { get; init; } = "";
                             public decimal Total { get; init; }
                         }
                     }
                     """;

        var result = RunGenerator(source);

        HasCompilationErrors(result).Should().BeFalse(
            string.Join(", ", GetCompilationErrors(result).Select(d => d.ToString())));

        var sources = GetGeneratedSourcesAsDictionary(result);
        var mainSource = GetGeneratedSource(result, "OrderDto.Mapping");

        // Should have FromEntity (from [MapFrom])
        mainSource.Should().Contain("FromEntity");
        // Should have ToEntity (from [MapTo])
        mainSource.Should().Contain("ToEntity");

        await Verify(sources);
    }

    // =========================================================================
    // Flattening Convention Tests
    // =========================================================================

    [Fact]
    public async Task MapFrom_WithFlattening_GeneratesNestedPropertyAccess()
    {
        var source = """
                     using Pragmatic.Mapping.Attributes;

                     namespace TestApp.Entities
                     {
                         public class Address
                         {
                             public string Street { get; set; } = "";
                             public string City { get; set; } = "";
                             public string PostalCode { get; set; } = "";
                         }

                         public class Company
                         {
                             public int Id { get; set; }
                             public string Name { get; set; } = "";
                             public Address? Address { get; set; }
                         }
                     }

                     namespace TestApp.Dtos
                     {
                         [MapFrom<TestApp.Entities.Company>]
                         public partial record CompanyDto
                         {
                             public int Id { get; init; }
                             public string Name { get; init; } = "";
                             // Flattening: Address.City -> AddressCity
                             public string? AddressCity { get; init; }
                             public string? AddressStreet { get; init; }
                         }
                     }
                     """;

        var result = RunGenerator(source);

        HasCompilationErrors(result).Should().BeFalse(
            string.Join(", ", GetCompilationErrors(result).Select(d => d.ToString())));

        var mainSource = GetGeneratedSource(result, "CompanyDto.Mapping");
        // Should use safe navigation for nullable address
        mainSource.Should().Contain("entity.Address?.");

        var sources = GetGeneratedSourcesAsDictionary(result);
        await Verify(sources);
    }

    // =========================================================================
    // FullName Concatenation Convention Tests
    // =========================================================================

    [Fact]
    public async Task MapFrom_WithFullNameConvention_GeneratesConcatenation()
    {
        var source = """
                     using Pragmatic.Mapping.Attributes;

                     namespace TestApp.Entities
                     {
                         public class Person
                         {
                             public int Id { get; set; }
                             public string FirstName { get; set; } = "";
                             public string LastName { get; set; } = "";
                         }
                     }

                     namespace TestApp.Dtos
                     {
                         [MapFrom<TestApp.Entities.Person>]
                         public partial record PersonDto
                         {
                             public int Id { get; init; }
                             // Concatenation convention: FirstName + " " + LastName
                             public string FullName { get; init; } = "";
                         }
                     }
                     """;

        var result = RunGenerator(source);

        HasCompilationErrors(result).Should().BeFalse(
            string.Join(", ", GetCompilationErrors(result).Select(d => d.ToString())));

        var mainSource = GetGeneratedSource(result, "PersonDto.Mapping");
        // Should generate concatenation expression
        mainSource.Should().Contain("FirstName");
        mainSource.Should().Contain("LastName");

        var sources = GetGeneratedSourcesAsDictionary(result);
        await Verify(sources);
    }

    // =========================================================================
    // Non-Partial Type Tests (Diagnostic)
    // =========================================================================

    [Fact]
    public void MapFrom_NonPartialClass_DoesNotGenerate()
    {
        var source = """
                     using Pragmatic.Mapping.Attributes;

                     namespace TestApp.Entities
                     {
                         public class Item
                         {
                             public int Id { get; set; }
                         }
                     }

                     namespace TestApp.Dtos
                     {
                         // Missing 'partial' keyword - should not generate
                         [MapFrom<TestApp.Entities.Item>]
                         public class ItemDto
                         {
                             public int Id { get; set; }
                         }
                     }
                     """;

        var result = RunGenerator(source);

        var sources = GetGeneratedSourcesAsDictionary(result);
        sources.Keys.Should().NotContain(k => k.EndsWith("ItemDto.Mapping.g.cs"));
    }

    // =========================================================================
    // Struct Tests
    // =========================================================================

    [Fact]
    public async Task MapFrom_RecordStruct_GeneratesCorrectly()
    {
        var source = """
                     using Pragmatic.Mapping.Attributes;

                     namespace TestApp.Entities
                     {
                         public class Point
                         {
                             public int X { get; set; }
                             public int Y { get; set; }
                         }
                     }

                     namespace TestApp.Dtos
                     {
                         [MapFrom<TestApp.Entities.Point>]
                         public partial record struct PointDto(int X, int Y);
                     }
                     """;

        var result = RunGenerator(source);

        HasCompilationErrors(result).Should().BeFalse(
            string.Join(", ", GetCompilationErrors(result).Select(d => d.ToString())));

        var mainSource = GetGeneratedSource(result, "PointDto.Mapping");
        mainSource.Should().Contain("partial record struct PointDto");

        var sources = GetGeneratedSourcesAsDictionary(result);
        await Verify(sources);
    }

    [Fact]
    public async Task MapTo_RecordStruct_GeneratesToEntity()
    {
        var source = """
                     using Pragmatic.Mapping.Attributes;

                     namespace TestApp.Entities
                     {
                         public class Point
                         {
                             public int X { get; set; }
                             public int Y { get; set; }
                         }
                     }

                     namespace TestApp.Dtos
                     {
                         [MapTo<TestApp.Entities.Point>]
                         public partial record struct PointDto(int X, int Y);
                     }
                     """;

        var result = RunGenerator(source);

        HasCompilationErrors(result).Should().BeFalse(
            string.Join(", ", GetCompilationErrors(result).Select(d => d.ToString())));

        var mainSource = GetGeneratedSource(result, "PointDto.Mapping");
        mainSource.Should().Contain("partial record struct PointDto");
        mainSource.Should().Contain("ToEntity");

        var sources = GetGeneratedSourcesAsDictionary(result);
        await Verify(sources);
    }

    [Fact]
    public async Task MapFrom_RecordStruct_WithProjection_GeneratesProjection()
    {
        var source = """
                     using Pragmatic.Mapping.Attributes;

                     namespace TestApp.Entities
                     {
                         public class Point
                         {
                             public int X { get; set; }
                             public int Y { get; set; }
                         }
                     }

                     namespace TestApp.Dtos
                     {
                         [MapFrom<TestApp.Entities.Point>]
                         [GenerateProjection]
                         public partial record struct PointDto(int X, int Y);
                     }
                     """;

        var result = RunGenerator(source);

        HasCompilationErrors(result).Should().BeFalse(
            string.Join(", ", GetCompilationErrors(result).Select(d => d.ToString())));

        var mainSource = GetGeneratedSource(result, "PointDto.Mapping");
        mainSource.Should().Contain("partial record struct PointDto");
        mainSource.Should().Contain("Projection");
        mainSource.Should().Contain("Expression<");

        var sources = GetGeneratedSourcesAsDictionary(result);
        await Verify(sources);
    }
}