// =============================================================================
// Pragmatic.Design - Verify Helpers
// Helpers for snapshot testing with Verify.Xunit
// =============================================================================

using System.Runtime.CompilerServices;
using System.Text;
using System.Text.RegularExpressions;
using VerifyTests;

namespace Pragmatic.Testing;

/// <summary>
///     Configuration for Verify in Pragmatic.Design tests.
///     Call Initialize() once in your test assembly's ModuleInitializer.
/// </summary>
public static class VerifyConfiguration
{
    private static bool _initialized;

    // The attribution CSharpTemplate writes under "// <auto-generated/>" — three lines — and the tool
    // line that follows when the template names its generator ("// Pragmatic.SourceGenerator/Caching
    // v1.0.0"). Collapsed to the one stable marker the snapshots have always carried, so that a
    // wording change here does not invalidate every verified file in the repository. The tool line is
    // recognised only right after the attribution: on its own it is an ordinary comment.
    private static readonly Regex AttributionHeaderPattern = new(
        """^// Generated by Pragmatic\.Design, a framework by [^\r\n]*(?<nl>\r?\n)// https://pragmaticdesign\.net\r?\n// This file belongs to your project[^\r\n]*\r?\n(?<tool>// (?!Source: |Trigger: )[^\r\n]* v[^\r\n]*\r?\n)?""",
        RegexOptions.Multiline | RegexOptions.Compiled);

    // Entire "// Generated by <feature> v<version>" banner line. Collapsing the
    // whole line to a single stable marker means version bumps, feature-path
    // renames, or banner wording tweaks are all invisible to snapshots.
    // ⚠️ Not the attribution line, which also opens with "Generated by": the order the two scrubbers
    // run in is Verify's to decide, and taking the attribution for a banner leaves the rest of the
    // header behind in every snapshot.
    private static readonly Regex GeneratorBannerPattern = new(
        @"^// Generated by (?!Pragmatic\.Design, )[^\r\n]+",
        RegexOptions.Multiline | RegexOptions.Compiled);

    // Trailing version-like tokens that leak into non-banner comments or strings
    // (e.g. Trigger comments, attribute metadata). Scrubbed independently so
    // genuine code output stays comparable.
    private static readonly Regex InlineVersionPattern = new(
        @"\bv\d+\.\d+\.\d+(-[A-Za-z0-9\.-]+)?(\+[A-Za-z0-9\.-]+)?",
        RegexOptions.Compiled);

    // ISO-8601 date/time literals that show up when templates capture the
    // build clock (rare, but cheap to guard against).
    private static readonly Regex TimestampPattern = new(
        @"\b\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})?",
        RegexOptions.Compiled);

    /// <summary>
    ///     Initializes Verify configuration for consistent snapshot testing.
    /// </summary>
    [ModuleInitializer]
    public static void Initialize()
    {
        if (_initialized)
            return;
        _initialized = true;

        // Use strict scrubbing for consistent snapshots
        VerifierSettings.DontScrubDateTimes();
        VerifierSettings.DontScrubGuids();

        VerifierSettings.AddScrubber(sb =>
        {
            var text = sb.ToString();
            var scrubbed = AttributionHeaderPattern.Replace(text, m => m.Groups["tool"].Success
                ? "// Generated by Pragmatic.SourceGenerator" + m.Groups["nl"].Value
                : string.Empty);
            if (scrubbed == text)
                return;
            sb.Clear();
            sb.Append(scrubbed);
        });

        VerifierSettings.AddScrubber(sb => ApplyReplace(sb, GeneratorBannerPattern, "// Generated by Pragmatic.SourceGenerator"));
        VerifierSettings.AddScrubber(sb => ApplyReplace(sb, InlineVersionPattern, "v*"));
        VerifierSettings.AddScrubber(sb => ApplyReplace(sb, TimestampPattern, "<timestamp>"));
    }

    private static void ApplyReplace(StringBuilder sb, Regex pattern, string replacement)
    {
        var text = sb.ToString();
        var scrubbed = pattern.Replace(text, replacement);
        if (scrubbed == text)
            return;
        sb.Clear();
        sb.Append(scrubbed);
    }
}

/// <summary>
///     Extensions for working with generated source in snapshot tests.
/// </summary>
public static class VerifySourceExtensions
{
    /// <summary>
    ///     Prepares generated source for snapshot verification.
    ///     Normalizes line endings and removes noise.
    /// </summary>
    public static string NormalizeForSnapshot(this string source)
    {
        return source
            .Replace("\r\n", "\n")
            .Trim();
    }
}