<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ExcludeSharedTesting>true</ExcludeSharedTesting>
    <NoWarn>$(NoWarn);CA2007</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.CodeFix.Testing" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Pragmatic.SourceGenerator.Analyzers\Pragmatic.SourceGenerator.Analyzers.csproj" />
    <ProjectReference Include="..\..\src\Pragmatic.SourceGenerator.CodeFixers\Pragmatic.SourceGenerator.CodeFixers.csproj" />
  </ItemGroup>

</Project>
