using Pragmatic.Testing.Assertions;
using Pragmatic.Result.Http;
using Showcase.Billing.Entities;
using Showcase.Billing.Enums;
using Showcase.Booking.Entities;
using Showcase.Booking.Enums;
using Xunit;

namespace Showcase.Tests.Unit.Entities;

/// <summary>
/// Demonstrates concurrency conflict handling in Showcase domain entities.
///
/// Two layers of protection are in place:
/// 1. <b>Domain-level</b>: state machine guards prevent illegal transitions
///    (e.g., checking in an already-checked-in reservation).
/// 2. <b>DB-level</b>: <c>[ConcurrencyAware]</c> generates a <c>RowVersion</c> column
///    tracked by EF Core. When two concurrent requests load + update the same entity,
///    the second <c>SaveChangesAsync</c> throws <c>DbUpdateConcurrencyException</c>.
///
/// These tests cover the domain-level protection. The DB-level protection is tested via
/// integration tests using a real DB provider (SQLite/SQL Server) that enforces row versions.
/// </summary>
public class ConcurrencyDemoTests
{
    // ─── Domain-level: State machine prevents invalid transitions ────────────

    [Fact]
    public void Reservation_DoubleCheckIn_IsRejectedByStateMachine()
    {
        // Arrange: Confirmed reservation
        var reservation = CreateConfirmedReservation();

        // Act: First check-in succeeds (anemic: set audit field, then transition)
        reservation.SetCheckedInBy("agent1");
        var first = reservation.TransitionTo(ReservationStatus.CheckedIn);
        first.IsSuccess.Should().BeTrue();
        reservation.Status.Should().Be(ReservationStatus.CheckedIn);

        // Act: Simulated concurrent check-in (stale state — already checked in)
        var second = reservation.TransitionTo(ReservationStatus.CheckedIn);

        // Assert: State machine rejects the duplicate transition
        second.IsFailure.Should().BeTrue();
        second.Error.Should().BeOfType<ConflictError>()
            .Which.Reason.Should().Contain("Cannot transition");
    }

    [Fact]
    public void Reservation_CancelAfterCheckIn_IsRejectedByStateMachine()
    {
        // Demonstrates state machine's directional enforcement —
        // checked-in reservations cannot be cancelled.
        var reservation = CreateConfirmedReservation();
        reservation.SetCheckedInBy("agent1");
        reservation.TransitionTo(ReservationStatus.CheckedIn);

        var cancel = reservation.TransitionTo(ReservationStatus.Cancelled);

        cancel.IsFailure.Should().BeTrue();
        cancel.Error.Should().BeOfType<ConflictError>();
    }

    [Fact]
    public void Invoice_RefundWhenNotPaid_ReturnsConflictError()
    {
        // Refund is only valid on Paid invoices.
        // Demonstrates domain guard preventing invalid state transitions.
        var invoice = CreateDraftInvoice();

        // Anemic: the Paid-only guard is the state machine ([TransitionFrom(Paid)] on Refunded).
        invoice.SetRefundTransactionId("txn_12345");
        var result = invoice.TransitionTo(InvoiceStatus.Refunded);

        result.IsFailure.Should().BeTrue();
        result.Error.Should().BeOfType<ConflictError>()
            .Which.Reason.Should().Contain("Cannot transition");
    }

    [Fact]
    public void Invoice_RefundWhenPaid_Succeeds_AndRaisesEvent()
    {
        var invoice = CreateDraftInvoice();
        invoice.TransitionTo(InvoiceStatus.Paid);
        invoice.ClearDomainEvents();

        invoice.SetRefundTransactionId("stripe_refund_abc123");
        var result = invoice.TransitionTo(InvoiceStatus.Refunded);

        result.IsSuccess.Should().BeTrue();
        invoice.Status.Should().Be(InvoiceStatus.Refunded);
        invoice.DomainEvents.Should().ContainSingle()
            .Which.Should().BeOfType<Billing.Events.InvoiceRefunded>()
            .Which.RefundTransactionId.Should().Be("stripe_refund_abc123");
    }

    [Fact]
    public void Invoice_DoubleRefund_IsRejectedByDomainGuard()
    {
        // Once refunded, a second refund attempt fails.
        var invoice = CreateDraftInvoice();
        invoice.TransitionTo(InvoiceStatus.Paid);

        invoice.SetRefundTransactionId("stripe_refund_first");
        invoice.TransitionTo(InvoiceStatus.Refunded);
        invoice.SetRefundTransactionId("stripe_refund_second");
        var second = invoice.TransitionTo(InvoiceStatus.Refunded);

        second.IsFailure.Should().BeTrue();
    }

    // ─── [ConcurrencyAware] — DB-level protection via provider-specific strategy ────
    // PostgreSQL: xmin system column (shadow property, no entity property)
    // SQL Server: byte[] RowVersion (generated by SG)
    // SQLite/Generic: uint RowVersion (generated by SG)
    // Concurrency conflict detection is verified via integration tests with real DB.

    // ─── Helpers ─────────────────────────────────────────────────────────────

    private static Reservation CreatePendingReservation() =>
        Reservation.Create(
            Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(),
            DateTimeOffset.UtcNow.AddDays(1), DateTimeOffset.UtcNow.AddDays(3),
            2, 300m, "EUR");

    private static Reservation CreateConfirmedReservation()
    {
        var r = CreatePendingReservation();
        r.TransitionTo(ReservationStatus.Confirmed);
        r.ClearDomainEvents();
        return r;
    }

    private static Invoice CreateDraftInvoice()
    {
        var invoice = new Invoice();
        invoice.SetInvoiceNumber("INV-202602-00001");
        invoice.SetReservationId(Guid.NewGuid());
        invoice.SetGuestId(Guid.NewGuid());
        invoice.SetSubTotal(500m);
        invoice.SetTaxAmount(100m);
        invoice.SetTotalAmount(600m);
        invoice.SetCurrency("EUR");
        invoice.SetStatus(InvoiceStatus.Draft);
        invoice.SetIssuedAt(DateTimeOffset.UtcNow);
        return invoice;
    }
}
