using Pragmatic.Documents.Spreadsheet;
using Pragmatic.Documents.Xlsx;

namespace Pragmatic.Documents.Xlsx.Samples.Samples;

/// <summary>
///     Multi-sheet workbook: a raw data sheet, a summary sheet, and a metadata
///     sheet in a single file. Sheet name appears on the bottom tab in Excel.
/// </summary>
public static class MultipleSheetsSample
{
    public static void Run(string outputDir)
    {
        Console.WriteLine("--- Multiple sheets in one workbook ---");

        var model = new SpreadsheetBuilder()
            .Title("Q1 2026 report")
            .Author("Pragmatic.Design")
            .Sheet("Raw data", s => s
                .HeaderRow("Date", "Channel", "Orders", "Revenue")
                .Row(new DateTime(2026, 1, 14), "web",    142,  18_530.00)
                .Row(new DateTime(2026, 1, 14), "mobile",  89,  11_340.00)
                .Row(new DateTime(2026, 2,  3), "web",    198,  25_770.50)
                .Row(new DateTime(2026, 2,  3), "mobile", 112,  14_490.20)
                .Row(new DateTime(2026, 3, 27), "web",    255,  33_210.00)
                .Row(new DateTime(2026, 3, 27), "mobile", 171,  22_120.75))
            .Sheet("Summary", s => s
                .HeaderRow("Channel", "Total orders", "Total revenue")
                .Row("web",    595, 77_510.50)
                .Row("mobile", 372, 47_950.95))
            .Sheet("Metadata", s => s
                .HeaderRow("Key", "Value")
                .Row("Report period",   "Q1 2026")
                .Row("Generated by",    "Pragmatic.Design preview.0")
                .Row("Generated at",    DateTime.UtcNow.ToString("u"))
                .Row("Data source",     "orders.db (snapshot)"))
            .Build();

        var bytes = XlsxRenderer.Render(model);
        var path = Path.Combine(outputDir, "q1-report.xlsx");
        File.WriteAllBytes(path, bytes);
        Console.WriteLine($"  q1-report.xlsx         {bytes.Length} bytes (3 sheets)");
        Console.WriteLine();
    }
}
