using Pragmatic.Testing.Assertions;
using Xunit;

namespace Pragmatic.Actions.Tests.Generator;

/// <summary>
///     An action or mutation that injects an <c>ILogger&lt;T&gt;</c>, which the invoker base also has.
/// </summary>
/// <remarks>
///     <para>
///         The generated invoker holds each dependency in a field. The name <c>_logger</c> is already
///         taken by <c>ActionInvokerBase</c>, so a generated field named after the author's would hide
///         the base's: CS0108, in a file the author did not write, and an error wherever warnings are
///         errors.
///     </para>
///     <para>
///         No other action in this repository injects a logger, so outside these tests the shape is
///         reachable by any user and generated by no test.
///     </para>
/// </remarks>
public class InjectedLoggerTests : ActionsGeneratorTestBase
{
    private const string Source = """
        using System;
        using System.Threading;
        using System.Threading.Tasks;
        using Microsoft.Extensions.Logging;
        using Pragmatic.Actions.Abstractions;
        using Pragmatic.Actions.Attributes;
        using Pragmatic.Actions.Mutation;
        using Pragmatic.Persistence.Entity;
        using Pragmatic.Result;

        namespace TestApp.Sales;

        public partial class Note : IEntity
        {
            public Guid PersistenceId { get; set; }
        }

        [Mutation(Mode = MutationMode.Create)]
        public partial class CreateNoteMutation : Mutation<Note>
        {
            private ILogger<CreateNoteMutation> _logger = null!;

            public required string Text { get; init; }
        }

        [DomainAction]
        public partial class WriteNoteAction : VoidDomainAction
        {
            private ILogger<WriteNoteAction> _logger = null!;

            public override Task<VoidResult<IError>> Execute(CancellationToken ct = default)
                => Task.FromResult(VoidResult<IError>.Success());
        }
        """;

    /// <summary>
    ///     The author's field keeps its name; only the invoker's holder is renamed.
    /// </summary>
    [Fact]
    public void AnActionInjectingALogger_DoesNotHideTheBaseField()
    {
        var generated = GetGeneratedSource(RunGeneratorWithEntities(Source), "WriteNoteAction.Invoker");

        generated.Should().NotBeNull();
        generated!.Should().NotContain("> _logger;",
            "declaring _logger over the base's is CS0108 — a warning inside generated code");
        generated.Should().Contain("_loggerDependency");
    }

    [Fact]
    public void AMutationInjectingALogger_DoesNotHideTheBaseField()
    {
        var generated = GetGeneratedSource(
            RunGeneratorWithEntities(Source), "CreateNoteMutation.MutationInvoker");

        generated.Should().NotBeNull();
        generated!.Should().NotContain("> _logger;");
    }

    /// <summary>
    ///     And the renamed field still reaches the action: a silenced warning that broke injection
    ///     would be the worse outcome.
    /// </summary>
    [Fact]
    public void TheRenamedField_IsStillWhatIsInjected()
    {
        GetGeneratedSource(RunGeneratorWithEntities(Source), "WriteNoteAction.Invoker")!
            .Should().Contain("action.SetDependencies(_loggerDependency)");
    }
}
