using System.Collections.Immutable;
using Pragmatic.Testing.Assertions;
using Pragmatic.SourceGenerator.Features.Persistence.Models;
using Pragmatic.SourceGenerator.Features.Persistence.Templates;
using Xunit;

namespace Pragmatic.Persistence.EFCore.Tests.Templates;

/// <summary>
///     Tests for the EntityCreateTemplate which generates static Create factory methods on entities.
/// </summary>
public class EntityCreateTemplateTests
{
    [Fact]
    public void SimpleEntity_GeneratesCreateMethod()
    {
        // Arrange
        var model = CreateBasicModel();

        // Act
        var template = new EntityCreateTemplate(model);
        var artifact = template.RenderOutput();

        // Assert
        artifact.IsEmpty.Should().BeFalse();
        var source = artifact.Text;

        source.Should().Contain("static");
        source.Should().Contain("Create");
    }

    [Fact]
    public void SimpleEntity_GeneratesPartialClass()
    {
        // Arrange
        var model = CreateBasicModel();

        // Act
        var template = new EntityCreateTemplate(model);
        var artifact = template.RenderOutput();

        // Assert
        var source = artifact.Text;

        source.Should().Contain("partial class Order");
    }

    [Fact]
    public void Entity_WithRequiredProperties_IncludesParameters()
    {
        // Arrange
        var model = CreateBasicModel() with
        {
            Properties = ImmutableArray.Create(
                new PropertyMetadataModel
                {
                    Name = "CustomerName",
                    TypeName = "string",
                    IsRequiredForCreate = true
                },
                new PropertyMetadataModel
                {
                    Name = "Amount",
                    TypeName = "decimal",
                    IsRequiredForCreate = true
                }
            )
        };

        // Act
        var template = new EntityCreateTemplate(model);
        var artifact = template.RenderOutput();

        // Assert
        var source = artifact.Text;

        source.Should().Contain("customerName");
        source.Should().Contain("amount");
    }

    [Fact]
    public void Entity_WithNoRequiredProperties_GeneratesParameterlessCreate()
    {
        // Arrange
        var model = CreateBasicModel() with
        {
            Properties = ImmutableArray<PropertyMetadataModel>.Empty
        };

        // Act
        var template = new EntityCreateTemplate(model);
        var artifact = template.RenderOutput();

        // Assert
        var source = artifact.Text;

        source.Should().Contain("Create()");
    }

    [Fact]
    public void Entity_WithGuidId_GeneratesGuid7Assignment()
    {
        // Arrange
        var model = CreateBasicModel() with
        {
            IdType = "System.Guid"
        };

        // Act
        var template = new EntityCreateTemplate(model);
        var artifact = template.RenderOutput();

        // Assert
        var source = artifact.Text;

        source.Should().Contain("Guid.CreateVersion7()");
    }

    [Fact]
    public void SimpleEntity_GeneratesCorrectNamespace()
    {
        // Arrange
        var model = CreateBasicModel();

        // Act
        var template = new EntityCreateTemplate(model);
        var artifact = template.RenderOutput();

        // Assert
        var source = artifact.Text;

        source.Should().Contain("namespace MyApp.Sales.Entities;");
    }

    [Fact]
    public void SimpleEntity_GeneratesCorrectHintName()
    {
        // Arrange
        var model = CreateBasicModel();

        // Act
        var template = new EntityCreateTemplate(model);
        var artifact = template.RenderOutput();

        // Assert
        artifact.HintName.Should().Contain("Order");
        artifact.HintName.Should().Contain("Create");
        artifact.HintName.Should().EndWith(".g.cs");
    }

    [Fact]
    public void SimpleEntity_GeneratesAutoGeneratedHeader()
    {
        // Arrange
        var model = CreateBasicModel();

        // Act
        var template = new EntityCreateTemplate(model);
        var artifact = template.RenderOutput();

        // Assert
        var source = artifact.Text;

        source.Should().Contain("<auto-generated");
    }

    [Fact]
    public void InvalidModel_ReturnsEmptySource()
    {
        // Arrange
        var model = CreateBasicModel() with { IsValid = false };

        // Act
        var template = new EntityCreateTemplate(model);
        var artifact = template.RenderOutput();

        // Assert
        artifact.Text.Should().BeEmpty();
    }

    [Fact]
    public void Entity_WithNullableProperty_ExcludesFromCreate()
    {
        // Arrange
        var model = CreateBasicModel() with
        {
            Properties = ImmutableArray.Create(
                new PropertyMetadataModel
                {
                    Name = "CustomerName",
                    TypeName = "string",
                    IsRequiredForCreate = true
                },
                new PropertyMetadataModel
                {
                    Name = "Notes",
                    TypeName = "string?",
                    IsNullable = true,
                    IsRequiredForCreate = false
                }
            )
        };

        // Act
        var template = new EntityCreateTemplate(model);
        var artifact = template.RenderOutput();

        // Assert
        var source = artifact.Text;

        source.Should().Contain("customerName");
        source.Should().NotContain("notes");
    }

    [Fact]
    public void Entity_WithDefaultValueProperty_ExcludesFromCreate()
    {
        // Arrange
        var model = CreateBasicModel() with
        {
            Properties = ImmutableArray.Create(
                new PropertyMetadataModel
                {
                    Name = "Status",
                    TypeName = "int",
                    HasDefaultValue = true,
                    IsRequiredForCreate = false
                },
                new PropertyMetadataModel
                {
                    Name = "Name",
                    TypeName = "string",
                    IsRequiredForCreate = true
                }
            )
        };

        // Act
        var template = new EntityCreateTemplate(model);
        var artifact = template.RenderOutput();

        // Assert
        var source = artifact.Text;

        source.Should().Contain("name");
    }

    [Fact]
    public void Entity_WithAuditableFlag_GeneratesAuditFields()
    {
        // Arrange
        var model = CreateBasicModel() with { IsAuditable = true };

        // Act
        var template = new EntityCreateTemplate(model);
        var artifact = template.RenderOutput();

        // Assert
        var source = artifact.Text;

        source.Should().Contain("CreatedAt");
        source.Should().Contain("UpdatedAt");
    }

    [Fact]
    public void Entity_WithSoftDelete_GeneratesIsDeletedFalse()
    {
        // Arrange
        var model = CreateBasicModel() with { IsSoftDelete = true };

        // Act
        var template = new EntityCreateTemplate(model);
        var artifact = template.RenderOutput();

        // Assert
        var source = artifact.Text;

        source.Should().Contain("IsDeleted");
        source.Should().Contain("false");
    }

    [Fact]
    public void RealisticScenario_OrderEntity()
    {
        // Arrange - Full order entity with multiple properties
        var model = new EntityMetadataModel
        {
            TypeName = "Order",
            FullTypeName = "Contoso.Sales.Entities.Order",
            Namespace = "Contoso.Sales.Entities",
            IdType = "System.Guid",
            IsAuditable = true,
            IsSoftDelete = true,
            Properties = ImmutableArray.Create(
                new PropertyMetadataModel
                {
                    Name = "OrderNumber",
                    TypeName = "string",
                    IsRequiredForCreate = true
                },
                new PropertyMetadataModel
                {
                    Name = "CustomerId",
                    TypeName = "System.Guid",
                    IsRequiredForCreate = true
                },
                new PropertyMetadataModel
                {
                    Name = "TotalAmount",
                    TypeName = "decimal",
                    IsRequiredForCreate = true
                },
                new PropertyMetadataModel
                {
                    Name = "Notes",
                    TypeName = "string?",
                    IsNullable = true,
                    IsRequiredForCreate = false
                }
            )
        };

        // Act
        var template = new EntityCreateTemplate(model);
        var artifact = template.RenderOutput();

        // Assert
        var source = artifact.Text;

        source.Should().Contain("namespace Contoso.Sales.Entities;");
        source.Should().Contain("partial class Order");
        source.Should().Contain("Create");
        source.Should().Contain("orderNumber");
        source.Should().Contain("customerId");
        source.Should().Contain("totalAmount");
        source.Should().Contain("Guid.CreateVersion7()");
        source.Should().Contain("CreatedAt");
        source.Should().Contain("IsDeleted");
    }

    private static EntityMetadataModel CreateBasicModel()
    {
        return new EntityMetadataModel
        {
            TypeName = "Order",
            FullTypeName = "MyApp.Sales.Entities.Order",
            Namespace = "MyApp.Sales.Entities",
            IdType = "System.Guid",
            Properties = ImmutableArray.Create(
                new PropertyMetadataModel
                {
                    Name = "OrderNumber",
                    TypeName = "string",
                    IsRequiredForCreate = true
                }
            )
        };
    }
}
