<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" VersionOverride="4.12.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Pragmatic.Client\Pragmatic.Client.csproj" />
    <ProjectReference Include="..\..\src\Pragmatic.Client.SourceGenerator\Pragmatic.Client.SourceGenerator.csproj" />
    <ProjectReference Include="..\..\src\Pragmatic.Client.Cli\Pragmatic.Client.Cli.csproj" />
    <ProjectReference Include="..\..\..\Pragmatic.Result\src\Pragmatic.Result\Pragmatic.Result.csproj" />
    <ProjectReference Include="..\..\..\Pragmatic.Abstractions\src\Pragmatic.Abstractions\Pragmatic.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\samples\Pragmatic.Client.Samples\PragmaticManifest.json"
          Link="Fixtures\PragmaticManifest.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
