<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Batch processing for Pragmatic.Messaging. Scatter/gather pattern, automatic progress tracking, rate limiting.</Description>
    <PackageTags>messaging;batch;scatter-gather;bulk;processing</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Pragmatic.Messaging.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pragmatic.Messaging.Core\Pragmatic.Messaging.Core.csproj" />
    <ProjectReference Include="..\Pragmatic.Messaging.Saga\Pragmatic.Messaging.Saga.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

</Project>
