namespace Pragmatic.Persistence.Entity;

/// <summary>
///     Declares the entity's domain key: the value, or the set of values, the domain identifies a row by.
/// </summary>
/// <remarks>
///     <para>
///         The key gets a unique index in the database, a <c>GetBy{A}And{B}Async(a, b)</c> lookup on the
///         repository and a specification. Two forms, for one key:
///         <list type="bullet">
///             <item>
///                 <description>
///                     on a <b>property</b>, one attribute per part — the usual form when every part is a
///                     property the class declares;
///                 </description>
///             </item>
///             <item>
///                 <description>
///                     on the <b>class</b>, naming the parts in order — the only form that can include a
///                     foreign key, because a relation's key is generated and no attribute can sit on a
///                     member the class does not have.
///                 </description>
///             </item>
///         </list>
///         One entity uses one form: both at once is <c>PRAG0637</c>, and a name on the class that is
///         neither a property nor a generated key is <c>PRAG0636</c>.
///     </para>
///     <example>
///         <code>
/// [Entity]
/// public partial class Order : IEntity
/// {
///     [LogicKey]
///     public string OrderNumber { get; private set; } = "";   // → GetByOrderNumberAsync(orderNumber)
/// }
///
/// [Entity]
/// [LogicKey(nameof(ExternalId), "WorkspaceId", Scope = UniquenessScope.Global)]
/// public partial class Member : IEntity        // WorkspaceId is generated by Workspace's [Relation.OneToMany&lt;Member&gt;]
/// {
///     public string ExternalId { get; private set; } = "";
/// }
/// </code>
///     </example>
/// </remarks>
[AttributeUsage(AttributeTargets.Property | AttributeTargets.Class)]
public sealed class LogicKeyAttribute : Attribute
{
    /// <summary>Marks the property it sits on as a part of the key.</summary>
    public LogicKeyAttribute()
    {
        PropertyNames = [];
    }

    /// <summary>
    ///     Declares the whole key on the class, naming its parts in the order they take in the index and
    ///     in the generated lookup's parameter list.
    /// </summary>
    /// <param name="propertyNames">
    ///     The parts: properties the class declares, or keys a <c>[Relation.*]</c> generates on it. Use
    ///     <c>nameof</c> where the member exists in source; a generated key has no symbol to name, so it
    ///     is a string — and a string that matches nothing is <c>PRAG0636</c> rather than an index that
    ///     quietly never gets created.
    /// </param>
    public LogicKeyAttribute(params string[] propertyNames)
    {
        PropertyNames = propertyNames;
    }

    /// <summary>The parts named on the class, in order; empty for the property form.</summary>
    public string[] PropertyNames { get; }

    /// <summary>
    ///     Where this property sits in a composite key. Lower first; equal values keep the order the
    ///     properties are declared in. Ignored on the class form, where the order is the order written.
    /// </summary>
    /// <remarks>
    ///     <para>
    ///         Position is not cosmetic in a composite key. It decides the column order of the unique
    ///         index — so which column is the leading one, the only one the index can be searched by on
    ///         its own — and the parameter order of the generated
    ///         <c>GetBy{A}And{B}Async(a, b)</c>. With two strings, both are silent when they are wrong.
    ///     </para>
    ///     <para>
    ///         Left unset on every part, the order is the order the properties appear in the class,
    ///         which is what the generator has always used and what every existing entity's index
    ///         reflects. That coupling is the reason this exists: moving a property up or down in the
    ///         file is otherwise a schema change and a signature change at once, with a green build.
    ///     </para>
    ///     <example>
    ///         <code>
    /// [LogicKey(Order = 1)] public string CountryCode { get; private set; } = "";
    /// [LogicKey(Order = 2)] public string Vat { get; private set; } = "";
    /// // → index on (CountryCode, Vat), GetByCountryCodeAndVatAsync(countryCode, vat)
    /// </code>
    ///     </example>
    /// </remarks>
    public int Order { get; set; }

    /// <summary>
    ///     How far the key has to be unique. Only meaningful on an entity that implements
    ///     <c>ITenantEntity</c>; everywhere else there is one scope and this changes nothing.
    /// </summary>
    /// <remarks>
    ///     <para>
    ///         ⚠️ <b>Per-tenant is the default.</b> A unique index covering the marked columns and
    ///         nothing else would, on a tenant-scoped entity, reach across every tenant: one workspace
    ///         granting a role a permission would stop the next one from granting the same pair, with a
    ///         conflict that names nothing — and tell the second workspace that somebody already holds
    ///         that value.
    ///     </para>
    ///     <para>
    ///         Set <see cref="UniquenessScope.Global" /> for the values that identify the same thing to
    ///         everyone — a national tax number, an externally issued code — where a duplicate in a
    ///         second tenant is the same mistake as a duplicate in the first.
    ///     </para>
    ///     <para>
    ///         On a composite key the parts have to agree: declaring one part global and another
    ///         per-tenant is <c>PRAG0625</c>, since an index has one scope and the parts are describing
    ///         the same index. On the class form there is one attribute, so one scope.
    ///     </para>
    /// </remarks>
    public UniquenessScope Scope { get; set; } = UniquenessScope.PerTenant;
}
