namespace Pragmatic.Persistence.EFCore;

/// <summary>
///     Marks a DbContext as auto-generated by Pragmatic.Persistence.EFCore.
///     Applied by the source generator to BoundaryDbContext and MigrationDbContext classes.
/// </summary>
[AttributeUsage(AttributeTargets.Class, Inherited = false)]
public sealed class PragmaticDbContextAttribute : Attribute
{
    /// <summary>
    ///     Creates a new <see cref="PragmaticDbContextAttribute"/>.
    /// </summary>
    /// <param name="boundaryName">The boundary name this DbContext belongs to, or "Migration" for the migration context.</param>
    public PragmaticDbContextAttribute(string boundaryName) => BoundaryName = boundaryName;

    /// <summary>
    ///     The boundary name this DbContext belongs to (e.g., "Catalog", "Booking").
    ///     "Migration" for the aggregated migration context.
    /// </summary>
    public string BoundaryName { get; }
}
