namespace Pragmatic.Endpoints.Extensions;

// Note: MapPragmaticEndpoints and AddPragmaticEndpoints extension methods
// are generated by Pragmatic.Endpoints.SourceGenerator.
// See the generated PragmaticEndpointsRegistrationExtensions class.