using System.Linq.Expressions;
using Pragmatic.Persistence.EFCore.Query.Visitors;
using Pragmatic.Persistence.Query.Filters;

namespace Pragmatic.Persistence.EFCore.Query;

/// <summary>
///     Composes the final <see cref="FilterMap"/> from:
///     1. Static SG-generated filters (via a static map factory delegate)
///     2. Dynamic visibility filters (via <see cref="IVisibilityFilterProvider"/> instances)
///     3. Respects <see cref="IQueryFilterToggle"/> for scoped disable/mode
/// </summary>
/// <remarks>
///     <para>
///         The composer is registered as scoped because it depends on the current
///         <see cref="IQueryFilterToggle"/> state and <see cref="IVisibilityFilterProvider"/> results.
///     </para>
///     <para>
///         The static map factory delegate is the <c>FilterMapRegistry.CreateForContext</c>
///         method generated by the SG. It is injected as a delegate to avoid coupling with
///         the generated type name.
///     </para>
/// </remarks>
public sealed class FilterMapComposer
{
    private readonly IQueryFilterToggle _filterToggle;
    private readonly IVisibilityFilterProvider[] _visibilityProviders;

    /// <summary>
    ///     One factory per module, merged rather than raced.
    /// </summary>
    /// <remarks>
    ///     Every module generates its own <c>FilterMapRegistry</c> and registers the factory for it.
    ///     With a single factory registered through <c>TryAdd</c>, the first module to register would
    ///     win: in a three-module application the static map in the container would be one module's,
    ///     and the other two modules' entities would have no navigation filters at all — soft-delete
    ///     would reach a collection in the winning module and nothing in the others.
    /// </remarks>
    private readonly Func<FilterContext, FilterMap>[] _staticMapFactories;

    /// <summary>Creates the composer over every module's map factory.</summary>
    public FilterMapComposer(
        IQueryFilterToggle filterToggle,
        IEnumerable<IVisibilityFilterProvider> visibilityProviders,
        IEnumerable<Func<FilterContext, FilterMap>>? staticMapFactories = null)
    {
        _filterToggle = filterToggle;
        _visibilityProviders = visibilityProviders as IVisibilityFilterProvider[]
                               ?? visibilityProviders.ToArray();
        _staticMapFactories = staticMapFactories is null
            ? []
            : staticMapFactories as Func<FilterContext, FilterMap>[] ?? [.. staticMapFactories];
    }

    // No single-factory overload. One existed for a moment and made the two constructors ambiguous to
    // the container, which failed every service that reaches a repository — 533 of 548 Showcase tests,
    // caught by ValidateOnBuild at startup. A caller with one factory passes an array with one in it.

    // Per-scope cache: avoids recomputing static map for the same context within a scope.
    // The (context, map) pair is read/written together under _cacheLock so a concurrent caller
    // (e.g. parallel queries sharing the scope) never observes a map paired with the wrong context.
    private readonly Lock _cacheLock = new();
    private FilterContext? _cachedContext;
    private FilterMap? _cachedStaticMap;

    // Materialize once to avoid multiple enumeration

    /// <summary>
    ///     Builds the composed <see cref="FilterMap"/> for the current context: the one for a collection
    ///     loaded with its entity (<see cref="FilterScope.Collections" />).
    /// </summary>
    public FilterMap Compose(FilterContext context) => Compose(context, FilterScope.Collections);

    /// <summary>
    ///     Builds the composed <see cref="FilterMap"/> for a collection read in
    ///     <paramref name="position" />.
    /// </summary>
    /// <remarks>
    ///     The static half does not vary with the position: soft-delete, tenant and validity are
    ///     generated with no scope to consult, and a row they hide is hidden wherever it is read. What
    ///     varies is the dynamic half, whose filters each declare a <see cref="IQueryFilter.Scope" />.
    /// </remarks>
    public FilterMap Compose(FilterContext context, FilterScope position)
    {
        // If all filters are disabled, return empty
        if (_filterToggle.AllDisabled)
            return FilterMap.Empty;

        // Start with static SG-generated filters (cached per-scope if context matches)
        var map = GetOrCreateStaticMap(context);

        // Merge dynamic filters, unless the mode lifts them wholesale. The gate stays because it is a
        // safety net for a provider that ignores the context it is handed — the one this is tested
        // with does exactly that.
        //
        // ⚠️ It costs an asymmetry, and it is deliberate rather than overlooked: a VisibilityRule
        // carries no marker interface, so DefaultQueryFilterProvider keeps applying it at the root in
        // Admin while this drops it from navigations in the same query. Root and navigation disagree
        // about what Admin means, because FilterContext gives one expression (Mode >= Admin) two
        // names — SkipVisibility and SkipPermissionBased — and the root only honours the second.
        // Settling that is a decision about what Admin is for, not something to fix by loosening this.
        if (!context.SkipVisibility)
        {
            foreach (var provider in _visibilityProviders)
            {
                var dynamicFilters = provider.GetFilters(context, position);
                if (dynamicFilters.Count > 0)
                    map = map.Merge(dynamicFilters);
            }
        }

        // Remove disabled filter types — WithoutTypes preserves the surviving types'
        // pre-resolved WhereMethods (rebuilding the map here would drop them, pushing
        // the visitor onto its reflection fallback).
        if (context.DisabledFilters.Count > 0)
            map = map.WithoutTypes(context.DisabledFilters);

        return map;
    }

    /// <summary>
    ///     Creates a <see cref="PragmaticQueryFilterVisitor"/> for the current context
    ///     and applies it to the given expression.
    /// </summary>
    public Expression ApplyVisitor(Expression expression, FilterContext context)
    {
        // One map per position a collection can be read in: a filter's scope may leave one out.
        var included = Compose(context, FilterScope.Collections);
        var predicated = Compose(context, FilterScope.Subqueries);
        var projected = Compose(context, FilterScope.Projections);
        if (!included.HasFilters && !predicated.HasFilters && !projected.HasFilters)
            return expression;

        var visitor = new PragmaticQueryFilterVisitor(included, predicated, projected);
        return visitor.Apply(expression);
    }

    /// <summary>
    ///     Applies navigation filters to an <see cref="IQueryable{T}"/>.
    ///     Wraps <see cref="ApplyVisitor"/> with IQueryable creation.
    ///     Short-circuits if no filters apply (returns same reference).
    /// </summary>
    public IQueryable<T> ApplyNavigationFilters<T>(IQueryable<T> query, FilterContext context) where T : class
    {
        var filteredExpression = ApplyVisitor(query.Expression, context);
        return ReferenceEquals(filteredExpression, query.Expression)
            ? query
            : query.Provider.CreateQuery<T>(filteredExpression);
    }

    private FilterMap GetOrCreateStaticMap(FilterContext context)
    {
        if (_staticMapFactories.Length == 0)
            return FilterMap.Empty;

        lock (_cacheLock)
        {
            // Cache hit: same context within the scope
            if (_cachedContext is not null && ReferenceEquals(_cachedContext, context))
                return _cachedStaticMap!;
        }

        // Compute outside the lock — the factories are non-trivial and side-effect free. Merged, so
        // an entity of any module is filtered: Merge ANDs where two maps name the same type, and
        // carries both sets of pre-resolved Where methods so the visitor never falls back.
        var map = _staticMapFactories[0](context);
        for (var i = 1; i < _staticMapFactories.Length; i++)
            map = map.Merge(_staticMapFactories[i](context));

        lock (_cacheLock)
        {
            // Another thread may have populated the cache for the same context meanwhile; prefer it.
            if (_cachedContext is not null && ReferenceEquals(_cachedContext, context))
                return _cachedStaticMap!;

            _cachedContext = context;
            _cachedStaticMap = map;
        }

        return map;
    }

}
